### ISSUE TITLE
Agent.start() should only do heartbeat to allow diagnostics for other issues

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#1634]
### Environment info
- Version: **71467595d586221d01affc22f9335fa4c82e96e1**
- Deployment: choose from - **Dev**
- Customer: choose from - **N/A**
### Actual behaviour
1. Agent.start() calls Agent._init_node() and then Agent.heartbeat()
2. In case anything other than connecting to the node monitor will fail the agent will disconnect from the server and will not allow any diagnostics or communication.
### Expected behavior
1. Agent.start() should only connect to the server.
2. Any other initialization sequence should occur without a dependency on the agent starting status, and maintain it's own status - for example block_store_inited status, etc.
### Steps to reproduce
1. Make the block_store init fail - for example make the agent_storage folder read-only 
### Screenshots or Logs or other output that would be helpful

(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Not relevant with the removal of agent outside a container. Error logs can be found at the pods logs
