### ISSUE TITLE
[Technical Debt] Bucket Storage Fetch eventually consistent, no support for multiple two way date jumps

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#1697]
### Environment info
- Version: **e11bd39337c39ea64d977f456fc451eef2cb6c3f**
- Deployment: **Dev** | **VBox**
- Customer: **QA**
### Actual behaviour
1. There are some major gaps that need to be covered regarding bucket storage calculation.
   Currently there is a bg worker that runs every 30 seconds and calculates the deltas in addition to known changes. The problem appears to be regarding time changes.
   There are two scenarios of time changes: 
   1) Going back in time - when the user decides to go back in time (manual time configuration or ntp fixes), the system realizes on the next bg cycle that it (system) went back in time and initializes all of the known bucket storage stats.
   In the next cycle the system starts building all of the storage stats all over again from scratch and starts scanning from epoch (0 time), till the new time (current time after change).
   Which means that you will not see the actual storage stats until you will reach the time that they were originally stored/created/deleted (thus making the calculations eventually consistent). 
   2) Going forward - When even you will go forward the system will get all of the changes immediately and it won't rebuild the storage stats.

There are problems when we jumps several times in date between the bg fetching cycles because we rely on timestamps of creations and deletions that are fluctuating and not growing consistently (like system ticks for example).
### Expected behavior
1. We should immediately know all of the changes and not be eventually consistent, also support multiple date changes during or between the bg fetch cycles.
### Steps to reproduce
1. It's always like that, just jump in times between the fetch cycles and make changes to the files.
### **Overall idea to implement**

We can take the idea of system store given ticks in order to get a consistent growing 'number'.
The system store will handle some growing number and it will publish it to everyone, when somebody will want to write a new file or delete a file, they will use the system's store provided "tick number" which will be managed according to date changes and etc`.
That way we will always know at what tick we are currently and will be able to track all of the changes regardless the timestamps, which will support all of the date changes.
Obviously it is a brief thought, and it needs more thinking.

**Comment by guymguym** [comment]
@nimrod-becker Closing as stale.
