### ISSUE TITLE
Phone Home Proxy Only HTTP Supported

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#1819]
### Environment info
- Version: **54347c891b6b93359ac36b2ee431bf1b733e7395**
- Deployment: **N/A**
- Customer: **N/A**
### Actual behaviour
1. Currently the Phone Home server is configured to receive HTTPS (but can be also configured to receive both HTTP and HTTPS)
   Which means that there are several ways to send data to the Phone Home server.

Without a proxy:
1) The data always sent using HTTPS (can easily be coded to send via HTTP as well but the decision was to use HTTPS only).

With a proxy:
1) With HTTP proxy to HTTPS (Phone Home server is HTTPS), it works fine.
2) With HTTPS proxy to HTTPS (Phone Home server is HTTPS), I couldn't make it work because I did not have an HTTPS proxy with a trusted certificate (it might maybe work with a trusted certificate).
The problem is that the response library (we use it to send the phone home data), doesn't use the command (strictSSL = false) for the proxy, which means that we get a problem or not trusted certificate and it doesn't proxy our request.
### Expected behavior
1. Should work with HTTPS proxy
### Steps to reproduce
1. Just configure an HTTPS phone home proxy, and attempt to send phone home data. 
### Screenshots or Logs or other output that would be helpful

(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
