### ISSUE TITLE
Upgrade failure screen should provide an explanation and solution for the problem

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#1910]
### Environment info

Version: 0.5.0-e455df2
Deployment: GCloud
Customer: QA
### Actual behaviour
1. If the upgrade process fails we only provide an error without any possible reasons or solutions.
### Expected behaviour
1.  for example- if our logs files are using all the user server capacity- we should provide an alert (even before he starts the upgrade process) so that he will be able to avoid upgrade failure or any uploading failure.
### Steps to reproduce

1.
### Screenshots or Logs or other output that would be helpful

(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
