### ISSUE TITLE
read count in UI doesn't show the correct number of reads

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#2017]
### Environment info
- Version: 0.5.1-5aaebee
- Deployment: GCloud
- Customer: QA
### Actual behaviour
1. every download of a file - the number of reads get up in 4-6.
### Expected behavior
1. every download should increase the reads number by 1
### Steps to reproduce
1. check the initial number of reads  
2. download a file in UI/cyberduck
3. check the new number of reads - more than 1 new reads (4-6 in my tries)
### Screenshots or Logs or other output that would be helpful

(If large, please upload as attachment)

![noobaa_management_console](https://cloud.githubusercontent.com/assets/20266280/18749190/590ba838-80de-11e6-9c77-98bb959a0407.png)
 where added

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
