### ISSUE TITLE
Windows agent with firewall blocks IO to the agent - Auto Fix FW

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#2094]
### Environment info
- Version: 0.5.2-9f9a5c4
- Deployment: AZURE
- Customer: QA
### Actual behavior
1. Started Noobaa server from Azure Market place
2. Added 3 linux agents 
3. Added a windows agent through the portal with default settings
4. Couldn't upload new data to noobaa
5. deactivated the windows client - IO is back again
6. disabled firewall and activated  the win agent - IO is still working
### Expected behavior

agent installation should verify the firewall is off ot the right ports is in, or warn the user if a firewall is on - so the agent can be operable
### Steps to reproduce
1. Create a Noobaa with 2-3 working nodes 
2. Add a new windows agent - Windows Server 2012 R2 - with default settings - firewall is on by default
3. See that the IO stop working

**Comment by nimrod-becker** [comment]
Windows agents no longer ssupported
