### ISSUE TITLE
MongoDB production-checklist-operations 

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#2110]
### Environment info
- Version: **75b138a73f99632c0c5591ee6bb65f0675eda934**
- Deployment: **N/A**
- Customer: **N/A**
### Actual behaviour
1. Not following https://docs.mongodb.com/v3.2/administration/production-checklist-operations/
### Expected behavior
- With the WiredTiger storage engine, use of XFS is strongly recommended to avoid performance issues found when using EXT4 with WiredTiger.
- Verify that all non-hidden replica set members are identically provisioned in terms of their RAM, CPU, disk, network setup, etc.
- Turn off transparent hugepages and defrag. See Transparent Huge Pages Settings for more information.
- Adjust the readahead settings on the devices storing your database files to suit your use case. For the WiredTiger storage engine, set readahead to 0 or 16.
- Disable the tuned tool if you are running RHEL 7 / CentOS 7 in a virtual environment. When RHEL 
  7 / CentOS 7 run in a virtual environment, the tuned tool automatically invokes a performance profile derived from performance throughput, which automatically sets the readahead settings to 4MB. This can negatively impact performance.
- Use noatime for the dbPath mount point.
- ~~Windows Azure: Adjust the TCP keepalive (tcp_keepalive_time) to 100-120. The default TTL for TCP connections on Windows Azure load balancers is too slow for MongoDB’s connection pooling behavior. - Done with #2115~~
- ~~Use the noop or deadline disk schedulers for SSD drive. - Already the case~~
- ~~Use the noop disk scheduler for virtualized drives in guest VMs. - Already the case~~
- ~~Disable NUMA or set vm.zone_reclaim_mode to 0 and run mongod instances with node interleaving. See: MongoDB and NUMA Hardware for more information.- Already the case~~
- ~~Adjust the ulimit values on your hardware to suit your use case. If multiple mongod or mongos instances are running under the same user, scale the ulimit values accordingly. See: UNIX ulimit Settings for more information. - Already the case according to the recommended values in https://docs.mongodb.com/v3.2/reference/ulimit/~~
- ~~Configure sufficient file handles (fs.file-max), kernel pid limit (kernel.pid_max), and maximum threads per process (kernel.threads-max) for your deployment. For large systems, the following values provide a good starting point: - Done with #2115~~
  ~~\- fs.file-max value of 98000, - already the case~~
  ~~\- kernel.pid_max value of 64000, already the case~~
  ~~\- kernel.threads-max value of 64000 - Done with #2115~~
- ~~Ensure that your system has swap space configured. Refer to your operating system’s documentation for details on appropriate sizing. - Already the case~~
- ~~Ensure that the system default TCP keepalive is set correctly. A value of 300 often provides better performance for replica sets and sharded clusters. See: Does TCP keepalive time affect MongoDB Deployments? in the Frequently Asked Questions for more information.- Done with #2115~~
- etc......

**Comment by nimrod-becker** [comment]
Working with a mongodb prepared container and not providing our own OVA.
Closing this issue
