### ISSUE TITLE
mongo client should failover without the need for restart services

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#2491]
### Environment info
- Version: **0.8.0-5041237.**
- Deployment: **All**
- Customer: **None**

### Actual behaviour
1. when the master is stopped with hard shut down, mongo client doesn't perform the failover fast enough (might take up to 15 minutes).
2. mongo shell on the same server seems to identify the failover much faster, and it gives an update rs.status() query.
3. as a workaround we currently have the mongo_monitor service that checks the status through the mongo shell, and restarts the services when a failover is identified.

### Expected behavior
1. we should find why the mongo client doesn't connect automatically to the new master as fast as the mongo shell does, and fix it.

### Steps to reproduce
1. create a cluster.
2. kill the primary by shutting it down \ powering off the vm

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
