### ISSUE TITLE
potential for ssl problems when redirecting from DNS name to master ip

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#2561]
### Environment info
- Version: **0.8**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. When accessing the cluster through DNS name the client might be redirected to the master ip address. there is a potential for problems with an uploaded ssl certificate since the host specified in the certificate is different then the redirected address

### Steps to reproduce
1. upload certificate to cluster
2. try to access non master node, and check what happens on redirect

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
