### ISSUE TITLE
After upgrade all overview elements statuses has only errors and issues

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#2595]
### Environment info
- Version: **0.9.0-52c99fc**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1.After upgrading the system all statuses has some kind of issue: - All nodes are offline - Cluster has a high number of issues - No available capacity - Unavailable storage is high.
2. The server version is not up to date until it sends HB and cluster status shows as has issues

This is a very bad overview look and it is scary for an admin to see. 

### Expected behavior
1. The user shouldn't refresh a few times and wait so we'll stabilise the system. it should be ready for him. if it's not- don't finish the upgrade process yet.
2. The server should be updated according to the system version before upgrade process is done.

### Steps to reproduce
1. Upgrade system
2. See overview screen
3. See cluster status and go to server page, see server version

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![image](https://cloud.githubusercontent.com/assets/10331355/22198798/d49ca230-e160-11e6-8587-f671c71aa259.png)

![image](https://cloud.githubusercontent.com/assets/10331355/22204723/22e015b0-e17c-11e6-9c73-729a84193dd0.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
