### ISSUE TITLE
peer to peer setting takes time. need to provide user feedback

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#2691]
### Environment info
- Version: **1.0.0-92796da**
- Deployment: **AZURE**
- Customer: **online sandbox**

maybe have animated button like diagnostics download.

### Actual behavior
1. http://noobaaonline.eastus.cloudapp.azure.com:8080/fe/systems/noobaaonline/management/advanced-options/p2p

Try to change. It takes about 20-30 seconds. no feedback for the user.

### Expected behavior
1. feedback. It takes time until we show the green message that it's ok. 

### Steps to reproduce
1.
URL: http://noobaaonline.eastus.cloudapp.azure.com:8080
Username: cleverball@noobaa.com
Password: XlkJvFXz

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
