### ISSUE TITLE
use the user's ssl certificates for mongo auth

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#2705]
### Environment info
- Version: **1.1**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**

### Actual behavior
currently, for mongo auth, we use self signed certificate that we generate on upgrade\deploy_base
this is not the best practice for production servers.

### Expected behavior
1. we should let the users upload their own certificates to be used for mongo authentication. 
2. it requires that the user can upload client, server and root-ca certificates.
3. in case there is a problem with the certificates (e.g. certificate expired) we should fall back to the self signed certificates, and notify the user.

**Comment by nimrod-becker** [comment]
Current clustering implementations changed (k8s) , closing
