### ISSUE TITLE
Nodes stuck in migrating after moving nodes between pools and retuning to the original pool

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#2728]
### Environment info
- Version: 1.1.0-35ea489
- Deployment: AZURE
- Customer: QA

### Actual behavior
1. Adding 4 nodes to the machine
2. falsely moving just 2 nodes to another pools - both pools are down - as they should
3. the nodes in the new pool go into migrating phase
4. decided to move the nodes back to the original pool to fix the problem
5. the nodes still stuck on migrating - default pool is down
 
### Expected behavior
1. the nodes should stop the migration in some phase - looks like it's a permanent situation 

### Steps to reproduce
1. written in actual behavior

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://cloud.githubusercontent.com/assets/20266280/23407036/9511ad3c-fdca-11e6-88d4-7579f7c01d2a.png)

**Comment by nimrod-becker** [comment]
@guymguym probably wasn't fixed with the latest PR but what do you think about addressing this with Jenia's upcoming PR of rebuilding without decrypt, encrypt (Eran just hit this one now)

**Comment by guymguym** [comment]
@nimrod-becker @tamireran How about this suggestion - we identify this case and just "cancel" the node migration if the node is back to the original pool?

**Comment by tamireran** [comment]
It can be a good start

**Comment by nimrod-becker** [comment]
sounds good

**Comment by nimrod-becker** [comment]
@jeniawhite lets add it as the part of the rebuild change
