### ISSUE TITLE
After deleting a cloud resource total system capacity doesn't update immediately 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#2792]
### Environment info
- Version: **1.3.0-c935b70**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. After removing all cloud resources in the system it took more then a 90 sec until the total capacity updated- the free capacity in the overview page shows error (1% free capacity)

### Expected behavior
1. Capacity should be updated immediately - this creates a feeling that the user did something wrong 

### Steps to reproduce
1. delete cloud resources
2. see overview- system status

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![image](https://cloud.githubusercontent.com/assets/10331355/24146166/28d3bc90-0e3d-11e7-846d-96faa8d36b40.png)

**Comment by nimrod-becker** [comment]
UI no longer supported
