### ISSUE TITLE
FireFox - buttons are out of the modal scope in Edit Server Time Settings

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#2840]
### Environment info
- Version: 1.3
- Deployment: AZURE
- Customer: QA

### Actual behavior
1. the buttons are out of scope

### Expected behavior
1. should be in the scope

### Steps to reproduce
1. FF + edit server time settings

### Screenshots or Logs or other output that would be helpful
![screen shot 2017-03-29 at 16 48 08](https://cloud.githubusercontent.com/assets/20266280/24457789/d3a77db0-149f-11e7-9183-790d726a75da.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
