### ISSUE TITLE
Idle system with many buckets runs system_store.make_changes every second

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#2846]
### Environment info
- Version: **1.3**
- Deployment: **DEV**
- Customer: **NA**

### Actual behavior
1. After running ceph s3-tests that created a lot of buckets I see make_changes being called every second by the bg worker to update storage stats:
```
Mar-29 18:28:49.231 [BGWorkers/5459] [L0]  core.server.system_services.system_store:: SystemStore.make_changes: { update: 
   { buckets: 
      [ { _id: 58dbcd46ee373314aa407f26,
          storage_stats: 
           { chunks_capacity: 0,
             objects_size: 0,
             objects_count: 0,
             blocks_size: 0,
             last_update: 1490799853169,
             objects_hist: [] } },
        { _id: 58dbcd46ee373314aa407f22,
          storage_stats: 
           { chunks_capacity: 0,
             objects_size: 0,
             objects_count: 0,
             blocks_size: 0,
             last_update: 1490799853169,
             objects_hist: [] } },
...
```

### Expected behavior
1. make_changes should not be called in such high frequency

### Steps to reproduce
1. Create many buckets
2. Maybe need to write something to each one
3. Behold the wonder happening by bg worker

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
@jackyalbo any changes after the scale PR ?

**Comment by jackyalbo** [comment]
> @jackyalbo any changes after the scale PR ?

I think we can close - if it is running in closing gaps mode - after the PR, it will still run make_changes(every second) as usual but won't load the system_store every time, which is the heavy part of the scenario.

**Comment by nimrod-becker** [comment]
#5570
