### ISSUE TITLE
dev scripts to reset a cluster (and other scripts) should be accessible from server

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#2896]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

1. we should have a way to load dev scripts easily in the server.
2. some of the scripts can be destructive, so we may not want them to be under src/

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
