### ISSUE TITLE
Cluster - Should give user better feedback when service is down

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#2968]
### Environment info
- Version: 1.4.1-e9ba76d
- Deployment: AZURE
- Customer: QA 

### Actual behavior
1. when taking off 2/3 servers in cluster - when accessing the only server which is up - you get no service and redirection to one of the servers which are down.

### Expected behavior
1. server should let the user know that currently there is no service in the system.

### Steps to reproduce
1. take off more than half of the servers in the cluster
2. try to access one of the servers which is still alive

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
