### ISSUE TITLE
Preview iframe allows running scripts and might allow XSS attack

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#3051]
### Environment info
- Version: **1.6**
- Deployment: **NA**
- Customer: **NA**

### Actual behavior
1. The preview iframe loads file contents and allows running its scripts on the page creating a security hole.

### Expected behavior
1. iframe sandbox - must specify the sandbox attribute to disallow any malicious content - see https://www.w3schools.com/tags/att_iframe_sandbox.asp
2. Restrict/cast content types - besides images, videos, pdf, and maybe also html, the rest of the files should cast to text (unless too large).

### Steps to reproduce
1. Upload an html file
2. Preview the html file
3. Behold as the preview window renders the html and runs its scripts

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
