### ISSUE TITLE
After uploading SSL certificate the webserver restarts-should be expresses in UI, upload two files instead of a zip

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3054]
### Environment info
- Version: **1.7**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. When Uploading SSL certificate the webserver and s3rver are restarted.
2. the UI does not warn against it, and does not refresh after (like when setting DNS)

### Expected behavior
1. there should be a warning that the operation will result in a restart
2. the UI should refresh afterwards
3. Also break certificate upload to 2 files instead of a zip 

### Steps to reproduce
1. upload SSL certificate

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
