### ISSUE TITLE
Azure blob container naming fails on first.bucket since it does not not allow dots

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#3061]
### Environment info
- Version: **1.6**
- Deployment: **NA**
- Customer: **NA**

### Actual behavior
1. Azure naming rules for containers do not allow dots, only lowercase alphanumeric and dash.
2. Our `first.bucket` immediately fails the Blob API.

Azure rules:
https://blogs.msdn.microsoft.com/jmstall/2014/06/12/azure-storage-naming-rules/
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

Amazon rules:
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

### Expected behavior
1. Omit buckets with dots from the Blob API because otherwise it breaks clients.
2. Consider renaming first.bucket to first-bucket
3. When creating a bucket name with dots consider one of these:
 - Allow to create bucket aliases so that it will allow to expose the bucket in a valid Blob container name
 - Allow to rename the bucket later - this is probably bad and will introduce complexities.
 - Warn that this bucket will not be available from Blob API
 - Do not allow it

### Steps to reproduce
1. Use Blob API with first.bucket

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Blob API no longer supported
