### ISSUE TITLE
when there are a lot of nodes switching between the filters in the ui  take several sec.

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3090]
### Environment info
- Version: **1.8.0-b618666**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. when moving between filters in the UI, under Resources -> pool -> nodes, and there are a lot of nodes (~230) every switch takes several sec.

### Expected behavior
1. the switching between filters should be fast, we should get a results in an instance.

### Steps to reproduce
1. create a lot (200+) of agents:
 - create one, then delete one (it will bring the system to have a lot of unhealthy agents).
2. try to switch between the filters.

![noobaa_management_console](https://user-images.githubusercontent.com/28217223/27130333-9fc9a67a-510e-11e7-80c0-07109acb60b4.png)

Danny saw the bug.

**Comment by nimrod-becker** [comment]
Not relevant anymore, we don't expect 230 nodes in a single k8s pool
