### ISSUE TITLE
On IP restrictions modal- when the IP list is long with scroll, focus out and then try to delete a token creates a jump

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3199]
### Environment info
- Version: **1.8.0-20c345a**
- Deployment: **AZURE
- Customer: **NAME**

### Actual behavior
1. When Allowed IPs token list is long (with scroll), deletion without focus creates a jump to the end of the list without deleting the wanted IP.

### Expected behavior
1. Deletion should occur when X is clicked.

### Steps to reproduce
1. Go to IP restriction modal
2. Enable and add a long IP list
3. When scroll exists, focus out and try to click on X on one of the top IPs on the list 

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![jun-29-2017 11-05-58](https://user-images.githubusercontent.com/10331355/27677834-aae192f8-5cbb-11e7-9edd-a4c5aa59273e.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
