### ISSUE TITLE
loging into a cluster  via the slave ip, always redirects to the master's eth0, if it was removed, no UI is displayed

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3247]
### Environment info
- Version: **1.9.0-2cfcc54**
- Deployment: **ESX**
- Customer: **QA**

### Actual behavior
1. In cluster, we cant reach the UI if we are trying to log into the slaves ip and on the master we removed (there is no) eth0
- looks like the slave redirect to the master's eth0 

### Expected behavior
1. if there is interface other then eth0 and eth0 is not exist on the master, we should redirect to it

### Steps to reproduce
1. Create a cluster with multiple nics on the master
2. Remove the eth0 nic from the cluster
3. Log into the UI via the slave's ip.

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
