### ISSUE TITLE
Node's Stored File Parts list links to a broken page of a deleted object

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3251]
### Environment info
- Version: **1.9**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Somehow we got to a situation where the Object MD is marked as deleted
2. the corresponding part, chunk and some of the blocks are not deleted.
3. when going to the **Stored File Parts** screen of the node which holds an undeleted block, there is a link to the deleted object.
4. clicking on the link leads to a broken page

this bug is related to #3135 

### Expected behavior
1. parts of deleted objects should not appear in the Stored File Parts screen of a node.

### Steps to reproduce
1. upload a file
2. in the DB mark only the object md as deleted
3. go to Stored File Parts of a node holding one of the blocks.
4. click on the link of the deleted object

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
