### ISSUE TITLE
Vertical scrolling appears on description box (in audit log) when event name is very long

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3331]
### Environment info
- Version: **1.10.0-c0de11c**
- Deployment: **AZURE|
- Customer: **NAME**

### Actual behavior
1. When the description entity name is very long the description gets a vertical scroll bar...

### Expected behavior
~~1. Description box should have max-width and the text should be cut according to it~~
1. Description box should support HTML/CSS formatting for handling similar cases

### Steps to reproduce
1. Upload a file with a long name 
2. See upload audit record description 

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![image](https://user-images.githubusercontent.com/10331355/28578694-27e95626-7163-11e7-9673-8d827e80b46f.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
