### ISSUE TITLE
Node's connectivity test misbehave

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3424]
### Environment info
- Version: **1.11.1-bcddb7e**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When running tests we should not be able to move between radio buttons 
(Full test/Connectivity/Bandwidth)
2. Abort and Close should be in separate buttons.
3. The list of test should scroll down automatically 
4. When pressing Run after a test, after we press we see the "Click on the run button to start the test" message

### Screenshots or Logs or other output that would be helpful
![node s_connectivity_test_window](https://user-images.githubusercontent.com/28217223/29321544-6944e0a0-81e3-11e7-9b2c-6736879207cf.gif)

**Comment by nimrod-becker** [comment]
Irrelevant with PV Pools
