### ISSUE TITLE
Provide visual focus indication for keyboard focus only. The outline shouldn't appear on every mouse click. 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3467]
### Environment info
- Version: **1.12.0-a4046c6**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. Every click on an element in the system changes the focus to that element. the user shouldn't receive any graphic indication unless he uses the keyboard "TAB"

### Expected behavior
1. Take github as an example, when clicking on a button or tab, you don't get a visual focus indication like we have. but when using "tab" key, you can see the focus by tab-index order. 
the cases who should get a visual focus on mouse interaction are textfields (also includes search boxes) and selected drop-downs. 

Some more examples: https://wicg.github.io/focus-ring/demo/
### Steps to reproduce
1. click on anything in the UI to see focus outline.

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![image](https://user-images.githubusercontent.com/10331355/29518628-c6fe03ea-8682-11e7-8c84-b3cffc0dca31.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
