### ISSUE TITLE
Chunked uploads choke endpoint process (may crash other services as well) - Should pass CONTAINER_MEM_REQUEST

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#3495]
### Environment info
- Version: **MASTER**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
Currently we have a single semaphore for reads and writes in our object_io.
We take up space from the semaphore by number of bytes of reads and writes.
On chunked uploads we do not always know how many bytes each chunk takes so we don't know how much place to take from the semaphore.
If we would take the maximum (256MB), we would take all of the semaphore and will get choked.
On the other hand if we will take less like we do now (1MB), we can crash the endpoint and other services since each chunk can be more thus we will load our semaphore with more data than expected.
We need to fix that as quick as possible since it is a major issue.

### Expected behavior
We should be flexible with our semaphore allocations on chunked uploads

### Steps to reproduce
Just create a chunked upload and see how the semaphore handles the data

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
With the move to stateless endpoints, we should pass the ```CONTAINER_MEM_REQUEST``` to the pods according to what was given (in case request and limit are not the same) in order to calculate the buffer sizes correctly

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Standalone endpoints](https://trello.com/c/LNrzkoOq/907-standalone-endpoints)

**Comment by nimrod-becker** [comment]
Relates to #5825

**Comment by nb-ohad** [comment]
closed with #5833
