### ISSUE TITLE
Deactivating an offline drive is not handled properly 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3505]
### Environment info
- Version: **1.12.0-a93bf39**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. We allow the user to deactivate a node when it's offline (by disabling all service). By doing that, the node goes to a deactivating state (without any data activity) and never finished the process. 

### Expected behavior
1. If a node is offline deactivating is irrelevant- perhaps we should alert the user that deactivating can not start until the node is back online and not even start the deactivation process.  

### Steps to reproduce
1. Go to an offline node > disable all services > see status + data activity. 

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![image](https://user-images.githubusercontent.com/10331355/29669376-e6d6586e-88eb-11e7-81ad-748da1e4e598.png)

**Comment by nimrod-becker** [comment]
Not relevant, k8s pools support scale options only
