### ISSUE TITLE
when host is only used for gateway it's showing "No Access" label in green color

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3507]
### Environment info
- Version: **1.12**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. when host is only used for gateway it's showing "No Access" label in green color

### Expected behavior
1. When a node has only S3 gate the access should be "No access- Used as S3 gateway only"

### Steps to reproduce
1. deactivate storage and enable s3

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/1476203/29676706-71500af2-8901-11e7-9317-cda91c0bf370.png)

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Standalone endpoints](https://trello.com/c/LNrzkoOq/907-standalone-endpoints)

**Comment by nimrod-becker** [comment]
Relates to #5825 5825

**Comment by nb-ohad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint UI/UX](https://trello.com/c/9Zrgc4To/924-endpoint-ui-ux)
