### ISSUE TITLE
Deleting a cloud resource that has used capacity by NooBaa on it is currently not prevented 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3554]
### Environment info
- Version: **1.12.0-f676751**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. After removing a cloud resource from a bucket data placement, the cloud resource node should start a rebuilding process to evacuate its stored data, but we don't prevent the resource deletion before that process ends. 

### Expected behavior
1. Show "evacuating data" cloud status and don't allow resource deletion until it's completely evacuated. 

### Steps to reproduce
1. Connect a cloud resource to a bucket > upload files > once replicas build is done remove the cloud resource from the bucket data placement > Go to cloud resource and delete the resource (see "Used capacity by NooBaa"

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![cloud](https://user-images.githubusercontent.com/10331355/29883151-fff1faf8-8db7-11e7-8d4f-ce4421c9169b.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
