### ISSUE TITLE
FE is stack on initializing when an invalid token is saved in the browser 

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#3618]
A change in the policy of the RPC prevents fulfilling requests that does not need authorization when an invalid token is send with the request. 

This change brought to the surface a race condition in the FE. 
The login-layout is trying to query the server for a system (calling the api.account.accounts_status - a call that does not need authorization).
while a failed restore handler is trying toe remove the token from the global api object. 

This was not a problem before because the RPC allowed the the call to be fulfilled and now it throws UNAUTHORIZED.

This bug will manifest itself in the following conditions:
1. After you delete a system and refresh the FE.
2 After you delete the working account and refresh the FE on a diff tab.

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
