### ISSUE TITLE
on centos 7 agents firewall should be checked using firewall-cmd

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3716]
### Environment info
- Version: **2.0**
- Deployment: **Centos7 agents**
- Customer: **NAME**

### Actual behavior
1. currently we only check iptables and windows firewall to check if ports are closed.
2. on centos 7 firewalld is used by default instead of iptables. we skip checking it for centos7 agents

### Expected behavior
1. we should use firewall-cmd to check ports, and report the same as we do with iptables

### Steps to reproduce
1. check centos 7 agent

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
No longer relevant with the remove of an agent outside a container
