### ISSUE TITLE
NTP sync test returns that we are not synced in the first few sec of deploying ova, leading to unneccecery alert.

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3738]
### Environment info
- Version: **2.0.0-a6ac935**
- Deployment: **ESX**
- Customer: **QA**

### Actual behavior
1. When deploying the ova on ESX we get the following alert immediately after we create the system: "Local server time is not synchronized with NTP Server, check NTP server configuration"

### Expected behavior
1. This Alert should not be prompt in the first few min  

### Steps to reproduce
1. Deploy the OVA in the ESX

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
