### ISSUE TITLE
/etc/issue is becoming empty after changing ip in the first deploy

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3760]
### Environment info
- Version: **2.0.0-cc09b11**
- Deployment: **ESX**
- Customer: **QA**

### Actual behavior
1. /etc/issue is becoming empty after changing ip in the first deploy

### Expected behavior
1. should not be empty 

### Steps to reproduce
1. connect to the first deploy
2. change the interface ip
3. exit the firtt deploy
4. reboot the machine.

* it doesn't happens every time.

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
