### ISSUE TITLE
New system - windows node is untrusted

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#3776]
### Environment info
- Version: **1.12.2-a65e9ad**
- Deployment: **VBOX**
- Customer: **Demo**

### Actual behavior
1. Created a new system. 
2. Installed agent on windows (7) 
3. node is untrusted
4. turned to trusted after few **minutes**. 

[log](http://swiggity.eastus.cloudapp.azure.com:8080/fe/systems/demo/buckets/customers/objects/host_office-et-PC_3_diagnostics_issue_3776.tgz)

![image](https://user-images.githubusercontent.com/3898274/31926995-dfe5724e-b846-11e7-8d3c-4f4f2cdb5ec2.png)

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Windows agents are no longer supported
