### ISSUE TITLE
[DEBT] Missing Blob API signature validation

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#3850]
### Environment info
- Version: **1.12.3**
- Deployment: **Any**
- Customer: **Any**

### Actual behavior
1. No signature validation is done for Blob API

### Expected behavior
1. Should validate signatures for authenticated data access

### Steps to reproduce
1. Access data with any credentials

**Comment by nimrod-becker** [comment]
Blob API no longer supported
