### ISSUE TITLE
Connection usage table missing/convoluted usage information

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#3884]
### Environment info
- Version: 2.0
- Deployment: ALL

Currently the connection usage table describe the buckets using a resource that is using the connection.

Consider the following scenario
We have 1 connection used by 2 cloud resources where each cloud resource is used by 2 buckets.
I stipulate 3 issues:
1. Will have only 1 line for this scenario so the user cannot separate between the usages: one form the first cloud resource used by 2 buckets and the other  cloud resource used by the other 2 buckets.
2. Also If the user wants to delete the connection cannot he know what resources he need to delete in order to free the connection for deletion.
3. if we crate a cloud resource but don't connect it to any bucket we will not have a row for this usage.

My suggestion is give each usage (cloud resource) its own line with a link to the resource in the usage column and in the NooBaa buckets column show the buckets that r using these resource.
So for the scenario above we will have 2 lines, one for each cloud resource with  2 NooBaa buckets in the last column

P.S
All of the above is also right for External Resource connections

**Comment by nimrod-becker** [comment]
Fixed
