### ISSUE TITLE
In Azure the DNS servers set in dhclient.conf are ignored - can't set DNS to 127.0.0.1

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3907]
### Environment info
- Version: **2.0**
- Deployment: **AZURE**
- Customer: **DEV**

### Actual behavior
1. In azure the settings in `/etc/dhclient.conf` are written to resolve.conf
2. After adding an internal DNS cache we want to set the dns server as 127.0.0.1
3. The only way to set it is through the Azure portal in the vnet settings

### Expected behavior
1. we should find a way to set the dns server in an azure VM to 127.0.0.1 without requiring a manual intervention from the user

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![dns_servers_-_microsoft_azure](https://user-images.githubusercontent.com/1476203/33027603-3ac11a98-ce1c-11e7-9cff-d624d4af9556.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
