### ISSUE TITLE
api.account.add_external_connection does not check the connection before creating it

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#3912]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. api.account.add_external_connection accept connection info and creates a connection without running first check_extneral_connection to verify that a connection can be established.

### Expected behavior
1. Should check_extneral_connection and throw if fail (should not relay on the FE to do the check for him)

**Comment by nimrod-becker** [comment]
already done via the operator flows
