### ISSUE TITLE
add a lot more debug messages to cluster related flows

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3931]
### Environment info
- Version: **2.0**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. currently we are lacking a lot of messages in many of cluster_server flows like add_member, update_member, etc.
2. most of these flows are very rare in the system's life. we should go over them and add a lot of log0 messages that can help us debug failures that occur less rarely 

### Expected behavior
1. more messages

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
