### ISSUE TITLE
Agent cli die and cannot be restarted after sending uninstall on dev machine (Darwin)

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#3932]
### Environment info
- Version: 2.0
- Deployment: DEV
- Customer: **NAME**

### Actual behavior
Some time after calling uninstall for a host, the agent cli dies and cannot be restarted.
A workaround: After the process dies, delete the agent_conf and noobaa_storage related to the deleted host and rerun agent_cli

### Expected behavior
1. Agent cli should clean itself after local uninstall and should not fall

### Steps to reproduce
1. Delete a host (using the UI) then wait for 2-3min. 

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

**Comment by nimrod-becker** [comment]
No longer relevant with agents deployed by k8s
