### ISSUE TITLE
Negative used capacity of bucket after using internal storage

### ISSUE THREAD

**Issue by YuliaKovalenko** [noobaa/noobaa-core#3961]
### Environment info
- Version: **2.0.0-d5e238c**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Negative used capacity of bucket 

### Expected behavior
1.Used capacity is 0 KB

### Steps to reproduce
1. Upload files to internal storage (pool without agents)
2. Delete files

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)
![negativeusagebucket](https://user-images.githubusercontent.com/12726938/33543461-cb4b2d56-d8df-11e7-84cb-3a67270897fd.JPG)
![negativeusagecapacity](https://user-images.githubusercontent.com/12726938/33543462-cb6d7b2c-d8df-11e7-9216-215d07234d78.JPG)

**Comment by nimrod-becker** [comment]
Closing, internal would only be used on dev env
