### ISSUE TITLE
highlight the relevant pie chart part when hovering over the legend's entries and vice versa

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#3968]
### Environment info
- Version: **2.0**
- Deployment: **AZURE|ESX|AWS|GCLOUD|DEV|VBOX**
- Customer: **NAME**

### Actual behavior
1. pie chart parts are highlighted when hovering over.

### Expected behavior
1. a nice enhancement can be if the relevant legend entry is also highlighted when hovering over the pie chart.
2. also when hovering over the legend, the relevant chart part can be highlighted.

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

![noobaa_management_console_and_ _ _ _ _ ___ _-_ _ _ _](https://user-images.githubusercontent.com/1476203/33608360-f7e32e3e-d9cc-11e7-8def-4bc01659a5e0.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
