### ISSUE TITLE
Internal storage reports usage of 830MG while there are only two chunks in the gridfs collection

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#3983]
### Environment info
- Version: **2.0.0-78d7867**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. On the overview we see that there is ~800MB in the spill over
2. On the Bucket Spillover it report 0MB
3. The system had a lot of free space on it's agents 

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/33804725-de9cf88e-ddb3-11e7-926a-b0d56c897c1f.png)
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/33804728-ef4158d8-ddb3-11e7-9c4e-f12c6b85ddcf.png)

**Comment by nimrod-becker** [comment]
Clising won't fix, internal would only be used on dev env
