### ISSUE TITLE
Editing Primary/ secondary DNS does not reflect in the UI until it returns which takes 10s

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#3989]
### Environment info
- Version: **2.0.0-2a662dd**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. I have a secondary DNS configured in the system, in order to remove it I delete the text in the secondary text field and click "save" but nothing happens and the configuration is not saved.

*** Same issue for primary DNS

## Expected behavior
1. Changes should be saved...

### Steps to reproduce
1. Go to configurations > Edit Server DNS Settings > remove the secondary DNS (if exist) > save and see edit modal again

### Screenshots or Logs or other output that would be helpful

![dns sec](https://user-images.githubusercontent.com/10331355/33825428-437f1bb8-de6a-11e7-89f0-6ec02743c105.gif)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
