### ISSUE TITLE
2 Step Upgrade | irrelevant report when uploading upgrade package and running verification

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4024]
### Environment info
- Version: **2.0.0-bed837c**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. when we are uploading upgrade package and running verification, reporting on 
"Staged Version: No previously tested version" is irrelevant. 

### Expected behavior
1. "Staged Version: No previously tested version" should not appear when we are in the the 1 step of the upgrade

### Steps to reproduce
1. Go to "System Management" -> "Version"
2. Upload a package 

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/33930190-c47cd3fa-dff4-11e7-9eb1-1a46f9be8125.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
