### ISSUE TITLE
Missing popup notification after uploading upgrade package is done (success/ failure) 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4026]
### Environment info
- Version: **2.0.0-bed837c**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. While uploading and testing an upgrade version we allow the user to continue working, assuming this might take a while but we do not notify the user when the first step is done. 

### Expected behavior
1. A popup notification should appear when the first step is done. 

### Steps to reproduce
1. Go to version upgrade > upload a file > leave upgrade page

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
