### ISSUE TITLE
Bucket usage capacity vs pool breakdown capacity has different values 

### ISSUE THREAD

**Issue by YuliaKovalenko** [noobaa/noobaa-core#4047]
### Environment info
- Version: **2.0.0-df66f3a**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. 
![capacity](https://user-images.githubusercontent.com/12726938/33982718-3281b0c6-e0ba-11e7-9aa3-0ed9ac9d6f1d.JPG)

![noobaa_management_console 1](https://user-images.githubusercontent.com/12726938/33982460-4868d226-e0b9-11e7-845d-f08daf90ede1.png)

### Expected behavior
1. Calculating should be relevant  

### Steps to reproduce
1. Upload files on bucket

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
