### ISSUE TITLE
Missing popup notification after file upload

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4054]
### Environment info
- Version: **2.0.0-543ce92**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. After uploading a file the user should receive a popup when it's done with a success/ failure message.

### Expected behavior
1. Return a popup notification

### Steps to reproduce
1. Upload a file > wait for it to finish

**Comment by nimrod-becker** [comment]
Closing wont fix
