### ISSUE TITLE
Edit Server Time Settings modal disappears when clicking on the timezone dropdown - happens on Retina screen only and when not in mirror

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4056]
### Environment info
- Version: **2.0.0-543ce92**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. Edit Server Time Settings modal disappears when clicking on the timezone dropdown 

### Expected behavior
1. The dropdown should be open and the modal shouldn't be effected 

### Steps to reproduce
1. Configurations > Edit Server Time Settings > Click on timezone dropdown

### Screenshots or Logs or other output that would be helpful

![dissapear](https://user-images.githubusercontent.com/10331355/33991668-2b5d6bdc-e0d8-11e7-8cb6-d0f58163bee3.gif)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
