### ISSUE TITLE
Alert should be prompt when we are drive HA but not Hosts HA 

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4072]
### Environment info
- Version: **2.0.0-6817f08**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When we have enough drives but not enough agents we are able to write.  We expect to be able to write even though we are not server HA. 
(for example in replica we need 3 places to distribute the data, if we have 1 agent and it have 3 drives we will distribute it on them, so we have drives HA but not server HA).

### Expected behavior
1. We expect to have an Alert when we are not Server HA even if we are drive HA

### Steps to reproduce
1. Create 1 agent with 3 disks.

**Comment by nimrod-becker** [comment]
Host to Drive (PV ) is 1:1, Irrelevant
