### ISSUE TITLE
On system upgrade, "running tests" should have a cancel option. 

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4074]
### Environment info
- Version: **2.0.0-6817f08**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. on system upgrade -> "running tests" don't have cancel  option. 

### Expected behavior
1. "running tests" should have a cancel option. 

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/34078287-c326d202-e31f-11e7-9042-09dc7e4d21d9.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
