### ISSUE TITLE
Rerun test btn doesn't work (or the UI doesn't reflect that he does)

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4081]
### Environment info
- Version: **2.0.0-51dcdf6**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. After a test failure, clicking on rerun test does nothing or doesn't look like it's doing something in the UI.

### Expected behavior
1. The test should run and show the user new results

### Steps to reproduce
1. Upload a damaged package > click on rerun test btn > see reaction 

### Screenshots or Logs or other output that would be helpful

![retest](https://user-images.githubusercontent.com/10331355/34081666-3eae1712-e359-11e7-98cd-b9d3162f811f.gif)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
