### ISSUE TITLE
No (x) or backdrop click in after upgrade modal 

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#4105]
The modal manager translate (X) button clicks and backdrop clicks to cancel operation which just closes the modal and this was the only use case in the FE  up until now.

The new after-upgrade-modal (2 step upgrade) has a "done" button which is attached with the action to redirect the page to the same url without the **afterupgrade** query.

In this case we need the side effect each time we close the modal which mean even when we click the backdrop or the (X) button.

Currently we have no good way to accomplish this so I removed the (X) button and disabled backdrop clicks.

The end desired result is that the (X) button clicks and backdrop clicks will run the side effect as well (the redirect).

**Comment by nimrod-becker** [comment]
Irrelevant when deploying on k8s (upgrade is unmanaged)
