### ISSUE TITLE
[Unknown Mount] in node storage mounts

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#4107]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. I have an Unknown Mount in the storage mounts of the node
2. I can activate and deactivate it
3. That mount was initializing as /mnt prior

### Expected behavior
1. I would expect it to remain /mnt after deactivation and not transfer to Unknown Mount

### Steps to reproduce
1. I just had an agent that was created from azure script
2. Stopped the agent
3. Started the agent
4. Waited for him to initialize
5. After about 30 seconds I saw second mount /mnt and he was in initialization state (don't know why it had second mount /mnt since we only have 1 mount /)
6. I deactivated the /mnt mount from the UI and immediately it showed Unknown Mount in the UI as disabled
7. I activated and deactivated it several times and it always remained to be Unknown Mount.

### Screenshots or Logs or other output that would be helpful
![screen shot 2017-12-20 at 11 30 51](https://user-images.githubusercontent.com/12246907/34200576-51813a4a-e57a-11e7-9610-18ff535068d9.png)
[noobaa.log.1.gz](https://github.com/noobaa/noobaa-core/files/1574972/noobaa.log.1.gz)
[noobaa.log](https://github.com/noobaa/noobaa-core/files/1574973/noobaa.log)

**Comment by nimrod-becker** [comment]
Azure agent deployment no longer supported
