### ISSUE TITLE
Win 2016 agent -  problem with reading firewall open ports

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#4115]
### Environment info
- Version: 2
- Deployment: AZURE
- Customer: QA

### Actual behavior
1. getting error on firewall on windows 2016:
```core.util.os_utils:: failed checking firewall rules on windows. treat as all ports are open TypeError: Cannot read property 'filter' of undefined    at promise_utils.exec.then.then.rules (C:\Program Files\NooBaa\src\util\os_utils.js:1031:41)    at tryCatcher (C:\Program Files\NooBaa\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Program Files\NooBaa\node_modules\bluebird\js\release\promise.js:512:31)    at Promise._settlePromise (C:\Program Files\NooBaa\node_modules\bluebird\js\release\promise.js:569:18)    at Promise._settlePromise0 (C:\Program Files\NooBaa\node_modules\bluebird\js\release\promise.js:614:10)    at Promise._settlePromises (C:\Program Files\NooBaa\node_modules\bluebird\js\release\promise.js:693:18)    at Async._drainQueue (C:\Program Files\NooBaa\node_modules\bluebird\js\release\async.js:133:16)    at Async._drainQueues (C:\Program Files\NooBaa\node_modules\bluebird\js\release\async.js:14```

### Expected behavior
1. should work

### Steps to reproduce
1. use win2016 agent if i'm not mistaken happens also on other windows versions

**Comment by nimrod-becker** [comment]
Agents on Windows no longer supported
