### ISSUE TITLE
Aborting an upload (deleting while uploading) only removes the file from the list but doesn't abort the upload

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4120]
### Environment info
- Version: **2.0.0-37efa55**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. When clicking on "delete" during a file upload the file is removed from the files tab list but in the "file uploads" the file is still displayed as uploading

EDIT: The file keeps on uploading for a few 10s of seconds after we send an abort on it and we don't reject the new parts

### Expected behavior
1. File upload should be listed as aborted

### Steps to reproduce
1. Upload a file from the UI > click on delete while uploading > see list and uploads modal 

### Screenshots or Logs or other output that would be helpful
![upload](https://user-images.githubusercontent.com/10331355/34257225-9e82225e-e661-11e7-9797-597b55f1b388.gif)

**Comment by nimrod-becker** [comment]
Upload from UI has been removed, closing
