### ISSUE TITLE
Agent has status 'Some ports might be blocked' without any reason

### ISSUE THREAD

**Issue by YuliaKovalenko** [noobaa/noobaa-core#4156]
### Environment info
- Version: **2.0.0-fda4028**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. 
![agentsblockedport](https://user-images.githubusercontent.com/12726938/34404241-56711322-ebb5-11e7-8d68-e7ee68bc47d0.PNG)

### Expected behavior
1. healthy agent

### Steps to reproduce
1. Add agents
2. Stop agent via Azure
3. Start agent
Reproduced only ones, used Azure-function for actions with agents

**Comment by nimrod-becker** [comment]
@dannyzaken Do you see a flow in which this is still relevant?
