### ISSUE TITLE
Progress of upgrade package verification and upgrade process is fake

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#4191]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. We are fakeing the progress

### Expected behavior
1. See real progress (some kind of measurement that indicate the actual progress) 

### Steps to reproduce
1. upgrade a system

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
