### ISSUE TITLE
Clicking on an accordion line to expand should automatically scroll according to the relevant position

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4259]
### Environment info
- Version: **2.1.0-924aa6f**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. In the accordion element, when there is a scroll and the user clicks on one of the top lines the expanded line doesn't get focus and the user needs to scroll alone. 

### Expected behavior
1. The focus should be on the current expanded line and the scrolling should be automatically 

### Steps to reproduce
1. Go to bucket page > expand bucket quota, for example,> click on data placement

### Screenshots or Logs or other output that would be helpful
![jan-16-2018 14-17-27](https://user-images.githubusercontent.com/10331355/34988797-aa9d41ec-fac8-11e7-9918-2b8aaf6f5c07.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
