### ISSUE TITLE
Bucket policies accordion buttons should be size small

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4260]
### Environment info
- Version: **2.1.0-924aa6f**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. The buttons are too big

### Expected behavior
1. Btn's height should be 30px as shown in the mock

### Steps to reproduce
1. Go to bucket page> see policies btns

### Screenshots or Logs or other output that would be helpful
System: 
![image](https://user-images.githubusercontent.com/10331355/34988993-751e9790-fac9-11e7-9176-9228db9ccef9.png)

Mock: 
![image](https://user-images.githubusercontent.com/10331355/34989009-82d1bcd2-fac9-11e7-9de1-4455c1e8fdbb.png)

**Comment by nb-ohad** [comment]
@nimrod-becker I don't know if this is still relevant after we moved to the PF like design

**Comment by nimrod-becker** [comment]
@shirimordechay ?

**Comment by shirimordechay** [comment]
There is still a small button by design (small/ medium/ large) but in the system, only 2 sizes are implemented (medium and large). 
It's a low priority task but still relevant.

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
