### ISSUE TITLE
Password validation in "risky data resiliency policy" alert automatically shows an error message when typing

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4262]
### Environment info
- Version: **2.1.0-924aa6f**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. While typing the password we show an error message, not letting the user the option to type all the password even once before the alert shows up. 

### Expected behavior
1. The behavior should be consistent with through the system- the user should receive an error message before finishing typing.
(see reset account password, for example, we don't show an error message before the user finishes typing the password for the first time. on lose focus we show the alert until the password is typed correctly)

### Steps to reproduce
1. In data resiliency policy configure 1 failure tolerance and click on Done > see alert > start typing the password > see alert 

### Screenshots or Logs or other output that would be helpful
![untitled](https://user-images.githubusercontent.com/10331355/34996820-739df20c-fae3-11e7-9d26-e02285dbf548.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
