### ISSUE TITLE
Overview data graph should not drow a line if there is 0 data history (after a point was saved in the db)

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4294]
### Environment info
- Version: **2.1.0-e430184**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. On the data buckets graph when there is 0 data history in nodes cloud and internal there should be "No data uploaded yet" instead of a line.

**Comment by nimrod-becker** [comment]
Already Fixed
