### ISSUE TITLE
add new connection modal does not save when clicking on Save button

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#4377]
### Environment info
- Version: **2.1**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. when adding a new connection, after entering al details, clicking save only perform the validation
2. only when clicking again the connection is actually saved

### Expected behavior
1. be less annoying 

### Steps to reproduce
1. add a new connection
2. enter all the details, and leave the cursor in the last text box
3. click save

### Screenshots or Logs or other output that would be helpful
![jan-31-2018 15-06-57](https://user-images.githubusercontent.com/1476203/35624728-7e26c134-0698-11e8-9fa1-82a0e31072e5.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
