### ISSUE TITLE
No indication for drive in file parts view

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#4422]
### Environment info
- Version: **2.1.2-52e964c**
- Deployment: **AZURE**
- Customer: **demo **

### Actual behavior
1. drill down to file parts - there is no way to tell which drive stores the data

### Expected behavior
1. an indication for a drive

### Screenshots or Logs or other output that would be helpful

![image](https://user-images.githubusercontent.com/3898274/35841424-c07725a8-0ab0-11e8-98f4-c420edbbe3b4.png)

**Comment by nimrod-becker** [comment]
with the move to work in k8s pools instead of seperate hosts, no longer relevant to manage the single drive manually
