### ISSUE TITLE
Failed to configure cluster on Azure

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#4427]
### Environment info
- Version: **2.1.2-52e964c** True for all versions
- Deployment: **AZURE **
- Customer: **demo2.0**

Clean system http://40.65.108.21:8080/fe/systems/clean/cluster/servers/noobaa-93874eab

### Actual behavior
1. NTP setup is required. There is no way to configure NTP without noobaaroot. 

### Expected behavior
1. Need to think about it. Maybe automatically configure the new server with the same NTP configuration instead of asking for pre-configuration @shirimordechay?

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
