### ISSUE TITLE
Failed to create a pool - non informative error

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#4435]
### Environment info
- Version: **2.1.2-52e964c**
- Deployment: **AZURE**
- Customer: **demo2**

### Actual behavior
1. While trying to create a new pool with an invalid host (demo20win, one of the windows machines that manually upgraded with wrong host-id) - getting a message that is not informative. Same happens while trying to join this machine to an existing pool

![image](https://user-images.githubusercontent.com/3898274/35933647-0fa86156-0bf0-11e8-9292-714f218555ad.png)

It's also not clear why the node is visible if it's invalid. 

### Expected behavior
1. True, in this case, it's an unexpected situation that we can't expect, but may happen in another case, and the user won't have an idea what is the cause. Either ignore problematic hosts or give a hint what is the problem (couldn't assign host XXX would be a good start).

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

[log](http://swiggity2.westus2.cloudapp.azure.com:8080/fe/systems/demo/buckets/customers/objects/demo_cluster_diagnostics_issue_4435.tgz
)
2018-02-07T10:00:42.167299-08:00 noobaa WebServer[63530]: [L0]  core.server.system_services.system_store:: SystemStore.make_changes: { insert:    { pools:   
    [ { _id: 5a7b3eca9602b4f82a9061df,          system: 5a5069476384c90442172134,          name: 'austin',          resource_type: 'HOSTS',          pool_nod
e_type: 'BLOCK_STORE_FS',          storage_stats: { blocks_size: 0, last_update: 1518026262164 } } ] } }
2018-02-07T10:00:42.183349-08:00 noobaa WebServer[63530]: [L0]  core.server.system_services.redirector:: publish_to_cluster: server_inter_process load_system
_store undefined [ 'fcall://fcall(2walq57)',  'ws://[::ffff:127.0.0.1]:51420/(349fs5w)',  'ws://[::ffff:127.0.0.1]:51422/(3hukjnq)',  'ws://[::ffff:127.0.0.1
]:51454/(3tqzaws)' ]
2018-02-07T10:00:42.241551-08:00 noobaa WebServer[63530]: [ERROR]  CONSOLE:: RPC._on_request: ERROR srv host_api.migrate_hosts_to_pool reqid 31784@wss://127.
0.0.1:8443(3vnp1g0) connid ws://[::ffff:127.0.0.1]:51472/(3w4k4lx) Error: No such host 1a7bbe02-ceb6-474e-8750-fffffff    at NodesMonitor._get_nodes_by_host_
id (/

**Comment by nimrod-becker** [comment]
Irrelevant
