### ISSUE TITLE
VM restarted - looks like a crash

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#4446]
### Environment info
- Version: **2.1.3-d307870**
- Deployment: **VBOX**
- Customer: **eran test**

### Actual behavior
1. Using my laptop, everything was slow. 
2. Uploaded objects to first.bucket (internal storage only)
3. The VM restarted - maybe crash. Maybe legit. Can't tell.

### Expected behavior
1.  Don't know what was the cause. If it's our code or OS resource starvation. 

### Steps to reproduce
1. Can't exactly. Just tried to upload 2GB objects.  

### Screenshots or Logs or other output that would be helpful

[log](http://swiggity2.westus2.cloudapp.azure.com:8080/fe/systems/demo/buckets/customers/objects/test_cluster_diagnostics_multiple_issues.tgz)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
