### ISSUE TITLE
API allows to set bucket both erasure coding and replicas 

### ISSUE THREAD

**Issue by EroolGui** [noobaa/noobaa-core#4494]
### Environment info
- Version: **2.1.3 65ecabe**
- Deployment: **AZURE **

### Actual behavior
1. API allows calls like this:
`client.tier.update_tier({
            name: res.tiering.tiers[0].tier,
            chunk_coder_config: { data_frags, parity_frags, replicas }
        })`
where all 3 parameters are not empty, e.g.
data_frags = 4,
parity_frags = 2,
replicas = 3,

In this case bucket will be set to erasure coding (4+2) and UI will report that you need minimal 6 agents. But even with 6 agents attached bucket sill be considered not healthy and will use spillover instead of nodes. 

### Expected behavior
1. Error thrown when all 3 parameters have value.
2. Or replicas ignored if data and parity frags have value.

### Steps to reproduce
1. Create a bucket with 6 nodes.
2. Set chunk_coder_config: { 4, 2, 3 }
3. Try to upload file to the bucket
4. Ensure that spillover used instead of agents and bucket shown as not healthy on UI.

**Comment by nimrod-becker** [comment]
Closing no fix
