### ISSUE TITLE
Edit Placement Policy table tooltip issue

### ISSUE THREAD

**Issue by Sergii-Karpiak** [noobaa/noobaa-core#4498]
### Environment info
- Version: 2.2.0
- Deployment: DEV
- Customer: sergii

### Actual behavior
1. tooltip appear in incorrect place (see picture below)

### Expected behavior
1. tooltip should appear below the middle of resource name text

### Steps to reproduce

1. go to bucket
2. click 'Edit Data Placement'
3. Edit Placement Policy modal will appear
4. move button on any resource name in the table

### Screenshots or Logs or other output that would be helpful

![image](https://user-images.githubusercontent.com/27498391/36596785-88cf09b0-18af-11e8-86ea-e398cf30dd8b.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
