### ISSUE TITLE
redundant log information 

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#4499]
### Environment info
- Version: **2.1.4-6781b7b**
- Deployment: **AZURE**
- Customer: **Samsung**

### Actual behavior
1. huge redundant dumps in the logs 
core.sdk.namespace_s3:: NamespaceS3.upload_object

### Expected behavior
1. remove - too much redundant info

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

Feb-22 22:14:11.374 [Endpoint/93695] [L0]  core.sdk.namespace_s3:: NamespaceS3.upload_object: first.bucket { bucket: 'nsbucket-noobaa.first.pool-aws.ns1',
  key: 'ezgif.com-gif-maker.gif',
  content_type: 'image/gif',
  copy_source: undefined,
  source_stream: 
   IncomingMessage {
:

**Comment by nimrod-becker** [comment]
Code is irrelevant, logs are being purged from time to time, can open a new one if new messages are found
