### ISSUE TITLE
Node rebuild progress for drives and pools is incorrect

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#4533]
### Environment info
- Version: **2.1.3-b3379aa**
- Deployment: **AZURE**
- Customer: **Shiri's System**

### Actual behavior
1. I had Linux agent with 4 drives and two additional agents with 1 drives each.
2. The agents had data written on them and I've assigned them to a newly created pool.
3. There were enough agents left for rebuild correctly without errors.
4. I can see inside agent's drives screen that the progress is 0% yet on the same screen, I see that one of the drive's progress is 68%.
5. The same problem happens with pool progress (probably because aggregated from drives)

### Expected behavior
1. The progress bar should be correct and show 68% / 4 instead of 0. 

### Steps to reproduce
1. Create host with 4 drives and additional 5 hosts with 1 drive each.
2. Upload data and store is at some agents
3. Assign hosts with 3 drives and additional 2 hosts to a different pool
4. Wait for a rebuild and look at the progress

### Screenshots or Logs or other output that would be helpful
![screen shot 2018-03-04 at 13 44 31](https://user-images.githubusercontent.com/12246907/36945385-df589d66-1fb5-11e8-85b1-bc54f86419e6.png)
![screen shot 2018-03-04 at 13 41 46](https://user-images.githubusercontent.com/12246907/36945386-df78aa5c-1fb5-11e8-80bd-10795a889b9f.png)

**Comment by nimrod-becker** [comment]
Agent assignment to pools is no longer relevant with k8s pools
