### ISSUE TITLE
Inconsistent info regarding first step of upgrade and non responsive UI

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#4535]
### Environment info
- Version: **2.2.0-12f16da**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. Attempted to downgrade the system
2. Did not get the error screen in the UI and got stuck in uploading model
3. Had to open a new tab and see the error
4. Saw a weird message that contradicts the other message on the same page

### Expected behavior
1. I should see errors that are consistent
2. The model should close and I should be able to see the error instead of opening a new tab

### Steps to reproduce
1. Just downgrade from version 2.2 to 2.1

### Screenshots or Logs or other output that would be helpful
![screen shot 2018-03-04 at 14 46 24](https://user-images.githubusercontent.com/12246907/36945763-4fbb1a5c-1fbb-11e8-9b44-ca0dd9b433bb.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
