### ISSUE TITLE
A cloud connection can be created with incorrect access+secret keys

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4537]
### Environment info
- Version: **2.2.0-6f5d853**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. A cloud connection can be created with incorrect access+secret keys 

### Expected behavior
1. Creation of such a connection should fail with the appropriate error

### Steps to reproduce
1. From the FE - choose to create a new connection, write some junk in the access and secret key fields, press save
2. from the RPC, call for add_external_connection with the made up fields

**Comment by nimrod-becker** [comment]
@liranmauda we don't seem to be able to repro, would love to get more info

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
