### ISSUE TITLE
Bucket policy changes progress and rebuilds should be reflected in the UI

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4550]
### Environment info
Version: 2.2.0-d8ad7fb
Deployment: AZURE
Customer: **User testing**

### Actual behavior
1. The user made resiliency changes and wanted to see what is happening. bucket status was healthy but inside a file page, he saw activity (rebuilding). he wanted to see those changes immediately in the bucket page with a proper progress bar and ETA.

### Expected behavior
1. When making a change in the bucket policies, there should be an indication of what is happening and when is it going to end. 

* Some of the newly planned bucket statuses helps but we still need to add data activity in bucket page. 

### Steps to reproduce
1. Go to bucket page > make any change that will create data rebuild > see the bucket status

### Screenshots or Logs or other output that would be helpful
![bp](https://user-images.githubusercontent.com/10331355/37092723-8f285f5e-2215-11e8-9485-0de03c65c36c.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
