### ISSUE TITLE
Agent fails on a high dense server - too many open FDs

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4554]
### Environment info
- Version: **2.1.3-b3379aa**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
Agent fails on a high dense server due to too many open FDs, the file descriptors are the TCP connections of our P2P between the various agents

### Expected behavior
1. The agent should be able to sustain the needed connections -> open FDs

### Steps to reproduce
1. Get a centos server
2. Create an agent on it
3. Create 64 additional HD 
4. Format the HD (ext4) and mount it
5. See that all of the HD are drives now.
6. Write.

**Comment by nimrod-becker** [comment]
Irrelevant with an agent only available is a container
