### ISSUE TITLE
After selecting (by mouse click) a value from a dropdown list, hit TAB key doesn't clear the dropdown focus

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4581]
### Environment info
- Version: **2.3.0-1013882**
- Deployment: **AZURE
- Customer: **NAME**

### Actual behavior
1. After selecting (with a mouse click) a value from a dropdown list and hit TAB on the keyboard the focus doesn't clear from the drop-down

### Expected behavior
1. The focus shouldn't get stuck

### Steps to reproduce
1. Go to a drop-down (in connections modal for example) > choose one of the drop-down options by mouse > hit TAB key and see the double focus

### Screenshots or Logs or other output that would be helpful
![focus](https://user-images.githubusercontent.com/10331355/37567707-63522204-2ad3-11e8-92dd-d7eaacd72d2c.gif)

[nbfedump.2018_03_18-17_40_40.json.zip](https://github.com/noobaa/noobaa-core/files/1822841/nbfedump.2018_03_18-17_40_40.json.zip)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
