### ISSUE TITLE
Uploading a file from mac of type 'TextEdit.app Document' crashes the UI

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#4589]
### Environment info
- Version: 2.3.0-62467f3
- Deployment: AZURE also local
- Customer: QA

### Actual behavior
1. tried uploading a file with no extension called schema
2. UI crashed - reproduce several times
3. @nb-ohad taken a look at the problem and saw that the file is of type TextEdit.app Document
4. created a new file from TextEdit - automatically saved as RTF - upload worked
5. deleted the extension - tried to upload - UI crashed

### Expected behavior
1. UI shouldn't crash

### Steps to reproduce
1. see Actual Behavior part

### Screenshots or Logs or other output that would be helpful
Aw, Snap!
Something went wrong while displaying this webpage.

**Comment by nimrod-becker** [comment]
Removed upload btn from UI, closing
