### ISSUE TITLE
Upgrade failed on yum rpm corrupted database without the ability to recover 

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4612]
### Environment info
- Version: **2.3.0-1798557**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Upgrade failed on yum rpm corrupted database without the ability to recover
- we can recover with manual intervention. 

### Expected behavior
1. When yum rpm corrupted database appear we should be able to recover.

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
