### ISSUE TITLE
Upload of files larger than 100 Mb fails via the UI

### ISSUE THREAD

**Issue by EroolGui** [noobaa/noobaa-core#4618]
### Environment info
- Version: *2.3.0-5904f07**
- Deployment: **AZURE ** (West US 2)

### Actual behavior
1. After several retries file fails to upload
2. Same file uploads via Cyberduck without failure

### Expected behavior
1. File uploads without issues

### Steps to reproduce
1. Open bucket tab on UI
2. Select any bucket (default first.bucket will fit)
3. Start uploading file with size > 100 Mb
4. Open File Uploads window 

Reproduced with spillover only bucket, disabled spillover bucket and bucket both with nodes pool and spillover

 
### Screenshots or Logs or other output that would be helpful
<img width="1272" alt="screen shot 2018-03-21 at 2 21 29 pm" src="https://user-images.githubusercontent.com/25663645/37722563-fead491e-2d34-11e8-888b-2e91ec51b5be.png">

![screesho111t](https://user-images.githubusercontent.com/25663645/37723104-3c02f6a0-2d36-11e8-99c6-04d974da6dc8.png)

[nbfedump.2018_03_21-18_27_13.json.zip](https://github.com/noobaa/noobaa-core/files/1834211/nbfedump.2018_03_21-18_27_13.json.zip)

**Comment by nimrod-becker** [comment]
Irrelevant, wont fix
