### ISSUE TITLE
diagnostics gaps

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#4658]
### Environment info
- Version: **2.1.3-b3379aa**
- Deployment: **ESX**
- Customer: ** EGA/RAK**

### Actual behavior
~~1. agent diagnostics does not return diags for all drives ~~
~~ - when taking diagnostics of a host with multiple drives we actually collect diags for one of~~ ~~the drives~~
2. when taking agent diagnostics we should add read_host_mappings output to diags
   - currently, read_host_mappings is **very** heavy (~40K per entry of an object). a lot of the data is unnecessary (digests and stuff) for both diagnostics and the UI. we should maybe redefine the API to only return the necessary data and use it foe UI and diags

### Expected behavior
1. diagnostics should be collected for all drives
2. should collect shared information only once (e.g. noobaa.log is shared)

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

**Comment by nimrod-becker** [comment]
1 is irrelevant

**Comment by nimrod-becker** [comment]
Not relevant since moving to pv pool based model
