### ISSUE TITLE
Node installation should indicate an estimation of time to wait

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4668]
### Environment info
- Version: **2.3.1-03f4e14**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When we are installing Node there is no indication how mach time we estimate it can take

### Expected behavior
1. Node installation should indicate an estimation of time to wait

**Comment by nimrod-becker** [comment]
Irrelevant with the remove of an agent outside a container
