### ISSUE TITLE
Creating a AWS connection fails and the UI stuck on the spinner forever

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4710]
### Environment info
- Version: **2.3.1-73a7583**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Creating a AWS connection fails and the UI stuck on the spinner forever
- it doesn't happens every time retrying in a new tab worked.

### Expected behavior
1. We should get a proper error and we should not get stuck.  

### Screenshots or Logs or other output that would be helpful
[nbfedump.2018_04_22-11_02_13.json.zip](https://github.com/noobaa/noobaa-core/files/1935426/nbfedump.2018_04_22-11_02_13.json.zip)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
