### ISSUE TITLE
Rename file in namespace bucket fails via cyberduck

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4711]
### Environment info
- Version: **2.3.1-73a7583**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Rename file in namespace bucket fails via cyberduck fails with internal error.
- we used azure connection

### Expected behavior
1. We should be able to rename

### Steps to reproduce
1. Create a connection to azure
2. Use the connection as a namespace resource  
3. Add a namespace bucket
4. Upload files to it
5. Rename using cyberduck
6. See that it fails.

**Comment by romayalon** [comment]
Does not reproduce using Cyberduck.
