### ISSUE TITLE
Copy a file in namespace bucket fails via cyberduck

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4712]
### Environment info
- Version: **2.3.1-73a7583**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Copy file in namespace bucket fails via cyberduck fails.
- we used azure connection

### Expected behavior
1. We should be able to preform copy

### Steps to reproduce
1. Create a connection to azure
2. Use the connection as a namespace resource  
3. Add a namespace bucket
4. Upload files to it
5. copy/duplicate using cyberduck
6. See that it fails.

**Comment by romayalon** [comment]
Can not reproduce using Cyberduck.
