### ISSUE TITLE
namespace bucket shows wrongly healthy status  

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4714]
### Environment info
- Version: **2.3.1-73a7583**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. namespace bucket shows wrongly healthy status  

### Expected behavior
1. namespace bucket should show the correct status 

### Steps to reproduce
1. Create a connection to azure
2. Use the connection as a namespace resource  
3. Add a namespace bucket with only this connection 
4. Go to azure portal and delete the container
5. See that the bucket status stay healthy although it have no resources connected

**Comment by nimrod-becker** [comment]
Updated as part of NamespaceStores, closing
