### ISSUE TITLE
Overview- Data buckets line graph loading time is very long

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4742]
### Environment info
- Version: **2.4.0-354730e**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. In the overview page- the page is not fully loaded after refreshing the page (or entering for the first time). The data buckets graph loads for a very long time.

### Expected behavior
1. Loading time should be shorter.

### Steps to reproduce
1. Go to overview page > refresh the page

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/39406390-b898d4ea-4bbe-11e8-8531-9c414b48dc2c.png)
[nbfedump.2018_04_29-15_05_48.json.gz](https://github.com/noobaa/noobaa-core/files/1958692/nbfedump.2018_04_29-15_05_48.json.gz)

**Comment by nimrod-becker** [comment]
UI no longer supported
