### ISSUE TITLE
We should give feedback when a node is stuck in migrating state

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#4788]
### Environment info
- Version: **2.5**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **dev**

### Actual behavior
1. When a node is moved to a different pool and data can't be moved from it the node will be in `MIGRATING` state forever
2. many times we know in the backend what are the reasons for that, and which blocks are problematic.
3. we should add some kind of troubleshooting page for the node\host, so we can forward this knowledge to the user.

### Expected behavior
1. add information on errors encountered during node rebuilds
2. when possible provide instructions on how to fix the situation

example from Shiri's server: a node was stuck on migrating. when we checked the file parts that are pending we saw that the bucket's placement policy was empty. this case can be easily solved by the user if feedback is given, but without it, it is difficult to identify the problem by the user

**Comment by nimrod-becker** [comment]
Node migration flows anymore
