### ISSUE TITLE
When a node is servicing as S3 endpoint only, the storage bar/ pie should be ignored/ disabled

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4794]
### Environment info
- Version: **2.5.0-1ca9fdb**
- Deployment: **AZURE 
- Customer: **NAME**

### Actual behavior
1. When a node is servicing as an S3 endpoint only, the usage bar/ pie looks fully used. It's confusing. 

### Expected behavior
1. Disable/ don't show node's usage when the service is S3 only

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/40173242-d63ec616-59d9-11e8-9bf8-59e21aab4a0b.png)

![image](https://user-images.githubusercontent.com/10331355/40173251-de31bec8-59d9-11e8-8541-17e9cccb45ad.png)

**Comment by nb-ohad** [comment]
Not relevant anymore - We do not allow disabling of a node storage service.

**Comment by nimrod-becker** [comment]
Coming very soon

**Comment by nimrod-becker** [comment]
Will be closed with the separation of endpoints into their own deployment

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Standalone endpoints](https://trello.com/c/LNrzkoOq/907-standalone-endpoints)

**Comment by nimrod-becker** [comment]
Relates to #5825

**Comment by nb-ohad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint UI/UX](https://trello.com/c/9Zrgc4To/924-endpoint-ui-ux)

**Comment by nimrod-becker** [comment]
endpoints seperated from nodes, irrelevant
