### ISSUE TITLE
When trying to add cluster we don't recheck the candidate on each Next press

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#4835]
### Environment info
- Version: 2.6
- Deployment: AZURE
- Customer: QA

### Actual behavior
1. trying to add a cluster member with unreachable IP - check fails
2. fixed something in the background - wants to try it again - no check - fails immediate

### Expected behavior
1. I want to check the candidate evertime i send next. i don't wan't to change the IP twice in order to check the candidate

### Steps to reproduce
1. try to add a cluster member which you can't reach - or has any other issue
2. fix the issue and try to press next again - it will fail without checking with BE

### Screenshots or Logs or other output that would be helpful
[nbfedump.2018_05_30-16_32_33.json.gz](https://github.com/noobaa/noobaa-core/files/2054128/nbfedump.2018_05_30-16_32_33.json.gz)

**Comment by nimrod-becker** [comment]
Irrelevant for now, flow changed
