### ISSUE TITLE
New ESX server is getting DHCP by default why it shouldn't

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#4840]
### Environment info
- Version: **2.6.0-2c95897**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When we installing fresh new ESX server, it gets DHCP by default

### Expected behavior
1. We should not get any ip from the DHCP by default.

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
