### ISSUE TITLE
cannot upload from Cyberduck using azure blob API (append blob)

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#4879]
### Environment info
- Version: **2.6**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. Cyberduck is using append blobs for uploads which we don't support yet.
2. currently we are not supporting append blocks, so all uploads from Cyberduck fails

### Expected behavior
1. in order to support Cyberduck we need to implement append blob operations.
2. append blob is a specific case of block blobs, and we can support it using the functionality added for put block\blockList (https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs)

### Steps to reproduce
1. upload from Cyberduck using blob API

**Comment by nimrod-becker** [comment]
Blob API no longer supported
