### ISSUE TITLE
No indication for V2/ V4 signature version after S3 compatible resource is created

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4893]
### Environment info
- Version: **2.7.0-55dd2c7**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. After creating a new cloud resource of generic S3 compatible there is no indication for with version is used (V2/ V4). (it is shown only in the connection tooltip for now)

### Expected behavior
1. The signature version should be indicated in the resource tooltip text. 

### Steps to reproduce
1. Create a cloud resource using a Generic S3 compatible connection > see resource table

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/41410906-af9e8576-6fe3-11e8-9e85-743f5c106d24.png)

**Comment by nimrod-becker** [comment]
@shirimordechay Are we talking about the resource table only or other places as well (for example resources in the bucket page or parts list)

**Comment by nimrod-becker** [comment]
Should be in all places

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
