### ISSUE TITLE
In object page with versions, switching between versions causes the bars to load twice, once for 0 bytes and once for the actual size

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#4972]
### Environment info
- Version: **2.8.0-160bdf3**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. In object page with versions, switching between versions in the drop down causes the bars to load twice, 1 for 0 bytes and 1 for the actual size

### Expected behavior
1. Bars should only load once. if it takes time to calculate the correct number it's better to show a loader for a second then loading 2 different numbers and grab the user attention to that direction for no reason. 

### Steps to reproduce
1. Go to object page > switch between versions in the dropdown

### Screenshots or Logs or other output that would be helpful
![bars switch](https://user-images.githubusercontent.com/10331355/42636402-68b7b42e-85f1-11e8-9a0c-8dd3ef0cd531.gif)

**Comment by nimrod-becker** [comment]
UI no longer supported
