### ISSUE TITLE
rsyslog is not writing to noobaa.log after logrotate failure

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5003]
### Environment info
- Version: **2.8**
- Deployment: **ALL**
- Customer: **NAME**

### Actual behavior
1. encountered an empty `noobaa.log` on Shiri's system
2. restarting rsyslog using `systemctl` fixed the problem
3. in `/var/log/messages` I saw this line: 
```
2018-07-22T03:49:02.536596+03:00 noobaa logrotate[97887]: ALERT exited abnormally with [1]
```
4. the dates don't seem to match since the last log file was on July 17. 
5. also the last compressed log was `/var/log/noobaa.log-20180717.gz` which is in a different format than `noobaa.log.1.gz`. this can indicate that a logrotate failure somehow got things  to get stuck.

### Expected behavior
1. rsyslog should always write to `noobaa.log`

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

**Comment by nimrod-becker** [comment]
irrelevant
