### ISSUE TITLE
ETA is 4 minutes for over 5 hours

### ISSUE THREAD

**Issue by tamireran** [noobaa/noobaa-core#5053]
### Environment info
- Version: **2.8.2-dc9d106**
- Deployment: **AZURE **
- Customer: **demo**

### Actual behavior
1. stopped most of the node, but left enough nodes to handle the data. ETA is 4 minutes for over 5 hours. 
Even if there are no available nodes, we should indicate it instead of such ETA. 
I checked each one of the nodes, all seems healthy.

Might be part of Jacky's next task, so low priority for now
### Expected behavior
1.

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/3898274/43689849-dd949c2e-9908-11e8-85fa-5f79332e11e1.png)

**Comment by nimrod-becker** [comment]
UI no longer supported
