### ISSUE TITLE
Cluster | After upgrade all nodes are down

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5090]
### Environment info
- Version: **2.9.0-aa129f6**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. after upgrade from 2.9.0-aa129f6 to 2.9.0-aa129f6 (same version) all nodes are down
@jeniawhite saw that the agents are getting the correct master ip. 

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/44332362-86d3f700-a474-11e8-9c26-e02df4e126a5.png)

@jeniawhite saw the bug.

**Comment by nimrod-becker** [comment]
Irrelevant with k8s sts nodes
