### ISSUE TITLE
On cluster master change UI shows upgrading page

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#5092]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. After the master change, the UI shows the upgrading page and then, later on, shows the UI normally.

### Expected behavior
1.

### Steps to reproduce
1. Change the master and attempt to connect

### Screenshots or Logs or other output that would be helpful
![screen shot 2018-08-22 at 17 00 20](https://user-images.githubusercontent.com/12246907/44468126-3358d900-a62d-11e8-82af-72a5a3c52e0f.png)

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
