### ISSUE TITLE
Cluster attach on NTP configuration validation only runs once

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#5095]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. I wanted to attach a server to a cluster and did not configure the NTP on the attaching server
2. When I saw the message to configure the NTP, I've opened a new tab and configured the NTP
3. I went back and couldn't proceed to attach the server since it won't run the validation once again

### Expected behavior
1. Should run the validation once again and let me attach the server

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
![screen shot 2018-08-26 at 14 36 49](https://user-images.githubusercontent.com/12246907/44627842-87213600-a93d-11e8-9227-f5d94a01ef7e.png)
[nbfedump.2018_08_26-14_39_01.json.gz](https://github.com/noobaa/noobaa-core/files/2321477/nbfedump.2018_08_26-14_39_01.json.gz)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
