### ISSUE TITLE
On master change the UI crashed when opening a new tab

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#5096]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. Just did a master change and opened a new tab with the old address
2. After waiting for a couple of seconds I've opened another tab and got redirected to the new master

### Expected behavior
1. I should either see the relevant server or nothing
2. I should not see WORKAROUND user and etc...

### Steps to reproduce
1. Change the master
2. Open a new tab and paste the old address

### Screenshots or Logs or other output that would be helpful
[nbfedump.2018_08_26-15_29_08.json.gz](https://github.com/noobaa/noobaa-core/files/2321499/nbfedump.2018_08_26-15_29_08.json.gz)
![screen shot 2018-08-26 at 15 28 39](https://user-images.githubusercontent.com/12246907/44628283-4c230080-a945-11e8-9744-19561e1e7879.png)

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
