### ISSUE TITLE
When pop up notification have a big name it gets a slide bar

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5097]
### Environment info
- Version: **2.8.1-9587959**
- Deployment: **AZURE **
- Customer: **QA**

### Actual behavior
1. when pop up notification have a big name it gets a slide bar

### Steps to reproduce
1. Write a file with a big name (or path)
2. Delete it

### Screenshots or Logs or other output that would be helpful
![popup_notification](https://user-images.githubusercontent.com/28217223/44628587-665fdd00-a94b-11e8-8ab3-9387f32cffaf.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
