### ISSUE TITLE
After a lot of writes/deletes on the internal storage,  the bg_workers and webserver crashed

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5105]
### Environment info
- Version: **2.8.1-9587959**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1.  after a lot of writes/deletes on the internal storage,  the bg_workers and webserver crashed.
```
[root@noobaa ~]# supervisorctl status all
STUN                             RUNNING   pid 1133, uptime 2 days, 2:03:25
bg_workers                       RUNNING   pid 53073, uptime 1:43:56
hosted_agents                    RUNNING   pid 1132, uptime 2 days, 2:03:25
mongo_wrapper                    RUNNING   pid 1124, uptime 2 days, 2:03:30
s3rver                           RUNNING   pid 1128, uptime 2 days, 2:03:25
webserver                        RUNNING   pid 53063, uptime 1:43:58
``` 

there is swap file on the machine:
```
[root@noobaa ~]# swapon -s
Filename				Type		Size	Used	Priority
/swapfile                              	file	8388604	661760	-1
```

### Screenshots or Logs or other output that would be helpful
https://wusdiagnostics.blob.core.windows.net/bootdiagnostics-a01-d7649d46-977a-4ddb-b815-dc80b34c0bea/a01.d7649d46-977a-4ddb-b815-dc80b34c0bea.screenshot.bmp?sv=2017-11-09&ss=bqtf&srt=sco&sp=rwdlacup&se=2018-08-28T17:31:28Z&sig=eXmtx8MIMSLSIZVWid65R7LZqjOrH2oXyoc02Cap6vY%3D

**Comment by nimrod-becker** [comment]
@liranmauda @jeniawhite still relevant?
