### ISSUE TITLE
UI/UX | "Change Cluster Connectivity IP" moduel text and location

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5127]
### Environment info
- Version: **2.9.2-a09fff9**
- Deployment: **AZURE**
- Customer: **QA**

1. Should the "Change Cluster Connectivity IP" button be only on the master?
2. there is a difference between the module name ("Change Cluster Connectivity IP") to the fields names (they contain the word "server")
3. the explanation have some issues: "Before updating the following fields, go to the linux installer or local DNS server and change the server IP. Once done, fill the following fields:"
 -  "linux installer" need a clarification that it is via the console.
 -  the explanation contain server and the module is cluster. 

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/45477863-3b4afb00-b74b-11e8-92d8-f8e355c511bf.png)

![noobaa_management_console](https://user-images.githubusercontent.com/28217223/45478217-13a86280-b74c-11e8-8f94-643f348508ae.png)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
