### ISSUE TITLE
in the UI, Switching pages when running package validation will start the count from the beginning.

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5155]
### Environment info
- Version: **2.9.2-a09fff9**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Switching pages when running validate will start the count from the beginning.
- It doesn't happens in the uploading
- The validation is actually working tn the BE.

### Expected behavior
1. Switching pages when running validate should not start the count from the beginning.

### Screenshots or Logs or other output that would be helpful
![swich_page_starts_validate_count_from_the_begining](https://user-images.githubusercontent.com/28217223/46736748-7b49c300-cca2-11e8-817a-1437ca8aec03.gif)

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal. Upgrade will be done via k8s (either initiated by the user or not, it will still be an unmanaged path)
