### ISSUE TITLE
In "Data Insights" the circle is cut off

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5160]
### Environment info
- Version: **2.10.0-a10539e**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. in "Data Insights" the circle is cut off

### Expected behavior
1.  the Y and the X should be bigger

### Screenshots or Logs or other output that would be helpful
![noobaa_management_console](https://user-images.githubusercontent.com/28217223/46915122-915fc800-cfaf-11e8-847a-fc4a65029cd5.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
