### ISSUE TITLE
Cloud service consumption tab in analytics flickers non-stop

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5164]
### Environment info
- Version: **2.10.0-61ae4b9**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. Cloud service consumption tab in analytics flickers non-stop (you don't need to do anything, depending on screen resolution I think) 

### Expected behavior
1. Stop flicker!

### Steps to reproduce
1. Go to analytics -> Cloud service consumption tab

### Screenshots or Logs or other output that would be helpful

![oct-15-2018 14-17-59](https://user-images.githubusercontent.com/10331355/46948186-ce968980-d085-11e8-9da0-e4bc8997a40f.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
