### ISSUE TITLE
Data insights bubble chart: assigned colors to buckets/ data type should not change

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5169]
### Environment info
- Version: **2.10.0-5befaf4**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. The bubbles colors in the bubble chart change according to data changes (new bucket added for example), it's very confusing since the user connected the bubble color to the bucket and will not check the bucket name every time

### Expected behavior
1. Bubbles colors should not change according to the data changes.

### Steps to reproduce
1. Go to data insight bubble chart -> see buckets related colors -> create a new bucket and upload data -> see bubble chart changes

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
