### ISSUE TITLE
list_hosts might return partial host info, which crashes UI

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5221]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. a race condition between adding new node and list_hosts can result in list_hosts returning partial information.
2. the problem is that `consolidate_host` can choose as a root_item a node where `item.node_from_store` is undefined. in that case `update_status` will skip it so some fields like `connectivity` are not set.
3. get_host_info will then return partial info in list_hosts

### Expected behavior
1. list_hosts should return all information for a host, the same as for nodes

### Suggested Fix
1. I tried to change `_handle_agent_response` to only add nodes to `_map_host_id`. it caused many unit tests to fail. didn't put too much effort into finding the problem.

### Steps to reproduce
1. try to list_hosts while agents are added
2. look for hosts that do not have `connectivity` property

**Comment by nimrod-becker** [comment]
@dannyzaken Still relevant with the k8s pools changes?

**Comment by dannyzaken** [comment]
I think it's still relevant for the partial info that is being returned. I am not sure how it affects the UI now.  @nb-ohad, any idea?

**Comment by nimrod-becker** [comment]
@nb-ohad ping

**Comment by nimrod-becker** [comment]
frontend no longer supported
