### ISSUE TITLE
Tiering | migration between tier 1 to tier 2 is not happening.

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5230]
### Environment info
- Version: **2.10.0-8b90705**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. migration between tier 1 to tier 2 is not happening. when we reach the point of migration we can see that the files are not migrating which leaves the first tier without space and new write are failing. 

### Expected behavior
1. file should be migrated

### Steps to reproduce
1. run tier_test

### Screenshots or Logs or other output that would be helpful
logs:
https://console.cloud.google.com/storage/browser/liran-test/tier_logs/?project=noobaa-test-1

**Comment by nimrod-becker** [comment]
Fixed with #5500
