### ISSUE TITLE
UI lists occasionally doesn't load until refreshing the page

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5232]
### Environment info
- Version: **2.10.0-8b90705**
- Deployment: **AZURE**
- Customer: **NAME**

### Actual behavior
1. Lists in the UI occasionally doesn't finish the load.
** Might be related to the fact that I am currently using the internal storage+ versioning.

### Expected behavior
1. If the UI crashes, show an error message

### Steps to reproduce
1.
[nbfedump.2018_11_20-14_08_37.json.gz](https://github.com/noobaa/noobaa-core/files/2599614/nbfedump.2018_11_20-14_08_37.json.gz)

### Screenshots or Logs or other output that would be helpful
2.10.0-8b90705

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
