### ISSUE TITLE
we don't have a link in the tool bar when we try to delete a pool and we cant due to an error

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5246]
### Environment info
- Version: **2.11.0-053654d**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. we don't have a link in the tool bar when we try to delete a pool and we cant due to an error

### Expected behavior
1. when we cannot delete the pool due to an error, we should have a link n the tool bar

### Screenshots or Logs or other output that would be helpful

![screen shot 2018-11-25 at 14 42 21](https://user-images.githubusercontent.com/28217223/48979248-7dd07280-f0c0-11e8-84f1-fc1aef0a44ff.png)

**Comment by nimrod-becker** [comment]
Irrelevant with the change into kube pools
