### ISSUE TITLE
mongo_client preforms many reconnects to db due to replSetGetStatus timeout

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5263]
### Environment info
- Version: **2.10.2**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **Demo**

### Actual behavior
1. mongo_client was unresponsive due to many reconnects caused by timeouts in `get_mongo_rs_status` 
2. timeout is set to 5 seconds by default. whenever the request is timed out reconnect is called. 
3. this eventually causes a chain of many disconnects and mongo_client is not able to function

### Expected behavior
1. `replSetGetStatus` should not cause such a severe result
2. one possible solution is to cache the result of last `replSetGetStatus` for a few seconds before requesting again. this can reduce the number of requests from mongo

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
Irrelevant with k8s HA implementation, closing
