### ISSUE TITLE
Function page: Execution function/ file display name on code tab is too short and looks like it’s loading

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5297]
### Environment info
Version: 2.11.0-65f4306
Deployment: **AZURE **
Customer: NAME

### Actual behavior
1. In the code tab on the function page, the execution function name or file name doesn't have enough place to display the names and each of the labels are shown with "...", it very confusing, especially when there is plenty of space to display the full name

### Expected behavior
1. Show the full names or at least give it more space (responsiveness/ breakpoints needed)

### Steps to reproduce
1. Go to function page > see names in the code tab

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/51847567-a5dc8c00-2324-11e9-846c-9f44d9f43967.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
