### ISSUE TITLE
Function page: View code area looks editable and the edit inline code modal it looks non-editable… very confusing

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5298]
### Environment info

Version: 2.11.0-65f4306
Deployment: **AZURE **
Customer: NAME

### Actual behavior
1. The code preview looks editable and the user will try to click and edit the code. 
The edit inline code (in the modal) DOESN'T look editable... 

### Expected behavior
1. In the edit code modal show the editor view, in the preview shows the "not-editable" look

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

Which one looks editable? 
![image](https://user-images.githubusercontent.com/10331355/51850162-dd016c00-2329-11e9-873f-aacb24e9a23e.png)

![image](https://user-images.githubusercontent.com/10331355/51850173-e559a700-2329-11e9-9332-977c2a968d68.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
