### ISSUE TITLE
Function page: Set event and invoke- missing feedback modal 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5299]
### Environment info

Version: 2.11.0-65f4306
Deployment: **AZURE **
Customer: NAME

### Actual behavior
1. After clicking on invoke nothing really happens (no response) for a very long time and the result is shown in a popup notification 

### Expected behavior
1. The invoke btn should show a working process and a result modal should appear after (error/ success) 

See example as planed in the mock: https://invis.io/HNN0XFXV46F 

### Steps to reproduce
1. Invoke an event in the function page

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/51850655-d8898300-232a-11e9-8625-0da9c440affe.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
