### ISSUE TITLE
Show popup blocked message (for example on open code in the functions section)

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5305]
### Environment info
- Version: **2.11.0-65f4306**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. The button doesn't do anything  

### Expected behavior
1. It should open the file content 

### Steps to reproduce
1.
[nbfedump.2019_01_30-13_55_42.json.gz](https://github.com/noobaa/noobaa-core/files/2812392/nbfedump.2019_01_30-13_55_42.json.gz)

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/51979656-5e760d00-2496-11e9-9dca-0764d73a0d60.png)

![image](https://user-images.githubusercontent.com/10331355/51979642-56b66880-2496-11e9-96f3-b8e031f614b8.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
