### ISSUE TITLE
in azure - setting search domains causes the server to become inaccessible

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5337]
### Environment info
- Version: **3.0**
- Deployment: **AZURE**
- Customer: **none**

### Actual behavior
1. after updating the search domains in an azure server, it becomes inaccessible through the network
2. this could be a result of performing `systemctl restart network` in `os_utils._set_search_domains - when I tried to run the command in the shell I get the same result (no connectivity)
3. I also got no connectivity a few seconds after updating `DOMAIN=` in `/etc/sysconfig/network-scripts/ifcfg-eth0`. not sure if it's a coincident or some script running in azure

### Expected behavior
1. we should either make it work or disable **Search Domains** updating in azure

### Steps to reproduce
1. update search domain in DNS configurations

### Screenshots or Logs or other output that would be helpful

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
