### ISSUE TITLE
Changing server host name on Azure server crashes the system

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5346]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE
- Customer: **NAME**

### Actual behavior
1. Go to server page > edit details > change hostname and save

### Expected behavior
1. It shouldn't crush :)

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
