### ISSUE TITLE
Updating server secondary DNS doesn't update and crashes the system 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5358]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1. When adding secondary DNS and clicking update, nothing happens and the server crashes.

### Expected behavior
1. The DNS should be updated successfully 

### Steps to reproduce
1. Go to environment DNS settings -> edit -> add a secondary DNS and update

**Comment by nimrod-becker** [comment]
No longer relevant due to OVA deployment support removal
