### ISSUE TITLE
UI should have auto logout after some period of idle time

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5385]
### Environment info
- Version: **3**
- Deployment: **NA**
- Customer:  **@cwilkers**

### Actual behavior
1. Leave the UI on for indefinite amount of time
2. It stays logged in.

### Expected behavior
1. Should logout after some amount of idle time.

### Steps to reproduce
1. See above.

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
