### ISSUE TITLE
The graph in "Resources -> Cloud Resources -> <name> -> Connected Buckets" should be centralized 

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5395]
### Environment info
- Version: **3.0.0-628423d**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. In Resources -> Cloud Resources -> <name> -> Connected Buckets, When switching to graph view, it is not centralized

### Expected behavior
1. The graph should be centralized 

### Screenshots or Logs or other output that would be helpful
![NooBaa_Management_Console](https://user-images.githubusercontent.com/28217223/55333984-feedab00-54a0-11e9-85fb-be3728773915.png)

**Comment by nb-ohad** [comment]
we decided to leave it on the left but add borders and background 
![image](https://user-images.githubusercontent.com/14993359/64334504-56a8b900-cfe1-11e9-821d-79a2d7a0e159.png)
