### ISSUE TITLE
Inconsistency in Inline validation for multiple requirements behavior 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5414]
### Environment info
- Version: **3.0.0-ca72b65**
- Deployment: **AZURE **
- Customer: **NAME**

### Actual behavior
1.Inconsistency in Inline validation for multiple requirements behavior (such as in create password/ bucket/ pool). some of the fields show the error message while typing some on losing focus/ submit.

### Expected behavior
1. As designed: 
Positive validation should be as shown- while typing. 
Errors should only be "red" after losing focus, there is no reason to tell the user he was wrong before he finished typing. leave the "not yet validated" bullets gray and the "validated" bullets green. when the user leaves the text field (focus/ submit) change the validation to red.

### Steps to reproduce
1. See create bucket vs. reset password.

### Screenshots or Logs or other output that would be helpful
![changepass](https://user-images.githubusercontent.com/10331355/55941373-c2f9d900-5c4a-11e9-89b9-3b21c95d8171.gif)
![bucket name](https://user-images.githubusercontent.com/10331355/55941390-ca20e700-5c4a-11e9-867c-f5d2a45538b7.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
