### ISSUE TITLE
Remove current password from reset password form

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5417]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. Currently a user need to enter his current password in order to select a new password after login with expired password 

### Expected behavior
1. We should remove the current password and get it from the last step

### Steps to reproduce
1. reset a user password then change try to login with that user

The main problem is that the current code base for these screens (old arch) does not allow us to pass the password from the last screen to this screen. We need to move the screens (and also login-layout) to the new arch in order to achieve the desired result.

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/14993359/55954820-63aac180-5c68-11e9-8fda-93cee89d10f3.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
