### ISSUE TITLE
Jump in table lines (for some tables) when hovering on delete button

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5426]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. There is a jump when hovering on delete button

### Expected behavior
1. There shouldn't be any jump

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful
![recording](https://user-images.githubusercontent.com/14993359/56131947-7f2c0a00-5f91-11e9-916c-a5d01fa95ddd.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
