### ISSUE TITLE
Create account modal - browser does not scroll to focused toggle

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5428]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. if even 1 px of the toggle is in view - because of user navigation/scrolling the browser will not scroll the toggle into full view 

### Expected behavior
1. should scroll the toggle into full view event if some of the toggle is out of the scroll box

### Steps to reproduce
1.

### Screenshots or Logs or other output that would be helpful

![Mar-03-2019_14-14-36](https://user-images.githubusercontent.com/14993359/56132390-83a4f280-5f92-11e9-9b10-122cfdb64421.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
