### ISSUE TITLE
Tables header does not behave as it should on scroll

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5432]
### Environment info
- Version: **VER3.0.0-2f62836**
- Deployment: **AZURE |**
- Customer: **NAME**

### Actual behavior
1. When scrolling in a table, the header line turns transparent and the scrolled content is still visible. 

### Expected behavior
1. The header line should be sticky and data should not be visible after leaving the content area.

### Steps to reproduce
1. Scroll in any of the following: edit resources, add tier, create bucket, assign nodes (both), objects tab, any other possible scrolling lists. 

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/56202610-1e153c80-604c-11e9-9a40-e94bb3bad9a2.png)
![image](https://user-images.githubusercontent.com/10331355/56202646-32593980-604c-11e9-8afd-b03c2a4dbe54.png)
![image](https://user-images.githubusercontent.com/10331355/56202680-43a24600-604c-11e9-959b-0733777155c2.png)

**Comment by jackyalbo** [comment]
still happens on 4.0

**Comment by shirimordechay** [comment]
Also on 5.1 tables
