### ISSUE TITLE
Redundant requirement in reset password screen

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5439]
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. "This field is required" - no need for that.

### Expected behavior
1. 

### Steps to reproduce
1. Create a new user and login with it/ reset a user password and try login.

### Screenshots or Logs or other output that would be helpful
![image](https://user-images.githubusercontent.com/10331355/56489763-78e6e200-64eb-11e9-9a9b-9e1095f7eeb8.png)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
