### ISSUE TITLE
Changing a multi-file function to a one-file zip shows an error message on execution file dropdown and prevent editing

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5448]
### Environment info
- Version: **3.0.0-499e226**
- Deployment: **KUBERNETES | AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. Editing an existing function (that was created with multi-files zip) and changing the zip to one file shows an unnecessary error message "Please choose an execution file name" even do it's disabled.

### Expected behavior
1. Once the file was changed identify if it's a multi-files zip or one file and show the correct indications

### Steps to reproduce
1. Go to functions -> create a new func using multi-files zip -> edit code-> upload a one file zip-> save and see the wronf error

### Screenshots or Logs or other output that would be helpful

![image](https://user-images.githubusercontent.com/10331355/56896646-f33bd700-6a94-11e9-9ab1-f9c417548fc3.png)

https://www.loom.com/share/77052e43b5624a70bad210c0533dfb2e

**Comment by nimrod-becker** [comment]
Fixed with #5710
