### ISSUE TITLE
Add a new cloud connection (async) validation is not properly implemented and interrupts the user flow 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5465]
### Environment info
- Version: **3.0.0-499e226**
- Deployment: **AZURE **
- Customer: **Chandler Wilkerson**

### Actual behavior
1. In the add connection process, the validation only starts after clicking on the "Save" button/ on lose focus. The feedback is always negative: an "error" feedback is received ("no no no effect").This implementation is confusing and doesn't match the system behavior. 
The user was surprised and wasn't sure what did he do wrong.

### Expected behavior
1. The validation should occur on submit, if the validation process is not done, show a "process" button until validation is completed. 

### Steps to reproduce
1. Create a new connection -> see feedback on "Save"

### Screenshots or Logs or other output that would be helpful

https://www.loom.com/share/5583e017208c4c519ea0c591e3658e5a

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
