### ISSUE TITLE
Installation without internet - can't pull image from docker hub?

### ISSUE THREAD

**Issue by meirhazonAnyVision** [noobaa/noobaa-core#5473]
Hello,

I am trying Noobaa, we deploy our product on prem and sometimes we do not have internet access, I have noticed that you access the internet for getting "S3 access keys from NooBaa system" during the installation.

Do you have a solution for an installation with no internet access?

Thanks so much,

Meir

**Comment by guymguym** [comment]
Hi @meirhazonAnyVision, thanks for reaching out!

- Which platform are you using? VBox, KVM, Kubernetes/Openshift?

- Can you share a screenshot or describe when in the installation flow you see this occurring? We don't have a real need for an internet connection during install, but I might be missing something that was leftover.

Yours truly,
Guy

**Comment by meirhazonAnyVision** [comment]
Hi,

Thanks so much for the quick prompt.
Kubernetes v1.14.1

statefulset.apps/noobaa-server created

Waiting for external IPs to be allocated for NooBaa services. this might take several minutes
Getting S3 access keys from NooBaa system. Waiting for NooBaa to be ready

Could not get S3 access keys. NooBaa did not become ready for over 10 minutes
Once the pod 'noobaa-server-0' is ready you can get S3 keys using 'noobaa_deploy_k8s.sh info' or from the management console

**Comment by guymguym** [comment]
I see, so this is when the pods are waiting for their image to be pulled from docker hub, which is the default registry we deploy with, but it can be easily changed. What we need in this case is to copy the image to your registry, and then update the deployment to refer to it.

1. Save the image from a host that can access the internet:
```
docker pull noobaa/noobaa-core:3.0.0
docker save noobaa/noobaa-core:3.0.0 | gzip > noobaa-core-3.0.0.tar.gz
```

2. Load the image tar `noobaa-core-3.0.0.tar.gz` on a host that can access your registry - you will need to identify your registry address in the tag name for the pod to know where to pull it from:
```
docker load < noobaa-core-3.0.0.tar.gz
docker tag noobaa/noobaa-core:3.0.0 <registry-host>:<port>/noobaa/noobaa-core:3.0.0
```

3. In the installation instructions, update the image address locally before starting the deploy:
```
wget https://raw.githubusercontent.com/noobaa/noobaa-core/master/src/deploy/NVA_build/noobaa_deploy_k8s.sh
wget https://raw.githubusercontent.com/noobaa/noobaa-core/master/src/deploy/NVA_build/noobaa_core.yaml
chmod +x noobaa_deploy_k8s.sh

# update the image address
sed -i -e 's|image: noobaa/noobaa-core:3.0.0|image: <registry-host>:<port>/noobaa/noobaa-core:3.0.0|g' noobaa_core.yaml

./noobaa_deploy_k8s.sh deploy -e <youremail> -n <namespace> -f noobaa_core.yaml
```

Let me know if any step here is not clear to you and I will elaborate.

**Comment by meirhazonAnyVision** [comment]
Hi,

I was referring to the following "Getting S3 access keys from NooBaa system" and not to the image download.

Getting the S3 doesnt require internet access?

It also relate to, https://github.com/noobaa/noobaa-core/issues/5474

Thanks,

Meir

**Comment by guymguym** [comment]
The message you see from the script is unrelated, unfortunately.
The script just creates the resources and then waits for the system to respond in order to show you the S3 keys for you to use, and since the pod never runs because the image is not available, the script complains.

You can easily see it with the following command:
```
kubectl -n <noobaa-namespace> describe pod/noobaa-server-0
```

And at the end of the output, you will see the `Events:` section which should probably say that the pod is failing to get the image.

Or at least, let's verify that this is really the case first.

**Comment by meirhazonAnyVision** [comment]
Thanks

**Comment by guymguym** [comment]
@meirhazonAnyVision Just to make sure I answer your question if we require internet to get S3 access keys - the answer is no - once we can pull the image from a private registry, the system will be fully functional using internal-network. 

Keep in mind that you will not be able to connect public-cloud-resources [as shown here](https://noobaa.desk.com/customer/en/portal/articles/2852133-create-a-cloud-resource) and you will also have to sync your private registry when you want to upgrade to a new version.

Let me know if loading the image to your registry resolve this issue. Is this how you typically import software into your cluster?

BTW if you want to talk to us on slack,  you can register here - www.noobaa.io/community and we will send you a slack invite.

**Comment by nimrod-becker** [comment]
@meirhazonAnyVision the deployment script was deprecated in favor of the operator (https://github.com/noobaa/noobaa-operator). I would love to get feedback / you experience if you want to try that path.

Closing this issue.
