### ISSUE TITLE
Why do I need external IP for Noobaa

### ISSUE THREAD

**Issue by meirhazonAnyVision** [noobaa/noobaa-core#5474]
Hello,

I am trying Noobaa,  our applications address our object store from within kubernetes mesh. why must I use external IPs for Noobaa?

In the following case its a NATed IP, I have got the following error, but I do not wish to use any external IP, Nated or not. 

How can I fix it in Nated IP?

How can I fix it for mesh Kubernetes IPs only?

Kubernetes v1.14.1

================================================================================
Could not identify an external IP to connect from outside the cluster
External IP is usually allocated automatically for Kubernetes clusters deployed on public cloud providers
You can try again later to see if an external IP was allocated using 'noobaa_deploy_k8s.sh info'

Thanks so much,

Meir

**Comment by guymguym** [comment]
I think this is still related to not being able to get the container image from docker hub without internet access as we are discussing in #5473. Let's keep this open for now and see if this is also resolved once we copy the image to your private container registry.
Thanks!

**Comment by meirhazonAnyVision** [comment]
Hi Guy,
There is an internet access in these cases. the IP is NATed in this case. 
I was referring to a general need to install without internet access.
Any how, WITH internet access but with a NATed IP (Google cloud) You give an error, it looks like you are trying to access the machine using a New connection.
Can you please read the case again?
Thanks so much,
Meir

**Comment by meirhazonAnyVision** [comment]
Hi Guy,
I have an external IP, please look. It was there at all time. I am using ports 6001 and 6443.
root@noobaa-1:~# kubectl get svc
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                                                                    AGE
kubernetes           ClusterIP      10.233.0.1      <none>         443/TCP                                                                                                    95m
netchecker-service   NodePort       10.233.18.154   <none>         8081:31081/TCP                                                                                             94m
noobaa-mgmt          LoadBalancer   10.233.5.64     35.187.25.10   8080:31015/TCP,8443:30091/TCP,8444:32721/TCP,8445:32608/TCP,8446:30423/TCP,6001:30406/TCP,6443:30114/TCP   58m
s3                   LoadBalancer   10.233.9.83     35.187.25.10   6001:30693/TCP,6443:30467/TCP                                                                              58m

root@noobaa-1:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=52 time=0.652 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=52 time=0.232 ms


The external IP is forwarded to a public google IP.
It looks like you are trying to access the machine using a New connection.



Error:
Could not identify an external IP to connect from outside the cluster
External IP is usually allocated automatically for Kubernetes clusters deployed on public cloud providers
You can try again later to see if an external IP was allocated using 'noobaa_deploy_k8s.sh info'

**Comment by meirhazonAnyVision** [comment]
Hi,

Also, it looks like the Kubernetes example you give uses minikube storage.

Can I ise a

**Comment by meirhazonAnyVision** [comment]
Closed by mistake

**Comment by meirhazonAnyVision** [comment]
Also, The example you give uses Minukube hostpath for storage, can you point me to some documentations and examples of your storage classes etc. for all in one and clusters.

Thank you

**Comment by guymguym** [comment]
Hi @meirhazonAnyVision 

Oops you're right - I mistakenly thought it was the same case as your other on-prem case, now I understand. So this cluster is on google cloud, and it has external IP assigned to the services, but for some reason the noobaa_deploy_k8s.sh script  did not identify the MGMT_IP:
https://github.com/noobaa/noobaa-core/blob/b6f6b655e7e27f54f8a046b45863f9d2458afb49/src/deploy/NVA_build/noobaa_deploy_k8s.sh#L122
https://github.com/noobaa/noobaa-core/blob/b6f6b655e7e27f54f8a046b45863f9d2458afb49/src/deploy/NVA_build/noobaa_deploy_k8s.sh#L189-L211

With your help, we can troubleshoot it - can you supply the output of the following commands:
```
./noobaa_deploy_k8s.sh info
kubectl get service noobaa-mgmt -o json
```

**Comment by meirhazonAnyVision** [comment]
Hi,

Following, Thanks.
Also, the PVC claim doesnt work properly though it is configured properly. also following inputs at the end

root@noobaa-1:~# bash -x ./noobaa_deploy_k8s.sh info
+ GREEN='\033[0;32m'
+ NC='\033[0m'
++ basename ./noobaa_deploy_k8s.sh
+ SCRIPT_NAME=noobaa_deploy_k8s.sh
+ EMAIL=
+ PASSWD=
+ SYS_NAME=noobaa
++ kubectl config get-contexts
++ grep '\*'
++ awk '{print $5}'
+ NAMESPACE=
+ NOOBAA_CORE_YAML=https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml
+ CREDS_SECRET_NAME=noobaa-create-sys-creds
+ ACCESS_KEY=
+ SECRET_KEY=
+ COMMAND=NONE
+ NOOBAA_POD_NAME=noobaa-server-0
++ kubectl config view --minify -o json
++ jq -r '.clusters[0].name'
+ CLUSTER_NAME=cluster.local
+ jq --version
+ '[' 0 -ne 0 ']'
+ true
+ case ${1} in
+ COMMAND=INFO
+ shift 1
+ '[' -z ']'
+ break
+ '[' '' == '' ']'
+ NAMESPACE=default
+ KUBECTL='kubectl --namespace default'
+ case ${COMMAND} in
+ echo -e '\033[0;32mCollecting NooBaa services information. this might take some time\033[0m'
Collecting NooBaa services information. this might take some time
+ print_noobaa_info
+ kubectl --namespace default get pod noobaa-server-0
+ grep -q noobaa-server-0
+ '[' 0 -ne 0 ']'
++ get_service_external_ip noobaa-mgmt
++ '[' cluster.local '!=' minikube ']'
++ '[' cluster.local '!=' minishift ']'
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
++ local IP=
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}'
++ local HOST_NAME=
++ local RETRIES=0
++ local MAX_RETRIES=60
++ '[' '' == '' ']'
++ '[' '' == '' ']'
++ RETRIES=1
++ '[' 1 -gt 60 ']'
++ sleep 5
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
++ IP=
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}'
++ HOST_NAME=
++ '[' '' == '' ']'
++ '[' '' == '' ']'
++ RETRIES=2
++ '[' 2 -gt 60 ']'
++ sleep 5
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
++ IP=
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}'
++ HOST_NAME=
++ '[' '' == '' ']'
++ '[' '' == '' ']'
++ RETRIES=3
++ '[' 3 -gt 60 ']'
++ sleep 5
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
++ IP=
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}'
++ HOST_NAME=
++ '[' '' == '' ']'
++ '[' '' == '' ']'
++ RETRIES=4
++ '[' 4 -gt 60 ']'
++ sleep 5
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
++ IP=
+++ kubectl --namespace default get service noobaa-mgmt -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}'
++ HOST_NAME=
++ '[' '' == '' ']'
++ '[' '' == '' ']'
++ RETRIES=5
++ '[' 5 -gt 60 ']'
++ sleep 5



root@noobaa-1:~# kubectl get service noobaa-mgmt -o json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"prometheus.io/port\":\"8080\",\"prometheus.io/scheme\":\"http\",\"prometheus.io/scrape\":\"true\"},\"labels\":{\"app\":\"noobaa\"},\"name\":\"noobaa-mgmt\",\"namespace\":\"default\"},\"spec\":{\"externalIPs\":[\"35.187.25.10\"],\"ports\":[{\"name\":\"mgmt\",\"port\":8080},{\"name\":\"mgmt-https\",\"port\":8443},{\"name\":\"md-https\",\"port\":8444},{\"name\":\"bg-https\",\"port\":8445},{\"name\":\"hosted-agents-https\",\"port\":8446},{\"name\":\"s3\",\"port\":6001,\"targetPort\":6001},{\"name\":\"s3-https\",\"port\":6443,\"targetPort\":6443}],\"selector\":{\"noobaa-mgmt\":\"true\"},\"type\":\"LoadBalancer\"}}\n",
            "prometheus.io/port": "8080",
            "prometheus.io/scheme": "http",
            "prometheus.io/scrape": "true"
        },
        "creationTimestamp": "2019-05-22T06:33:58Z",
        "labels": {
            "app": "noobaa"
        },
        "name": "noobaa-mgmt",
        "namespace": "default",
        "resourceVersion": "138255",
        "selfLink": "/api/v1/namespaces/default/services/noobaa-mgmt",
        "uid": "94583f4f-7c5b-11e9-a4f5-42010a84004f"
    },
    "spec": {
        "clusterIP": "10.233.41.181",
        "externalIPs": [
            "35.187.25.10"
        ],
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "mgmt",
                "nodePort": 31338,
                "port": 8080,
                "protocol": "TCP",
                "targetPort": 8080
            },
            {
                "name": "mgmt-https",
                "nodePort": 31932,
                "port": 8443,
                "protocol": "TCP",
                "targetPort": 8443
            },
            {
                "name": "md-https",
                "nodePort": 30923,
                "port": 8444,
                "protocol": "TCP",
                "targetPort": 8444
            },
            {
                "name": "bg-https",
                "nodePort": 30985,
                "port": 8445,
                "protocol": "TCP",
                "targetPort": 8445
            },
            {
                "name": "hosted-agents-https",
                "nodePort": 31842,
                "port": 8446,
                "protocol": "TCP",
                "targetPort": 8446
            },
            {
                "name": "s3",
                "nodePort": 30259,
                "port": 6001,
                "protocol": "TCP",
                "targetPort": 6001
            },
            {
                "name": "s3-https",
                "nodePort": 31736,
                "port": 6443,
                "protocol": "TCP",
                "targetPort": 6443
            }
        ],
        "selector": {
            "noobaa-mgmt": "true"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}


root@noobaa-1:~# kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS    REASON   AGE
local-pv    500Gi      RWO            Retain           Available           local-storage            54m
local-pv1   500Gi      RWO            Retain           Available           local-storage            54m
local-pv2   500Gi      RWO            Retain           Available           local-storage            54m

root@noobaa-1:~# cat noobaa-sc.yaml 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

    - metadata:
        name: logdir
        labels:
          app: noobaa
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-storage
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: datadir
        labels:
          app: noobaa
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-storage
        resources:
          requests:
            storage: 6Gi
root@noobaa-1:~# 

#kubectl describe pods noobaa-server-0

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  52s (x27 over 39m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.

**Comment by guymguym** [comment]
Many thanks @meirhazonAnyVision! 

So I see on your env the load balancer doesn't add its addresses to `status: { loadBalancer: {} }`
but instead the external IP is in `spec: { externalIPs: [ ... ] }`.

I can suggest a quick patch to the script for your case - line 191:
```
-         local IP=$(${KUBECTL} get service $1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}') 
+         local IP=$(${KUBECTL} get service $1 -o jsonpath='{.spec.externalIPs[0]}') 
```
Then run again `./noobaa_deploy_k8s.sh info` to get the info in a human readable way.

Keep in mind that you might need to open ports in security policy (firewall). Specifically the ports for mgmt service should be accessible on the external IP from your browser (or the nodePort access). For the S3 service, you might also want to open it to access the buckets from your workstation and not only from inside the cluster.

Going forward - @dannyzaken Can you think how to automate this case in addition to existing cases in the script?

**Comment by guymguym** [comment]
Regarding the PV's - so the current status is that the pod is not able to allocate a PV and run.

I don't think we tried it with [Local volumes](https://kubernetes.io/docs/concepts/storage/storage-classes/#local) yet and I'm not sure if our PVC is considered "dynamic" provisioning, that is documented to not be supported, or is PVC considered static provisioning.

Do you happen to know if local volumes support PVC provisioning?
Let me try it too on my env.

**Comment by meirhazonAnyVision** [comment]
Do you happen to know if local volumes support PVC provisioning? sure,

https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

For minikune you use hostpath, its exactly the same. 

What do you suggest for storage then? should I install noobaa on top of Ceph? :-)  
How do you suggest creating a local (host) storage for noobaa on plain Kubernetes 14.1 ?

Thanks

**Comment by guymguym** [comment]
OK I just never used local volumes, because we typically use the default storage class on the cloud so it dynamically allocates PV's from PVC's using AWS/Google/Azure drives.

For local volumes if I understand correctly the PVC size should match exactly to the PV size, right?
Perhaps you can try to update the PVC's storage to claim 500Gi to match you existing local PV's?

**Comment by meirhazonAnyVision** [comment]
For local volumes if I understand correctly the PVC size should match exactly to the PV size, right? No, the pvc has to claim a lower size.
Any how, I had some old PVCs that caused the issue, Now PVs and PVCs look good (look below)
Still, it hangs for ever (20 minuets now) at "Waiting for external IPs to be allocated for NooBaa services. this might take several minutes
Getting S3 access keys from NooBaa system. Waiting for NooBaa to be ready"


NAME                      STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS    AGE
datadir-noobaa-server-0   Bound    local-pv2   500Gi      RWO            local-storage   43s
logdir-noobaa-server-0    Bound    local-pv    500Gi      RWO            local-storage   43s
root@noobaa-1:~# kubectl get pvc
NAME                      STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS    AGE
datadir-noobaa-server-0   Bound    local-pv2   500Gi      RWO            local-storage   108s
logdir-noobaa-server-0    Bound    local-pv    500Gi      RWO            local-storage   108s

**Comment by meirhazonAnyVision** [comment]
Now I am getting, (when trying to redeploy)

root@noobaa-1:~# ./noobaa_deploy_k8s.sh deploy -e meirh@anyvision.co -n default -f noobaa_core.yaml
Creating NooBaa resources in namespace default
secret/noobaa-create-sys-creds created
serviceaccount/noobaa-account created
role.rbac.authorization.k8s.io/noobaa-role created
rolebinding.rbac.authorization.k8s.io/noobaa-role-binding created
service/s3 created
service/noobaa-mgmt created
statefulset.apps/noobaa-server created

Waiting for external IPs to be allocated for NooBaa services. this might take several minutes
Error: NooBaa is not deployed in the namespace 'default'. you can deploy using noobaa_deploy_k8s.sh deploy

**Comment by dannyzaken** [comment]
@meirhazonAnyVision try to run `./noobaa_deploy_k8s.sh info` now. looks like a failure when trying to verify the pod exists. by running `info` you will just retry the information retrieval on the existing deployment

**Comment by guymguym** [comment]
Got you. thanks.
So you might be able to try to patch the script to get external IP properly now.

**Comment by guymguym** [comment]
As Danny said I think you can just check for info as your deployment seem to be ok and you don't need to redeploy. However if you do want to redeploy you should first delete the existing deployment with `./noobaa_deploy_k8s.sh delete`.

**Comment by meirhazonAnyVision** [comment]
Please look,

./noobaa_deploy_k8s.sh delete -f noobaa_core.yaml
Deleting NooBaa resources in namespace default
Error from server (NotFound): error when deleting "noobaa_core.yaml": serviceaccounts "noobaa-account" not found
Error from server (NotFound): error when deleting "noobaa_core.yaml": roles.rbac.authorization.k8s.io "noobaa-role" not found
Error from server (NotFound): error when deleting "noobaa_core.yaml": rolebindings.rbac.authorization.k8s.io "noobaa-role-binding" not found
Error from server (NotFound): error when deleting "noobaa_core.yaml": services "s3" not found
Error from server (NotFound): error when deleting "noobaa_core.yaml": services "noobaa-mgmt" not found
Error from server (NotFound): error when deleting "noobaa_core.yaml": statefulsets.apps "noobaa-server" not found
Error from server (NotFound): persistentvolumeclaims "datadir-noobaa-server-0" not found
Error from server (NotFound): persistentvolumeclaims "logdir-noobaa-server-0" not found
root@noobaa-1:~# ./noobaa_deploy_k8s.sh deploy -e meirh@anyvision.co -n default -f noobaa_core.yaml
Creating NooBaa resources in namespace default
secret/noobaa-create-sys-creds created
serviceaccount/noobaa-account created
role.rbac.authorization.k8s.io/noobaa-role created
rolebinding.rbac.authorization.k8s.io/noobaa-role-binding created
service/s3 created
service/noobaa-mgmt created
statefulset.apps/noobaa-server created

Waiting for external IPs to be allocated for NooBaa services. this might take several minutes
Error: NooBaa is not deployed in the namespace 'default'. you can deploy using noobaa_deploy_k8s.sh deploy

**Comment by dannyzaken** [comment]
@meirhazonAnyVision can you attach the output you get for 
```
kubectl --namespace default get pod noobaa-server-0
```

**Comment by dannyzaken** [comment]
@meirhazonAnyVision - did a few changes to the script. can you test it on your env?

[noobaa_deploy_k8s.sh.zip](https://github.com/noobaa/noobaa-core/files/3207080/noobaa_deploy_k8s.sh.zip)

**Comment by guymguym** [comment]
Adding to what @dannyzaken wrote - I can suggest checking the connectivity to the mgmt service manually. 

Get the service details:
```
kubectl get service noobaa-mgmt
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                                                                    AGE
noobaa-mgmt          LoadBalancer   10.233.5.64     35.187.25.10   8080:31015/TCP,8443:30091/TCP,8444:32721/TCP,8445:32608/TCP,8446:30423/TCP,6001:30406/TCP,6443:30114/TCP   58m
```

Try accessing the mgmt port (8080) on the external IP (35.187.25.10):
```
curl 35.187.25.10:8080
```

If this doesn't work, let's try to access using node ip:port. 
The node IP you might know already, but in our script we get it with: `kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'` - I wonder if that gives the right IP in your case?
The node port is the internally mapped port so in the example above `8080:31015` so the node port is 31015, but it might differ in your env now.

**Comment by meirhazonAnyVision** [comment]
Hi,
With the new script,

root@noobaa-1:~# ./noobaa_deploy_k8s.sh delete -f noobaa_core.yaml
Deleting NooBaa resources in namespace default
serviceaccount "noobaa-account" deleted
role.rbac.authorization.k8s.io "noobaa-role" deleted
rolebinding.rbac.authorization.k8s.io "noobaa-role-binding" deleted
service "s3" deleted
service "noobaa-mgmt" deleted
statefulset.apps "noobaa-server" deleted
persistentvolumeclaim "datadir-noobaa-server-0" deleted
Error from server (NotFound): persistentvolumeclaims "logdir-noobaa-server-0" not found
root@noobaa-1:~# ./noobaa_deploy_k8s.sh delete 
Deleting NooBaa resources in namespace default
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": secrets "noobaaimages.azurecr.io" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": serviceaccounts "noobaa-account" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": roles.rbac.authorization.k8s.io "noobaa-role" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": rolebindings.rbac.authorization.k8s.io "noobaa-role-binding" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": services "s3" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": services "noobaa-mgmt" not found
Error from server (NotFound): error when deleting "https://s3.amazonaws.com/noobaa-deploy/noobaa_core.yaml": statefulsets.apps "noobaa-server" not found
Error from server (NotFound): persistentvolumeclaims "datadir-noobaa-server-0" not found
Error from server (NotFound): persistentvolumeclaims "logdir-noobaa-server-0" not found
root@noobaa-1:~# kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                             STORAGECLASS    REASON   AGE
local-pv    500Gi      RWO            Retain           Released   default/datadir-noobaa-server-0   local-storage            130m
local-pv1   500Gi      RWO            Retain           Released   default/datadir-noobaa-server-0   local-storage            130m
local-pv2   500Gi      RWO            Retain           Released   default/datadir-noobaa-server-0   local-storage            130m
root@noobaa-1:~# kubectl get pvc
No resources found.
root@noobaa-1:~# ./noobaa_deploy_k8s.sh deploy -e meirh@anyvision.co -n default -f noobaa_core.yaml
Creating NooBaa resources in namespace default
secret/noobaa-create-sys-creds created
serviceaccount/noobaa-account created
role.rbac.authorization.k8s.io/noobaa-role created
rolebinding.rbac.authorization.k8s.io/noobaa-role-binding created
service/s3 created
service/noobaa-mgmt created
statefulset.apps/noobaa-server created

Waiting for external IPs to be allocated for NooBaa services. this might take several minutes
Getting S3 access keys from NooBaa system. Waiting for NooBaa to be ready
Error from server (NotFound): pods "noobaa-server-0" not found
Error from server (NotFound): pods "noobaa-server-0" not found
Error from server (NotFound): pods "noobaa-server-0" not found
Error from server (NotFound): pods "noobaa-server-0" not found

root@noobaa-1:~# kubectl get service noobaa-mgmt
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                    AGE
noobaa-mgmt   LoadBalancer   10.233.54.166   10.132.0.79   8080:32736/TCP,8443:32153/TCP,8444:30223/TCP,8445:30713/TCP,8446:30397/TCP,6001:30235/TCP,6443:30562/TCP   52s
root@noobaa-1:~# curl 10.132.0.79:8080
curl: (7) Failed to connect to 10.132.0.79 port 8080: Connection refused
root@noobaa-1:~#

**Comment by dannyzaken** [comment]
@meirhazonAnyVision it looks like the pod is not created, or takes a long time to create.

if you didn't delete this deployment yet then let's get the following info:
1. `kubectl get pod noobaa-server-0`
2. `kubectl describe statefulset noobaa-server`

**Comment by meirhazonAnyVision** [comment]
This is what I am getting now, please help.

Events:
  Type     Reason            Age              From               Message
  ----     ------            ----             ----               -------
  Warning  FailedScheduling  2m (x2 over 2m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         119s             default-scheduler  Successfully assigned default/noobaa-server-0 to noobaa-1
  Normal   Pulling           118s             kubelet, noobaa-1  Pulling image "noobaa/noobaa-core:3.0.0"
  Normal   Pulled            93s              kubelet, noobaa-1  Successfully pulled image "noobaa/noobaa-core:3.0.0"
  Normal   Created           93s              kubelet, noobaa-1  Created container noobaa-server
  Normal   Started           92s              kubelet, noobaa-1  Started container noobaa-server
  Warning  Unhealthy         86s              kubelet, noobaa-1  Readiness probe failed: Get http://10.233.64.11:8080/version: dial tcp 10.233.64.11:8080: connect: connection refused
root@noobaa-1:~# telnet 10.132.0.79 8080
Trying 10.132.0.79...
Connected to 10.132.0.79.
Escape character is '^]'.

**Comment by guymguym** [comment]
@meirhazonAnyVision Can I help - let me know what is the status, and if possible we can do a quick phone call, and then update here on the findings.

**Comment by meirhazonAnyVision** [comment]
Thanks so much, very busy day, will continue working on it now.

**Comment by meirhazonAnyVision** [comment]
Pls look, Thanks


root@noobaa-1:~# s3cmd --access_key='jfPDqbeO5xWoXEEFig74' --secret_key='928OYzkrPS3wQmN7nTHcNhthzfVechdApJVulLOS' --host='10.132.0.79:6001' mb s3://meir

root@noobaa-1:~# ./noobaa_deploy_k8s.sh info
Collecting NooBaa services information. this might take some time
Getting S3 access keys from NooBaa system. Waiting for NooBaa to be ready


================================================================================
External management console   : http://10.132.0.79:8080 or 
                                https://10.132.0.79:8443
nodePort access for management: http://10.132.0.79:31202

      login email             : meirh@anyvision.co
      login password          : DAZigYfXwzKscg==

External S3 endpoint          : http://10.132.0.79:80 or 
                                https://10.132.0.79:443
nodePort access for S3        : http://10.132.0.79:30795

Cluster internal S3 endpoint  : http://s3.default.svc.cluster.local:80 or
                                https://s3.default.svc.cluster.local:443
      S3 access key           : jfPDqbeO5xWoXEEFig74
      S3 secret key           : 928OYzkrPS3wQmN7nTHcNhthzfVechdApJVulLOS

you can view all NooBaa resources in kubernetes using the following command:
      kubectl --namespace default get all --selector=app=noobaa
================================================================================

Please consider logging in to the management console and changing the initial password

**Comment by meirhazonAnyVision** [comment]
Hi,

The following works, can you please share a python example with me? Thanks

root@noobaa-1:~#  s3cmd mb --no-ssl --access_key=jfPDqbeO5xWoXEEFig74 --secret_key='928OYzkrPS3wQmN7nTHcNhthzfVechdApJVulLOS' --host
='10.132.0.79:6001' --host-bucket=  s3://test1
Bucket 's3://test1/' created

**Comment by guymguym** [comment]
Hi @meirhazonAnyVision 

The problem that upload does not work with bucket `test1` is that we have a usability BUG in this 3.0.0 version. Note that version 3 was our first version for kubernetes and we are about to release version 4 this week which does not have this issue.

The current issue that you are experiencing is that newly created buckets have no storage resources attached to them. There are two options to make it work:

 1. Login to the mgmt URL, open the bucket `test1` and in  "Bucket Policies" tab click on the "Bucket Spillover" and edit it to enable it on internal storage. However, this will only take effect on this bucket and newly created buckets will also suffer from the same issue.

 2. Login to the mgmt URL, open cloud resources, add a cloud resource on google-cloud-storage (see [create cloud resource](https://noobaa.desk.com/customer/en/portal/articles/2852133-create-a-cloud-resource)), then go to Accounts -> current-account -> Button "Edit S3 Access" -> Choose "S3 default placement" to be the cloud storage you created - see screenshots. The benefit is that with this flow any new buckets created using these access/secret keys will have this default storage policy. Any existing buckets such as `test1` or `first.bucket` will need to be updated in the bucket page to use this resources (see [editing placement policy](https://noobaa.desk.com/customer/en/portal/articles/2854268-editing-a-bucket-data-placement-policy-)).

Did you manage to login to the MGMT UI?
Let me know if these instructions are clear enough or I can help in any way.
In addition, I will be happy to guide you through using version 4 once we release it in the next few days.


Screenshot of enable spillover:
![image](https://user-images.githubusercontent.com/1091422/58405447-1c3d9080-8070-11e9-9c27-f560787af088.png)

Screenshot of changing the S3 default placement:
![image](https://user-images.githubusercontent.com/1091422/58405456-2069ae00-8070-11e9-8c8a-0b802772c242.png)

**Comment by meirhazonAnyVision** [comment]
Hi,

Using the console isn't applicable in our case. sorry. Can you please LMK once version 4 is released?

Thanks so much,

Meir

**Comment by guymguym** [comment]
Sure I will let you know of course.

BTW I can guide you how to make the same change through API calls with curl - will that be a workaround you can use?

**Comment by meirhazonAnyVision** [comment]
Not really, our apps create buckets dynamically. 
Thanks so much

**Comment by guymguym** [comment]
I see. I have 2 questions:
1. Which storage do you want to use for your data? Google-cloud-storage? PV storage? other?
2. How do you install your kubernetes cluster? We also tried to run GKE cluster and saw a different external-IP behavior than yours, so I assume it's not GKE...

**Comment by meirhazonAnyVision** [comment]
Hi,
1. PV or hostPath
2. Its a generic kubernetes 14.01, we use kubespray (kube adm)
Thanks

**Comment by dannyzaken** [comment]
Hi @meirhazonAnyVision 

I added to the script the ability to provision k8s PVs to use as storage backend in noobaa.
try to run the **attached script** with the command:
```
./noobaa_deploy_k8s.sh storage
```
this will deploy by default 3 noobaa agents that will use a PV of 50GB each (total 150GB). 
notice that by default noobaa writes 3 replicas for each uploaded object, so this will give you 50GB of available storage for objects (This policy can be changed per bucket)

if you want different numbers you can use 
```
noobaa_deploy_k8s.sh storage --size <PV size in GB> --num-pvs <number of pvs\agents>
```
number of PVs must be at least 3 when using the script. 
You can change the number of agents later by running the script with different numbers

e.g. if you want to have 100GB available for upload run 
```
noobaa_deploy_k8s.sh storage --size 100 --num-pvs 3
```


[noobaa_deploy_k8s.sh.zip](https://github.com/noobaa/noobaa-core/files/3224024/noobaa_deploy_k8s.sh.zip)

**Comment by dannyzaken** [comment]
@meirhazonAnyVision use script attached in this comment (not the previous one if you already took it)

in the new script you can use `--class` flag to pass a storage class you want to use. e.g.:
```
noobaa_deploy_k8s.sh storage --class local-storage
```
 

[noobaa_deploy_k8s.sh.zip](https://github.com/noobaa/noobaa-core/files/3224108/noobaa_deploy_k8s.sh.zip)

**Comment by meirhazonAnyVision** [comment]
Good morning, a little busy, will try it out next week. Thanks

**Comment by meirhazonAnyVision** [comment]
Good morning,

This is what I am getting,

root@noobaa-1:~# ./noobaa_deploy_k8s.sh storage
Error: NooBaa is not deployed in the namespace 'default'. you can deploy using noobaa_deploy_k8s.sh deploy
root@noobaa-1:~# 

Please help.

Thanks

**Comment by dannyzaken** [comment]
@meirhazonAnyVision I guess noobaa is deployed. can you send me the output for 
```
kubectl get statefulset
```

**Comment by dannyzaken** [comment]
in any case, if noobaa is not deployed, then redeploy it first. the `storage` command does not deploy, it just adds storage to an already deployed system

**Comment by meirhazonAnyVision** [comment]
root@noobaa-1:~#  ./noobaa_deploy_k8s.sh storage
Deploying noobaa agents for storage. This operation will provision 3 PVs of size 50 GB
error: no objects passed to apply

root@noobaa-1:~# kubectl get statefulset
NAME            READY   AGE
collate         3/3     3d21h
consul-server   1/1     3d21h
edge            1/1     3d21h
noobaa-server   1/1     4m20s

**Comment by dannyzaken** [comment]
do you have `mktemp` tool installed on the machine? the script is using it to create a temp file. if you don't have it installed and you can install it then it should fix it.  
if you can't install it for some reason then try

**Comment by dannyzaken** [comment]
do you have `mktemp` tool installed on the machine? the script is using it to create a temp file. if you don't have it installed and you can install it then it should fix it.  
if you can't install it for some reason then try to run
```
sed -i -e 's/TMP_YAML_FILE=$(mktemp)/TMP_YAML_FILE=tmp_agents.yaml/' noobaa_deploy_k8s.sh
```
it will replace the `mktemp` with a static file named `tmp_agents.yaml` which you can delete after the run

**Comment by guymguym** [comment]
@meirhazonAnyVision One point to make sure we are aligned -
You explained that you are using staticly provisioned PV's.
So in order to add storage to NooBaa based on PV's will require you to prepare 3 PV's for that script to work in order to satisfy the 3 PVC's that we will create...

**Comment by guymguym** [comment]
Closing - this is stale by now.
@meirhazonAnyVision please refer to using https://github.com/noobaa/noobaa-operator which has advanced a lot since last year.
Let us know if you have new issues.
Godspeed.
