### ISSUE TITLE
Can't not list objects with pagination

### ISSUE THREAD

**Issue by sberequek** [noobaa/noobaa-core#5476]
### Environment info
- Version: **2.10.4**
- Deployment: **ESX**

### Actual behavior
1. In java when call the listObjects with the delimiter, prefix and maxKeys parameters, the result is always the first page, in an infinite loop.

### Expected behavior
1. List of paginated objects.

### Steps to reproduce
1. Create a bucket with different folders and insert in all a sufficient number of files for simulate the pagination (eg 50 files);
2. Create a java maven project with this dependency:
```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
    <version>1.11.557</version>
</dependency>
```
3. Import the attach file "ListKeys.java" and setting it. 
[ListKeys.java.zip](https://github.com/noobaa/noobaa-core/files/3210870/ListKeys.java.zip)
4. Run the Main in ListKeys.java and check the infinite loop.

**Comment by jeniawhite** [comment]
@sberequek 
I'm investigating the issue and will follow up with an update.
Thank you.

**Comment by jeniawhite** [comment]
@sberequek 
I couldn't reproduce an infinite loop scenario.
I did the following:
1) Uploaded objects with keys: ```folder/file[1..200]```
2) Did a query with the following parameters:
```
- prefix: folder/
- limit: 50
- delimiter: /
```
I've managed to find an issue in our listing mechanism and did a fix, but I'm interested in the infinite loop case that you described.
Could you please give more info regarding the key names, folder name, query parameters that you've used?

Thank you.

**Comment by sberequek** [comment]
@jeniawhite 
Using the example code for amazon [ListingObjectKeysUsingJava](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingJava.html) (similar to the code I shared less than the prefix parameter) the infinite loop depends on the fact that the **NextContinuationToken** used for set the **ContinuationToken** in next request not change.

The infinite loop depends on the implementation of the requests made in the java code. Just change the java code and make a break if the **NextContinuationToken** is the same as the previous **ContinuationToken** to avoid it.

In my scenario I have a bucket with 5 folders and in every folder I have at least a thousand json files. But I noticed that the problem also occurred with buckets with a single folder and a few dozen files, obviously changing the maxKeys parameter with a low value to start paging. The query I use in java code has the following parameters:
```
- Prefix = "folder1/"
- Delimiter = "/"
- MaxKeys = 50
```
If you need more information, I am at your disposal.

Thank you

**Comment by jeniawhite** [comment]
@sberequek 
I was interested in the exact representation of your folders structure and files with names if possible.
I've managed to reproduce the infinite loop with a minimal use case:
1) Upload objects with keys: ```['d/d/d/', 'd/d/f', 'd/f']```
2) List with the following query: ```{
- Prefix = "d/"
- Delimiter = "/"
- MaxKeys = 1
}```
I will investigate this case and issue a fix. 
If you could add more info regarding your exact folder and files structure (maybe it is similar to mine), it could help in order to find additional issues or make sure that your case will be closed with the issued fix.
Thank you.

**Comment by sberequek** [comment]
@jeniawhite 
I created summary files for tests with my bucket hierarchy and query parameters. In the hierarchy I have indicated the names of the files and folders I use:

- [noobaa-test-01.txt](https://github.com/noobaa/noobaa-core/files/3222463/noobaa-test-01.txt)
- [noobaa-test-02.txt](https://github.com/noobaa/noobaa-core/files/3222462/noobaa-test-02.txt)
- [noobaa-test-03.txt](https://github.com/noobaa/noobaa-core/files/3222461/noobaa-test-03.txt)

I don't know if it can be useful, but the files I created in my tests all have additional meta tags. Here is an example of the additional meta tags I use:

```
resource-id: 2399953_5310628572012276714_333158043181933418
resource-type: comment
source-id: blogger
```
I hope it can be useful.

**Comment by jeniawhite** [comment]
@sberequek 
I've simulated all of the test cases with your version and **DID** encounter an infinite loop.

I've applied the fixes to that system and ran the cases once again.
I've also checked every case using ```- MaxKeys = 1```.
I've attached the Java console log for every case (exact is the exact copy or your MaxKeys and Limit 1 is a run with MaxKeys = 1).
[Test01Exact.txt](https://github.com/noobaa/noobaa-core/files/3224085/Test01Exact.txt)
[Test01Limit1.txt](https://github.com/noobaa/noobaa-core/files/3224086/Test01Limit1.txt)
[Test02Exact.txt](https://github.com/noobaa/noobaa-core/files/3224087/Test02Exact.txt)
[Test02Limit1.txt](https://github.com/noobaa/noobaa-core/files/3224088/Test02Limit1.txt)
[Test03Exact.txt](https://github.com/noobaa/noobaa-core/files/3224089/Test03Exact.txt)
[Test03Limit1.txt](https://github.com/noobaa/noobaa-core/files/3224090/Test03Limit1.txt)
You can see that the listing works in all of the test cases and there is no infinite loop.

This fix is expected to be a part of the next release.

Thank you very much for your feedback and your cooperation. 
The data was very useful and exactly what I needed.

**Comment by sberequek** [comment]
@jeniawhite 
perfect, great job. I await the release I hope will come soon :)

Thank you
