### ISSUE TITLE
some issues with welcome screen for a new system

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5493]
### Environment info
- Version: **4.0.0**
- Deployment: **KUBERNETES | AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
some issues that confused me in the first welcome screen for a new system
1. the description of fields on the left is unnoticeable.  
the first thing I see is **company-name**, which seems required and not relevant.  
2. the example for the password is a bit amusing (******* is not really an example)
3. the comman after e.g. is redundant

### Expected behavior
1. I think the field names should be more noticeable somehow, and the examples should be more consistent. for example instead of `company-name` maybe use `cloud.com` which is the domain of the email in the next box.

### Steps to reproduce
1.

### Additional Information
![NooBaa_Management_Console](https://user-images.githubusercontent.com/1476203/58537179-a7df2a80-81f2-11e9-8342-66d3e1e824ac.png)

**Comment by shirimordechay** [comment]
@nimrod-becker Is this still relevant?

**Comment by nimrod-becker** [comment]
@shirimordechay in theory, can be deployed not via the operator and then yes, but very low pri

**Comment by nimrod-becker** [comment]
Closing, assuming most installations via the operator flow
