### ISSUE TITLE
S3 - trying to upload/delete files with brackets fails

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#5502]
### Environment info
- Version: master
- Deployment: DEV
- Customer: QA

### Actual behavior
1. trying to upload a file named: "log (1).txt" or anything else in this structure like: "S3 (HTTP).cyberduckprofile" using Cyberduck 
2. failing on access denied
3. in the logs we can see the issue is with the signature: ```
CONSOLE:: RPC._on_request: ERROR srv object_api.create_object_upload reqid 48@fcall://fcall(6b78wgx3) connid fcall://fcall(6b78wgx3) RPC ERROR UNAUTHORIZED SignatureDoesNotMatch```
4. also delete and probably and other action on objects with this format fails.

### Expected behavior
1. Works with AWS - upload should succeed

### Steps to reproduce
1. upload an object in the above format: anytext(space)(open bracket)anynumber(closing brucket).anypostfix

**Comment by jeniawhite** [comment]
Upgrading to a newer version of Cyberduck fixes this issue.
In order to fix for the older version, we would need to decodeURI and escape the path in our signature_utils (this should be checked for all of the queries as well prior to the fix).

**Comment by nimrod-becker** [comment]
This is an old issue and since a 6/19 version of cyberduck already fixes it, closing
