### ISSUE TITLE
Add functions to bucket via api 

### ISSUE THREAD

**Issue by sberequek** [noobaa/noobaa-core#5503]
I would like to automate the creation of a bucket with the association of one or more "Restless Functions" of noobaa. How can I do? Are there any noobaa api that can be used?

Thanks

**Comment by guymguym** [comment]
Hi @sberequek 

NooBaa serves both S3 and Lambda API's so you can create a bucket, and create a lambda function from the AWS.S3/AWS.Lambda from your SDK of choice.

The only gap is to link between the bucket and a function.
This is an API that currently is not implemented in NooBaa called BucketNotification.
See https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html
We certainly see this API being added to NooBaa and would love to cooperate on that.

In the meanwhile, you can use our internal API (feeling brave?) to achieve the same goal
This Wiki will give you the basic instructions on how to start using the API:
https://github.com/noobaa/noobaa-core/wiki/RPC

To set the bucket to trigger functions you can use the bucket_api add_bucket_lambda_trigger() defined in a json schema here:
https://github.com/noobaa/noobaa-core/blob/b878c9607359ada87fc32c275da2bf9308692bcc/src/api/bucket_api.js#L646-L650
https://github.com/noobaa/noobaa-core/blob/b878c9607359ada87fc32c275da2bf9308692bcc/src/api/bucket_api.js#L1043-L1053

Calling it from cURL will be something like this 
(Note you will need to take the `NOOBAA_MGMT` http/s service address and also authenticate and get a jwt token as `NOOBAA_TOKEN` as explained in the RPC Wiki)
```
curl $NOOBAA_MGMT/rpc/ -sd '{
  "api": "bucket_api",
  "method": "add_bucket_lambda_trigger",
  "params": { "bucket_name": "XXX", "func_name": "YYY", "event_name": "ObjectCreated" },
  "auth_token": "'$NOOBAA_TOKEN'"
}'
```

Let me know if that makes sense.
Guy

**Comment by guymguym** [comment]
BTW what did you think of our geeky name "Restless Functions"?

**Comment by sberequek** [comment]
Hi @guymguym 

I'm trying to use the internal API [https://github.com/noobaa/noobaa-core/wiki/RPC](https://github.com/noobaa/noobaa-core/wiki/RPC) but I can't get over the "Create System" or the next call "Auth Token". In detail the answer message is "RPC VERSION MAGIC MISMATCH". The call I am using for "Create System" is as follows:
```
 curl https://{MY_INSTANCE_NOOBAA_MGMT}:8443/rpc/ -sd '{
  "api": "system_api",
  "method": "create_system",
  "params": {
    "name": "demo",
    "email": "{MY_USERNAME}",
    "password": "{MY_PASSWORD}",
    "activation_code": "123"
  }
}
```
I honestly don't know how to set the "activation_code" field, suggestions? If it can be useful I am using NooBaa version 2.10.4 - Deployment ESX.

Thanks

Ps The name "Restless Functions" is really cool :)

**Comment by guymguym** [comment]
Hi @sberequek !

OK so I am sorry for the confusion, I assumed you were using the 3.0.0 release for Kubernetes, but in the 2.x versions, we did not expose the internal RPC API through http yet, so the error you get is expected though unfortunate (also the activation_code was dropped since then).

Going forward we are focusing on Kubernetes as a platform.
Does that make sense for you to use?
If so, you can follow the deployment guide on the [README](../)

I added a terminal recording that might give you a preview of how the deployment process goes now - 

[![asciicast](https://asciinema.org/a/kCziF0feQD9qmNioLUSAZNoEm.svg)](https://asciinema.org/a/kCziF0feQD9qmNioLUSAZNoEm?speed=2&autoplay=1)

Let me know what you think

**Comment by sberequek** [comment]
Thanks @guymguym 

I will follow your advice.

**Comment by guymguym** [comment]
Great @sberequek. Let me know how it goes.
