### ISSUE TITLE
read_account in account_api is not authenticated

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5517]
### Environment info
- Version: **4.0**
- Deployment: **KUBERNETES | AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. `read_account` in `account_api` is not authenticated
2. anyone can call it with an email and get all account info including S3 access keys

### Expected behavior
1. read_account should be authenticated.

### Steps to reproduce
```
SERVER_ADDR=<server ip>
ACCOUNT_EMAIL=<email>
curl http://${SERVER_ADDR}:8080/rpc/ -sd '{
                "api": "account_api",
                "method": "read_account",
                "params": { "email": "${ACCOUNT_EMAIL}" },
                "auth_token": ""
                }'
```

### Additional Information

**Comment by dannyzaken** [comment]
@guymguym any reason why it's not authenticated? the fix should be simple, just require auth in api.

**Comment by guymguym** [comment]
@dannyzaken It should be. Good catch.
Just need to test and verify with @nb-ohad that the two UI paths that call this are OK with this change:
https://github.com/noobaa/noobaa-core/blob/b5e5f468ecdb1bea39b0756adc15eb7c4132fa37/frontend/src/app/epics/restore-session.js#L49
https://github.com/noobaa/noobaa-core/blob/b5e5f468ecdb1bea39b0756adc15eb7c4132fa37/frontend/src/app/epics/sign-in.js#L20

**Comment by nb-ohad** [comment]
@dannyzaken @guymguym 
I checked both locations read accounts is called with a token already installed in the RPC (form create_auth call or from the browser local session)

**Comment by dannyzaken** [comment]
other unauthenticated apis that seems problematic are `create_account` and `update_account`
*

**Comment by dannyzaken** [comment]
for `create_accout` I think we should have a separate unauthenticated function that is only used for the first account during create_system

**Comment by guymguym** [comment]
`update_account` - it checks `is_support_or_admin_or_me()` so it seems to allow only these certain cases.

`create_account` - This is called from system_server `_create_owner_account` which can generate an auth token, so I think we can add auth the API and handle there. Though I didn't look on all the callers in the code.
