### ISSUE TITLE
when deleting a pool that is referenced by a function read_system gets broken

### ISSUE THREAD

**Issue by dannyzaken** [noobaa/noobaa-core#5520]
### Environment info
- Version: **VERSION**
- Deployment: **KUBERNETES | AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. if a function is referencing a deleted pool in its config then `_get_func_info` in `func_server` is failing on `system_store.data.get_by_id(pool).name;`
2. this eventually breaks `read_system`, which breaks the UI
3. Getting to this situation is only possible when creating a function using the RPC and not from the UI. the UI does not have an option to set pools for the function.

### Expected behavior
1. read_system should not fail for this
2. one option is to remove any reference to the pool from the functions when a pool is deleted

### Steps to reproduce
1. create a function using the RPC and include an existing pool in the func config
2. delete the pool
3. read_system should fail

### Additional Information

**Comment by dannyzaken** [comment]
@nimrod-becker why critical? this bug cannot be exposed when working through the UI. the only way to expose it is to use RPC directly and configure pools in the func_config. also it is not a new bug

**Comment by nimrod-becker** [comment]
Should also check in create_function that given pools are not cloud resources
