### ISSUE TITLE
License info fails

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5524]
### Environment info
- Version: **4.0.0-ca24850-master**
- Deployment: **KUBERNETES**

### Actual behavior
1. Cannot get license info because of server failure to scan it

### Expected behavior
1. Should work

### Steps to reproduce
1. kubectl exec -it noobaa-server-0
2. node src/server/license_info.js --dir /root  # Running this just exists without output

### Screenshots or Logs or other output that would be helpful

![image](https://user-images.githubusercontent.com/1091422/59152712-66504a00-8a52-11e9-9907-9adb1aae5312.png)

**Comment by nb-ohad** [comment]
Closing - relevant only to non-Kubernetes dev environments
