### ISSUE TITLE
UI - object parts It is possible to move to next page when no extra parts available 

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#5525]
### Environment info
- NooBaa Version: master
- Platform: dev-local

### Actual behavior
1. opening the object parts modal for an object with exactly 25 parts
2. It is possible to move to the next page and see the attached screen: 2 of 1 page and empty list of parts

### Expected behavior
1. the next page should be disabled

### Steps to reproduce
1. read the object parts of an object with exactly 25 parts

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/20266280/59187358-f5a64c00-8b7d-11e9-91f4-3bf08096d9e7.png)

**Comment by shirimordechay** [comment]
Also happens on folder pages which have 0 object parts but the page shows 1 of 0:
![Screen Shot 2019-06-11 at 18 28 31](https://user-images.githubusercontent.com/10331355/59285631-f1118e80-8c76-11e9-86f8-c9f591cfd1dd.png)
