### ISSUE TITLE
Alert on DNS in kubernetes when you can't configure DNS

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#5531]
### Environment info
- NooBaa Version: 4.0
- Platform: minikube 1.1.1

### Actual behavior
1. no real DNS problem - so no need for the alert. I can access aws for example

### Expected behavior
1. don't show alert

### Steps to reproduce
1. 

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/20266280/59286376-48fcc500-8c78-11e9-8a05-c02211abd005.png)

**Comment by nimrod-becker** [comment]
Can you remove the alert altogether? I also believe we removed the check for DNS but it might be in #5521
