### ISSUE TITLE
Upload file from UI over uses non-https endpoint from https page and fails

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5574]
### Environment info
- NooBaa Version: **4.0.1**
- Platform: **OpenShift 4.1**
- Found my: @mvazquezc (Thanks)

### Actual behavior
1. Error uploading files through the LoadBalanced service for the mgmt console on port 8443 on because of mixed content.
2. Using 8080 works.

### Expected behavior
1. No errors

### Steps to reproduce
1. Upload file to UI on secure port 8443

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/1091422/60207088-d2f28380-985d-11e9-91d8-92620ab78a9a.png)

**Comment by nimrod-becker** [comment]
Removed ul option from the UI, closing.

**Comment by mvazquezc** [comment]
Out of curiosity, is there any reason behind removing the option to upload files to buckets within the WebUI? 

I find that option very convenient and user-friendly.

**Comment by nimrod-becker** [comment]
We've had several incidents regarding uploads from the UI and for now decided to hide that option (we didn't actually delete the code, just hidden the btn) - We might bring it back if we see the need from users. 
Thanks for updating us, it will help us with the decision.
