### ISSUE TITLE
Automated error handling for k8s pool scaling (and creation)

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5640]
### Environment info
- NooBaa Version: **5.0.1-9afb1f5**
- Platform: **Kubernetes v1.12.7**

### Actual behavior
Two flows to consider:

1. Creating a pool with a certain amount of agents, which fail (agents not being able to be provisioned) is stuck and actions (delete/scale) cannot be performed on it.

2. Scaling a pool (probably increase num of agents only) which does not finish. The pool is stuck on that operation and cannot advance (for example to scale back down)

### Expected behavior
1. If the pool was not "fully" created 
  1.1. We should prevent a pool from being used (attached to buckets) before it was finished its first creation (we can mark it as not ready in the db). The pool should appear disabled in the placement policy modals
  1.2. We should be able to delete this pool and agents within it (without going through eviction, they were not used so nothing to evict)
  1.3. After a t/o send alert on pool creation failure

2. Scaling up a pool should have a timeout after which
  2.1. We will update the StatefulSet to the current number of agents which were provisioned. So for example, scaling from 6 to 10, and getting stuck at 8, we will update the StatefulSet to 8. This will release the pool from being locked on operations.
  2.2. We will send an alert with the info about which pool failed to scale and which state the pool is in now (8 nodes in the previous example)

**Comment by nimrod-becker** [comment]
@shirimordechay Do you see we need something UX wise here?

**Comment by shirimordechay** [comment]
If we're not deleting it right away (why BTW?), then yes we should indicate the user that something is happening and send an alert/ warning if something went wrong

**Comment by nimrod-becker** [comment]
In this case, there is no data, so we can delete away

**Comment by nimrod-becker** [comment]
@shirimordechay I updated the description and the desired behavior. Would like to get your input and the UX perspective in case I missed something.

**Comment by shirimordechay** [comment]
1. If we are preventing the user from selecting "Initializing" pools, the bucket data placement modal should show this line (disabled) with a tooltip and an explanation for why can't he select it. this brings us back to an old UI gap which we'll need to solve (no tooltip on disabled rows).

Also, An alert should be sent after X time and notify the user his pool is not scaling/ initializing as it should.

2. How do we know when to "force stop" the scaling process? do we know to identify when the K8s storage is not enough? how do we know it's not just taking a while?

- Make sure that the Audit log description matches the actual scaled number of nodes and not the desired number. 

+1 on the alert, I would consider adding a popup notice if the user is still active in the UI as an addition to the alert. We can open an enhancement for those kinds of alerts that are currently missing in the system.

**Comment by nimrod-becker** [comment]
Updated the expected behavior with #1 and the alert.

For 2. easiest way would be a timeout, we might be able to identify the error itself in provisioning the agents but that might be a future improvement.

Regarding audit, the first audit would be fired when the action is requested. Later on we will send an alert on failure, we can also send another audit on failure with the actual numbers if you think we should.
