### ISSUE TITLE
Buckets UI should reflect running events and data activities 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5642]
### Environment info
- NooBaa Version: **5.0.1-9afb1f5**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Currently, when making a change in one of the bucket's policies (placement, resiliency, etc.) there is no indication on the bucket page that a rebuilding process is running. 

### Expected behavior
1. The bucket should show it's data activities and ETA for the process. The user should see an indication of his changes and its results.

### Steps to reproduce
1. Go to a bucket with data-> change policies-> see bucket page.

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
