### ISSUE TITLE
Failed login crushes the system

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5643]
### Environment info
- NooBaa Version: **5.0.1-9afb1f5**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. When trying to login with the wrong details, an error is shown (as it should) but correcting it doesn't help and the login is not working until hard-refreshing the system.

### Expected behavior
1. After entering the correct login details the user should be logged in successfully to the system

### Steps to reproduce
1. Go to login screen -> enter wrong details -> see validation -> enter correct details -> try login

### More information - Screenshots / Logs / Other output

![login](https://user-images.githubusercontent.com/10331355/62139600-50dcfb00-b2f2-11e9-8f77-f1da6137bc50.gif)

**Comment by nimrod-becker** [comment]
No longer reproducible
