### ISSUE TITLE
Uploading objects from the UI is always blocked for OpenShift Users

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5644]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **OpenShift 4.1**

### Actual behavior
1. When users logges-in via OpenShift we don't allow them to sign out and they are not considered as the system owners. Currently, we do not allow users that are not the system owners to upload object via the UI, meaning that they will never be able to upload. 

### Expected behavior
1. Remove the Uploading UI block, it is no longer relevant. 

### Steps to reproduce
1. Login via OpenShift -> try to upload an object via the UI

**Comment by nimrod-becker** [comment]
Le'ts remove it all together

**Comment by nimrod-becker** [comment]
Removed the option to upload from the UI - not relevant for our demos / POCs anymore
