### ISSUE TITLE
Missing help information in edit pool configuration modal

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5648]
### Environment info
- NooBaa Version: **5.0.1-97bf3e6**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. In edit pool configuration modal, the help information presented is not as designed.

### Expected behavior
1. In the edit modal the information should help the user decide what are the changes he needs to do and alert if there is an issue with his configuration.

See mock: https://invis.io/C4RB22DZRH2#/358457404_K8s_Pool-_modals-_edit_Statefulset

### Steps to reproduce
1. See create pool vs. edit

**Comment by nimrod-becker** [comment]
Related to #5641
