### ISSUE TITLE
Operator account holds the first resource as default resource and the resource cannot be deleted

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5651]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. When the first resource is created in the system it is automatically assigned to all accounts as default resource, this includes the operator account.
2. A resource cannot be deleted if an account holds it as a default resource
3. No like other accounts, we cannot edit (from the FE) the default resource for the operator account because this account is filtered out from the FE.

### Expected behavior
1. The user must have a way to delete the first resource.

### Steps to reproduce
1. create a new system, then create a resource (pool or cloud).

**Comment by guymguym** [comment]
FYI @dannyzaken
