### ISSUE TITLE
Maintenance mode leads to a non existing tab 

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5660]
### Environment info
- NooBaa Version: **5.0.1-7d31a2e**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Clicking on the Maintenance mode section in the configuration leads to nowhere.

### Expected behavior
1. It should open the Maintenance mode section... 

### Steps to reproduce
1. Go to configuration -> click on Maintenance mode

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/10331355/62607934-965b8280-b907-11e9-9a55-7b124dcece0e.png)

**Comment by nimrod-becker** [comment]
Closed with #5663
