### ISSUE TITLE
Allow to delete last bucket

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5670]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. See discussion in #860
2. Deleting the last bucket from the operator/CLI fails with an error:
```
Code=LAST_BUCKET
Message=Cannot delete bucket
```

### Expected behavior
1. Deleting last bucket should be allowed.

### Steps to reproduce
1. Use the noobaa cli:
```
. devenv.sh
nb install
nb bucket delete first.bucket
```

### More information - Screenshots / Logs / Other output
```
$ nb bucket delete first.bucket
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: StatefulSet "noobaa-core"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Service "s3"
INFO[0000] ✅ Exists: Secret "noobaa-server"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: bucket.delete_bucket() Request: nb.DeleteBucketParams{Name:"first.bucket"}
ERRO[0000] ⚠️ RPC: bucket.delete_bucket() Response Error: Code=LAST_BUCKET Message=Cannot delete bucket
PANI[0000] ☠️  Panic Attack: [] Cannot delete bucket
```

**Comment by nimrod-becker** [comment]
Main thing would be to verify we don't have flows which assume there is at least 1 bucket (same in the FE)
