### ISSUE TITLE
Create account with S3 access when no resources requires default_pool

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5675]
### Environment info
- NooBaa Version: **5.1**
- Platform: **Kubernetes 1.15 | minikube 1.3**

### Actual behavior
1. According to the code it should allow it but seems like there's a typo - it should look for `mongo_info` instead of `mongo_pool_info:
https://github.com/noobaa/noobaa-core/blob/d76679d9b1fb9a40789d8985250172ceaceeef9c/src/server/system_services/account_server.js#L1194-L1199

### Expected behavior
1. Should allow creating account with s3_access without default pool when there are no other pools.

### Steps to reproduce
1. Create account with s3_access

**Comment by nimrod-becker** [comment]
Seems like the issue is with allowed_buckets (optional, but fails when not provided) - should pass if allowed buckets is empty but allow bucket creation it true
