### ISSUE TITLE
get_aprox_dedup_keys_number runs for more than 3 minutes

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#5678]
### Environment info
- NooBaa Version: 4.0.2-1548373
- Platform: OpenShift 4.1

### Actual behavior
1. When Dedup indexer run the get_aprox_dedup_keys_number to try and get the approximate size of dedup index it takes more than 3 minutes on a system with a big number of chunks (>1.5M)

### Expected behavior
1. some options here:
- The query should be indexed better - taking much less than 3 minutes
- Dedup Indexer should run less - currently running every 1 minute - when each run takes 3 minutes sound too much

### Steps to reproduce
1. Run dedup indexer in a system with a large amount of chunks

**Comment by nimrod-becker** [comment]
Let's fix to run less, for now, 12h sounds good
