### ISSUE TITLE
Inner tables in buckets/ resources pages jumps to the right after loading the page content

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5692]
### Environment info
- NooBaa Version: **5.1.1-32b0e18**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. after a couple of seconds on the buckets or resources screen, the inner content of the table moves to the right side and aligns. 

### Expected behavior
1. The table content should not move, tilt or align after the screen is presented. 

### Steps to reproduce
1. Go to the buckets list page, focus on the lines-> see the movement

### More information - Screenshots / Logs / Other output
![Aug-27-2019 14-35-07](https://user-images.githubusercontent.com/10331355/63771829-8fa9a500-c8e0-11e9-8403-7e276616dcaa.gif)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
