### ISSUE TITLE
Should update cert in agents when cert changes

### ISSUE THREAD

**Issue by nimrod-becker** [noobaa/noobaa-core#5722]
### Environment info
- NooBaa Version: 5
- Platform: All

### Actual behavior
1. When we update the NooBaa cert, we restart webserver and s3rver
2. As a result of the webserver restart, the nodes_monitor would also restart which would cause all agents to reconnect to it.
3. Upon the new connection, we would call ```_run``` which will call ```_update_node_service```

During this flow, we check if location or s3 gw on the node was changed, if yes we update the node with the server's cert, if not we don't.

```
const service_enabled_not_changed = (item.node.enabled && should_enable) || (!item.node.enabled && !should_enable);
        const location_info_not_changed = _.isEqual(item.agent_info.location_info, location_info);
        if (service_enabled_not_changed && location_info_not_changed) {
            return;
        }
```

### Expected behavior
1. We should also update the node cert if the server cert was updated 

### Steps to reproduce
1. Create k8s agents
2. Update server cert

**Comment by nb-ohad** [comment]
As of the separation of endpoints from storage agents, this bug is not relevant anymore
