### ISSUE TITLE
Round trip time shows- Nan ms

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#5733]
### Environment info
- NooBaa Version: 5.2.0
- Platform: minikube 1.1.1

### Actual behavior
1. Round trip time shows Nan ms

### Expected behavior
1. Round trip time should show numeric ms and not Nan. 

### Steps to reproduce
1.

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/35330373/65145129-77313400-da21-11e9-8d4f-6b52985cdc21.png)
[nbfedump.2019_09_18-14_35_18.json.gz](https://github.com/noobaa/noobaa-core/files/3626140/nbfedump.2019_09_18-14_35_18.json.gz)

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
