### ISSUE TITLE
Offline nodes capacity is considered as "other" usage instead of "unavailable" in node capacity pie chart

### ISSUE THREAD

**Issue by shirimordechay** [noobaa/noobaa-core#5749]
### Environment info
- NooBaa Version: **5.2.0-643fa2f**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. When a K8s node is offline, we describe his capacity as "other" in the pie chart

### Expected behavior
1. It should be "unavailable", this is the exact purpose of "unavailable" capacity 

### Steps to reproduce
1. See offline node page 

### More information - Screenshots / Logs / Other output
<img width="1041" alt="Screen Shot 2019-09-25 at 15 04 02" src="https://user-images.githubusercontent.com/10331355/65599213-000e1980-dfa6-11e9-8d45-d25dcc5f0866.png">
<img width="1671" alt="Screen Shot 2019-09-25 at 15 03 30" src="https://user-images.githubusercontent.com/10331355/65599215-000e1980-dfa6-11e9-99ef-5f712f7e0f51.png">

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
