### ISSUE TITLE
Add bucket usage to the Prometheus Metrics (OBC and OB)

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#5755]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have any usage for OBC and OB.

**Describe the solution you'd like**
We should be able to know the usage and export it to Prometheus metrics

**Describe alternatives you've considered**
Description of alternative solutions or features you've considered.

**Additional context**
This is required for OCS 4.3

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OCS Dashboard Debt](https://trello.com/c/uYkXGuLY/903-ocs-dashboard-debt)

**Comment by nimrod-becker** [comment]
@jeniawhite Can you remind me what exactly is missing here ?

**Comment by jeniawhite** [comment]
@nimrod-becker 
It is solved with the new upcoming version of the dashboard.
The user will be able to see in the project usage breakdown the cluster-wide (OB) and all of the other projects will be the OBC usage.
