### ISSUE TITLE
k8s pool status is stuck on initializing when a persistent volume cannot be allocated

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5758]
### Environment info
- NooBaa Version: 5.2.0
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 **

### Actual behavior
1. When creating a k8s pool, if the persistent volumes cannot be allocated or mount, the pool status is stuck on initializing

### Expected behavior
1. The pool status should change to some kind of an error status after a period of time (timeout the operation)

### Steps to reproduce
1.

**Comment by shirimordechay** [comment]
@nb-ohad Add a new status after time out "Pool initialization failed" (red error icon) + Add an alert (if doesn't exist yet) "Kubernetes Pool POOL_NAME initialization could not be completed, check the cluster capacity or delete this pool"

**Comment by mykaul** [comment]
@nb-ohad  - is this being worked on? Does this block https://bugzilla.redhat.com/show_bug.cgi?id=1757500 ?

**Comment by nimrod-becker** [comment]
Yes, its the same. 
There is an alert, only the status is missing

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agents via Operator](https://trello.com/c/VPZdQjvY/857-agents-via-operator)
