### ISSUE TITLE
negative Data Reduction Savings when connecting a bucket to s3-compatible backingstore

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5768]
### Environment info
- NooBaa Version: **5.2.0-d6fd801**
- Platform: **minikube 1.4.0**

### Actual behavior
1. Data Reduction Savings:  -10 bytes (0%)

```
	"storage_stats" : {
		"chunks_capacity" : 1029,
		"objects_size" : 1024,
		"objects_count" : 1,
```

```
> db.objectmds.find({ deleted: null }).pretty()
{
	"_id" : ObjectId("5d95e948095faf0055afdaec"),
	"system" : ObjectId("5d95e45abafae0002628b383"),
	"bucket" : ObjectId("5d95e45dbafae0002628b399"),
	"key" : "noobaa_blocks/5d95e461bafae0002628b3a0/blocks_tree/other.blocks/_test_store_perf",
	"content_type" : "application/octet-stream",
	"size" : 1024,
	"sha256_b64" : "Iul7m9v9Lk7kbkNNk+AdEzFtuHLor3Zuzgn5foUMZ+s=",
	"xattr" : {

	},
	"create_time" : ISODate("2019-10-03T12:27:52.209Z"),
	"etag" : "0b392a457cc847c1d4cdb733acfb74ad",
	"md5_b64" : "CzkqRXzIR8HUzbczrPt0rQ==",
	"num_parts" : 1,
	"version_seq" : 251,
	"stats" : {
		"last_read" : ISODate("2019-10-03T12:27:53.486Z"),
		"reads" : 6
	}
}
```

```
> db.datachunks.find({ deleted: null }).pretty()
{
	"_id" : ObjectId("5d95e986095faf0055afdaf8"),
	"bucket" : ObjectId("5d95e45abafae0002628b38a"),
	"tier" : ObjectId("5d95e45abafae0002628b388"),
	"size" : 1024,
	"compress_size" : 1029,
	"frag_size" : 1029,
	"dedup_key" : BinData(0,"vgKGGii+G49XSa/cqy0UtCZfekgFCRl6nYOpK9yvZu9kLKNZp/r3DLmX8n1OcrzJ"),
	"digest" : BinData(0,"vgKGGii+G49XSa/cqy0UtCZfekgFCRl6nYOpK9yvZu9kLKNZp/r3DLmX8n1OcrzJ"),
	"cipher_key" : BinData(0,"iXRPUSJQpXG2IkWrvdLPOyesBBXMT8LF2zulkdgkmBk="),
	"chunk_config" : ObjectId("5d95e45abafae0002628b385"),
	"system" : ObjectId("5d95e45abafae0002628b383"),
	"tier_lru" : ISODate("2019-10-03T12:28:56.922Z"),
	"frags" : [
		{
			"_id" : ObjectId("5d95e986095faf0055afdafa"),
			"data_index" : 0,
			"digest" : BinData(0,"DW8EecSBhpsSGxDxui6os/cAoGo=")
		}
	]
}
```

```
> db.datablocks.find({ deleted: null }).pretty()
{
	"_id" : ObjectId("5d95e986095faf0055afdaf6"),
	"bucket" : ObjectId("5d95e45abafae0002628b38a"),
	"chunk" : ObjectId("5d95e986095faf0055afdaf8"),
	"frag" : ObjectId("5d95e986095faf0055afdafa"),
	"node" : ObjectId("5d95e45cbafae0002628b394"),
	"pool" : ObjectId("5d95e45abafae0002628b384"),
	"size" : 1029,
	"system" : ObjectId("5d95e45abafae0002628b383")
}
```

### Expected behavior
1.  Data Reduction Savings should not be negative

### Steps to reproduce
1. Create s3-compatible backingstore and connect a bucket to it
2. upload unique 1k files.
3. See that the Data Reduction Savings is negative

**Comment by nimrod-becker** [comment]
Seems like its not an error in counting, but rather it's an issue in which we try to compress an already compressed object and thus the actual size is larger

**Comment by shirimordechay** [comment]
@nb-ohad Please add an explanation next to the negative number for this use case:
![image](https://user-images.githubusercontent.com/10331355/66296479-4d6b7e80-e8f6-11e9-97d4-ef723cfed89c.png)

**Comment by mykaul** [comment]
@nimrod-becker  - then we need another issue to track the real issue - you should not be storing the result if it ended up larger than the non-compressed version. I'd assume you might be hitting this with an already encrypted object, etc.

(Also, it'd be nice if we could not try to compress the whole chunk and give up after half of it or so if it did not give us enough compression ration...)

**Comment by nimrod-becker** [comment]
@mykaul We can try to identify this way or another if we should compress or not, I agree on that. 
But what do you mean not store the result? There are two numbers here, the logical size and the actual size of disk. From those two you get this statistic.

**Comment by mykaul** [comment]
I meant that if you try to compress a block and it ends up bigger than the original size, don't store the result 'compressed' block, but the original block instead.
