### ISSUE TITLE
NooBaa image can be "downgraded"

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5779]
Using various methods (for example kubectl edit NooBaa), one update the NooBaa image to an older image than the current. This may cause undesired behaviors.

I suggest a fix where the NooBaa operator will not accept updates to the NooBaa CRD where the NooBaa image is older build then the current installed one.

**Comment by nimrod-becker** [comment]
Moved from operator to core. 
INIT container (during its upgrade check) should verify if we try to "downgrade", communicate to logs/alerts whatever and prevent the pod from continuing

**Comment by guymguym** [comment]
Adding one request to this - please allow env var such as:
```
FORCE_DOWNGRADE_FROM_VERSION="5.1.1" 
```
that will allow to bypass this check if the current version of the DB matches.
