### ISSUE TITLE
Cannot log in after installation

### ISSUE THREAD

**Issue by cwilkers** [noobaa/noobaa-core#5793]
### Environment info
- NooBaa Version: **5.0.1-2dda7b3**
- Platform: **OpenShift 4.1 **

### Actual behavior
1. On first login attempt:

    {"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"/fe/"}

Logs below

### Expected behavior
1. first login dialogue as admin

### Steps to reproduce
1. Installed using https://raw.githubusercontent.com/noobaa/noobaa-core/master/src/deploy/NVA_build/noobaa_deploy_k8s.sh
2. ./noobaa_deploy_k8s.sh deploy -n noobaa
3. Created openshift route for mgmt service
4. login with chrome as firefox was rejected.

### More information - Screenshots / Logs / Other output

https://gist.github.com/cwilkers/695f78c253a88ea2e11e006b0049d14c

**Comment by cwilkers** [comment]
I deleted the namespace and retried the installer. Now, if I go through the nodeip URL, I get:

on firefox: Noobaa works best on chrome, no possibility to continue with firefox.

on chrome: infinite loop of redirect to cluster oauth url with an ssl certificate error. each time I accept the certificate and try to continue, I end up on the same page again asking to accept the invalid certificate for the same site.

**Comment by nimrod-becker** [comment]
@cwilkers 
Both documentation and the script are outdated. We will fix the docs today and will remove the script. It became irrelevant with our noobaa-operator offering in operatorhub / noobaa-cli (https://github.com/noobaa/noobaa-operator)

**Comment by ron1** [comment]
@nimrod-becker What is the current state of support for Firefox? Does NooBaa just work "best" on Chrome or does it currently not work at all on Firefox?

**Comment by nimrod-becker** [comment]
@ron1 
FF is not tested. We are aware of several UI glitches (scrollers not in place etc.)
So I guess my answer would be depends on what you are trying to do, and that might change as well with the next FF version.

**Comment by cwilkers** [comment]
@nimrod-becker Thanks! The operator worked for me (though only the 2.0.3 version under releases, not 2.0.0 mentioned in the README.md)
