### ISSUE TITLE
Separate Endpoints & Auto-Scale

### ISSUE THREAD

**Issue by nimrod-becker** [noobaa/noobaa-core#5825]
**Is your feature request related to a problem? Please describe.**
- Today endpoints are a part of the core container (forked according to cpu/mem resources) or a part of the agents deployed as part of the k8s pools.
- Scaling endpoints can only be done by either adding more resources to the core pod, or increasing the k8s pool sts, which also requires PVs (since it serves both endpoints and storage) and it not very dynamic (can be changed via admin config)
- Endpoints scaling can be helpful since the CPU intensive work is done in the endpoint. Dynamic provisioning is better since it can address the current conditions of the cluster instead of a pre-configured one.

**Describe the solution you'd like**
- Separated stateless endpoints with auto-scaling
- Corresponding UI to manage/understand statistics and history of the endpoints workloads

**Additional context**
- Stateless endpoints as deployments with auto-scale
- One deployment per cluster
- External cluster deployment support
- Management / Statistics UI for endpoints
- Cleanup of old pieces of UI related to endpoints from k8s pools
- Cleanup old endpoint flows from nodes_monitor

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Standalone endpoints](https://trello.com/c/LNrzkoOq/907-standalone-endpoints)

**Comment by nb-ohad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint UI/UX](https://trello.com/c/9Zrgc4To/924-endpoint-ui-ux)

**Comment by nimrod-becker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint Management](https://trello.com/c/9Zrgc4To/924-endpoint-ui-ux)

**Comment by nimrod-becker** [comment]
@nb-ohad what's missing here?

**Comment by guymguym** [comment]
@nimrod-becker @nb-ohad Can you add a summary of why this issue is closed - is it resolved completely/partially, etc. Thanks

**Comment by nimrod-becker** [comment]
Sure,
Issue was resolved in 5.3 with the separation of endpoints from agents and the addition of K8S HPA integration (corresponding operator branch 2.1)
