### ISSUE TITLE
Cluster page (UI) shows negative memory usage

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#5869]
### Environment info
- NooBaa Version: **5.3.0-ab60a6e**
- Platform: **Kubernetes 1.15.7**

### Actual behavior
1. Cluster page shows negative memory usage

### Expected behavior
1. Memory usage cannot be negative

### More information - Screenshots / Logs / Other output
![NooBaa_Management_Console](https://user-images.githubusercontent.com/28217223/72345256-e96a0a80-36db-11ea-83e2-4d05ae1cb64a.png)

**Comment by liranmauda** [comment]
in os_utils.js under the function os_info we get the totalmem from the container limit.
the free mem we get from os.freemem() (which is not correct for containers)

The way we should get the used memory in a pod is to run: `$ kubectl top pod noobaa-core-0`
```
$ kubectl top pod noobaa-core-0
NAME            CPU(cores)   MEMORY(bytes)
noobaa-core-0   41m          468Mi
```

**Comment by nimrod-becker** [comment]
Screen was removed
