### ISSUE TITLE
Logout after create system redirects to create system

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#5898]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. I'm getting redirected to create a system after log out. When I open a new tab I'm getting redirected to log in screen as expected.

### Expected behavior
1. I should get redirected to log in screen.

### Steps to reproduce
1. Create a system
2. Log out

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
