### ISSUE TITLE
Logs are full with INVALID_SCHEMA errors

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#5915]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

A couple of months ago we added a lst_update field to every system_store.make_change  operation (for inserts and updates) but not all of the core entity schemas were updated.
This causes a lot of INVALID_SCHEMA errors (which are actual warnings) in the logs which clutter the logs and obfuscate actual schema violations.

### Actual behavior
1. Noobaa core logs are full with schema violations of `additnialproperties: last_update` for many of the core entities

### Expected behavior
1. No error should occur for valid entities.

### Steps to reproduce
1. Create a system, let it run, look at the logs.

**Comment by liranmauda** [comment]
Not reproducible, Closing.
