### ISSUE TITLE
MongoDB Seg Faults

### ISSUE THREAD

**Issue by gbadanahatti** [noobaa/noobaa-core#5971]
### Environment info
- NooBaa Version:
root@ait-kube-1:~/noobaa/2.1.0# ./noobaa-linux-v2.1.0 version
INFO[0000] CLI version: 2.1.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:5.3.0       
INFO[0000] operator-image: noobaa/noobaa-operator:2.1.0 

 Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**
Kubernetes 1.14.1 with VMWare CSI drivers

### Actual behavior
1. MongoDB seg faults with "Invalid Access at address 0" and this results in an un-usable system.

### Expected behavior
1. DB should remain up. Or at a restart try to repair the DB so that the system is usable.

### Steps to reproduce
1. Trigger to create the problem is not known at this time. 

### More information - Screenshots / Logs / Other output
![Screen Shot 2020-03-31 at 9 37 39 AM](https://user-images.githubusercontent.com/37121690/78046294-9ac42800-733c-11ea-8201-9e8951a3ba65.png)

**Comment by gbadanahatti** [comment]
@nimrod-becker: Thanks! Looks like there is no workaround at this time - correct?

**Comment by guymguym** [comment]
Hi @gbadanahatti Thanks.
We were trying to catch this case in order to replace the db container image with a debug version of it. 
@jackyalbo Can provide the info - I think it was this image `jalbo/mongodbg3.6.3:1` from docker hub.

**Comment by jackyalbo** [comment]
indeed this is the version with debug symbols:
[https://hub.docker.com/repository/docker/jalbo/mongodbg3.6.3](url)
@gbadanahatti if you can try to reproduce with this version it will be a huge help.
Sadly we failed reproducing while working with this version.

**Comment by gbadanahatti** [comment]
@jackyalbo , will try with this image and let you know.

**Comment by gbadanahatti** [comment]
@jackyalbo ,  I have been running load with this image for the past 18 hours and have not seen it. Is this debug version based on the same version that exists in the build? Looking at the forums, it seems that this issue in mongodb has been fixed in 3.4.6. Will we be able to reproduce this issue with this image?

**Comment by jackyalbo** [comment]
@gbadanahatti ,yes, this is the image we are using (for upstream) centos/mongodb-36-centos7
the image we gave you is base on the same 3.6 version just with debug-symbols
both are later then 3.4.6

https://hub.docker.com/r/centos/mongodb-36-centos7

**Comment by guymguym** [comment]
FWIW I think every version of mongo probably fixed multiple segv issues...

**Comment by gbadanahatti** [comment]
@jackyalbo , last night the mongo db pod restarted. Although, there is nothing obvious in the logs that indicates a failure. So I am not sure why there was a restart and as a result the endpoint also restarted. Does the endpoint self signed certificate change after the restart? This interrupts the
 client traffic. I have attached the logs of the container that restarted.
[mongo.log.gz](https://github.com/noobaa/noobaa-core/files/4428110/mongo.log.gz)

**Comment by gbadanahatti** [comment]
@jackyalbo : Under load, the the DB has crashed 50 times over the past 24hours with the debug image. This results in end point restart as well.

**Comment by jackyalbo** [comment]
@gbadanahatti Can you send me/attach the whole logs?

**Comment by gbadanahatti** [comment]
@jackyalbo , these are probably not logs that will help becuase of the number of restarts that has happened. Should we change the restart policy to not restart and catch the logs. 

[mongo.tar.gz](https://github.com/noobaa/noobaa-core/files/4446227/mongo.tar.gz)
