### ISSUE TITLE
Incorrect error returned if a user tries to recreate a bucket

### ISSUE THREAD

**Issue by soumyakoduri** [noobaa/noobaa-core#5980]
### Environment info
- NooBaa Version: master
- Platform: minikube 1.1.1 

### Actual behavior
1. If a user tries to recreate a bucket which it already owns, Noobaa server throws "BucketAlreadyExists" error

### Expected behavior
1. But as per https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html, Noobaa server should return "BucketAlreadyOwnedByYou" error.

### Steps to reproduce
1. Create a bucket on Noobaa endpoint from a user
2. Now via the same user, try to recreate the bucket with same name
3. The operation fails with 'BucketAlreadyExists' error

**Comment by soumyakoduri** [comment]
I have posted https://github.com/noobaa/noobaa-core/pull/5979 to fix this issue. Kindly review.

**Comment by guymguym** [comment]
Hey @soumyakoduri 
1. Is this covered by ceph/s3-tests?
2. Notice this has some legacy caveats as documented by aws docs -
‘’’
The bucket you tried to create already exists, and you own it. Amazon S3 returns this error in all AWS Regions except us-east-1 (N. Virginia). For legacy compatibility, if you re-create an existing bucket that you already own in us-east-1, Amazon S3 returns 200 OK and resets the bucket access control lists (ACLs).
‘’’

**Comment by soumyakoduri** [comment]
> Hey @soumyakoduri
> 
>     1. Is this covered by ceph/s3-tests?
> 
No. I have been manually testing it using s3cmd and aws tools. I will confirm with Ceph RGW lead and update.

>     2. Notice this has some legacy caveats as documented by aws docs -

Right. When I inquired about it, I was told that it should be okay to return this error all the time. I will re-confirm and update.

**Comment by soumyakoduri** [comment]
Hi @guymguym 
> > ```
> > 1. Is this covered by ceph/s3-tests?
> > ```
> 
> No. I have been manually testing it using s3cmd and aws tools. I will confirm with Ceph RGW lead and update.

Seems like there are two test-cases in ceph/s3-tests to test this scenario -

test_bucket_create_exists() - expects '200 OK or a 409 BucketAlreadyOwnedByYou'
test_bucket_create_exists_nonowner() - BucketAlreadyExists

> 
> > ```
> > 2. Notice this has some legacy caveats as documented by aws docs -
> > ```
> 
> Right. When I inquired about it, I was told that it should be okay to return this error all the time. I will re-confirm and update.

Casey, RGW lead  gave a detailed explanation on this -
