### ISSUE TITLE
Question: What is the planed strategy for using Noobaa-Function with additional modules needed.

### ISSUE THREAD

**Issue by QuintinBecker** [noobaa/noobaa-core#5993]
Is there any documentation available on how to include additional modules used by functions?

We tried adding modules within a zip-file with a subfolder (./node_modules/…) which resulted in a function that can no longer be triggered (Errorcode: “new invocation failed”).

If we build core-images on our own we include modules but lack the possibility of automatic updates.

**Comment by QuintinBecker** [comment]
@jeniawhite 
Can you help us with this issue, it would help us a lot to add modules on demand. 
If we try to add modules in a subfolder ``` packages``` and get following error:
```
May-8 11:32:00.907 [WebServer/41] [ERROR] CONSOLE:: _load_func_code: FAILED Error: EEXIST: file already exists, mkdir '/tmp/functions_loading/k9y4dhq6/package'
--
May-8 11:32:00.912 [WebServer/41] [ERROR] CONSOLE:: RPC._on_request: ERROR srv func_api.invoke_func reqid 893@wss://noobaa-mgmt-noobaa-test.some-path.com(11idd0n.zu8r) connid ws://[::ffff:10.129.2.1]:53186/(8rmeekve) Error: EEXIST: file already exists, mkdir '/tmp/functions_loading/k9y4dhq6/package'

```

**Comment by jeniawhite** [comment]
@QuintinBecker 
Sorry for the late response, somehow missed the mention.
NooBaa Lambda requires modules from the core node_modules and not attached node_modules folder when you upload the functions.
This means that you can require modules that are present in core's node_modules without the attachment of these modules (like aws_sdk for example).
If you'd like to require your own custom modules, you can do so by uploading a .js file beside your handler function file and requiring it from your handler function file.

**Comment by dannyzaken** [comment]
@QuintinBecker thanks for the feedback. this was indeed a bug, PR #6090 should fix it.
please let me know if you encounter any other issues with your package. If you do see issues then attach a package that reproduces the issue
