### ISSUE TITLE
Deleted all buckets using OBC fail to cleanup the data from the backing store

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6001]
### Environment info
- NooBaa Version: **5.3.0-9f579d9**
- Platform: **OpenShift 4.3**

### Actual behavior
1. Deleted 4 OBC with total 500 GB stored on the default backing store (AWS).
2. Waited about 1 hour and didn't see the size of the resource getting lower.
3. Full logs attached, but this errors repeat in the log:

```
Apr-27 16:51:31.679 [BGWorkers/31]    [L0] core.server.bg_services.buckets_reclaimer:: emptying bucket SENSITIVE-11db7f09259043b50ec16f62ed701d31. deleting next 1000 objects
Apr-27 16:51:31.680 [WebServer/37] [ERROR] CONSOLE:: RPC._on_request: ERROR srv object_api.delete_multiple_objects_by_prefix reqid 324396@wss://127.0.0.1:8443/(3oz5ju7) connid ws://[::ffff:127.0.0.1]:58876/(3t3wsrl) Error: No permission to access bucket
    at RpcRequest.req.check_s3_bucket_permission (/root/node_modules/noobaa-core/src/server/common_services/auth_server.js:625:19)
    at load_bucket (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1184:9)
    at Object.delete_multiple_objects_by_prefix (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:737:5)
    at Object.server_func (/root/node_modules/noobaa-core/src/rpc/rpc.js:86:48)
    at /root/node_modules/noobaa-core/src/rpc/rpc.js:348:41
```

### Expected behavior
1. Should cleanup the storage.

### Steps to reproduce
1. Create OBC
2. Use it to fill data to the bucket
3. Delete OBC

### More information - Screenshots / Logs / Other output

Logs:
[read-system.log](https://github.com/noobaa/noobaa-core/files/4551864/read-system.log)
[noobaa-core-0.log](https://github.com/noobaa/noobaa-core/files/4551866/noobaa-core-0.log)

![image](https://user-images.githubusercontent.com/1091422/80599702-0381eb80-8a34-11ea-8e88-542140392198.png)

**Comment by BarakSason** [comment]
This issue was not seen by testing with version 5.9.
A minor accounting issue was seen (created https://github.com/noobaa/noobaa-core/issues/6650 for tracking).
