### ISSUE TITLE
S3 Namespace Triggers

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#6007]
**Is your feature request related to a problem? Please describe.**
Currently, supported triggers are ObjectCreated. ObjectRead, ObjectRemoved.
We should be fully compliant with S3 trigger event structure (ObjectCreated:Put, ObjectCreated:Copy etc..., and not just trigger a single Trigger in all these cases.
Multipart creation trigger is working on Namespace_NB but not on Namespace buckets (due to requirement of content-type and size, which will create another query for MD and this is very inefficient).

**Comment by QuintinBecker** [comment]
We just ran in this problem when using namespace buckets. 

As you target a fully S3 compliant interface what might be some work-arounds possible from this point? 

How much impact might these additional calls to get full info of the object have on the performance ? I can not estimate based on my current experience.

**Comment by lallinger-arbeit** [comment]
@jeniawhite any update on this? We currently use a quite ugly workaround for create triggers on multipart uploads on namespaced buckets where we statically define the content-type and content-size, because we do not need this information..

**Comment by jeniawhite** [comment]
@lallinger-arbeit 
The only supported triggers and their ops in namespace buckets (when target resource is not NooBaa bucket) are:
`read_object_stream => ObjectRead` 
`upload_object => ObjectCreated` 
`delete_object => ObjectRemoved`
`delete_multiple_objects => ObjectRemoved`.
We did not advance with the triggers further than what we currently have.

@QuintinBecker 
We need to evaluate the performance impact once again (due to codebase changes over time), in order to give out a precise estimate.
But as far as I remember it was running additional queries like head object/parts/blob to the remote resource (AWS, Azure, GCP bucket/container) to get more info on the object/blob.
You run this on every initialization and etc...

@nimrod-becker 
Do you have anything to add regarding trigger planning?

**Comment by lallinger-arbeit** [comment]
@jeniawhite i think having a performance impact on an namespaced bucket, which has a function activated, is better than not having the ability to use the triggers, because currently you think everything works for example for object created when only testing with small files until you upload a file which gets split into multipart and then wonder why it's not working..

I would prefere if the triggers would work on namespaced buckets exactly the same they work on encrypted buckets and being informed that this may lead to performance impacts, e.g. by a popup in the UI when enabling a function on a namespaced bucket.

**Comment by jeniawhite** [comment]
@lallinger-arbeit @QuintinBecker 
Hello,
I would like you to join our community meeting today.
We would like to hear your use case story and help to advance the gaps.

We have a Slack channel and weekly occurring community meetings via Google Meet (recorded and uploaded to YouTube).
NooBaa community:
* Slack:
    * Get a Slack invite - https://www.noobaa.io/community
    * Sign in to slack - https://noobaa.slack.com
* Meetings:
    * Public Calendar - https://calendar.google.com/calendar/u/1/r?cid=aGFvbmJiMWszb2dib2phbXIxa2YwdGpldWdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
    * Agenda Document - https://docs.google.com/document/d/1VgiNOuLW92KcuJ0sGnXRVfT9oeImwbzbpEb4QkCEvDY/edit#heading=h.z2otx7ykzp6t
    * Youtube community meeting recordings - https://www.youtube.com/playlist?list=PLsawh7cxjeFDiUsuOGncF_KZImQCgj5U-

Here is a link to today's Google Meet - https://meet.google.com/uwm-ogup-oxr (scheduled to 6 PM-7 PM Israel Standard Time GMT+2).

Would be awesome if you'd join.
Thank you.
