### ISSUE TITLE
Question: Disable deduplication and compression

### ISSUE THREAD

**Issue by gbadanahatti** [noobaa/noobaa-core#6015]
Is there a way to disable deduplication and compression in noobaa?

**Comment by nimrod-becker** [comment]
To begin with, and this is a very user-friendly option, the config.js file contains most of the capabilities enabled or disabled, you could always change that.

Specifically for encryption, we saw the need and added a more friendly way to do it, please see
https://github.com/noobaa/noobaa-core/pull/5911

This allows this configuration to be passed as an ENV variable mapped to the pod.

**Comment by gbadanahatti** [comment]
Thanks!
