### ISSUE TITLE
Export nodejs default prometheus metrics for bg_workers and hosted_agents processes 

### ISSUE THREAD

**Issue by nb-ohad** [noobaa/noobaa-core#6062]
**Is your feature request related to a problem? Please describe.**
Currently, we only expose default nodejs metrics using the nodejs Prometheus client from the web_server process. The information is very valuable when trying to analyze the CPU and Memory consumption behavior of our processes over time.

**Describe the solution you'd like**
Export the default nodejs Prometheus client metrics for the  bg_workers and hosted_agents processes 

**Additional context**
The way we expose these metrics for scraping should work for Prometheus installed on OpenShift clusters, In that case, I am not sure if we can have more the one scraped endpoint per pod which might make exposing these metrics more tricky

**Comment by guymguym** [comment]
If we move those processes to separate containers we will get it out of the box.
The only technical gap for us is to handle to code paths that ask to restart those services internally.
I would explore this direction to solve this issue because it aligns with microservices design and exposes finer control to kubernetes operators.
Thoughts?

**Comment by nimrod-becker** [comment]
yes. Would also require finer tuning for resources we allocate per each container (cpu, mem)

**Comment by guymguym** [comment]
Going to the complete opposite direction would mean to make the core pod even more fat and include an internal metrics server process inside that can fetch on demand from the other processes. Will work easily too, just depends on where we are going with those internal services, and is there really enough benefit exposing them to kubernetes for the loss of dynamic resource allocation between them.
