### ISSUE TITLE
Replace Bluebird with native promise

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6070]
See the list of occurrences below.
I think we can start from the top and resolve them one by one.
For example `P.resolve` can be replaced with `Promise.resolve`.
But `Promise.fromCallback` requires refactor or keeping a util function.
I suggest to keep this module in `require(./src/util/promise')` to have promise utilities and even merge into it the utils from `require('./src/util/promise_utils')`.

```
$ rg 'P\.\w+|new P\(' --only-matching --no-heading --no-line-number --no-filename | sort | uniq -c | sort -nr
 334 P.resolve
 101 P.fromCallback
  98 P.delay
  84 P.map
  75 P.fcall
  46 P.all
  41 P.ninvoke
  37 new P(
  34 P.join
  16 P.try
  15 P.defer
  11 P.nfcall
  10 P.reject
  10 P.each
   5 P.TimeoutError
   4 P.promisifyAll
   4 P.hijackQ
   3 P.config
   2 P.test
   2 P.prototype
   2 P.props
   2 P.promisify
   2 P.any
   1 P.then
   1 P.catch
```

**Comment by liranmauda** [comment]
👍 
I think that in simple function like: https://github.com/noobaa/noobaa-core/blob/master/src/agent/agent.js#L222:L235
We can even eliminate the use of P.resolve like this:
```
    async start() {
        const dbg = this.dbg;
        this.is_started = true;
        this.rpc.set_disconnected_state(false);
      try { 
       await this._init_node();
       await this._do_heartbeat();
      } catch (err) {
                dbg.error('server failed to start', err.stack || err);
                this.stop();
                throw err;
      }
    }
```
don't code review it, Just my 2 cents... 🙂

**Comment by guymguym** [comment]
Sure, but I would actually start with a simple search replace of `P.resolve(` to `Promise.resolve(` because that case is at least trivial to replace without refactoring to async-await.

**Comment by liranmauda** [comment]
Changing `P.resolve()` to `Promise.resolve()` where there is `.return()` `.timeout()` `.delay()` and `.spread()` is not possible without refractoring.

**Comment by guymguym** [comment]
@liranmauda can we close?

**Comment by liranmauda** [comment]
@guymguym I guess so.
Closing.
