### ISSUE TITLE
Can't use override environment variables for config.js

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6154]
### Environment info
- NooBaa Version: 5.4
- Platform: Any

### Actual behavior
1. When specifying environment variables starting with `CONFIG_JS_` these get ignored because  the config.js file first tries to require a local config and if this does fail it does not check the environment variables:

https://github.com/noobaa/noobaa-core/blob/74b79637d8a9a1dca2baf51598860579711a5c6b/config.js#L466-L475

### Expected behavior
1. The `config.js` file should first try to require the `local-config` in its own try catch block
2. In a second try catch block it should be tried to load environment variables

=> Setting a `CONFIG_JS_` variable leads to the set value getting loaded.

### Steps to reproduce
1. Set a `CONFIG_JS_` variable

**Comment by guymguym** [comment]
Fixed already in #6213 . Thanks !!
