### ISSUE TITLE
NS-CACHE: Metrics cleanup for bucket names - GAP

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6212]
### Environment info
- NooBaa Version: **5.6**
- Platform: **NA**

### Actual behavior
1. Collecting cache metrics with bucket-name labels means we need to cleanup those metrics when the bucket is deleted.
2. See update_namespace_cache_stats() 
https://github.com/noobaa/noobaa-core/blob/43dd7bbb1fea7b4e772ec2a6c0276b0afbf2e810/src/sdk/endpoint_stats_collector.js#L118-L133

### Expected behavior
1. Should not leave garbage in endpoint memory/prometheus.

### Steps to reproduce
1. @nb-ohad @jeniawhite

**Comment by nimrod-becker** [comment]
We collect for NS buckets as well, this would be important not just cache buckets
