### ISSUE TITLE
native code sha1 calculation is wrong

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-core#6223]
### Environment info
- NooBaa Version: master
- Platform: local

### Actual behavior
1. running the following code to calculate sha1:
SHA1_MB)().update(Buffer.from("jacky")).digest().toString("hex")
2. got eea339da0d4b6b5eefbf5532901860950907d8af
3. expected result is: 64366715a186eea098dd2391f69c1afda4507574

### Expected behavior
1. expected result is: 64366715a186eea098dd2391f69c1afda4507574

### Steps to reproduce
1. complie native code 
2. run the above command  
```node -p 'new (require("./src/util/nb_native")().SHA1_MB)().update(Buffer.from("jacky")).digest().toString("hex")'```
3. verify it's as expected - 64366715a186eea098dd2391f69c1afda4507574

**Comment by guymguym** [comment]
There are two issues here - first the fact that now in master (efb132e781e6515960f94f8ecd6587bf71248778) the accidental addition of base_aliases to the x64 build is causing it to return incorrect results. When I removed it from the gyp the hash changed to `15673664a0ee86a19123dd98fd1a9cf6747550a4`.

If we break this to words (uint32):
```
15673664
a0ee86a1
9123dd98
fd1a9cf6
747550a4
```

and now reverse byte-order:
```
64366715
a186eea0
98dd2391
f69c1afd
a4507574
```
and that's the correct sha1.
not sure why we get it in reverse byte-order just for sha1....
