### ISSUE TITLE
Failing metrics tests in test_namespace_cache

### ISSUE THREAD

**Issue by mcrepeau** [noobaa/noobaa-core#6232]
### Environment info
- NooBaa Version: master branch (commit b5a1664c52)
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. When running unit tests in test_namespace_cache tests, some metrics tests are failing

### Expected behavior
1. These tests should pass

### Steps to reproduce
1. Uncomment the lines starting with validate_metric in test_namespace_cache.js
2. Run unit tests within that class

**Comment by guymguym** [comment]
Thanks @mcrepeau 
Just adding a reference here to your PR that this was created from - #6181
