### ISSUE TITLE
Spark Support

### ISSUE THREAD

**Issue by motorman-ibm** [noobaa/noobaa-core#6272]
### Environment info
- NooBaa Version: noobaa-core-nsfs
- Platform: Kubernetes 1.19.1

Specifically:
noobaa-core-6077
plus hand merged issue 6206
plus hacks to support/bypass issues opened here (along with additional error 404 fixes)

### Actual behavior
1. Spark  dataframe.write.parquet() fails
2. Presto create schema/table fails

### Expected behavior
1. Spark dataframe.write.parquet() succeeds
2. Presto create schema/table succeeds

### Steps to reproduce
Install noobaa
Run with Spark + Hadoop (currently spark-3.0.0-bin-without-hadoop + hadoop-3.1.2) - hadoop is only used to provide the s3a shim for Spark.
Create a dataframe with some data
dataframe.write.parquet()

Run with Presto (currently presto-server-0.242)
Start with default schema
create a new schema 
restart presto with schema
create a table

### More information - Screenshots / Logs / Other output

Suggested fixes. @guy has another list of fixes that are needed (mostly catching filesystem errors and returning 404). In addition to those changes, this list is needed for Spark/Noobaa compatibility

•	 REMOVED - opened as separate issue (#6417) -> _Log Management - With Spark I managed to drive Noobaa logs to the point where kubernetes killed the pods due to disk usage - that implies a log management is required for 24x7 running_
•	add mkdir for path of object on put (causes failure to put) - this is crashing write.parquet()
•	md5 management - single and multi-part puts - Extension of issue 6206
•	delete of object should remove all empty subdirs in its path (going backwards down path)
•	recursive empty subdir path delete on POST delete_multiple (going backwards down path)
•	local fs copy object does not work - Spark builds in temp dirs then copies results

A more detailed description is at
https://ibm.box.com/s/ty15l5usjttjnp6gp5p4i8xwtc0o1nop

**Comment by delillol** [comment]
Also seeing this on Noobaa version 5.7.  In this case, we see the following:

We are seeing with two of our IO stress tools, warp and cosbench, that directories are not being cleaned up after deletes supposedly occur.

1. When we run warp to our nsfs bucket, it creates directories and puts objects into those directories.  The final thing that warp does is a cleanup where it deletes all objects that it PUT into the bucket.  The objects get deleted, but the directories remain.
2. When we run Cosbench, it makes buckets (not inside nsfs bucket, but where we run to the endpoint).  Those buckets show up as directories at the endpoint.  In Cosbench's final phases, it does what it calls a "cleanup" where it deletes all of the objects.  This works OK.  It also does a "dispose" where it deletes the buckets.  The buckets seem to get deleted, but again the directories remain.
3. For Cosbench, we have ran tests to minio and found that during the "dispose" phase, the directories were deleted.  This is what leads us to believe that there may be an issue with Noobaa as to how it handles removing directories.

**Comment by motorman-ibm** [comment]
I am going to split out log management from this issue and open one specific to log management

**Comment by nimrod-becker** [comment]
should be fixed with latest PR of Fixed with #6651

**Comment by davidbw246** [comment]
@nimrod-becker I am setting to run Spark/TPC-DS on HPO. Is the fix for this issue included in a noobaa build I should use to avoid this issue?

**Comment by nimrod-becker** [comment]
Taking the latest build (for example the one which will be created today 20210721) would be the best choice
