### ISSUE TITLE
Noobaa Functions - Endpoints are not aware of running functions on scaledown

### ISSUE THREAD

**Issue by QuintinBecker** [noobaa/noobaa-core#6350]
### Environment info
NooBaa Version: master+30ee3535b5 , built in house with additional dependencies
Platform: OKD 4.5

### Actual behavior
1. When Endpint Autoscaling is enabled and Noobaa functions are running within Endpoints, there seems to be no check for running functions on a scaledown. 
2. We have been using autoscaling and saw functions running as the scaledown happened and all the running functions were lost.

### Expected behavior
1. Endpoint scaledown should only appear when all running functions have finished.
2. Behavior like: Do not accept s3 traffic on endpoint --> check for running functions --> wait till all timeouts have finished --> Scaledown.

### Steps to reproduce
1. Use a minimal function with a sleep within. 
2. Enable autoscaling of endpoints. 
3. Hit Noobaa with some traffic (like 1000 files) and wait for functions to get started in logs of container. 
4. Stop Upload and watch scaledown.
5. On monitoring you can see the wrong number of events.

**Comment by dannyzaken** [comment]
currently, we are not handling graceful shutdown in any of our processes. 
we need to catch the SIGTERM signal when the pod is stopping and maybe increase the `terminationGracePeriodSeconds`. 
when SIGTERM is received the endpoint should enter a `shutting_down` mode and reject any new requests\function invocations. when all running functions and requests are completed the endpoint should exit gracefully.
