### ISSUE TITLE
Unauthorized download of objects is possible with namespaced buckets

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6371]
### Environment info
- NooBaa Version: current master
- Platform: OKD 4.5

### Actual behavior
1. Create a namespaced bucket `somebucket`
2. Place `somefile.txt` with any data in it in the bucket
3. Run this python code it is possible to download any object without specifying a access key or secret key (set `endpoint_url` correctly):
```
import boto3
from botocore import UNSIGNED
from botocore.client import Config
s3 = boto3.client('s3',
                  endpoint_url="https://s3:443",
                  verify=False, use_ssl=True, config=Config(signature_version=UNSIGNED))
s3.download_file('somebucket', 'somefile.txt', 'out.txt')
```
4.  `somefile.txt` will be downloaded as `out.txt`

### Expected behavior
1. Download fails with "Unauthorized" or similiar error

### Steps to reproduce
1. see above

**Comment by guymguym** [comment]
Thanks for reporting @lallinger-arbeit this is indeed very serious. @jeniawhite handled a related issue in this code before so would be good to get him involved. Also FYI to @nimrod-becker to set critical priority. Lets get this sorted out asap.

**Comment by lallinger-arbeit** [comment]
@jeniawhite just tested it, and anonymous down- and upload are now blocked. The only minor thing i noticed is that the error differs between download ("forbidden") and upload ("Access denied"). This may be boto3 specific, or even intended, either way it's just a minor detail.
And thank you Jenia for the quick fix!
