### ISSUE TITLE
nsfs: noobaa UI is not showing data written on buckets

### ISSUE THREAD

**Issue by nishant16** [noobaa/noobaa-core#6406]
when we write anything under nsfs in any bucket , UI is showing 0 bytes data under  'Data Written on Buckets'  It always shows:
```
Data Written on Buckets   0 bytes
```

<img width="884" alt="nsfs_defect" src="https://user-images.githubusercontent.com/26307189/110601325-d3a28900-81aa-11eb-86bd-a7b26a131f10.PNG">

**Comment by nimrod-becker** [comment]
Moved issue to noobaa-core

**Comment by nimrod-becker** [comment]
Currently we are not collecting R/W amount per NS buckets, its an open task.
You can see the collected data per NS bucket when you go into such a bucket

example
![Screen Shot 2021-03-11 at 9 42 17](https://user-images.githubusercontent.com/11143994/110752661-3e58d080-824e-11eb-8ba0-e15965934d96.png)

**Comment by akmithal** [comment]
Hi @nimrod-becker , This UI has been very useful for debugging and getting a good view of the system. The Grafana gives a bigger picture but not details like No. of namespace buckets, No. of objects in bucket etc. 

Is there a way to get it integrated with ODF UI  or else, if there is a way to see that in current view itself. Thanks.

**Comment by romayalon** [comment]
@akmithal @nimrod-becker 
We actually do report on num_namespace_buckets metric,
Should we keep this defect for collecting and reporting R/W amount per NS buckets / No. of objects in bucket
or do we have another Github issue that tracks it?

**Comment by nimrod-becker** [comment]
We are actually in the process of deprecating and removing the noobaa UI

**Comment by akmithal** [comment]
Understood. We can close this defect then. @nimrod-becker , please do so( I don't have permission to close it)

**Comment by liranmauda** [comment]
#6948

**Comment by nimrod-becker** [comment]
Closing :)
