### ISSUE TITLE
NSFS add Etag-MD5 compatibility mode to calc MD5 on PUT-object

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6427]
### Environment info
- NooBaa Version: **5.9**
- Platform: **NA**

### Actual behavior
1. Currently all etags in nsfs are generated from inode number and mtime.
2. By using a dash `-` we make sure that the etag is not considered as md5 by the client SDK.
3. Some applications have  relied on Etags being MD5 in the PUT response and might not be able to run if PUT-object will return a non MD5 Etag.

### Expected behavior
1. We should introduce a new nsfs_account_config flag that will set that account to use etag_mode=md5 to support those applications by spending the additional CPU to calculate MD5 while streaming the data and store that in the file xattr.

**Comment by jeniawhite** [comment]
Seems relevant
https://github.com/noobaa/noobaa-core/issues/6228

**Comment by nimrod-becker** [comment]
Fixed with #6651
