### ISSUE TITLE
Function monitoring showing wrong timestamps

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6433]
### Environment info
- NooBaa Version: any
- Platform: OKD 4.6

### Actual behavior
1. The timestamps in the monitoring tab of the functions is showing wrong timestamps:
![grafik](https://user-images.githubusercontent.com/54403915/113174928-2bcd2800-924b-11eb-8939-949740b50c17.png)

### Expected behavior
1. Should show correct timestamps
### Steps to reproduce
1. Just open the monitoring tab with the 60 minute timeframe selected, no events needed

**Comment by liranmauda** [comment]
@lallinger-arbeit @jeniawhite 
This is a UI issue. (It also exists when using mongo).
The `read_func_stats` replay has `since` and `till` to determine the candle's timestamps. 
the `since` is progressing and the `till` is not which leads to this display Issue.
