### ISSUE TITLE
Error when running npm run build

### ISSUE THREAD

**Issue by YiannisGkoufas** [noobaa/noobaa-core#6448]
### Environment info
- NooBaa Version: Master branch

### Actual behavior
1. Run `npm run build`
2. Fails with errors
```
/home/yiannis/Workspaces/hybrid-storage/noobaa-core/src/native/third_party/isa-l/erasure_code/gf_vect_dot_prod_avx512.asm:142: error: parser: instruction expected
/home/yiannis/Workspaces/hybrid-storage/noobaa-core/src/native/third_party/isa-l/erasure_code/gf_vect_dot_prod_avx512.asm:148: error: parser: instruction expected
```
Attaching full logs in the end of the issue

### Expected behavior
1. Run `npm run build`
2. Build successfully

### More information - Screenshots / Logs / Other output

[error.log](https://github.com/noobaa/noobaa-core/files/6296004/error.log)

**Comment by liranmauda** [comment]
Hi @YiannisGkoufas 
What is the OS you are running on? 
It is building successfully for me on my Mac, censos8, and RHEL8

Have you tried reinstalling the node modules (We bumped some of the dependencies recently):
1. `npm run clean --force`
2. `npm install`
3. `npm run build`

**Comment by YiannisGkoufas** [comment]
Hi @liranmauda I did the steps but same error. I am on RHEL 7.9, maybe I can disable code erasure altogether?

**Comment by YiannisGkoufas** [comment]
Got it, my nasm version was old (2.10.x) due to RHEL 7.9 is a bit behind on some packages.
In case anyone runs into the issue, I needed to update to nasm 2.14 for the npm run build to work.
One side-question, the noobaa binary is build in this repo or in the noobaa-operator one?

**Comment by guymguym** [comment]
@YiannisGkoufas build the noobaa-core binary form this repo - use `npm run build:core` and it will output the binary for linux and mac in build/noobaa-core-macos/linux.

**Comment by guymguym** [comment]
@liranmauda We can improve this experience if we check the nasm version in asm.gypi:

```
    'variables': {
        'nasm_version': '''<!(nasm -v | sed -e 's/NASM version \([^ ]*\).*/\1/')''',
    },
```

similar to how we use node_arch in common.gypi:

https://github.com/noobaa/noobaa-core/blob/90ca221719245d97c08d69be37fbd6335cd012a8/src/native/common.gypi#L7

And then we can use it to warn somehow in asm.gypi ... not sure exactly how though...
