### ISSUE TITLE
Standalone NSFS support account auth with access_key/secret_key and mapping to uid/gid

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6470]
### Environment info
- NooBaa Version: **master-20210426**
- Platform: **Standalone**
- CC: @eshelmarc @jeniawhite 

### Actual behavior
1. Currently the standalone noobaa-core does not do any access authentication.
2. Also there is no mapping to uid/gid.

### Expected behavior
1. First step is to allow a global account for the standalone endpoint which will have access_key/secret_key.
2. By default it should map to the current user uid/gid.
3. Second step is to allow a separate account for every bucket, with its own uid/gid mapping.

### Steps to reproduce
1. NA

**Comment by nimrod-becker** [comment]
Old, we are working on it and some of it is already available, closing
