### ISSUE TITLE
Prevent creation of two buckets on top of the same NS FS path

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6483]
Environment info
[root@ocp-neha-1-inf ~]# oc version
Client Version: 4.7.0
Server Version: 4.7.0
Kubernetes Version: v1.20.0+bd9e442
[root@ocp-neha-1-inf ~]# noobaa version
INFO[0000] CLI version: 5.8.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.8.0-20210418
INFO[0000] operator-image: noobaa/noobaa-operator:5.8.0
[root@ocp-neha-1-inf ~]#

### Actual behavior
1. Bucket object is listed but bucket name is not shown inside endpoint.
2. If I create another bucket at same path with new name it will have all the objects of other bucket at that path

### Expected behavior
1. Bucket name should be created and objects should be listed inside it in endpoint pod. This "trial-buc" bucket should be created .
2. Two buckets data can't be copied automatically without any s3 operation performed on it

### Steps to reproduce
1. Create a namespace resource
noobaa api pool_api create_namespace_resource '{
  "name": "fs1", 
  "nsfs_config": {
      "fs_backend": "GPFS",   
      "fs_root_path": "/nsfs/fs1"           
  }
}'

2. noobaa api bucket_api create_bucket '{
  "name": "trial-buc",
  "namespace":{
    "write_resource": { "resource": "fs1", "path": "trial/" },
    "read_resources": [ { "resource": "fs1", "path": "trial/" }]
  }
}' 

### More information - Screenshots / Logs / Other output
Inside endpoint pod:
sh-4.4# [root@ocp-neha-1-inf ~]# oc rsh noobaa-endpoint-57c787988d-57wfv
sh-4.4# cd nsfs
sh-4.4# ls
fs1  fs2  neha
sh-4.4# cd fs1
sh-4.4# ls
dg  hello.txt  nsfs  test  trial
sh-4.4# cd trial
sh-4.4# ls
object.txt  
sh-4.4# [root@ocp-neha-1-inf ~]#

On App node:
[root@fyreauto-x-app1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.29.143'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-05-03 03:26:11 ne-there
2021-05-03 03:26:11 first.bucket
2021-05-03 03:26:11 trial-buc
2021-05-03 03:26:11 trial-buc-new
[root@fyreauto-x-app1 ~]# s3 ls s3://trial-buc
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.29.143'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-05-03 02:46:32          6 object.txt

[endpoint.log](https://github.com/noobaa/noobaa-core/files/6414385/endpoint.log)

**Comment by nimrod-becker** [comment]
How did you export the trial-buc bucket and to which directory he points?

**Comment by nehasharma5** [comment]
I created trial-buc bucket at path nsfs/fs1/trail and using s3 cp copied some object into it

**Comment by nehasharma5** [comment]
When a created one more bucket with new name at path nsfs/fs1/trail , bucket got created and have objects of "trial-buc" into it automatically even I didn't performed any s3 operation

**Comment by nimrod-becker** [comment]
you mapped two buckets on the same path, so both buckets show the same object list. Am I missing something here ?

**Comment by romayalon** [comment]
Hey @nehasharma5 
1. directory with bucket name shouldn't be created - it was true in previous version of this feature but there was a requirement to change it and not use the same name of the bucket but the `path` you passed when calling create_bucket.. 
    when you created `trial-buc`, you pointed to `/nsfs/fs1/trial/`, which is a path that already exist.
2. and regarding `Two buckets data can't be copied automatically without any s3 operation performed on it` - Nimrod is correct and you basically have 2 buckets that are pointing to the same directory so it's not copied, it's exactly the same directory.

**Comment by nehasharma5** [comment]
@nimrod-becker There are two things 
1. I created a bucket (trial-buc)on the path (nsfs/fs1/trial)which already exist on the File system and copied some object into it.  When I went to that path(nsfs/fs1/trial) , i can see the objects under it , no bucket was created with name trial-buck. Isn't it should be nsfs/fs1/trail/tria-buc and then objects should be there inside trial-buc?
2. I created one more bucket with different name at path nsfs/fs1/trial , when list objects of this bucket it have all objects of "trial-buc" . It should be empty ?

**Comment by nehasharma5** [comment]
@romayalon as per your comment, at one path we can only have one bucket and there will no bucket name on FS path as it was there in earlier build of noobaa.

**Comment by nimrod-becker** [comment]
I think it boils down to blocking exporting two buckets on the same path (via the CLI, via S3 create - see PR in review, its already blocked)
@romayalon @jeniawhite WFYT? Should we just add that verification in the CLI?

**Comment by nimrod-becker** [comment]
Updating the title of the issue
