### ISSUE TITLE
NSFS: Warp IO not working for 2nd user

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6499]
### Environment info
- NooBaa Version: master-20210510-nsfs
- Platform: OCP 4.6.16

### Actual behavior
1. IO tool warp unable to do IO using 2nd user. With 1st user, it works well.

### Expected behavior
1. IO tool warp should be able to do IO using multiple users

### Steps to reproduce
1. Created 3 accounts:
-------
Account Details:

- access_keys:
  - access_key: BPjWnNHXZ4NV4WyK0JN3
    secret_key: Ms9k5H3GPMP9attJD1pI0BuuVG19rTvTe69aN4/E
  email: akmithal-3@ibm.com

- access_keys:
  - access_key: 3MSr6uUZopNzNAa39D05
    secret_key: yjDmVHv5fA6CcHqmDa9C4ngdelWwz+BUJAR839Xd
  email: akmithal-2@ibm.com

- access_keys:
  - access_key: tEDTFASzWZwjE7iCdnHR
    secret_key: yGtf6FurpUjU5u5Y+OaOJwEyhSAjMy9n1HJPRxkO
  email: akmithal-1@ibm.com  **--->  1st user**
-------

IO initiated and concluded well with credentials for user 1:

-----
root@hpo-node1 ~]# warp mixed --access-key=tEDTFASzWZwjE7iCdnHR --secret-key=yGtf6FurpUjU5u5Y+OaOJwEyhSAjMy9n1HJPRxkO --obj.size=1K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com  --duration=60s --objects=50         --bucket=bucket-2  --debug --tls --insecure
warp: <ERROR> We encountered an internal error. Please try again.                                                                                                                                   
warp: Benchmark data written to "warp-mixed-2021-05-11[033243]-ayfu.csv.zst"                                                                                                                        
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Duration: 59s.
 * Throughput: 25.63 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 59s.
 * Throughput: 0.11 MiB/s, 115.32 obj/s

Operation: PUT, 15%, Concurrency: 20, Duration: 59s.
 * Throughput: 0.04 MiB/s, 38.58 obj/s

Operation: STAT, 30%, Concurrency: 20, Duration: 59s.
 * Throughput: 76.66 obj/s

Cluster Total: 0.15 MiB/s, 256.06 obj/s over 1m0s.

-----

IO could not start with credentials of user 2/3. In o/p below, credentials of user 3 are shown

------
[root@hpo-node1 ~]# warp mixed --access-key=BPjWnNHXZ4NV4WyK0JN3 --secret-key=Ms9k5H3GPMP9attJD1pI0BuuVG19rTvTe69aN4/E  --obj.size=1K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com  --duration=60s --objects=50         --bucket=bucket-2  --debug --tls --insecure
warp: <ERROR> We encountered an internal error. Please try again.                                                                                                                                   
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.                                                                                                                     
warp: <ERROR> upload error: We encountered an internal error. Please try again.      

------
### More information - Screenshots / Logs / Other output

Uploading noobaa diagnose logs

**Comment by akmithal** [comment]
[Uploading noobaa_diagnostics_1620729715.tar.gz…]()

**Comment by guymguym** [comment]
@akmithal Is this a permissions issue? CC @romayalon @nimrod-becker

**Comment by akmithal** [comment]
Hi @guymguym , Yes this looks a permission problem. Here is one more way I reproduced it:

Credentials are of user 2 are not working for uploading objects whereas listing is working fine. 
-------
[root@hpo-node1 ~]# alias s3="AWS_ACCESS_KEY_ID=3MSr6uUZopNzNAa39D05 AWS_SECRET_ACCESS_KEY=yjDmVHv5fA6CcHqmDa9C4ngdelWwz+BUJAR839Xd aws --endpoint https://api.ocp-akshat-1.cp.fyre.ibm.com:8443/ --no-verify-ssl s3"
[root@hpo-node1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-05-16 23:14:06 first.bucket
2021-05-16 23:14:06 bucket-1
2021-05-16 23:14:06 bucket-2
[root@hpo-node1 ~]# echo test_content | s3 cp - s3://bucket-2/file_user_2
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: - to s3://bucket-2/file_user_2 An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error. Please try again.
[root@hpo-node1 ~]# 

-------

The underlying directory permissions should not matter here as for 1st user it works well but for 2nd onwards it fails.

**Comment by guymguym** [comment]
@akmithal Can you try to list the objects of bucket-2 with: `s3 ls s3://bucket-2` with user 2?

**Comment by guymguym** [comment]
Also it would be useful to see the filesystem permissions on these folders and the account's uid's

**Comment by akmithal** [comment]
Hello Guy, I created a new setup this morning and finding same results. The first user is able to upload the file well and 2nd user gets a permission error. 

In today's run, I had 2 users with different UID but same GID. 

----
[root@ocp-akshat-1-inf akshat]# noobaa api account_api list_accounts |grep -e email -e key -e id
ERRO[0000] Error discovered: the server is currently unable to handle the request 
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: account.list_accounts() Request: <nil> 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:40591/rpc/ 0xc000aee820 
INFO[0001] RPC: Connecting websocket (0xc000aee820) &{RPC:0xc000186cd0 Address:wss://localhost:40591/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000aee820) &{RPC:0xc000186cd0 Address:wss://localhost:40591/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: account.list_accounts() Response OK: took 0.3ms 
- access_keys:
  - access_key: 2vWeT8V7GxpxjWx58ZPo
    secret_key: 50YRdvg7Lu0we8/ffpgQVrBdu8XPDIzhe9o1XeUE
  email: akmithal-3
    gid: 10
    uid: 300
- access_keys:
  - access_key: PQk0Y2fYEDe0QRPA6xIw
    secret_key: ihLl12FflDe6f/y04hl+jtiz0F/7mg3/E5mWtMVD
  email: akmithal-2
    gid: 10
    uid: 200
- access_keys:
  - access_key: 4YNRFT2HCsZ1MlVLamXy
    secret_key: hA6nyOLcXMLkBUGnmtXNw9IB/3i7nehzLJHk1bJP
  email: akmithal-1
    gid: 10
    uid: 100
- access_keys:
  - access_key: Fv9IPtGyXDfLjr56lDid
    secret_key: wvzoNacMQjuXuOa5BJlDD5bXT4LxLQgusnYjdBV4
  email: operator@noobaa.io
- access_keys:
  - access_key: BEPi0kEtJPO8StDTkKnQ
    secret_key: 5TczMy0PZ5JfxgEXQMG5m+I+MDBqyMJG/nZ8aIz2
  email: admin@noobaa.io

----

fs_root_path **/nsfs/parent** permission is 777

From endpoint log:

------
May-18 6:46:45.688 [Endpoint/8]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT bucket-1 file_user1_new  
May-18 6:47:15.765 [Endpoint/8]   [LOG] CONSOLE:: update_endpoint_stats. namespace_stats = []
May-18 6:47:15.769 [Endpoint/8]    [L0] core.util.mongo_client:: _init_collection: created collection bucketstats
May-18 6:47:15.772 [Endpoint/8]    [L0] core.util.mongo_client:: _init_collection: created index bucketstats bucket_1
May-18 6:47:18.065 [Endpoint/8]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '2e157ab6-da18-41e7-9028-68a98869fbae', hostname: 'noobaa-endpoint-568b456f68-tmpd9' }
May-18 6:50:13.490 [Endpoint/8]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  name: SENSITIVE-f53e749d8f84e52b,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-d4bc82999e444a8c,
  bucket_info: { name: SENSITIVE-f53e749d8f84e52b, owner_account: { email: SENSITIVE-d4bc82999e444a8c, id: '60a359e3413664002cb11123' }, namespace: { write_resource: { resource: 'nsfs-nsr-1', path: '/' }, read_resources: [ { resource: 'nsfs-nsr-1', path: '/' }, [length]: 1 ] }, tiering: { name: SENSITIVE-e3a91458bff22bc9, tiers: [ { order: 0, tier: SENSITIVE-e3a91458bff22bc9, spillover: false, disabled: false, mode: 'OPTIMAL' }, [length]: 1 ], storage: { total: 5368709120, used: 0, used_other: 0, free: 5368709120, reserved: 0, unavailable_free: 0, unavailable_used: 0 }, data: { free: 5368709120 }, mode: 'NO_RESOURCES_INTERNAL' }, tag: '', num_objects: { value: 0, last_update: 1621320077799 }, writable: true, storage: { values: { used: 0, used_other: 0, total: 5368709120, free: 5368709120 }, last_update: 1621320497794 }, data: { size: 0, size_reduced: 0, free: 5368709120, available_for_upload: 5368709120, last_update: 1621320497794 }, usage_by_pool: { pools: [ [length]: 0 ], last_update: 1621320077799 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', host_tolerance: 0, node_tolerance: 0, bucket_type: 'NAMESPACE', versioning: 'DISABLED', triggers: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60a35c48413664002cb1112e', name: 'nsfs-nsr-1' }, path: '/' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60a35c48413664002cb1112e', name: 'nsfs-nsr-1' }, path: '/' }, [length]: 1 ]
  }
}
May-18 6:50:13.491 [Endpoint/8]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT bucket-1 file_user2_new  
**May-18 6:50:13.493 [Endpoint/8] [ERROR] CONSOLE:: _upload_stream had error:  [Error: Permission denied] { code: 'EACCES' }**
May-18 6:50:13.494 [Endpoint/8] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/file_user2_new</Resource><RequestId>kotofjvs-cetx2v-adz</RequestId></Error> PUT /bucket-1/file_user2_new {"host":"api.ocp-akshat-1.cp.fyre.ibm.com:8443","accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.22.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","content-md5":"mt/4AC6pewyhrCpv2rWj3A==","expect":"100-continue","x-amz-date":"20210518T065013Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=PQk0Y2fYEDe0QRPA6xIw/20210518/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=73422d41cf5c1c173f0e4b67a905d77a57943017a9902b23dfdf646dd9b7671a","content-length":"23"} Error: Permission denied
May-18 6:50:14.377 [Endpoint/8]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT bucket-1 file_user2_new  
May-18 6:50:14.378 [Endpoint/8] [ERROR] CONSOLE:: _upload_stream had error:  [Error: Permission denied] { code: 'EACCES' }
May-18 6:50:14.378 [Endpoint/8] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/file_user2_new</Resource><RequestId>kotofkko-ap2be4-11u2</RequestId></Error> PUT /bucket-1/file_user2_new {"host":"api.ocp-akshat-1.cp.fyre.ibm.com:8443","accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.22.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","content-md5":"mt/4AC6pewyhrCpv2rWj3A==","expect":"100-continue","x-amz-date":"20210518T065014Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=PQk0Y2fYEDe0QRPA6xIw/20210518/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=1b79859e548d9ce7c48ade74a5e3fb9555971cbfdcf1bb0801b5609bd9975bc2","content-length":"23"} Error: Permission denied
May-18 6:50:15.805 [Endpoint/8]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT bucket-1 file_user2_new  
May-18 6:50:15.806 [Endpoint/8] [ERROR] CONSOLE:: _upload_stream had error:  [Error: Permission denied] { code: 'EACCES' }
May-18 6:50:15.806 [Endpoint/8] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/file_user2_new</Resource><RequestId>kotofloc-18lpxv-ef4</RequestId></Error> PUT /bucket-1/file_user2_new {"host":"api.ocp-akshat-1.cp.fyre.ibm.com:8443","accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.22.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","content-md5":"mt/4AC6pewyhrCpv2rWj3A==","expect":"100-continue","x-amz-date":"20210518T065015Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=PQk0Y2fYEDe0QRPA6xIw/20210518/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=aa4af0d78e94b3d6cc734ef49af95b73b6c2b9fda49e4ceea43b9d5a601fae56","content-length":"23"} Error: Permission denied

------

Error from app server:

------

[root@hpo-node1 ~]# s3u2 cp u2_file_user2 s3://bucket-1/file_user2_new
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ./u2_file_user2 to s3://bucket-1/file_user2_new An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error. Please try again.

------- 

From with-in the endpoint pod:
------
sh-4.4# cd /nsfs/parent/
sh-4.4# ls -lart
total 4
drwxrwx--x. 3 root root  4096 May 18 06:17 ..
drwxr-x---. 3  100 wheel 4096 May 18 06:46 .noobaa-nsfs
-rw-r-----. 1  100 wheel   13 May 18 06:46 file_user1_new
drwxrwxrwx. 3 root root  4096 May 18 06:46 .

------

**Comment by troppens** [comment]
User 2 cannot write to `.noobaa-nsfs`. Have you tried to set permission to `770` (as well as for sub directories in `.noobaa-nsfs`)?

**Comment by akmithal** [comment]
[Uploading noobaa_diagnostics_1621321043.tar.gz…]()

**Comment by jeniawhite** [comment]
Looks like with the latest changes that we did this issue got solved.
https://github.com/noobaa/noobaa-core/issues/6574
I can see that you are managing to write with all of the users for several hours.
@akmithal Please confirm if that is the case and we will close this issue.
Thanks!

**Comment by akmithal** [comment]
Closing this bug now as it was working for me for builds upto 20th June.
