### ISSUE TITLE
noobaa api account_api list_accounts command fails for INVALID_SCHEMA_PARAMS

### ISSUE THREAD

**Issue by steve-delillo** [noobaa/noobaa-core#6539]
### Environment info
- NooBaa Version:
- INFO[0000] CLI version: 5.9.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210526 
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0 

- Platform: OCP 4.7.4

### Actual behavior
On a system with noobaa freshly installed (only one account and a few buckets had been created), we get the following.  Whether accounts exist, or not, no errors should get produced.  In this case, one account existed called "s3user1"

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/84864338/119873244-33bae880-bed9-11eb-9bd7-6692ba8f4a96.png">

### Expected behavior
No errors should get produced and the existing account should be shown.

### Steps to reproduce
1. Fresh install noobaa manually
2. Create one account
3. Run `noobaa api account_api list_accounts` on the infra node

**Comment by guymguym** [comment]
@steve-delillo This call requires an object for params, but it has no required properties, so from the CLI do like this:
```
noobaa api account_api list_accounts '{}'
```

Let me know if this works.
Closing.

**Comment by steve-delillo** [comment]
Thanks, Guy.  Yeah, that worked very well.  I thought for just listing, we wouldn't need object call outs.
