### ISSUE TITLE
getting Error: unknown flag: --pvc-name when tring to create noobaa namespacestore

### ISSUE THREAD

**Issue by radhalankisetti** [noobaa/noobaa-core#6553]
### Environment info
- NooBaa Version: master-20210518-nsfs
- Platform: OpenShift 4.7.1

### Actual behavior
1.noobaa namespacestore create nsfs d2 --pvc-name='nsfs-gpfs-vol' --fs-backend='GPFS'
Error: unknown flag: --pvc-name

### Expected behavior
1.to create a namespace store with PVC attached

### Steps to reproduce
1.installed noobaa master-20210518-nsfs
2.created a pvc for nsfs
3.trying to create a namespace store and attach pvc to it according to https://github.com/noobaa/noobaa-core/wiki/NSFS-on-Kubernetes

**Comment by guymguym** [comment]
@radhalankisetti You need to use a newer build for that.
This was merged just 6 days ago - https://github.com/noobaa/noobaa-operator/pull/640
Closing.

**Comment by radhalankisetti** [comment]
but that was the latest nsfs image right with -nsfs in the tag name can you tell from which build it is enabled

**Comment by guymguym** [comment]
I don't follow what do you mean. 
Do you still have an issue when using a new build?

**Comment by radhalankisetti** [comment]
yes
[root@deeghuge3-inf ~]# noobaa namespacestore create nsfs fs1 --pvc-name='nsfs-gpfs-vol' --fs-backend='GPFS'
Error: unknown flag: --pvc-name
See 'noobaa namespacestore create nsfs --help' for usage.
[root@deeghuge3-inf ~]# noobaa status
INFO[0001] CLI version: 5.9.0
INFO[0001] noobaa-image: noobaa/noobaa-core:master-20210607
INFO[0001] operator-image: noobaa/noobaa-operator:master-20210607
INFO[0001] noobaa-db-image: centos/mongodb-36-centos7

**Comment by guymguym** [comment]
did you download the matching CLI from -
https://noobaa-operator-cli.s3.amazonaws.com/noobaa-linux-master-20210607
?

**Comment by radhalankisetti** [comment]
No i have downloaded cli using the commands mentioned here https://github.com/noobaa/noobaa-operator#noobaa-operator

**Comment by guymguym** [comment]
This will give you latest release, not a master build

**Comment by guymguym** [comment]
see step 1 -
https://github.com/noobaa/noobaa-core/wiki/NSFS-on-Kubernetes#step-1---deploy-in-kubernetes

**Comment by guymguym** [comment]
https://github.com/noobaa/noobaa-core/wiki/Weekly-Master-Builds

**Comment by radhalankisetti** [comment]
Thank you that command worked after installing cli but there is a problem when I create namespace store using the command the bucket is created and I can see in noobaa management when I try to list buckets  or upload a object t to the bucket it is saying bucket it not found
