### ISSUE TITLE
Warp run failure with ENOSPC, though sufficient space available:

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6574]
### Environment info
- NooBaa Version: master-20210607
- Platform: OCP 4.6.16

### Actual behavior
1. Warp run failure after couple of hours with no space available error

### Expected behavior
1. If space is available, warp should not fail

### Steps to reproduce
1. Started warp run for multiple users for multiple buckets
2. Run failed with errors for all 3 instances:

Endpoint log:

```
Jun-14 10:18:46.019 [Endpoint/20944] [ERROR] CONSOLE:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Jun-14 10:18:46.019 [Endpoint/20944] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-3/ik1XtOaS/24818.1XehEvkPzWF1ScPS.rnd</Resource><RequestId>kpwgrqma-22qkki-rvl</RequestId></Error> PUT /bucket-3/ik1XtOaS/24818.1XehEvkPzWF1ScPS.rnd {"user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.3.43","content-length":"2000","authorization":"AWS4-HMAC-SHA256 Credential=hKS6i9HcpgYGAf0Phvlb/20210614/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=92cd8fe170ef2b96b0d1d39ed7028d99b06570528ec198328e4274f685a54eb9","content-type":"application/octet-stream","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20210614T101845Z","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No space left on device
```

```
warp: <ERROR> upload error: We encountered an internal error. Please try again.
warp: <ERROR> upload error: We encountered an internal error. Please try again.
warp: <ERROR> upload error: We encountered an internal error. Please try again.
warp: Benchmark data written to "warp-mixed-2021-06-13[231811]-TTvY.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Duration: 3h59m59s.
 * Throughput: 23.23 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 4h0m0s.
 * Throughput: 0.10 MiB/s, 104.53 obj/s

Operation: PUT, 15%, Concurrency: 20, Duration: 4h0m0s.
Errors: 2735
 * Throughput: 0.03 MiB/s, 34.65 obj/s

Operation: STAT, 30%, Concurrency: 20, Duration: 3h59m59s.
 * Throughput: 69.68 obj/s

Cluster Total: 0.13 MiB/s, 232.09 obj/s, 2735 errors over 4h0m0s.
Total Errors:2735.
```

```
[root@hpo-node1 ~]# ps -ef |grep warp
root      165384   18609 24 Jun13 pts/3    00:48:58 warp mixed --access-key=YrpJ6lYpmcU6u8ODljQG --secret-key=2MTlqrO7sIn62sOvX0lid77V/DffpiE8fDASFnmp --obj.size=1K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-1 --debug --tls --insecure
root      165407   18814 24 Jun13 pts/4    00:48:31 warp mixed --access-key=pRDEb8zcwKB03fqyxhum --secret-key=/I2QbkVtIBQ9aQmahHAIrzIPrA1LNY/gVxgVBLYN --obj.size=1K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-2 --debug --tls --insecure
root      165441  165415 24 Jun13 pts/2    00:48:41 warp mixed --access-key=hKS6i9HcpgYGAf0Phvlb --secret-key=U12FbixuAmjHKgvZVIalZP00ynZRo0veY1ZMhIw2 --obj.size=2K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-3 --debug --tls --insecure
root      165938  165449  0 02:38 pts/5    00:00:00 grep --color=auto warp
```

Sufficient space is available:
```
[root@ocp-akshat-1-inf ~]# oc rsh noobaa-endpoint-74dfc4b786-n6zjp     
sh-4.4# df -h
Filesystem                            Size  Used Avail Use% Mounted on
overlay                               250G   31G  219G  13% /
tmpfs                                  64M     0   64M   0% /dev
tmpfs                                  16G     0   16G   0% /sys/fs/cgroup
shm                                    64M     0   64M   0% /dev/shm
tmpfs                                  16G   46M   16G   1% /etc/hostname
tmpfs                                  16G  8.0K   16G   1% /etc/mgmt-secret
tmpfs                                  16G  8.0K   16G   1% /etc/s3-secret
fs1                                   2.0T  324G  1.7T  17% /nsfs/nsfs-nsr-1    -----------> Sufficient space is there
/dev/mapper/coreos-luks-root-nocrypt  250G   31G  219G  13% /etc/hosts
tmpfs                                  16G   28K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                  16G     0   16G   0% /proc/acpi
tmpfs                                  16G     0   16G   0% /proc/scsi
tmpfs                                  16G     0   16G   0% /sys/firmware
```

### More information - Screenshots / Logs / Other output

Created 32 GB file in the bucket to validate if space errors are coming:

```
sh-4.4# cd /nsfs/nsfs-nsr-1/bucket-3
sh-4.4# ls
 0GK5F7J2   CNpeIK08   TNK9GvdS   ZaeMzzFp   'de9u(XkH'  'f)E1F0DR'   ik1XtOaS	 kEsPw8Rw   sixdrrbR   tvUYYsr7   zLZVopem
 9yb5sXTg   RPaALJVu   XVqv2BrZ   check_big  'eRBX9)2a'  'hV5)0G8o'   inHhHlpV	 qz0yH5ml   tPNjhiEy   vjXMLi7Y
sh-4.4# ls -lrt
total 92151808
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28 'eRBX9)2a'
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  TNK9GvdS
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  inHhHlpV
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28 'f)E1F0DR'
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  XVqv2BrZ
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  tvUYYsr7
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  vjXMLi7Y
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  CNpeIK08
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  0GK5F7J2
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  kEsPw8Rw
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  sixdrrbR
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  ZaeMzzFp
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  zLZVopem
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  tPNjhiEy
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  qz0yH5ml
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  RPaALJVu
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28 'de9u(XkH'
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  ik1XtOaS
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28 'hV5)0G8o'
drwxr-x---. 2 5002 800     1048576 Jun 14 10:28  9yb5sXTg
-rw-rw-rw-. 1 5002 800 94387535872 Jun 14 12:58  check_big
sh-4.4# setpriv --reuid=5002 --regid=800 --inh-caps=-all --clear-groups dd if=/dev/zero of=check_big bs=32768 count=1000000
1000000+0 records in
1000000+0 records out
32768000000 bytes (33 GB, 31 GiB) copied, 52.2783 s, 627 MB/s

```

```
[root@hpo-node1 ~]# du -sh check_9mb   
8.8M    check_9mb
[root@hpo-node1 ~]# s3u3 cp check_9mb s3://bucket-3/
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload: ./check_9mb to s3://bucket-3/check_9mb                    
[root@hpo-node1 ~]# s3u3 ls s3://bucket-3/
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                           PRE 0GK5F7J2/
                           PRE 9yb5sXTg/
                           PRE CNpeIK08/
                           PRE RPaALJVu/
                           PRE TNK9GvdS/
                           PRE XVqv2BrZ/
                           PRE ZaeMzzFp/
                           PRE de9u(XkH/
                           PRE eRBX9)2a/
                           PRE f)E1F0DR/
                           PRE hV5)0G8o/
                           PRE ik1XtOaS/
                           PRE inHhHlpV/
                           PRE kEsPw8Rw/
                           PRE qz0yH5ml/
                           PRE sixdrrbR/
                           PRE tPNjhiEy/
                           PRE tvUYYsr7/
                           PRE vjXMLi7Y/
                           PRE zLZVopem/
2021-06-14 06:21:57    9216000 check_9mb
2021-06-14 06:02:40 327680000000 check_big
```

**Comment by akmithal** [comment]
[noobaa_diagnostics_1623677733.tar.gz](https://github.com/noobaa/noobaa-core/files/6648630/noobaa_diagnostics_1623677733.tar.gz)

**Comment by nimrod-becker** [comment]
@akmithal Per Jenia's comment in 6499, can we verify and close if indeed fixed?

**Comment by akmithal** [comment]
Hi @nimrod-becker , Update in 6499 was for closing 6499 but this defect should still be investigated I think. @jeniawhite , please confirm.

**Comment by akmithal** [comment]
Hi, I have picked up build master-20210721. This problem is still persisting. 

Started IO run for 3 users and got ENOSPC error, inspite of space being available. 

`Jul-22 17:35:13.066 [Endpoint/9] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Jul-22 17:35:13.066 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/1M-objects/obj_207606</Resource><RequestId>krf73dzy-9r0t96-vw3</RequestId></Error> PUT /bucket-1/1M-objects/obj_207606 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.7.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.sync","content-md5":"2nCzttqVdObUgL8OsybBuw==","expect":"100-continue","x-amz-date":"20210722T173513Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=nm21nfNliFIJx2PBWh9M/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=e6f3b74f36579e96c76c79f111639b49dd0c0e5bc630b925565bd90d98a4be6a","content-length":"512","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No space left on device
Jul-22 17:35:13.067 [Endpoint/9] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Jul-22 17:35:13.067 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/1M-objects/obj_207605</Resource><RequestId>krf73dzz-9rw8jc-1cvm</RequestId></Error> PUT /bucket-1/1M-objects/obj_207605 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.7.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.sync","content-md5":"Ivp9gx7K2F1cXN1wGtmLgA==","expect":"100-continue","x-amz-date":"20210722T173513Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=nm21nfNliFIJx2PBWh9M/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=79206927b8ea3a94d934328e16e2184714fa1a27e59baee19e663c40b7887780","content-length":"512","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No space left on device
Jul-22 17:35:13.080 [Endpoint/9] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Jul-22 17:35:13.081 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/bucket-1/1M-objects/obj_207600</Resource><RequestId>krf73e06-9vsu7g-km3</RequestId></Error> PUT /bucket-1/1M-objects/obj_207600 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.7.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.sync","content-md5":"ZcgO/4mCjSnX0h6drv3t4g==","expect":"100-continue","x-amz-date":"20210722T173513Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=nm21nfNliFIJx2PBWh9M/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=77c6877ff4c41cce2e1798126f006ff6a061d2a3ac8e153911d15510065d00f8","content-length":"512","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No space left on device
`

Space is available:

```
[root@ocp-akshat-1-inf akshat]# oc rsh noobaa-endpoint-85646d8687-p45z6  
sh-4.4# df -h
Filesystem                            Size  Used Avail Use% Mounted on
overlay                               250G   55G  195G  23% /
tmpfs                                  64M     0   64M   0% /dev
tmpfs                                  16G     0   16G   0% /sys/fs/cgroup
shm                                    64M     0   64M   0% /dev/shm
tmpfs                                  16G   59M   16G   1% /etc/hostname
tmpfs                                  16G  8.0K   16G   1% /etc/mgmt-secret
tmpfs                                  16G  8.0K   16G   1% /etc/s3-secret
fs1                                   2.0T  254G  1.8T  13% /nsfs/nsfs-nsr-1    ---> Space is available
/dev/mapper/coreos-luks-root-nocrypt  250G   55G  195G  23% /etc/hosts
tmpfs                                  16G   28K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                  16G     0   16G   0% /proc/acpi
tmpfs                                  16G     0   16G   0% /proc/scsi
tmpfs                                  16G     0   16G   0% /sys/firmware
```

**Comment by akmithal** [comment]
Uploading must-gather logs. 

[must-gather-5.tar.gz](https://github.com/noobaa/noobaa-core/files/6866924/must-gather-5.tar.gz)

**Comment by guymguym** [comment]
@akmithal Can you try to run some writes on that mount point from the endpoint?

**Comment by nimrod-becker** [comment]
@akmithal Can you verify if writing to the mount point works as Guy suggested?

**Comment by akmithal** [comment]
This is not reproducible with build master-20210812 onwards hence closing it.
