### ISSUE TITLE
Triggers not working anymore with namespaced buckets with s3 backend

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6575]
### Environment info
- NooBaa Core Version: master+d9dd10ae7d33f4a21f4acdce183e4603630c3bb4
- Platform: OKD 4.6

### Actual behavior
1. Trigger not executed on namespaced bucket

### Expected behavior
1. Trigger gets executed

### Steps to reproduce
1. Create namespace resource with s3 compatible v2 backend
2. Create namespace bucket with the same backend bucket as read and write resource

### More information - Screenshots / Logs / Other output
I think this addition
https://github.com/noobaa/noobaa-core/blob/4a3c59daa150a208d655cb977222c59449d44278/src/sdk/object_sdk.js#L203-L209
is the problem, as now no longer a NamespaceMerge object is created but instead a NamespaceS3 object and the NamespaceS3 class does not implement trigger functionality

**Comment by lallinger-arbeit** [comment]
@liranmauda as we currently do not focus on trigger implementation this could be closed from my side for now, but it should definitely be fixed in the future

**Comment by liranmauda** [comment]
Sure, Let's close it for now, and if/when relevant we can reopen it.
