### ISSUE TITLE
Creation bucket caused noobaa core and noobaa endpoint pods crash

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6584]
### Environment info
- NooBaa Version: master-20210607
- Platform: OCP 4.6.16

### Actual behavior
1. Creation of multiple buckets caused multiple noobaa pods crash

### Expected behavior
1. No pods should crash 

### Steps to reproduce
1. Started a loop for 100's of buckets. 
2. In between, it failed creation of buckets operation. 
Overall 352 buckets were created.

**No IO was running for this test.**

Noobaa pods and noobaa endpoint pods crashed and noobaa status is failing

```
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                                      0/1     CrashLoopBackOff   4          24h
noobaa-db-pg-0                                     1/1     Running            0          24h
noobaa-default-backing-store-noobaa-pod-615be21a   0/1     Terminating        0          6d16h
noobaa-endpoint-74dfc4b786-468kd                   1/1     Running            7          24h
noobaa-endpoint-74dfc4b786-j9d49                   1/1     Running            0          3m33s
noobaa-operator-7996cfc767-h2lnd                   1/1     Running            0          24h
```

**Comment by akmithal** [comment]
[noobaa_diagnostics_1623861046.tar.gz](https://github.com/noobaa/noobaa-core/files/6664529/noobaa_diagnostics_1623861046.tar.gz)

**Comment by akmithal** [comment]
[nbcore_postgres.gz](https://github.com/noobaa/noobaa-core/files/6693463/nbcore_postgres.gz)
[noobaa_diagnostics_1624330483.tar.gz](https://github.com/noobaa/noobaa-core/files/6693464/noobaa_diagnostics_1624330483.tar.gz)

**Comment by jackyalbo** [comment]
Hey @akmithal , taking a look on the logs I can see an issue with a same bucket being created twice - which of course we should block, so few questions:  
1. is this part of your test? what does your test do exactly? create and delete same/random 100 buckets in loop? did it fail on the 3rd loop (on 352)
2. Are you creating these buckets using s3?
I couldn't really find the error on the time that it really happened. the last logs you sent have only the issue from after both core and endpoint was restarted - so it doesn't have too valuable data except for the errors on the key appearing twice.
```
Jun-22 2:55:10.276 [BGWorkers/30] [ERROR] core.server.system_services.system_store:: SystemStoreData: buckets_by_name collision on key bucket-4piqv4 { _id: 60d0d3313a4fd5002cd52d2e, tag: '', name: SENSITIVE-ae587f039dd6656e, system: <ref *1>
```
From the DB that you attached I can see this: 
```
60d0d3313a4fd5002cd52d30        {"_id": "60d0d3313a4fd5002cd52d30", "desc": "bucket-4piqv4 was created by akmithal-1@ibm.com", "time": "2021-06-21T17:58:09.989Z", "actor": "60d0cebc3a4fd5002cd523aa", "event": "bucket.create", "level": "info", "bucket": "60d0d3313a4fd5002cd52d2e", "system": "60d0b1973a4fd5002cd5238f"}
60d0d34f3a4fd5002cd53057        {"_id": "60d0d34f3a4fd5002cd53057", "desc": "bucket-4piqv4 was created by akmithal-1@ibm.com", "time": "2021-06-21T17:58:39.767Z", "actor": "60d0cebc3a4fd5002cd523aa", "event": "bucket.create", "level": "info", "bucket": "60d0d34f3a4fd5002cd53055", "system": "60d0b1973a4fd5002cd5238f"}
```
two buckets with the same name created 30 seconds apart from each other - So I think that's what causing the issue.
Will try to reproduce myself. But if in any case you can get a reproduce easily and to attach the previous logs for both core and endpoint that will be great. 
```
oc logs noobaa-core-0 -p
oc logs noobaa-endpoint-<the terminsting one> (suppose to be part of the diagnositcs but this last time it didn't appear)
```
Thanks

**Comment by akmithal** [comment]
Hi @jackyalbo : 

1. Yes this is part of my test to create 500 buckets for MVP. I use a loop to do that instead of manual operation. It even fails on 1st instance now. I think it should be easily reproducible on any environment involving Namespace buckets on OCP. 

2. I am using s3 to achieve this and hence it is a sequential operation. Just a simple for loop. 

Reproducing it, disturbs my whole setup and then I have to install the code again. 

If you are not able to reproduce with the above steps, let me know will have to plan the run accordingly.

**Comment by jackyalbo** [comment]
Hi @akmithal 

I slowly slowly created ~300 buckets,  but it doesn't reproduce to me. 
Created on top of nsfs namespace,  I ran in minikube, with postgres, created all the buckets from s3. 
Also deleted around 100, and tried to create an already created buckets once again - It does't reproduce.
I need some specific guidelines on how to reproduce, maybe you can share your code of creating the buckets I can try it.
Another option is you creating a repro once again and saving all the logs from both new and old pods once its start to restart.

**Comment by liranmauda** [comment]
looping on creating a bucket lead me to duplicate entries in the DB:
```
time for i in {1..500} ; do date ; time aws s3 --endpoint-url=<endpoint url> mb s3://bucket-${i} --no-verify-ssl ; date ; done
```

**Comment by akmithal** [comment]
[noobaa_diagnostics_1625645200.tar.gz](https://github.com/noobaa/noobaa-core/files/6775475/noobaa_diagnostics_1625645200.tar.gz)

**Comment by akmithal** [comment]
The latest above logs are done on 0706 build. bucket-324 was the affected one. No pods are crashed here.

**Comment by jackyalbo** [comment]
I understand we shouldn't close the issues - So reopening.

**Comment by akmithal** [comment]
This fix is working well. Thanks @jackyalbo , closing the bug.
