### ISSUE TITLE
Without IO, Noobaa endpoints didn't scale down

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6585]
### Environment info
- NooBaa Version: master-20210607
- Platform: OCP 4.6.16

### Actual behavior
1. Noobaa pods still didn't down. oc get hpa showed upto 90% CPU consumption

It fluctuates between 0-90% 

```
Every 2.0s: oc get hpa; oc get pod -n noobaa -o wide                                                                                                      ocp-akshat-1-inf: Wed Jun 16 22:19:17 2021

NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   57%/80%   1         3         3          8d
NAME                                               READY   STATUS        RESTARTS   AGE    IP              NODE                                   NOMINATED NODE   READINESS GATES
noobaa-core-0                                      1/1     Running	 9          37h    10.254.12.204   worker1.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-db-pg-0                                     1/1     Running	 0          37h    10.254.16.16    worker2.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-default-backing-store-noobaa-pod-615be21a   0/1     Terminating   0          7d5h   <none>          worker0.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-endpoint-74dfc4b786-468kd                   1/1     Running	 7          37h    10.254.17.54    worker2.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-endpoint-74dfc4b786-dhhxz                   1/1     Running	 1          12h    10.254.12.206   worker1.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-endpoint-74dfc4b786-pkrpj                   1/1     Running	 0          12h    10.254.17.73    worker2.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
noobaa-operator-7996cfc767-h2lnd                   1/1     Running	 0          37h    10.254.16.8     worker2.ocp-akshat-1.cp.fyre.ibm.com   <none>           <none>
```

### Expected behavior
1. Without any IO, noobaa pods CPU consumption should be 0

### Steps to reproduce
1. Found bug 6584. Stand was idle with NO IO running

### More information - Screenshots / Logs / Other output

Endpoint logs didn't show any IO instances.Checked all 3 endpoint logs:

```
Jun-16 23:54:26.583 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:04:26.623 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:14:26.668 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:24:59.301 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:34:59.350 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:44:59.393 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 0:55:27.189 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:05:27.241 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:15:27.284 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:25:42.306 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:35:42.366 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:45:42.414 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 1:55:42.455 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:06:14.195 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:16:14.251 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:26:21.404 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:36:21.456 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:46:29.900 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 2:56:29.956 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:06:57.100 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:16:57.161 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:26:57.206 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:36:57.247 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:42:25.495 [Endpoint/9]    [L0] core.server.system_services.system_store:: SystemStore.load: Got load request with a timestamp older then my last update time
Jun-17 3:46:57.292 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 3:57:18.195 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:07:18.249 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:17:36.188 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:27:36.241 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:37:38.710 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:47:38.816 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 4:58:02.101 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 5:08:02.155 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
Jun-17 5:18:02.198 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: '24b4b5b2-712a-4d88-bb51-145afd321e71', hostname: 'noobaa-endpoint-74dfc4b786-pkrpj' }
```

**Comment by akmithal** [comment]
[noobaa_diagnostics_1623906877.tar.gz](https://github.com/noobaa/noobaa-core/files/6668757/noobaa_diagnostics_1623906877.tar.gz)

**Comment by akmithal** [comment]
[noobaa_diagnostics_1624330483.tar.gz](https://github.com/noobaa/noobaa-core/files/6693444/noobaa_diagnostics_1624330483.tar.gz)

**Comment by jackyalbo** [comment]
> [noobaa_diagnostics_1624330483.tar.gz](https://github.com/noobaa/noobaa-core/files/6693444/noobaa_diagnostics_1624330483.tar.gz)

@akmithal  about this second logs - I see only one endpoint pod and it's empty - So I guess it's not relevant for this issue. Correct me If I'm wrong

**Comment by jackyalbo** [comment]
@akmithal I tried the following scenario (on minikube) - HPA of min 1 max 2
ran s3 sync - it got to more than 80% and created a second replica. Stopped IO completely
wait for about 20 minutes -  cpu dropped to 15%. second replica was dropped: 
> Normal  SuccessfulRescale  61m   horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
So it maybe a specific glitch in your env - Or maybe didn't wait enough time. I don't see in the logs any reason for the endpoint CPU to be at around 90%.
I would suggest running the following scenario again with current code - and update this issue.

**Comment by akmithal** [comment]
Hi @jackyalbo , @guymguym : I believe we discussed about a PR for high CPU consumption. Is that merged now ? We can retry this in that case.

**Comment by nimrod-becker** [comment]
The one that comes to mind fixed flows in the core pod, and fixes in the posrtgres performance can also affect this

**Comment by akmithal** [comment]
This one is not reproducible with master-20210808. Closing this bug.

**Comment by ketankhurana64** [comment]
Adding the logs

**Comment by ketankhurana64** [comment]
NAME              REFERENCE                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   <unknown>/80%   1         3         3          25h


Steps to reproduce:
patch the endpoints as min=5, max=10
5 endpoints are in running state
Patch again with min=1,max=3
3 endpoints will be in running state
No IO was running in either case

**Comment by jackyalbo** [comment]
```<unknown>/80%```
@ketankhurana64 Is this permanent or can you see sometime that the CPU usage has a number (and not unknown). 
I think this cluster maybe have metrics disabled. @akmithal did you run anything specific in OCP for getting the CPU target usage when you got this issue?

**Comment by ketankhurana64** [comment]
[root@api.osculate.cp.fyre.ibm.com ~]# kubectl top pod
NAME                               CPU(cores)   MEMORY(bytes)
noobaa-core-0                      69m          372Mi
noobaa-db-pg-0                     20m          86Mi
noobaa-endpoint-578f67656f-2vf8s   13m          102Mi
noobaa-endpoint-578f67656f-mpgr2   10m          103Mi
noobaa-endpoint-578f67656f-qw2cf   15m          86Mi
noobaa-operator-6fbd9ddcd7-pc5nz   23m          33Mi

**Comment by jackyalbo** [comment]
I think that's suppose to equal much less than 80%... (~15m/100m = ~15%)
@ketankhurana64 Is it always showing unknown?

**Comment by akmithal** [comment]
Hi @jackyalbo , No specific thing I have done to get a finite no instead of <unknown>. I don't have access to this page but this one looks like a similar problem - https://access.redhat.com/solutions/3638421

**Comment by ketankhurana64** [comment]
@jackyalbo it shows unknown to me. Are more updates updates from me?

**Comment by jackyalbo** [comment]
@ketankhurana64 Yes, for some reason the mustgather you provided does not include the all the oc commands section. 
So if you can share the ```oc get deployment noobaa-endpoint -o yaml``` I want to check if the resources section is configured correctly. 
Usually this issue is due to one of two reasons:
One would be metrics-server not running which doesn't seem the issue in your case as you get the right info in ```kubectl top```. 
And the other is a missing cpu limit in the resources section  of the pod. So please share the info so we can check that.
Thanks

**Comment by ketankhurana64** [comment]
[root@api.osculate.cp.fyre.ibm.com ~]# oc get deployment noobaa-endpoint -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ConfigMapHash: 109221e924cc07b59e9d6ad4d40cb1438d2836cc34345266f8ee41258009cf78
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-08-20T09:37:55Z"
  generation: 6
  labels:
    app: noobaa
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:ConfigMapHash: {}
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"fa1c2bf9-28b0-40c3-9eca-b5f382f3673f"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:noobaa-s3: {}
          f:spec:
            f:containers:
              k:{"name":"endpoint"}:
                .: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"BG_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CONTAINER_CPU_LIMIT"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:resourceFieldRef:
                        .: {}
                        f:divisor: {}
                        f:resource: {}
                  k:{"name":"CONTAINER_CPU_REQUEST"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:resourceFieldRef:
                        .: {}
                        f:divisor: {}
                        f:resource: {}
                  k:{"name":"CONTAINER_MEM_LIMIT"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:resourceFieldRef:
                        .: {}
                        f:divisor: {}
                        f:resource: {}
                  k:{"name":"CONTAINER_MEM_REQUEST"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:resourceFieldRef:
                        .: {}
                        f:divisor: {}
                        f:resource: {}
                  k:{"name":"DB_TYPE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENDPOINT_GROUP_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"HOSTED_AGENTS_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"JWT_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"LOCAL_MD_SERVER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOCAL_N2N_AGENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MD_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MGMT_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NOOBAA_AUTH_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"NOOBAA_DISABLE_COMPRESSION"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"NOOBAA_LOG_LEVEL"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"NOOBAA_ROOT_SECRET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRES_DBNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRES_HOST"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRES_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"POSTGRES_USER"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"REGION"}:
                    .: {}
                    f:name: {}
                  k:{"name":"VIRTUAL_HOSTS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":6001,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                  k:{"containerPort":6443,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:tcpSocket:
                    .: {}
                    f:port: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:capabilities:
                    .: {}
                    f:add: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/mgmt-secret"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/etc/s3-secret"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/nsfs/fs1"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"myregistrykey"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext:
              .: {}
              f:runAsGroup: {}
              f:runAsUser: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"mgmt-secret"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:optional: {}
                  f:secretName: {}
              k:{"name":"nsfs-fs1"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
              k:{"name":"s3-secret"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:optional: {}
                  f:secretName: {}
    manager: noobaa-operator
    operation: Update
    time: "2021-08-20T09:38:11Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-08-23T15:09:03Z"
  name: noobaa-endpoint
  namespace: noobaa
  ownerReferences:
  - apiVersion: noobaa.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NooBaa
    name: noobaa
    uid: fa1c2bf9-28b0-40c3-9eca-b5f382f3673f
  resourceVersion: "12319972"
  uid: bc86669f-fd64-4cf1-8f2f-71bc0a9e13db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      noobaa-s3: noobaa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noobaa
        noobaa-s3: noobaa
    spec:
      containers:
      - command:
        - /noobaa_init_files/noobaa_init.sh
        - init_endpoint
        env:
        - name: NOOBAA_DISABLE_COMPRESSION
          valueFrom:
            configMapKeyRef:
              key: NOOBAA_DISABLE_COMPRESSION
              name: noobaa-config
        - name: NOOBAA_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: NOOBAA_LOG_LEVEL
              name: noobaa-config
        - name: MGMT_ADDR
          value: wss://noobaa-mgmt.noobaa.svc:443
        - name: BG_ADDR
          value: wss://noobaa-mgmt.noobaa.svc:8445
        - name: MD_ADDR
          value: wss://s3.noobaa.svc:8444
        - name: HOSTED_AGENTS_ADDR
          value: wss://noobaa-mgmt.noobaa.svc:8446
        - name: DB_TYPE
          value: postgres
        - name: MONGODB_URL
          value: mongodb://noobaa-db-0.noobaa-db/nbcore
        - name: POSTGRES_HOST
          value: noobaa-db-pg-0.noobaa-db-pg
        - name: POSTGRES_DBNAME
          value: nbcore
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: noobaa-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: noobaa-db
        - name: VIRTUAL_HOSTS
          value: s3.noobaa.svc
        - name: REGION
        - name: ENDPOINT_GROUP_ID
          value: fa1c2bf9-28b0-40c3-9eca-b5f382f3673f
        - name: LOCAL_MD_SERVER
          value: "true"
        - name: LOCAL_N2N_AGENT
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt
              name: noobaa-server
        - name: NOOBAA_ROOT_SECRET
          value: O0zkpSqtqTEN0icAg2z5WENgY9IK/oXFf8kZ3UXLVFw=
        - name: NOOBAA_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: auth_token
              name: noobaa-endpoints
        - name: CONTAINER_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: CONTAINER_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        - name: CONTAINER_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        image: noobaa/noobaa-core:master-20210802
        imagePullPolicy: IfNotPresent
        name: endpoint
        ports:
        - containerPort: 6001
          protocol: TCP
        - containerPort: 6443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6001
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
            - SETUID
            - SETGID
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mgmt-secret
          name: mgmt-secret
          readOnly: true
        - mountPath: /etc/s3-secret
          name: s3-secret
          readOnly: true
        - mountPath: /nsfs/fs1
          name: nsfs-fs1
          subPath: ketan
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccount: noobaa-endpoint
      serviceAccountName: noobaa-endpoint
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mgmt-secret
        secret:
          defaultMode: 420
          optional: true
          secretName: noobaa-mgmt-serving-cert
      - name: s3-secret
        secret:
          defaultMode: 420
          optional: true
          secretName: noobaa-s3-serving-cert
      - name: nsfs-fs1
        persistentVolumeClaim:
          claimName: gpfs-vol
status:
  conditions:
  - lastTransitionTime: "2021-08-20T09:37:55Z"
    lastUpdateTime: "2021-08-20T09:38:34Z"
    message: ReplicaSet "noobaa-endpoint-865dcbdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-08-23T15:09:03Z"
    lastUpdateTime: "2021-08-23T15:09:03Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 6
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

@jackyalbo

**Comment by jackyalbo** [comment]
@ketankhurana64 @akmithal 
So I took a look on the noobaa dev cluster running on AWS:
Same exact setup - No \<unknown\>
```
oc get hpa
NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          6d20h```

The difference between the 2 seems to be that this is OCP 4.6.16 and noobaa cluster is 4.7.13
So I would add this issue to issues need to be double check after you upgrade to newer OCP versions.
WDYT?

**Comment by ketankhurana64** [comment]
I tried replicating the same issue on 4.8.5 and it replicated there with below observations

```patch the endpoints as min=5, max=10
5 endpoints are in running state
Patch again with min=1,max=3
3 endpoints will be in running state
No IO was running in either case```

**Comment by ketankhurana64** [comment]
Test automation framework uses older patching command
```kubectl patch noobaa noobaa --type merge  --patch '{
          "spec": {
            "coreResources": {
              "requests": null,
              "limit": null
            },
            "dbResources": {
              "requests": null,
              "limit": null
            },
            "endpoints": {
              "minCount": '1',
              "maxCount": '2',
              "resources": {
                "requests": null,
                "limit": null
              }
            }
          }
        }'
```
 which was causing the Target to set to unknown and hence pods were not scaling down.
 Changing the patching command to below worked for me as I could see pods scaling down after some wait
```
kubectl patch noobaa noobaa --type merge --patch '{
  "spec": {
    "endpoints": {
      "minCount": 1,   
      "maxCount": 1
    }
  }
}'
```

**Comment by akmithal** [comment]
Closing this bug now as it works well with the step defined above.
