### ISSUE TITLE
typo nubmer on several frontend and components locations 

### ISSUE THREAD

**Issue by rflorenc** [noobaa/noobaa-core#6594]
### Environment info
- NooBaa Version: all
- Platform: NA

### Actual behavior
1.Nubmer typo found in several frontent files. Example: Nubmer of pods, Nubmer of nodes, buildNubmer, etc. 

### Expected behavior
1.Should be replaced with Number.

### Steps to reproduce
1.NA

### More information - Screenshots / Logs / Other output
<img width="474" alt="Screenshot 2021-06-22 at 10 59 17" src="https://user-images.githubusercontent.com/14233925/122896051-fa935e00-d348-11eb-8987-b1ad5724cc7a.png">

**Comment by guymguym** [comment]
`Nubmer` is so @nb-ohad ... LOL

**Comment by nb-ohad** [comment]
Left hand writing faster than right one :(
