### ISSUE TITLE
Unable to create buckets if new_buckets_path is set, couldn't create new buckets under that directory through s3 mb 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6608]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa status
INFO[0001] CLI version: 5.9.0
INFO[0001] noobaa-image: noobaa/noobaa-core:master-20210624
INFO[0001] operator-image: noobaa/noobaa-operator:master-20210624
INFO[0001] noobaa-db-image: centos/postgresql-12-centos7
INFO[0001] Namespace: noobaa

oc version
Client Version: 4.7.8
Server Version: 4.7.8
Kubernetes Version: v1.20.0+7d0a2b2

 cat account-create-user8.sh
noobaa api account_api create_account '{
  "email": "user8fs@noobaa.io",
  "name" : "user8fs",
  "has_login": false,
  "s3_access": true,
  "allowed_buckets": { "full_permission": true },
  "default_resource": "fs1",
  "nsfs_account_config": {
    "uid": 5008,
    "gid": 5111,
    "new_buckets_path": "user8-bucket-26Jun/"
  }
}'

on backend FS the directory is created as user8-bucket-26Jun 

[root@storage-rkomandu-x-worker1 fset-rkomandu]# mkdir user8-bucket-26Jun
[root@storage-rkomandu-x-worker1 fset-rkomandu]# ls -lrt user8-bucket-26Jun
total 0
[root@storage-rkomandu-x-worker1 fset-rkomandu]# ls -ld user8-bucket-26Jun
drwxr-xr-x 2 root root 4096 Jun 26 07:39 user8-bucket-26Jun
[root@storage-rkomandu-x-worker1 fset-rkomandu]# chown 5008:5111 user8-bucket-26Jun
[root@storage-rkomandu-x-worker1 fset-rkomandu]# ls -lrd user8-bucket-26Jun
drwxr-xr-x 2 5008 5111 4096 Jun 26 07:39 user8-bucket-26Jun

under the user8-bucket-26Jun the below bucket has to get created and it is not the case as shown below shows as Access Denied 

Unable to create s3 mb from Application node through s3 credentials 

[root@rkomandu-app-node1 ~]# s3u8 mb s3://new-bucket-sunday26
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://new-bucket-sunday26 An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

ls -lrt /nsfs/fs1
total 6
drwxrwxr-x. 2 5000 5100 4096 Jun 23 06:54 user1-fs-bucket
drwxrwxrwx. 2 5001 5100 4096 Jun 23 06:54 user2-fs-bucket
drwxr-x---. 3 5002 5100 4096 Jun 23 07:39 test
drwxr-x---. 3 5004 5004 4096 Jun 23 07:50 test4dir
drwxr-x---. 3 5002 5100 4096 Jun 23 11:16 test-bucket
drwxrwxrwx. 2 root root 4096 Jun 23 11:20 user5-fs-bucket
drwxr-x---. 3 5002 5100 4096 Jun 24 15:23 newtest-day
drwxrwxrwx. 2 5006 5111 4096 Jun 25 09:14 user6-fs-bucket
drwxr-x---. 2 5002 5100 4096 Jun 25 09:19 newbucket-25
drwxr-xr-x. 2 5007 5111 4096 Jun 26 14:25 user-bucket-26Jun
drwxr-xr-x. 2 5008 5111 4096 Jun 26 14:39 user8-bucket-26Jun
sh-4.4# ls -ld /nsfs/fs1
drwxrwxrwx. 13 root root 4096 Jun 26 14:39 /nsfs/fs1

### Actual behavior
1.

### Expected behavior
1. It should be able to create directory under the respective new_buckets_path from the userlevel with appropriate credentials. 

### Steps to reproduce
1. follow step 5 from https://github.com/noobaa/noobaa-core/wiki/NSFS-on-Kubernetes#step-6---create-buckets---via-noobaa-api
2. create s3 bucket using s3mb.
Note: on FS backend the respective user directory is created and has the set of permissions before the s3 mb is called

**Comment by rkomandu** [comment]
sh-4.4# cd /nsfs/fs1
sh-4.4# cd user8-bucket-26Jun
sh-4.4# ls -lrt
ls: cannot open directory '.': Permission denied


what is wrong in my process, let me know

**Comment by romayalon** [comment]
take a look at:
`drwxr-xr-x 2 5008 5111 4096 Jun 26 07:39 user8-bucket-26Jun`
you don't have write permissions for group so you get access denied.

**Comment by rkomandu** [comment]
@romayalon as we tried today w/o permissions or with permissions on the group level the same problem of Access denied 

we gave permission for the new user today that we created  
drwxrwxrwx  2 5009 5111 4096 Jun 28 03:57 user9-bucket-28Jun

FS backend
ls -lrt
total 7
drwxrwxr-x  2 5000 5100 4096 Jun 22 23:54 user1-fs-bucket
drwxrwxrwx  2 5001 5100 4096 Jun 22 23:54 user2-fs-bucket
drwxr-x---. 3 5002 5100 4096 Jun 23 00:39 test
drwxr-x---. 3 5004 5004 4096 Jun 23 00:50 test4dir
drwxr-x---. 3 5002 5100 4096 Jun 23 04:16 test-bucket
drwxrwxrwx  2 root root 4096 Jun 23 04:20 user5-fs-bucket
drwxr-x---. 3 5002 5100 4096 Jun 24 08:23 newtest-day
drwxrwxrwx  2 5006 5111 4096 Jun 25 02:14 user6-fs-bucket
drwxr-x---. 2 5002 5100 4096 Jun 25 02:19 newbucket-25
drwxr-xr-x  2 5007 5111 4096 Jun 26 07:25 user-bucket-26Jun
drwxr-xr-x  2 5008 5111 4096 Jun 26 07:39 user8-bucket-26Jun
drwxrwxrwx  2 5009 5111 4096 Jun 28 03:57 user9-bucket-28Jun
drwxr-x---. 3 5002 5100 4096 Jun 28 04:33 newbucket-today-ravi




endpoint logs:

Jun-28 12:27:45.819 [Endpoint/100]    [L0] core.sdk.bucketspace_nb:: could not create underlying directory - nsfs, deleting bucket [Error: Permission denied] { code: 'EACCES', rpc_code: 'UNAUTHORIZED' }
Jun-28 12:27:45.857 [Endpoint/100] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/newbucket-with-romy1</Resource><RequestId>kqgljjxn-ajw04e-17wr</RequestId></Error> PUT /newbucket-with-romy1 {"host":"10.17.113.231:30341","accept-encoding":"identity","user-agent":"aws-cli/2.1.38 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.mb","x-amz-date":"20210628T122745Z","x-amz-content-sha256":"61d056dc66f1882c0f4053be381523a7a28d384abde04fcf5b0021c716bb0ea1","authorization":"AWS4-HMAC-SHA256 Credential=qS4wkFORQzvAcHkrCOxE/20210628/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=cbaaf40aaf7711df8d9435a1b7ecb8bb89f1fc5bba820fb88c57f624d116f35a","content-length":"154"} Error: Permission denied
Jun-28 12:32:48.215 [Endpoint/100]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  _id: '60d9c170333657002790b8ce',
  name: SENSITIVE-3792f7ef6d0f10e8,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-96b610c81a30aba3,
  bucket_info: { name: SENSITIVE-3792f7ef6d0f10e8, owner_account: { email: SENSITIVE-96b610c81a30aba3, id: '60d9abac333657002790b8b7' }, namespace: { write_resource: { resource: 'fs1', path: 'user9-bucket-28Jun/newbucket-with-romy1' }, read_resources: [ { resource: 'fs1', path: 'user9-bucket-28Jun/newbucket-with-romy1' }, [length]: 1 ], should_create_underlying_storage: true }, tag: '', num_objects: { value: 0, last_update: 1624883370000 }, writable: false, storage: { values: { used: 0, used_other: 0, total: 0, free: 0 }, last_update: 1624883474452 }, data: { size: 0, size_reduced: 0, free: 0, available_for_upload: 0, last_update: 1624883474452 }, usage_by_pool: { pools: [ [length]: 0 ], last_update: 1624883370000 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', bucket_type: 'NAMESPACE', versioning: 'DISABLED', triggers: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/fs1', fs_backend: 'GPFS', id: '60d2d930d47cc90023fd9c68', name: 'fs1' }, path: 'user9-bucket-28Jun/newbucket-with-romy1' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/fs1', fs_backend: 'GPFS', id: '60d2d930d47cc90023fd9c68', name: 'fs1' }, path: 'user9-bucket-28Jun/newbucket-with-romy1' }, [length]: 1 ],
    should_create_underlying_storage: true
  }
}
Jun-28 12:32:48.216 [Endpoint/100]    [L0] core.sdk.namespace_fs:: NamespaceFS: buffers_pool BuffersPool {
  buf_size: 8388608,
  buffers: [],
  sem: Semaphore { _initial: 536870912, _value: 536870912, _waiting_value: 0, _wq: WaitQueue { _name: '_wq_', _q: <ref *1> LinkedList { next: '_lln_', prev: '_llp_', head: '_llh_', length: 0, _lln_: [Circular *1], _llp_: [Circular *1], _llh_: [Circular *1] } } }
}
Jun-28 12:32:48.216 [Endpoint/100]   [LOG] CONSOLE:: create_uls: /nsfs/fs1
Jun-28 12:32:48.216 [Endpoint/100]   [LOG] CONSOLE:: create_uls: { gid: 5111, uid: 5009, new_buckets_path: 'user9-bucket-28Jun/', backend: 'GPFS' } newbucket-with-romy1 /nsfs/fs1/user9-bucket-28Jun/newbucket-with-romy1
Jun-28 12:32:48.218 [Endpoint/100]   [LOG] CONSOLE:: create_uls: [Error: Permission denied] { code: 'EACCES' }
Jun-28 12:32:48.219 [Endpoint/100]    [L0] core.sdk.bucketspace_nb:: could not create underlying directory - nsfs, deleting bucket [Error: Permission denied] { code: 'EACCES', rpc_code: 'UNAUTHORIZED' }
Jun-28 12:32:48.296 [Endpoint/100] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/newbucket-with-romy1</Resource><RequestId>kqglq1bh-1ppozc-75q</RequestId></Error> PUT /newbucket-with-romy1 {"host":"10.17.113.231:30341","accept-encoding":"identity","user-agent":"aws-cli/2.1.38 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.mb","x-amz-date":"20210628T123248Z","x-amz-content-sha256":"61d056dc66f1882c0f4053be381523a7a28d384abde04fcf5b0021c716bb0ea1","authorization":"AWS4-HMAC-SHA256 Credential=qS4wkFORQzvAcHkrCOxE/20210628/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1a69c6f5dcf077faa7675cc7400954e9f5569abb16b68a82cf2f01c78883ef22","content-length":"154"} Error: Permission denied

pvc.yaml and pv.yaml 
less pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpfs-rkomandu-static-vol-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 245Gi
  volumeName: "gpfs-static-pv-rkomandu"
  storageClassName: "ibm-spectrum-scale-csi-fileset"
[root@rkomandu-hpo-inf static]# less pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
        name: gpfs-static-pv-rkomandu
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    #volumeHandle: 12597195971916547483;0A0B30A5:6011484F;fileset=164;path=/mnt/fs1/rkomandu-fset/rkomandu-static-pv
    volumeHandle: 7611214299663493378;0A0B7649:60D0E9DB;path=/mnt/fs1/
  storageClassName: ibm-spectrum-scale-csi-fileset

oc get pvc
NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
db-noobaa-db-pg-0                                  Bound    pvc-7695c910-d6d9-4c84-9176-dfa5d3765983   50Gi       RWO            ibm-spectrum-scale-csi-fileset   5d20h
gpfs-rkomandu-static-vol-pvc                       Bound    gpfs-static-pv-rkomandu                    250Gi      RWX            ibm-spectrum-scale-csi-fileset   5d6h

**Comment by rkomandu** [comment]
this is on the 20210624 build. 

@romayalon based on our webex debug session around 8:20 PM IST posting for your reference nooba-endpoint logs 

Jun-28 15:09:22.224 [Endpoint/100]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  _id: '60d9e621333657002790b8de',
  name: SENSITIVE-166e2d0b24a0650e,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-49efe8841da2448b,
  bucket_info: { name: SENSITIVE-166e2d0b24a0650e, owner_account: { email: SENSITIVE-49efe8841da2448b, id: '60d9e5b9333657002790b8da' }, namespace: { write_resource:
{ resource: 'fs1', path: 'user10-bucket-28Jun/newbucket-romy-new' }, read_resources: [ { resource: 'fs1', path: 'user10-bucket-28Jun/newbucket-romy-new' }, [length]:
1 ], should_create_underlying_storage: true }, tag: '', num_objects: { value: 0, last_update: 1624892760000 }, writable: false, storage: { values: { used: 0, used_oth
er: 0, total: 0, free: 0 }, last_update: 1624892866723 }, data: { size: 0, size_reduced: 0, free: 0, available_for_upload: 0, last_update: 1624892866723 }, usage_by_p
ool: { pools: [ [length]: 0 ], last_update: 1624892760000 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', bucket_type: 'NAMESPACE', versioning: 'DISABLED', trigge
rs: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/fs1', fs_backend: 'GPFS', id: '60d2d930d47cc90023fd9c68', name: 'fs1' }, path: 'user10-bucket-28Jun/newbucket-r
omy-new' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/fs1', fs_backend: 'GPFS', id: '60d2d930d47cc90023fd9c68', name: 'fs1' }, path: 'user10-bucket-28Jun/newbucket
-romy-new' }, [length]: 1 ],
    should_create_underlying_storage: true
  }
}
Jun-28 15:09:22.225 [Endpoint/100]    [L0] core.sdk.namespace_fs:: NamespaceFS: buffers_pool BuffersPool {
  buf_size: 8388608,
  buffers: [],
  sem: Semaphore { _initial: 536870912, _value: 536870912, _waiting_value: 0, _wq: WaitQueue { _name: '_wq_', _q: <ref *1> LinkedList { next: '_lln_', prev: '_llp_',
head: '_llh_', length: 0, _lln_: [Circular *1], _llp_: [Circular *1], _llh_: [Circular *1] } } }
}
Jun-28 15:09:22.225 [Endpoint/100]   [LOG] CONSOLE:: create_uls: /nsfs/fs1
Jun-28 15:09:22.225 [Endpoint/100]   [LOG] CONSOLE:: create_uls: { gid: 5111, uid: 5010, new_buckets_path: 'user10-bucket-28Jun/', backend: 'GPFS' } newbucket-romy-ne
w /nsfs/fs1/user10-bucket-28Jun/newbucket-romy-new
2021-06-28 15:09:22.225658 [PID-100/TID-100] [L1] FS::FSWorker::Begin: Mkdir _path=/nsfs/fs1/user10-bucket-28Jun/newbucket-romy-new _mode=504
2021-06-28 15:09:22.225764 [PID-100/TID-108] [L1] FS::FSWorker::Execute: Mkdir _path=/nsfs/fs1/user10-bucket-28Jun/newbucket-romy-new _mode=504 _uid=5010 _gid=5111 _b
ackend=GPFS
2021-06-28 15:09:22.228790 [PID-100/TID-100] [L1] FS::FSWorker::OnError: Mkdir _path=/nsfs/fs1/user10-bucket-28Jun/newbucket-romy-new _mode=504  error.Message()=Permi
ssion denied
Jun-28 15:09:22.229 [Endpoint/100]   [LOG] CONSOLE:: create_uls: [Error: Permission denied] { code: 'EACCES' }
Jun-28 15:09:22.229 [Endpoint/100]    [L0] core.sdk.bucketspace_nb:: could not create underlying directory - nsfs, deleting bucket [Error: Permission denied] { code:
'EACCES', rpc_code: 'UNAUTHORIZED' }
Jun-28 15:09:22.230 [Endpoint/100]    [L3] core.rpc.rpc:: RPC ROUTER default => wss://noobaa-mgmt.noobaa.svc:443
Jun-28 15:09:22.230 [Endpoint/100]    [L2] core.rpc.rpc:: RPC _get_connection: existing address wss://noobaa-mgmt.noobaa.svc:443 srv bucket_api.delete_bucket connid w
ss://noobaa-mgmt.noobaa.svc:443(17c6vqe)

**Comment by nimrod-becker** [comment]
@rkomandu seems like on other system the issue is not reproduced, as well as seen [here](https://github.com/noobaa/noobaa-operator/issues/676) that that path does work.

In addition I understand that manual mkdir from within the pod fails with permission denied. This is a PVC side issue, don't see how it's related to NS FS if mkdir fails.

Can we close?

**Comment by rkomandu** [comment]
@nimrod-becker it is not a PVC related issue as plain s3 mb works when the new_buckets_path is set to "/", it doesn't work only when you have a directory at the backend with appropriate permissions, the s3 mb should create inside that. If it is a PVC issue then the storage side we tried using setpriv and it worked, the same didn't work from noobaa pod. Jenia and Romy have the background on this.

Jenia, Romy had a debugging session on Mon, Tue of this week and we have come to the conclusion this needs investigation.

**Comment by rkomandu** [comment]
Posting a fresh type of recreate which you might get further insight. I would think this has to be sorted out 

Filesystem backend . the directory was created before the newBucketsPath is passed before the  mmdas account create command

drwxrwxrwx  2 9002 9002 4096 Jul  2 11:22 newdir
[root@storage-rkomandu-x-master fset-rkomandu]# pwd
/ibm/fs1/fset-rkomandu


mmdas account create s92user --uid 9002 --gid 9002 --newBucketsPath "newdir" --resource fs1
Account created successfully, below are the secret and access keys
 Secret Key                                     Access Key
 ----------                                     -----------
 iFzdgK9/iL+ZSnOgXGlPwWldy2wHN8zGPYxmy4mv       3zJJibpQFsGMSz3PqN9o

mmdas account list s92user

 Name           UID     GID     Accesskey               Secretkey                                       New buckets path        Resource
 ----           ---     ---     ---------               ---------                                       ----------------        ----------------
 s92user        9002    9002    3zJJibpQFsGMSz3PqN9o    iFzdgK9/iL+ZSnOgXGlPwWldy2wHN8zGPYxmy4mv        newdir                  fs1

Noobaa endpoint 
sh-4.4# cd newdir
sh-4.4# ls -lrt
ls: cannot open directory '.': Permission denied
sh-4.4# pwd
/nsfs/fs1/newdir

Now s3 mb fails 
s3u92 mb s3://s92user-bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://s92user-bucket An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

I did update the newBucketsPath from mmdas account update as shown below

[root@rkomandu-hpo-inf ~]# mmdas account update s92user --newBucketsPath "/"
Account is successfully updated
[root@rkomandu-hpo-inf ~]# mmdas account list s92user

 Name           UID     GID     Accesskey               Secretkey                                       New buckets path        Resource
 ----           ---     ---     ---------               ---------                                       ----------------        ----------------
 s92user        9002    9002    3zJJibpQFsGMSz3PqN9o    iFzdgK9/iL+ZSnOgXGlPwWldy2wHN8zGPYxmy4mv        /                       fs1

Note: newdir is now marked as "/" 

Tried s3 mb it failed 
[root@rkomandu-app-node1 ~]# s3u92 mb s3://s92user-bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://s92user-bucket An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

After 600 sec, the s3 mb passed on creating the bucket under the / (i.e of namespacestore/subpath on the same PVC). 

[root@rkomandu-app-node1 ~]# sleep 600; s3u92 mb s3://s92user-bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: s92user-bucket
[root@rkomandu-app-node1 ~]# s3u92 cp /bin/date s3://s92user-bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload: ../bin/date to s3://s92user-bucket/date
[root@rkomandu-app-node1 ~]# s3u92 ls s3://s92user-bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-02 11:56:01     108624 date

Two things here as explained in this defect 
1. new_buckets_path when set to dir which is already created on the backend FS and visible on the endpoint with the 777 permissions , the s3 mb doesn't work 
2. When the new_buckets_path is changed to "/" then after 600 sec the s3 mb works from mmdas perspective 

3. From the noobaa create_account API if we have the newBucketsPath set to dir which is existing and have appropriate permissions, then also the s3 mb doesn't work.. even after 600 sec as we didn't update the newbucketsPath to be at "/". 



Would request you/Romy/Jenia to take a further look onto this. Please let me know whether providing newBucketspath a value is allowed or not

**Comment by nimrod-becker** [comment]
For #2 there is a 10m cache of the accounts details, it was already discussed on a different issue

For #3 I am aware that as part of the above-mentioned discussion it was verified that after 10m it does indeed take effect and works as expected.

This leads me to #1 which we know also works on other deployments for the team, what's is the difference in this env that we see its failing?

**Comment by rkomandu** [comment]
@nimrod-becker @jeniawhite @romayalon 

As per the Tue call discussion, uploading the steps of where am facing an issue for s3 users created using new_buckets_path="<some-dir>" vs new_buckets_path="/" 

[Noobaa-defect.txt](https://github.com/noobaa/noobaa-core/files/6815203/Noobaa-defect.txt)


I would like to upgrade to the latest build (as CRD change is there for debugLevel to set, but given the setup would like you guys to investigate) and let me know if something is not appropriate in my setup.

**Comment by akmithal** [comment]
Hi @rkomandu , can you please share latest update here from the discussion/observation.

**Comment by rkomandu** [comment]
Akshat, I posted my steps above your update. Not sure whether you missed it

**Comment by romayalon** [comment]
@rkomandu 
there are some redundant ops in the steps you posted, with that said, when I tried to run the same commands on minikube and on another OCP cluster they all worked and I didn't get this error (the only thing I did differently was the PVC/PV creation).
I also compared your PV/PVC yamls and Srikanth and it looks like there are some differences, in the storageClassName, volumeHandle field, etc, have you tried to create a PV/PVC as he did? (if yes, did it worked? which one is the correct way?)

**Comment by rkomandu** [comment]
Srikanth PVC/PV Volume handle would be different as he was using shared backed cluster (i.e SC). I have got my own SC and the values in the pvc are as per my SC cluster. my SC works fine as we saw that s3 mb creates well for the new_buckets_path="/". 

What are the redundant steps that you are referring to.. I am guessing that the create bucket_api with the same name has got into this problem.. that is the only thing which was done in the steps if you observe carefully, that is not required is my understanding

**Comment by romayalon** [comment]
@rkomandu yes I meant to the bucket_api, these are redundant, but regardless I ran it too to check if it causes the issue but I didn't experience an issue even when running this step.

yes I know it works for you when new_buckets_path is "/" but still as we discussed, it's not related to noobaa-core code since even when you are trying to run mkdir from inside the pod in sub directories you get access_denied error.  when you are using your own SC, noobaa endpoint pod don't get correct access to the PV/PVC.

**Comment by rkomandu** [comment]
Tried on the endpoint with directory creation rather than on the backend which is typically the process.  When created through endpoint we aren't seeing any issues when cd was issued (earlier it showed permission denied when cd <dir> that was created on backend) 

drwxrwxrwx. 2 root   root 4096 Jul 20 10:36 user99-fs-bucket (backend dir created) 
drwxrwxrwx. 3 root   root 4096 Jul 20 10:44 user100-fs-bucket (created from noobaa enpoint) 
drwxrwxrwx. 2 root   root 4096 Jul 20 10:45 user101-fs-bucket
drwxrwxrwx. 2 root   root 4096 Jul 20 11:01 user102-fs-bucket
drwxrwxrwx. 3 root   root 4096 Jul 20 11:43 user103-fs-bucket
drwxr-xr-x. 3 100064 5111 4096 Jul 20 12:11 user104-fs-bucket

sh-4.4# cd user99-fs-bucket/
sh-4.4# ls -lt
ls: cannot open directory '.': Permission denied
sh-4.4# cd ..
sh-4.4# cd user100-fs-bucket
sh-4.4# ls
newbucket-20jul

After the above exercise went with the checking on the SC and then checked from other SC cluster that team uses the difference seems to be in the Permissive mode of SELinux policy. Changed from Disabled to Permissive on my 3 node SC cluster and tried with directory creation on SC (above user103-fs-bucket, user104-fs-bucket) 

Created these accounts for 103, 104 and then issued s3 mb from Application nodes .. then it could successfully create the buckets when new_buckets_path = <dir>. 

From endpoint 
drwxrwxrwx. 3 root   root 4096 Jul 20 11:43 user103-fs-bucket
drwxr-xr-x. 3 100064 5111 4096 Jul 20 12:11 user104-fs-bucket
sh-4.4# cd user103-fs-bucket
sh-4.4# ls
newbucket-u103-20jul
sh-4.4# ls -ltr
total 1
drwxr-x---. 3 100063 5111 4096 Jul 20 11:44 newbucket-u103-20jul
sh-4.4# cd ..
sh-4.4# cd user104-fs-bucket
sh-4.4# ls -lrt
total 1
drwxr-x---. 3 100064 5111 4096 Jul 20 12:13 newbucket-u104-20jul



Thank you @romayalon for the discussion and finally could see it is working once SELinux is set 

Closing this issue.
