### ISSUE TITLE
Without IO, endpoint consumes 800MB throughout

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6621]
### Environment info
- NooBaa Version: master-20210728
- Platform: OCP 4.6.16

### Actual behavior
1. Idle system Grafana view showed 800+MB consumption by endpoint pod. CPU usage is 1% which is OK

### Expected behavior
1. Endpoint pod should consume much less memory as it is 40% of the overall memory. 

### Steps to reproduce
1. Captured Grafana view and looked at top command from endpoint pod

Copying Grafana o/p and must-gather o/p along with noobaa diagnose

**Comment by akmithal** [comment]
[noobaa_diagnostics_1625025948.tar.gz](https://github.com/noobaa/noobaa-core/files/6738269/noobaa_diagnostics_1625025948.tar.gz)

**Comment by akmithal** [comment]
[Memory_Snapshot_Grafana.zip](https://github.com/noobaa/noobaa-core/files/6738272/Memory_Snapshot_Grafana.zip)

**Comment by guymguym** [comment]
@akmithal How much memory would you expect the endpoint pod to consume?
You can define endpoint resource limit in the NooBaa CR (spec.endpoints.resources... - [doc](https://github.com/noobaa/noobaa-operator/blob/master/doc/noobaa-crd.md#custom-cpu-and-memory-resources))
Or you mean that you expect the endpoints to shrink their heap size more aggressively after I/O calms down?

**Comment by akmithal** [comment]
Hello @guymguym , I found 40% consumption of 2 GB limit in idle environment to be very high. My reference point is, on new installation, it stayed around 200-300MB. On doing IO, it peaks upto 1.5 GB's but I was expecting it to come down to initial memory limit post installation. I didn't change any resource value in the configuration.

I suspect such consumption in idle setup would result in huge scaling of endpoints resulting in proportionate allocation of memory. 

Does this consumption of resources look OK to you ?

**Comment by nimrod-becker** [comment]
@jeniawhite had a thought regarding our 500MB buffers for NS FS which might be affecting this as well. Those are not dynamic but flat 500...

**Comment by nimrod-becker** [comment]
@akmithal endpoints would currently scale only on CPU and not mem

**Comment by akmithal** [comment]
Hi @nimrod-becker , I am finding that Memory resources were not freed up after IO was stopped. 
I have 3 GB RAM defined in the configuration. During IO, usage went upto 1.8GB and it didn't drop after that.

[must-gather-1.tar.gz](https://github.com/noobaa/noobaa-core/files/6839859/must-gather-1.tar.gz)

**Comment by rkomandu** [comment]
@romayalon can we have the JIRA ticket mentioned for this 

@nimrod-becker , could you screen and assign

**Comment by nimrod-becker** [comment]
There were multiple fixes to memory handling in the endpoint by Guy and Jacky, can we please rerun with a new build ?

**Comment by nimrod-becker** [comment]
It is available 4.11 as well as 4.10

**Comment by rkomandu** [comment]
@neeshapan , please check when time permits.

**Comment by romayalon** [comment]
Closing, HPO is discontinued.
