### ISSUE TITLE
Implicit Deny doesn't work in Bucket Policy

### ISSUE THREAD

**Issue by rtotarocuebiq** [noobaa/noobaa-core#6656]
### Environment info
- NooBaa Version: 5.7.0
- Platform: Kubernetes 1.18

### Actual behavior
An account can access to the entire bucket also if an allow policy is set on the bucket

### Expected behavior
The account must access only to the allowed resources

### Steps to reproduce
1. Configure a namespace resource
2. Configure a namespace bucket for the resource
3. Create an account and give access to the bucket
4. create a bucket policy like:
 ```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "folderAccess",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Principal": {"AWS":"test-noobaa"},
            "Resource": "arn:aws:s3:::your-bucket/subfolder/*"
        }
    ]
}
```

### More information - Screenshots / Logs / Other output

Value IMPLICIT_DENY returned by this function

```
function has_bucket_policy_permission(policy, account, method, arn_path) {
    const [allow_statements, deny_statements] = _.partition(policy.statement, statement => statement.effect === 'allow');

    // look for explicit denies
    if (_is_statements_fit(deny_statements, account, method, arn_path)) return 'DENY';

    // look for explicit allows
    if (_is_statements_fit(allow_statements, account, method, arn_path)) return 'ALLOW';

    // implicit deny
    return 'IMPLICIT_DENY';
}
```

seems to be ignored by 

```
async function authorize_request_policy(req) {
    //OMISSIS
        const permission = s3_utils.has_bucket_policy_permission(s3_policy, account ? account.email.unwrap() : undefined, method, arn_path);
        if (permission === 'DENY') {
            throw new S3Error(S3Error.AccessDenied);
        } // TODO handle down the permission lane that bp_allow will allow access to bucket
        if (permission === 'ALLOW' || is_owner) req.bucket_policy_allowed = true;
    }
}
```

**Comment by jackyalbo** [comment]
This is by design. By default a user have full access to a bucket - we have an allowed bucket list for each user. if the user has a bucket in this list he will have access to it unless he have an explicit deny. Implicit deny means that if the bucket is not in the allowed list and also have no other explicit allow statements we will deny the access.
So in your case you just need to add a statement that deny all other access to this bucket.

**Comment by rtotarocuebiq** [comment]
Thx for the reply, What do you mean with "allowed bucket list" ? I tried to remove my bucket from the allow list for the user and add the following policy:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "full-access",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Principal": {"AWS":"test-noobaa"},
            "Resource": "arn:aws:s3:::org-103/notebooks/*"
        },
        {
            "Sid": "full-access",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Principal": {"AWS":"test-noobaa"},
            "Resource": "arn:aws:s3:::org-103"
        }
    ]
}`

when I try to list the bucket:

`aws --profile=noobaa-profile --no-verify-ssl  --endpoint-url=https://localhost:9000 s3 ls org-103/`

I receive an Access Deny error message and the following logs in the endpoint pod:

`core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/org-103?list-type=2&amp;prefix=&amp;delimiter=%2F&amp;encoding-type=url</Resource><RequestId>kr377v0i-9nvfpf-fpu</RequestId></Error> GET /org-103?list-type=2&prefix=&delimiter=%2F&encoding-type=url {"host":"localhost:9000","accept-encoding":"identity","user-agent":"aws-cli/2.1.11 Python/3.9.1 Darwin/20.4.0 source/x86_64 prompt/off command/s3.ls","x-amz-date":"20210714T080527Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=M9BASLql5tLod8covDjp/20210714/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=ecceaced2edcf439d175a6902be660a9ea3c35b9c7450e5c27261c6f9d0aeb95"} Error: No permission to access bucket
    at ObjectSDK.authorize_request_account (/root/node_modules/noobaa-core/src/sdk/object_sdk.js:156:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async authorize_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:301:5)
    at async handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:148:5)
    at async s3_rest (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:102:9)
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: action fit? s3:* s3:listbucket
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: principal fit? SENSITIVE-13226dc0b6bd64d3 test-noobaa
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: resource fit? /^arn:aws:s3:::org-103\/notebooks\/.*$/ arn:aws:s3:::org-103
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: is_statements_fit true true false
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: action fit? s3:listbucket s3:listbucket
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: principal fit? SENSITIVE-13226dc0b6bd64d3 test-noobaa
Jul-14 8:05:27.622 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: resource fit? /^arn:aws:s3:::org-103$/ arn:aws:s3:::org-103
Jul-14 8:05:27.623 [Endpoint/12]    [L0] core.endpoint.s3.s3_utils:: bucket_policy: is_statements_fit true true true
`

What am I doing wrong?

**Comment by jackyalbo** [comment]
So about that sadly we do have an opened gap: https://github.com/noobaa/noobaa-core/issues/6251
For now I would suggest adding the bucket to the list. and adding a second deny statement for the bucket.

**Comment by rtotarocuebiq** [comment]
thx for information
