### ISSUE TITLE
Noobaa db pod crashed on idle setup

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6658]
### Environment info
- NooBaa Version: master-20210709
- Platform: OCP 4.6.16

### Actual behavior
1. noobaa db pod crashing continuously

### Expected behavior
1. Pod should not crash

### Steps to reproduce
1. Noobaa db pod crashed on idle setup

```
[root@ocp-akshat-1-inf ~]# podn
NAME                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                      1/1     Running            0          2d19h
noobaa-db-pg-0                     0/1     CrashLoopBackOff   476        2d19h
noobaa-endpoint-79458c94db-27ff5   1/1     Running            0          2d18h
noobaa-endpoint-79458c94db-bjmbs   1/1     Running            0          2d18h
noobaa-endpoint-79458c94db-dh4c2   1/1     Running            0          2d18h
noobaa-endpoint-79458c94db-jl2nd   1/1     Running            0          2d18h
noobaa-endpoint-79458c94db-qc5t4   1/1     Running            0          2d18h
noobaa-endpoint-79458c94db-sgmf9   1/1     Running            0          2d18h
noobaa-operator-6496bdc56b-wsn4m   1/1     Running            1          2d19h
```

Deleting pod is not fixing the error and it restarts again. 

Logs:

```
waiting for server to start....2021-07-12 05:21:36.411 UTC [25] LOG:  starting PostgreSQL 12.5 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
2021-07-12 05:21:36.414 UTC [25] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-07-12 05:21:36.428 UTC [25] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-07-12 05:21:36.486 UTC [25] LOG:  redirecting log output to logging collector process
2021-07-12 05:21:36.486 UTC [25] HINT:  Future log output will appear in directory "log".
.... stopped waiting
pg_ctl: could not start server
Examine the log output.
```

**Comment by liranmauda** [comment]
Hi @akmithal 
can you please describe the pod?

**Comment by liranmauda** [comment]
Another point is that I see: `OCP 4.6.16`
I don't think we are supporting it. @nimrod-becker? 
as far as I know, it should eventually support OCP 4.9 and 4.8, and now as there is no OCP 4.8 GA, you should at list use OCP 4.7

**Comment by nimrod-becker** [comment]
I don't think OCP bothers us, also that's a d/s consideratrion

**Comment by akmithal** [comment]
[noobaa_diagnostics_1626069694.tar.gz](https://github.com/noobaa/noobaa-core/files/6807882/noobaa_diagnostics_1626069694.tar.gz)

Hi @liranmauda , Sorry I forgot the logs. Please find them here.

**Comment by jackyalbo** [comment]
So I went over the logs - all have logs from after the DB crash. @akmithal As I asked from you in slack, please try next time to get the logs located here (from noobaa-db-pg-0): /var/lib/pgsql/data/userdata/log/
As well as all the logs from the core pod (from noobaa-core-0): under /log
Thanks.

**Comment by nimrod-becker** [comment]
@jackyalbo I assume those are not printed and so not collected with the pod logs right ?
If that is indeed the case, we should probably add it to our CLI diag pack

**Comment by jackyalbo** [comment]
@nimrod-becker Are we doing it for core? I don't think it will be that easy if the pod is CLBO

**Comment by nimrod-becker** [comment]
Well, ofc if its CLBO it won't be avail, but we can do 3 attempts or something similar and skip if we fail on all 3

**Comment by jackyalbo** [comment]
@nehasharma5 Can you please write here what you saw about this issue. About the errors in the storage system. Thanks.

**Comment by nehasharma5** [comment]
[root@storage-x-master log]# cat postgresql-Tue.log
cat: postgresql-Tue.log: Input/output error

**Comment by nimrod-becker** [comment]
@akmithal @nehasharma5
Seems like a problem in the underlying PV and no within the NooBaa side

**Comment by nehasharma5** [comment]
@akmithal As you are the creator f this bug , could you close it because as discussed earlier this issue was because nsd got down on Storage cluster

**Comment by akmithal** [comment]
Closing it.
