### ISSUE TITLE
ocp adm must-gather is not picking noobaa diagnose logs

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6669]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.ocp adm must-gather is not collecting noobaa diagnose logs. 

### Expected behavior
1. noobaa diagnose logs should get collected inside must-gather directory.

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
Which exact command did you run @akmithal

**Comment by akmithal** [comment]
`oc adm must-gather`

**Comment by nimrod-becker** [comment]
This will run the OCP must gather and it is not expected to collect anything for NooBaa. You need to supply the image, for example
```
oc adm must-gather --image=registry.redhat.io/ocs4/ocs-must-gather-rhel8
```
