### ISSUE TITLE
Native fs logs are missing from endpoint

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6671]
### Environment info
- NooBaa Version: master-20210718
- Platform: OCP 4.7

### Actual behavior
1. Native FS logs are missing

### Expected behavior
1. Native FS logs should continue to come during IO operation

### Steps to reproduce
1. Enabled debugLevel: 5 by editing "oc edit noobaas noobaa". 
2. Did IO run, IO logs showed logs with `FS:FSWorker ` logs. 
3. After a while, these logs stopped printing while doing IO

Uploading must-gather for debugging. 

@liranmauda / @jackyalbo : Since you added this code last time to work with debug 5, would you be able to fix this one. Thanks

**Comment by akmithal** [comment]
[must-gather-1.tar.gz](https://github.com/noobaa/noobaa-core/files/6840003/must-gather-1.tar.gz)

**Comment by akmithal** [comment]
@nimrod-becker , this can become a big problem for long runs. Kindly have this triaged.

**Comment by akmithal** [comment]
Hi @nimrod-becker , I have not seen this bug lately but do you suspect it to be a problem in code and should this be investigated considering we have cleared high priority defects.

**Comment by liranmauda** [comment]
Hi @akmithal 
The code handling debug was changed in #6697 
In your case (the pervious method) you had to set the debug to it's level (5)
In the new code you are only changing according to the debug config (our case nsfs).
If this bug doesn't repeat, I think it is safe to close it.
WDYT?

**Comment by akmithal** [comment]
Ok, let's close it as not seen since some time now.
