### ISSUE TITLE
s3 mb gives  Access Denied on restarting a node on which endpoint is scheduled

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6676]
Environment info
[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210719
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

Actual behavior
Access Denied while creating a new bucket after restarting a node on which we have endpoint scheduled. On debugging founf fs1 permission changed itself

Expected behavior
FS1 permission was given chmod 777 , they should not have changed itself

Steps to reproduce
Install noobaa and start a copy object operation into a bucket
Once copy is finished , start another copy operation
While copy operation is going on shutdown the node on which noobaa is installed (I have only endpoint pod scheduled on that node , no other noobaa pode)
Start the node
Delete db pod

App Node:

[root@fyreauto-x-app1 ~]# s3 mb s3://new-buck
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://new-buck An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

Inf node:
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod -o wide
NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
noobaa-core-0 1/1 Running 0 73m 10.254.3.167 master1.ns.cp.fyre.ibm.com
noobaa-db-pg-0 1/1 Running 0 60m 10.254.4.17 master0.ns.cp.fyre.ibm.com
noobaa-default-backing-store-noobaa-pod-62daf8d7 0/1 Terminating 0 38m master2.ns.cp.fyre.ibm.com
noobaa-endpoint-565dbbd667-gfzt2 1/1 Running 0 74m 10.254.4.14 master0.ns.cp.fyre.ibm.com
noobaa-operator-6d54447bc5-hr7sb 1/1 Running 1 19h 10.254.3.136 master1.ns.cp.fyre.ibm.com
[root@api.ns.cp.fyre.ibm.com ~]#

sh-4.4# cd nsfs
sh-4.4# ls -lrt
total 0
drwxr-xr-x. 2 root root 6 Jul 23 05:59 fs1
sh-4.4# ls
fs1
sh-4.4# cd fs1
sh-4.4# ls
sh-4.4# ls
sh-4.4# ls

[must-gather.local.2961412144701386214.tar.gz](https://github.com/noobaa/noobaa-core/files/6867489/must-gather.local.2961412144701386214.tar.gz)
[endp.log](https://github.com/noobaa/noobaa-core/files/6867492/endp.log)

**Comment by igorpick** [comment]
Hey,
I am trying to reproduce the issue.
Could you send me please exactly all steps/commands what you did in order to catch the issue?
How did you create nsfs, account, bucket, upload entities, stop the node and so on.
Please send me status of the system, nodes, files permissions before shutdown and after.
Thank you

**Comment by nimrod-becker** [comment]
@nehasharma5

**Comment by nehasharma5** [comment]
@igorpick 
1. I created nsfs account using 
2. noobaa api account_api create_account '{
  "email": "s3user1@noobaa.io",
  "name" : "s3user1",
  "has_login": false,
  "s3_access": true,
  "allowed_buckets": { "full_permission": true },
  "default_resource": "fs1",
  "nsfs_account_config": {
    "uid": 2001,
    "gid": 2002,
    "new_buckets_path": "/",
	"nsfs_only": true
  }
}'

Created nsfs using noobaa namespacestore create nsfs fs1 --pvc-name='gpfs-vol-pvc-new1' --sub-path='error' --fs-backend='GPFS'

Created bucket using s3 mb s3://<bucket-name>

Upload using s3 cp <filename> s3://<bucket-name>

All steps are mentioned above are same which I performed . Before shutdown nsfs/fs1 was given chmod 777

I shutdown the node using fyre GUI

**Comment by nehasharma5** [comment]
[root@api.ns.cp.fyre.ibm.com ~]# cat pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
        name: gpfs-pv-31
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: 12597195971916547483;0A0B30A5:6011484F;path=/mnt/fs1
[root@api.ns.cp.fyre.ibm.com ~]#

[root@api.ns.cp.fyre.ibm.com ~]# cat pvc_1.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpfs-vol-pvc-new11
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  volumeName: "gpfs-pv-31"
  storageclassname: ""
[root@api.ns.cp.fyre.ibm.com ~]#

**Comment by igorpick** [comment]
@nehasharma5  
Thank you. 
Permissions of fs1 are permissions of the mount target folder, from the pod to the node file system.
When you restart the node, for some reason, node changes the permissions of this folder, but you see these permissions on fs1. 
In any reason, I guess, it's not related to noobaa.
@dannyzaken what do you think?

**Comment by nehasharma5** [comment]
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod -o wide
NAME                                               READY   STATUS        RESTARTS   AGE     IP              NODE                         NOMINATED NODE   READINESS GATES
noobaa-core-0                                      1/1     Running       0          24h     10.254.0.42     master1.ns.cp.fyre.ibm.com   <none>           <none>
noobaa-db-pg-0                                     1/1     Running       0          24h     10.254.10.109   master0.ns.cp.fyre.ibm.com   <none>           <none>
noobaa-default-backing-store-noobaa-pod-3286ab30   0/1     Terminating   0          5h15m   <none>          master2.ns.cp.fyre.ibm.com   <none>           <none>
noobaa-endpoint-7557dd8674-w29hf                   1/1     Running       0          24h     10.254.0.41     master1.ns.cp.fyre.ibm.com   <none>           <none>
noobaa-endpoint-7557dd8674-xjxll                   1/1     Running       0          20m     10.254.6.222    master2.ns.cp.fyre.ibm.com   <none>           <none>
noobaa-operator-7f9884fd66-l24p5                   1/1     Running       25         24h     10.254.0.40     master1.ns.cp.fyre.ibm.com   <none>           <none>

Shutdown master1.ns.cp.fyre.ibm.com and got up

[root@api.ns.cp.fyre.ibm.com ~]# oc get pod
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          24h
noobaa-db-pg-0                                     1/1     Running       0          24h
noobaa-default-backing-store-noobaa-pod-3286ab30   0/1     Terminating   0          5h19m
noobaa-endpoint-7557dd8674-w29hf                   1/1     Running       0          24h
noobaa-endpoint-7557dd8674-xjxll                   1/1     Running       0          23m
noobaa-operator-7f9884fd66-l24p5                   1/1     Running       0          24h
[root@api.ns.cp.fyre.ibm.com ~]# oc rsh noobaa-endpoint-7557dd8674-xjxll
sh-4.4# cd nsfs
sh-4.4# ls -lrt
total 1
drwxrwxrwx. 5 root root 4096 Aug 17 08:08 fs2
sh-4.4# exit
exit
[root@api.ns.cp.fyre.ibm.com ~]# oc rsh noobaa-endpoint-7557dd8674-w29hf
sh-4.4# cd nsfs
sh-4.4# ls -lrt
total 0
drwxr-xr-x. 2 root root 6 Aug 17 08:22 fs2
sh-4.4#

**Comment by igorpick** [comment]
@nehasharma5 
As I understood, there is related csi issue. Once it's fixed, please update.

**Comment by nehasharma5** [comment]
We can close this issue as with 5.1.1.3 cnsa and csi 2.3.0 is not reproducible
