### ISSUE TITLE
Data Integrity failure on getting eth inferace down while running IO

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6678]
Environment info
[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210719
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

### Actual behavior
1. Started uploading 129 G file and only 1000 M is uploaded

### Expected behavior
1. In case of network down , noobaa should have rolled back or complete upload should be done.
2. S3 ls does shows all bucket and its object
3. Bucket my-buck and its object were not shown

### Steps to reproduce
1. Create bucket and upload object
2. Again start uploading object in new bucket and down the eth interface
download: s3://neha/testfile to ./dow-test
[root@fyreauto-x-app1 ~]# md5sum dow-test
e5c834fbdaa6bfd8eac5eb9404eefdd4  dow-test

[root@fyreauto-x-app1 ~]# md5sum testfile
64348dcd0f05e1af53ee4634bb486faa  testfile
[root@fyreauto-x-app1 ~]#
[root@fyreauto-x-app1 ~]#
[root@fyreauto-x-app1 ~]#
[root@fyreauto-x-app1 ~]# du -sh testfile
129G    testfile
[root@fyreauto-x-app1 ~]# du -sh dow-test
1000M   dow-test
[root@fyreauto-x-app1 ~]# dow-test

[root@fyreauto-x-app1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-23 04:15:45 neha

[root@fyreauto-x-app1 ~]# ifdown eth0
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
Device 'eth0' successfully disconnected.
[root@fyreauto-x-app1 ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 9.30.204.83/22 brd 9.30.207.255 scope global dynamic noprefixroute eth1
       valid_lft 26983sec preferred_lft 26983sec
[root@fyreauto-x-app1 ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 9.30.204.83/22 brd 9.30.207.255 scope global dynamic noprefixroute eth1
       valid_lft 26964sec preferred_lft 26964sec
[root@fyreauto-x-app1 ~]# ifup eth0
WARN      : [ifup] You are using 'ifup' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifup] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifup] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/5)
[root@fyreauto-x-app1 ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.11.32.14/20 brd 10.11.47.255 scope global dynamic noprefixroute eth0
       valid_lft 43193sec preferred_lft 43193sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 9.30.204.83/22 brd 9.30.207.255 scope global dynamic noprefixroute eth1
       valid_lft 26865sec preferred_lft 26865sec
[root@fyreauto-x-app1 ~]#

**Comment by nehasharma5** [comment]
[must-gather.local.6328555135155415983.zip](https://github.com/noobaa/noobaa-core/files/6868545/must-gather.local.6328555135155415983.zip)

**Comment by nimrod-becker** [comment]
@nehasharma5 it's not clear to me which eth0 you have taken down? endpoint? core? app?

In any case, the bucket should be listed ven if you disrupt the upload operation. However, for an upload operation, there is no rollback or complete. It will stay in an "uncompletd" state until the client either cancels or resumes and eventually completes. 

You have written the bucket is not visible on the list buckets command? I just want to make sure if the bucket itself is visible or not, the object would only be visible if you specifically request to list the uncompleted uploads.

**Comment by nehasharma5** [comment]
@nimrod-becker : eth0 is adapter name . I have mentioned above the complete flow how to check and how get interface down. 
I had two buckets out of which only one bucket is visible . I am not aware how to specially request to list the uncompleted uploads. Its just a upload was started to a bucket and only partial of the object is uploaded. I have seen the upload if upload is failed due to any reason , the object is not shown  into bucket but in this case I can see partial upload of object into the bucket

**Comment by nimrod-becker** [comment]
eth0 of what? The OCP node? Something else ?

Regarding multipart uploads, a listing would not should you uncompleted uploads, not will they fail unless you (or the client) explicitly send an abort command.
Regarding listing uncompleted uploads, see https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListMultipartUploads.html

**Comment by jackyalbo** [comment]
@nimrod-becker I just now had a quick talk about another issue with @nehasharma5 
The eth0 is the network adapter of the client. So during an upload it suppose to break the upload.
The thing is she is not seeing any uncompleted objects using s3 cli, So after shutting down the interface the object doesn't suppose to pop. We need to investigate how the object got created and marked as completed in some way - making it appear in the listing.

**Comment by jackyalbo** [comment]
@nehasharma5 Is it possible that you did not cancel the upload? I can't find proof in the logs but I can see that the parts are being copied into the final file - which suppose to happen only when complete was sent by the client. So my guess here is that you didn't break the upload, you let the upload continue, and then when network came up again the client completed the upload just with the parts he successfully upload. Did the s3 client failed the upload? did he respond with any errors? did you break the upload manually?

**Comment by nehasharma5** [comment]
@jackyalbo Yes , S3 client failed the upload I get 503 . Yes, I got the network down manually. The upload was partial because the file which I started uploading and the one which is uploaded have different size

**Comment by nehasharma5** [comment]
@jeniawhite I again tried this with new noobaa build (15 AUg) and new build of cnsa/csi , here are the observation
1. S3 cp operation did not fail and shows upload success message
2. Size of file in bucket is 0 
 [root@fyreauto-x-app1 ~]# ifdown eth0
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
Device 'eth0' successfully disconnected.
[root@fyreauto-x-app1 ~]# ifup eth0
WARN      : [ifup] You are using 'ifup' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifup] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifup] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/4)
[root@fyreauto-x-app1 ~]# ifdown eth0
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
Device 'eth0' successfully disconnected.

upload: ./test_file_90 to s3://new-buck/test_file_90

[root@fyreauto-x-app1 ~]# s3 ls s3://new-buck
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-08-16 00:25:40        282 bucket.py
2021-08-16 00:32:07 10737418240 test_file_10
2021-08-16 23:21:07          0 test_file_129
2021-08-16 23:34:03 53687091200 test_file_90
[root@fyreauto-x-app1 ~]#

[root@fyreauto-x-app1 ~]# du -sh test_file_129
53G     test_file_129

**Comment by nehasharma5** [comment]
Tried multiple times with 18 Aug build , not able reproduce with 18 Aug build.
