### ISSUE TITLE
Getting SSL validation failed on S3 client

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6683]
Environment info
[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210725
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

Actual behavior
Getting upload failed: ./testfile to s3://never/testfile SSL validation failed for https://s3-noobaa.apps.ns.cp.fyre.ibm.com/never/testfile?uploadId=b4094bc8-0217-4e64-88bf-3846cf96394d&partNumber=462 EOF occurred in violation of protocol (_ssl.c:1125)

Expected:
IO should have failed with a proper message which is understood by enduser

Steps to reproduce
1. Create bucket and upload object
2. Again start uploading object in new bucket and down the eth interface between the nodes on which noobaa is installed

[root@api.ns.cp.fyre.ibm.com ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.17.33.26/19 brd 10.17.63.255 scope global dynamic noprefixroute ens3
       valid_lft 338sec preferred_lft 338sec
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 9.46.193.183/21 brd 9.46.199.255 scope global dynamic noprefixroute ens4
       valid_lft 563sec preferred_lft 563sec
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
[root@api.ns.cp.fyre.ibm.com ~]# ifdown ens3
Connection 'ens3' successfully deactivated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/4)
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod
^C
[root@api.ns.cp.fyre.ibm.com ~]# ifup ens3
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/5)
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod
NAME                               READY   STATUS    RESTARTS   AGE
noobaa-core-0                      1/1     Running   0          19m
noobaa-db-pg-0                     1/1     Running   1          19m
noobaa-endpoint-94c457f8b-2b4bh    1/1     Running   0          20m
noobaa-endpoint-94c457f8b-xvfsd    1/1     Running   0          12m
noobaa-operator-58ff475bfb-dqsgz   1/1     Running   0          20m

App Node:
s.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ./testfile to s3://never/testfile SSL validation failed for https://s3-noobaa.apps.ns.cp.fyre.ibm.com/never/testfile?uploadId=b4094bc8-0217-4e64-88bf-3846cf96394d&partNumber=462 EOF occurred in violation of protocol (_ssl.c:1125)
[root@fyreauto-x-app1 ~]#

[dan.tar.gz](https://github.com/noobaa/noobaa-core/files/6884589/dan.tar.gz)

**Comment by nehasharma5** [comment]
Still able to reproduce with 15 Aug noobaa build

upload failed: ./test_file_10 to s3://new-buck/test_file_10 SSL validation failed for https://s3-noobaa.apps.ns.cp.fyre.ibm.com/new-buck/test_file_10?uploadId=b0e86295-545f-45e5-b43b-98c8fc6e564f&partNumber=284 EOF occurred in violation of protocol

**Comment by nimrod-becker** [comment]
@akmithal

Not a user setup (single eth without LB), also doesn't seem like a NooBaa side error but a more lower level issue

**Comment by nehasharma5** [comment]
Yes, I checked for SSL validation error on google  and find this is not something related to application .
