### ISSUE TITLE
"noobaa api account_api list_accounts '{}'" fails with INVALID_SCHEMA_REPLY 

### ISSUE THREAD

**Issue by davidbw246** [noobaa/noobaa-core#6685]
### Environment info
- NooBaa Version: 
- root@cb-inf ocp]# noobaa version
INFO[0000] CLI version: 5.9.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210726 
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0 

- Platform: OCP 4.7.4

### Actual behavior
1. After upgrading noobaa from 0701 to 0726, "noobaa status" is stuck in "System Phase is "Configuring". Waiting for phase ready ... ". The noobaa operator log show multiple errors per second with "Code=INVALID_SCHEMA_REPLY Message=INVALID_SCHEMA_REPLY SERVER account_api#/methods/list_accounts""

2. The command " noobaa api account_api list_accounts '{}'" fails with:
ERRO[0001] ⚠️  RPC: account.list_accounts() Response Error: Code=INVALID_SCHEMA_REPLY Message=INVALID_SCHEMA_REPLY SERVER account_api#/methods/list_accounts 
FATA[0001] ❌ INVALID_SCHEMA_REPLY SERVER account_api#/methods/list_accounts 

3.  The command "noobaa  api account_api read_account '{"email":"s3user@noobaa.io"}'  fails with:
ERRO[0001] ⚠️  RPC: account.read_account() Response Error: Code=INVALID_SCHEMA_REPLY Message=INVALID_SCHEMA_REPLY SERVER account_api#/methods/read_account 
FATA[0001] ❌ INVALID_SCHEMA_REPLY SERVER account_api#/methods/read_account 

4. The command "noobaa  api account_api read_account" with admin and operator accounts work.
5. "aws s3 ls" works with admin account but fails with s3user account.

### Expected behavior
1. All commands above work with no errors.

### Steps to reproduce
1. upgrade from 0701 to 0726

### More information - Screenshots / Logs / Other output
[noobaa-operator-log.txt](https://github.com/noobaa/noobaa-core/files/6888065/noobaa-operator-log.txt)

**Comment by nimrod-becker** [comment]
There was a new field added to the accounts, "nsfs_only" between the two versions you stated.
By upgrade I guess you mean changing the images, but that' doesn't take care of the schema which needs to be updated (between version we take care of it, but nightly builds on master can ofc change).

You can easily get out of it by using the cli command to update the accounts you have on the system and add the nsfs_only property
