### ISSUE TITLE
Warp fails with multiple user run and show unexpected EOF

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6702]
Environment info
NooBaa Version: master-20210809
Platform: OCP 4.7.13

### Actual behavior
1. Running IO with multiple user gives unexpected EOF and use of closed network connection
### Expected behavior
1. No error should be shown

### Steps to reproduce
1. Run 3 warp instances with 3 different user and bucket

### More information - Screenshots / Logs / Other output
[root@fyreauto-x-app1 ~]# s3 mb s3://buck-1
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.c p.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance d-usage.html#ssl-warnings
make_bucket: buck-1
[root@fyreauto-x-app1 ~]# warp mixed --objects=300 --bucket=buck-1 --insecure --debug --tls --host=s3-noobaa.apps.ns.cp.fyr e.ibm.com --access-key=9RpKEfPS5AxuoNVgZ7Og --secret-key=t7a3yO5eAE+JOTiM3hjqUFCHT3Hmxrn7L9A8A3kY --duration=1800s  --obj.s ize=120M
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/rZDkJAAd/2.OBCQKi2uNYL4qVMJ.rnd": write t cp 9.30.204.83:48546->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/8%29lRugn7/2.tI6MxARonuNvCtEi.rnd": write  tcp 9.30.204.83:48584->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/oIbtyyvx/2.scWRKeG6YZJnwe2U.rnd": write t cp 9.30.204.83:48568->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/05N0ynej/2.75wEaQo1bfPSXis4.rnd": write t cp 9.30.204.83:48606->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/Vx46g0Dq/2.bu2DwiiWUBW5ULr5.rnd": write t cp 9.30.204.83:48614->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/xUL88XNL/2.OohfUEemK9rMZFiW.rnd": write t cp 9.30.204.83:48628->9.30.232.205:443: write: broken pipe
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/6lEdsWn1/2.SBbSKEku5TPCzlny.rnd": write t cp 9.30.204.83:48646->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/dm0WqSNy/2.V6NXh%283r59K7BCCo.rnd": write  tcp 9.30.204.83:48648->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/3kcxttwN/2.w6n5UiFFXEOvz8Li.rnd": write t cp 9.30.204.83:48650->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/tbXPxeW7/2.oCLQjKQvfFMclVBR.rnd": write t cp 9.30.204.83:48634->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/zjRIfKID/2.3UMnrQ8VZP0IPCnU.rnd": write t cp 9.30.204.83:48636->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/c6hPXxOY/2.h%28U%28leHyIMmD2zcS.rnd": wri te tcp 9.30.204.83:48664->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/vR7nlOpS/2.XGLtohBJodPm3GJ9.rnd": write t cp 9.30.204.83:48692->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/FjUitcJE/2.TW4Oa1lMpzPTWsR%28.rnd": write  tcp 9.30.204.83:48706->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/F3i4WxA3/2.3mCzq%28%29GQJrKOx4j.rnd": wri te tcp 9.30.204.83:48710->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/0j4uyB8i/2.5VBEoN95pcZOec5r.rnd": write t cp 9.30.204.83:48708->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/%29WzTVky%28/2.xtuevnaFg4%29s9l4A.rnd": w rite tcp 9.30.204.83:48722->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/xj6qpt3j/2.ZVbo2zgxhWZR3Bat.rnd": write t cp 9.30.204.83:48724->9.30.232.205:443: use of closed network connection
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/57WQpaX%28/2.HRbk6oEt%28%29pHjb8K.rnd": w rite tcp 9.30.204.83:48784->9.30.232.205:443: use of closed network connection
warp: <ERROR> upload error: Put "https://s3-noobaa.apps.ns.cp.fyre.ibm.com/buck-1/KqGkEAZK/2.dd5pCwlUzX285H%287.rnd": write  tcp 9.30.204.83:48822->9.30.232.205:443: use of closed network connection
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> download error: unexpected EOF
warp: <ERROR> delete error:  The specified key does not exist.
warp: Benchmark data written to "warp-mixed-2021-08-10[230221]-qqax.csv.zst"
Mixed operations.
Operation: DELETE, 11%, Concurrency: 20, Duration: 29m56s.
Errors: 1
 * Throughput: 0.08 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 30m1s.
Errors: 7
 * Throughput: 39.24 MiB/s, 0.34 obj/s

Operation: PUT, 13%, Concurrency: 20, Duration: 31m31s.
Errors: 20
 * Throughput: 11.63 MiB/s, 0.10 obj/s
 * 
The other two also show same as above 
[root@fyreauto-x-app1 ~]# warp mixed --objects=300 --bucket=buck-2 --insecure --debug --tls --host=s3-noobaa.apps.ns.cp.fyr e.ibm.com --access-key=EFiul4DdX7sWyOAszBNL --secret-key=++htUePTDRoqVF7gl1FMZRmSnrNQtNs+pHnwOdU+ --duration=1800s  --obj.s ize=120M

make_bucket: buck-3
[root@fyreauto-x-app1 ~]# alias s3='AWS_ACCESS_KEY_ID=RrSPa7MeU6oCjk39Bq3m AWS_SECRET_ACCESS_KEY=1V+WPZY22sOKhRW97V6dSDgIyo z4c4R1USi7tz7e aws --endpoint https://s3-noobaa.apps.ns.cp.fyre.ibm.com   --no-verify-ssl s3'
[root@fyreauto-x-app1 ~]# warp mixed --objects=300 --bucket=buck-3 --insecure --debug --tls --host=s3-noobaa.apps.ns.cp.fyr e.ibm.com --access-key=RrSPa7MeU6oCjk39Bq3m --secret-key=1V+WPZY22sOKhRW97V6dSDgIyoz4c4R1USi7tz7e --duration=1800s  --obj.s ize=120M

While simple copy operation works fine
[root@fyreauto-x-app1 ~]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-08-11 01:24:44 buck-4
2021-08-11 01:24:44 buck-3
[root@fyreauto-x-app1 ~]# s3 cp test_file s3://buck-3
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload: ./test_file to s3://buck-3/test_file
[root@fyreauto-x-app1 ~]#

Logs:
[log.tar.gz](https://github.com/noobaa/noobaa-core/files/6967937/log.tar.gz)

**Comment by akmithal** [comment]
Hi @nehasharma5 , Please point to relevant endpoint logs for this error. Please ensure logs are not wrapped up as otherwise, it wouldn't be useful.

Also, share observations with individual file and set of files for same size(120MB etc.) if it has worked or failed.

**Comment by nehasharma5** [comment]
With 12 and 15 Aug this issue is no more reproducible
