### ISSUE TITLE
Noobaa endpoint stuck in CreateContainerError

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6708]
### Environment info
- NooBaa Version: master-20210810
- Platform: OCP 4.7

### Actual behavior
1. Noobaa endpoint stuck in CreateContainerError

### Expected behavior
1. The pod should be able to start after restart or delete

### Steps to reproduce
1. Found defect 6707. 

This defect is for getting a way out of following error state: `Error: context deadline exceeded`

```
Events:
  Type     Reason                  Age                        From                     Message
  ----     ------                  ----                       ----                     -------
  Normal   Scheduled               5m20s                      default-scheduler        Successfully assigned noobaa/noobaa-endpoint-75db6b8d47-446pm to worker2.ocp-akshat-1.cp.fyre.ibm.com
  Normal   SuccessfulAttachVolume  5m21s                      attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-cc7283b6-b2c4-4474-aac2-96e5a1512d1f"
  Normal   AddedInterface          5m12s                      multus                   Add eth0 [10.254.19.158/22]
  Normal   Pulled                  <invalid> (x4 over 5m11s)  kubelet                  Container image "noobaa/noobaa-core:master-20210810" already present on machine
  Warning  Failed                  <invalid> (x3 over 3m11s)  kubelet                  Error: context deadline exceeded
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS                 RESTARTS   AGE
noobaa-core-0                                      1/1     Running                0          2d
noobaa-db-pg-0                                     1/1     Running                0          2d1h
noobaa-default-backing-store-noobaa-pod-e1b8222a   0/1     Terminating            0          41h
noobaa-endpoint-75db6b8d47-446pm                   0/1     CreateContainerError   0          7m35s
noobaa-endpoint-75db6b8d47-v8trg                   0/1     Terminating            0          2d
noobaa-operator-569ffd7c9c-t9kll                   1/1     Running                10         2d1h
```

**Comment by akmithal** [comment]
[endpoint_1308_137.zip](https://github.com/noobaa/noobaa-core/files/6980259/endpoint_1308_137.zip)
[must-gather-1308-1.tar.gz](https://github.com/noobaa/noobaa-core/files/6980260/must-gather-1308-1.tar.gz)

**Comment by liranmauda** [comment]
Hi @akmithal 
The logs here are missing.
The logs of the endpoint (and those who in the must gather) are from `noobaa-endpoint-75db6b8d47-v8trg`.
We are looking for `noobaa-endpoint-75db6b8d47-446pm` and there are none.

Looking at the nodes we can see:
```
Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Warning  SystemOOM  68s   kubelet  System OOM encountered, victim process: node, pid: 691851
  Warning  SystemOOM  68s   kubelet  System OOM encountered, victim process: pod, pid: 691771
```
Not sure that what is happening in the OCP, We need to look at the master nodes and see what the memory there.
Can you please run on this cluster the following:

log into each master node and run `free -h` to check the free memory.
We want to see if the free memory is low and the available is high.

**Comment by akmithal** [comment]
Hello @liranmauda , Does must gather collect logs for the pod in state "CreateContainerError" ? I don't have this environment with me currently as this was reported 2 weeks back.

Probably this is an enhancement in our noobaa diagnose to collect memory state to debug such issues. @jeniawhite is debugging 6707 defect and reported memory available is very low.

**Comment by liranmauda** [comment]
@akmithal 
AFAIK, the must-gather should collect the node's info, not sure why it is missing.
In this specific case, as we see that it is probably related to node memory we need a cluster in this state.
Then what we could do try to release the memory by doing `sync; echo 3 > /proc/sys/vm/drop_caches` 

So We need a cluster in this stat. 
Let's keep this issue open for now and try to reproduce it on an OCP 4.8 cluster.
We can reevaluate this issue after a few and decide what to do.
WDYT?
