### ISSUE TITLE
Noobaa patch does not work when we're reducing the min count

### ISSUE THREAD

**Issue by ketankhurana64** [noobaa/noobaa-core#6713]
### Environment info
- NooBaa Version: master-20210816
- Platform: 4.7.4

### Actual behavior
1. Number of endpoints does not get reduced

### Expected behavior
1. Number of endpoints should get reduced

### Steps to reproduce
1. Install Noobaa
2. Patch the endpoints to min=10, max=10
3. Endpoints will come in running state
4. Patch endpoitns to min=2,max=10
5. Endpoints will remain 10 in count only
[must-gather.local.6657970441521352069.tar.gz](https://github.com/noobaa/noobaa-core/files/7012759/must-gather.local.6657970441521352069.tar.gz)

**Comment by akmithal** [comment]
@ketankhurana64 , please provide `oc get pod `and other relevant outputs when you raise bugs. It is easy to comprehend that way.

**Comment by liranmauda** [comment]
Hi @ketankhurana64 @akmithal @jackyalbo 
This looks like a reproduction of https://github.com/noobaa/noobaa-core/issues/6585

Why do we think it is something different? 
Can we close this one?

**Comment by ketankhurana64** [comment]
Both are different. For 6585, i was not able to replicate as it was suggested earlier in 6585. So, i replicated 6585 differently, which in turn is causing them to be seen as same defects

**Comment by liranmauda** [comment]
Hi @ketankhurana64 
As we talked at the meeting, looks like the same issue.
Can you please see if you have `<unknown>/80%` ?

**Comment by ketankhurana64** [comment]
As discussed previously in the call,
```[root@api.osculate.cp.fyre.ibm.com ocp]# oc get hpa
NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   0%/80%    1         2         1          68m
```

**Comment by ketankhurana64** [comment]
Closing it, as same bug is covered under 6585
