### ISSUE TITLE
Creating namespacestore gives error NamespaceStore.noobaa.io "fs10" is invalid: spec.nsfs.fsPath: Required value 

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6725]
### Environment info
 noobaa status
INFO[0001] CLI version: 5.9.0                           
INFO[0001] noobaa-image: noobaa/noobaa-core:master-20210907 
INFO[0001] operator-image: noobaa/noobaa-operator:master-20210907 
INFO[0001] noobaa-db-image: centos/postgresql-12-centos7 
INFO[0001] Namespace: openshift-storage  

### Actual behavior
1. Creating namespacestore gives error
2.  noobaa namespacestore create nsfs fs10 --fs-backend='GPFS' --pvc-name='gpfs-vol-pvc'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ❌ Invalid: NamespaceStore "fs10": NamespaceStore.noobaa.io "fs10" is invalid: spec.nsfs.fsPath: Required value 
FATA[0001] ❌ Could not create NamespaceStore "fs10" in Namespace "openshift-storage" (conflict) 

### Expected behavior
1. Namespacestore should be created

### Steps to reproduce
1. Deployed noobaa via ocs with image 4.8.0
2. Noobaa came with version 0419 and upgraded to master-20210907
 oc get pod
NAME                                               READY   STATUS    RESTARTS   AGE
noobaa-core-0                                      1/1     Running   0          18h
noobaa-db-pg-0                                     1/1     Running   0          18h
noobaa-default-backing-store-noobaa-pod-5a30afbe   1/1     Running   0          18h
noobaa-endpoint-7657f6fc5d-nmtcx                   1/1     Running   0          18h
noobaa-operator-77599db7ff-kn754                   1/1     Running   13         18h
ocs-metrics-exporter-6b5dcbc8c-np5dz               1/1     Running   0          21h
ocs-operator-66ffb5d496-h5s97                      1/1     Running   15         18h
rook-ceph-operator-785779d4f9-8z2rv                1/1     Running   0          21h

 oc get pvc
NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
db-noobaa-db-pg-0                                  Bound    pvc-b91c966c-f88e-4168-a1f0-7ce0ca77c94e   50Gi       RWO            ibm-spectrum-scale-csi-fileset   18h
gpfs-vol-pvc                                       Bound    gpfs-pv                                    50Gi       RWX                                             14m
noobaa-default-backing-store-noobaa-pvc-5a30afbe   Bound    pvc-12a57062-8f15-4520-af42-a7d6cb9e2189   50Gi       RWO            ibm-spectrum-scale-csi-fileset   18h

**Comment by bssrikanth** [comment]
Attaching the must-gather logs.
[must-gather.local.7913165914490915881.tar.gz](https://github.com/noobaa/noobaa-core/files/7134893/must-gather.local.7913165914490915881.tar.gz)

**Comment by jeniawhite** [comment]
Looks like old CRDs, since in the latest CRDs we do not have this value at all.
It looks like the cluster has an older version of the CRDs.

**Comment by nimrod-becker** [comment]
@bssrikanth Does it happen with a new noobaa version?
Upgrading not via OCS between two minor versions would probably not update the CRDs which is what Jenia saw

**Comment by nehasharma5** [comment]
This issue was because of old CRDS
