### ISSUE TITLE
pok hpo baremetal cluster get fails

### ISSUE THREAD

**Issue by davidbw246** [noobaa/noobaa-core#6734]
### Environment info
- POK baremetal cluster(c83f1-infa)
- NooBaa Version: 
INFO[0001] CLI version: 5.9.0                           
INFO[0001] noobaa-image: noobaa/noobaa-core:master-20210923 
INFO[0001] operator-image: noobaa/noobaa-operator:master-20210923 
INFO[0001] noobaa-db-image: centos/postgresql-12-centos7 
   
- Platform:
[root@c83f1-infa ~]# oc version
Client Version: 4.7.23
Server Version: 4.8.11
Kubernetes Version: v1.21.1+9807387

### Actual behavior
1. Small percentage(0.02%) of cosbench gets fail on low stress test(2 workers doing random gets from bucket with 100 objects).
Error reported by cosbench: "com.amazonaws.AmazonClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt."

### Expected behavior
1. No gets fail.

### Steps to reproduce
1. Run cosbench with 2 workers doing random gets from bucket with 100 objects.

### More information - Screenshots / Logs / Other output
[must-gather.tar.gz](https://github.com/noobaa/noobaa-core/files/7239110/must-gather.tar.gz)

**Comment by davidbw246** [comment]
@nimrod-becker Please add the NS-FS label to this issue.

**Comment by liranmauda** [comment]
Hi @davidbw246 
What version of cosbench are you using? 
- Please add the trace of the error.
might be related to https://github.com/intel-cloud/cosbench/issues/320

- Can you please describe happened in this cluster? 
- From the endpoint logs it looks like the endpoint was not up (or maybe restated), can you provide the must gather with --previous to get the crashed pod logs?

P.S. Just to verify, Are you using Upstream builds?

**Comment by liranmauda** [comment]
hi @davidbw246 
can you please try with the latest cosbench version (0.4.2 and not 0.4.2.c4)  
It looks like it is an issue with aws-java-sdk which has been updated in 0.4.2

**Comment by davidbw246** [comment]
I am closing because Monica is not seeing this issue on the latest level.
