### ISSUE TITLE
S3 users when gid is same and uid is different the bucket creation happens into the shared group rather than its users account 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6757]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

We are on the d/s build with ODF install shared by RH team on the 4.9.0-161.ci 

oc get csv -n openshift-storage
NAME                            DISPLAY                       VERSION        REPLACES   PHASE
noobaa-operator.v4.9.0-161.ci   NooBaa Operator               4.9.0-161.ci              Succeeded
ocs-operator.v4.9.0-161.ci      OpenShift Container Storage   4.9.0-161.ci              Succeeded
odf-operator.v4.9.0-161.ci      OpenShift Data Foundation     4.9.0-161.ci              Succeeded

and then upgraded the noobaa core and operator using csv method on SHA images from the rhceph-dev/mcg-core, rhceph-dev/mcg-operator 

oc edit csv noobaa-operator 

Users are created on the back-end Spectrum Scale file system as shown below with appropriate uid and gid 

Spectrum Scale FS 

drwxr-xr-x.  3 7009 8000 4096 Oct 13 02:40 s3user9-dir
drwxrwxr-x.  6 7008 8000 4096 Oct 13 03:25 s3user8-dir

on Noobaa endpoint 

sh-4.4# ls -lrt /nsfs/noobaa-s3res-4080029599/
total 16
drwxrwx--x.  3 root root 4096 Jun 22 12:33 spectrum-scale-csi-volume-store
drwxrwx--x.  3 root root 4096 Oct 10 18:58 pvc-022ca3a5-722d-4607-a516-2fc846db0003
drwxrwx--x.  3 root root 4096 Oct 10 19:00 pvc-fe9d84b5-443c-459d-8b07-036f90ed1e4c
drwxrwxr-x.  2 7001 8000 4096 Oct 11 16:38 s3user1-dir
drwxrwxr-x.  2 7003 8003 4096 Oct 11 16:38 s3user3-dir
drwxrwxr-x.  2 7002 8000 4096 Oct 12 19:12 s3user2-dir
drwxr-xr-x.  3 7009 8000 4096 Oct 13 09:40 s3user9-dir
drwxrwxr-x.  6 7008 8000 4096 Oct 13 10:25 s3user8-dir

Accounts are created using mmdas (HPO mgmt control path) 
mmdas account create s3user9 --gid 8000 --uid 7009 --newBucketsPath "/mnt/remote-sample/s3user9-dir"

 mmdas account list

 Name                   UID     GID     New buckets path
 ----                   ---     ---     ----------------
 s3user9                7009    8000    /mnt/remote-sample/s3user9-dir
 s3user8                7008    8000    /mnt/remote-sample/s3user8-dir/

When S3user is creating bucket which will be default to the respective New buckets path that is set to when creating Accounts 
However as you can see 

step 1: 
[root@rkomandu-app-node1 ~]# s3u509 mb s3://newbucket-user9  **(Works as expected)**
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-user9

step 2:
[root@rkomandu-app-node1 ~]# s3u509 cp /bin/file s3://newbucket-user9  **(Works as expected)**
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload: ../bin/file to s3://newbucket-user9/file

step 3:
[root@rkomandu-app-node1 ~]# s3u508 mb s3://newbucket-user8-from-user9 **(Works as expected)**
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-user8-from-user9

step 4:
[root@rkomandu-app-node1 ~]# s3u508 mb s3://newbucket-user9-from-user8 
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-user9-from-user8

step 5:
[root@rkomandu-app-node1 ~]# s3u508 rb s3://newbucket-user9-from-user8
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
remove_bucket: newbucket-user9-from-user8

step 6:
[root@rkomandu-app-node1 ~]# s3u509 mb s3://newbucket-user9-from-user8 **(Shouldn't created in s3u508 default path)**
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-user9-from-user8

On Noobaa-endpoint 
===================
sh-4.4# ls -lRt /nsfs/noobaa-s3res-4080029599/s3user8-dir/
/nsfs/noobaa-s3res-4080029599/s3user8-dir/:
total 2
drwxr-x---. 2 7009 8000 4096 Oct 13 10:25 newbucket-user9-from-user8
drwxr-x---. 2 7008 8000 4096 Oct 13 10:23 newbucket-user8-from-user9
drwxr-x---. 3 7008 8000 4096 Oct 13 09:26 newbucket-user8-new
drwxr-x---. 3 7008 8000 4096 Oct 12 19:40 newbucket-user8

/nsfs/noobaa-s3res-4080029599/s3user8-dir/newbucket-user9-from-user8:
total 0

/nsfs/noobaa-s3res-4080029599/s3user8-dir/newbucket-user8-from-user9:
total 0

/nsfs/noobaa-s3res-4080029599/s3user8-dir/newbucket-user8-new:
total 40
-rw-r-----. 1 7008 8000 34184 Oct 13 09:26 size

/nsfs/noobaa-s3res-4080029599/s3user8-dir/newbucket-user8:
total 112
-rw-r-----. 1 7008 8000 108624 Oct 12 19:40 date

sh-4.4# ls -lRt /nsfs/noobaa-s3res-4080029599/s3user9-dir/    --> (above step 6 should have created in this default newbucketsPath which is not the case as it created in the s3user8-dir)

/nsfs/noobaa-s3res-4080029599/s3user9-dir/:
total 1
drwxr-x---. 3 7009 8000 4096 Oct 13 09:41 newbucket-user9

/nsfs/noobaa-s3res-4080029599/s3user9-dir/newbucket-user9:
total 32
-rw-r-----. 1 7009 8000 25392 Oct 13 09:41 file

Will attach the oc adm logs that are collected on the system 
oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.9

[must-gather-user-group.tar.gz](https://github.com/noobaa/noobaa-core/files/7337819/must-gather-user-group.tar.gz)

noobaa status
I1013 03:58:51.714630 2326063 request.go:668] Waited for 1.033296653s due to client-side throttling, not priority and fairness, request: GET:https://api.rkomandu-ocp.cp.fyre.ibm.com:6443/apis/discovery.k8s.io/v1beta1?timeout=32s
INFO[0001] CLI version: 5.9.0
INFO[0001] noobaa-image: quay.io/rhceph-dev/mcg-core@sha256:d2119adea1b6c019d462b8e6412bbbded6e17332c86a62077160af278cb4186a
INFO[0001] operator-image: quay.io/rhceph-dev/mcg-operator@sha256:e448b04d37f8a33a1983fd452ea8590b74aa761b7b51e76f8f8942886736d7a5
INFO[0001] noobaa-db-image: registry.redhat.io/rhel8/postgresql-12@sha256:1b91c9946f4351bd3688bc538d498e6738cd8a5285af998be6e8dfe218dca6fa
INFO[0001] Namespace: openshift-storage

### Actual behavior
1.

### Expected behavior
1. The respective user even though it has the group id shared with some other user the creation of bucket would need to be done in the default new_buckets_path set when creating the user accounts. 

### Steps to reproduce
1.

**Comment by rkomandu** [comment]
@liranmauda 
Tried on the setup and it is working after 60 sec of sleep between the same gid user the newbucketspath is kicking in as expected 

[root@rkomandu-app-node1 ~]# s3u509 mb s3://newbucket-user9-from-user8
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-user9-from-user8
[root@rkomandu-app-node1 ~]# s3u508 mb s3://newbucket-13oct-user8key ; s3u508 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-13oct-user8key
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-13 09:06:12 newbucket-13oct-user8key
2021-10-13 09:06:12 newbucket-user8-from-user9
2021-10-13 09:06:12 newbucket-user9
2021-10-13 09:06:12 newbucket-user8-new
2021-10-13 09:06:12 newbucket-user8
[root@rkomandu-app-node1 ~]# date; s3u508 rb s3://newbucket-13oct-user8key ; date; s3u508 ls s3:// ; sleep 61; s3u509 mb s3://newbucket-13oct-user8key ; s3u509 ls s3://
Wed Oct 13 09:07:24 PDT 2021
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
remove_bucket: newbucket-13oct-user8key
Wed Oct 13 09:07:27 PDT 2021
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-13 09:07:30 newbucket-user8-from-user9
2021-10-13 09:07:30 newbucket-user9
2021-10-13 09:07:30 newbucket-user8-new
2021-10-13 09:07:30 newbucket-user8
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-13oct-user8key
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-13 09:08:36 newbucket-13oct-user8key
2021-10-13 09:08:36 newbucket-user8-from-user9
2021-10-13 09:08:36 newbucket-user9
2021-10-13 09:08:36 newbucket-user8-new
2021-10-13 09:08:36 newbucket-user8

**Comment by liranmauda** [comment]
Hi @rkomandu 
Can you attach the must-gather?

**Comment by rkomandu** [comment]
Attaching the logs 
[must-gather-s3ls.tar.gz](https://github.com/noobaa/noobaa-core/files/7344841/must-gather-s3ls.tar.gz)

**Comment by rkomandu** [comment]
@liranmauda .. please check

**Comment by rkomandu** [comment]
opened https://github.com/noobaa/noobaa-core/issues/6763 

Closing this one as per the response from Liran on the 60sec cache that we have in place today
