### ISSUE TITLE
nsfs permission has to be set to 777 for creating the user buckets, otherwise permission denied is displayed

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6761]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.

When the s3 service is deployed, on the noobaa-endpoint we need to set the permission to 777 for /nsfs. If this is not set then we can't get the s3users buckets created in the /nsfs/<ns>/<dir> 

s3users directory are pre-existing on the Storage Cluster 
```
sh-4.4# pwd
/nsfs/noobaa-s3res-4080029599

drwxrwxr-x.  2 7001 8000 4096 Oct 11 16:38 s3user1-dir
drwxrwxr-x.  2 7003 8003 4096 Oct 11 16:38 s3user3-dir
drwxrwxr-x.  2 7002 8000 4096 Oct 12 19:12 s3user2-dir

sh-4.4# ls -lrt s3user1-dir
ls: cannot open directory 's3user1-dir': Permission denied
sh-4.4# ls -lrt s3user2-dir
ls: cannot open directory 's3user2-dir': Permission denied

After setting the permissions on the /nsfs as 777 and then create the s3 user accounts then there is no longer the Permission denied error for the user directories that are created thereafter 

sh-4.4# pwd
/nsfs/noobaa-s3res-4080029599

drwxrwxr-x.  6 7008 8000 4096 Oct 13 16:07 s3user8-dir
drwxr-xr-x.  4 7009 8000 4096 Oct 13 16:08 s3user9-dir

sh-4.4# ls -lrt s3user8-dir
total 2
drwxr-x---. 3 7008 8000 4096 Oct 12 19:40 newbucket-user8
drwxr-x---. 3 7008 8000 4096 Oct 13 09:26 newbucket-user8-new
drwxr-x---. 2 7008 8000 4096 Oct 13 10:23 newbucket-user8-from-user9
drwxr-x---. 2 7009 8000 4096 Oct 13 10:25 newbucket-user9-from-user8
sh-4.4# ls -lrt s3user9-dir
total 1
drwxr-x---. 3 7009 8000 4096 Oct 13 09:41 newbucket-user9
drwxr-x---. 2 7009 8000 4096 Oct 13 16:08 newbucket-13oct-user8key

```

Summary is chmod 777 on /nsfs has to be done everytime by logging to the noobaa-endpoint pod which may not be the right way. Added to that in dev/test env when we do the upgrades of ODF or through delete pod method, the Noobaa will be freshly installed/re-conciled as a result the permission for the /nsfs set are lost and we need to set it again.

Ask: Is there a way to set this 777 for /nsfs in the noobaa-core when creating itself as it is not a good practice to ask Customers to set this by logging onto the noobaa pod.

We have appropriate permissions on the Storage Cluster and hence need this setting from Noobaa so it is taken care automatically when the namespacestore is created with the /nsfs to be at 777. Remember that on SC we have the SELINUX is set to Permissive mode. 

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
@rkomandu can this be the same as #6676 ?

**Comment by rkomandu** [comment]
This is on my SC 

[root@storage-rkomandu-x-worker2 fs1]# ls -ld /ibm/fs1
drwxrwxrwx. 35 root root 262144 Oct 15 10:39 /ibm/fs1
[root@storage-rkomandu-x-worker2 fs1]# ls -ld /ibm/fs1/s3user1-dir
drwxrwxr-x. 2 7001 8000 4096 Oct 11 09:38 /ibm/fs1/s3user1-dir
[root@storage-rkomandu-x-worker2 fs1]# ls -ld /ibm/fs1/s3user8-dir
drwxrwxr-x. 6 7008 8000 4096 Oct 13 09:07 /ibm/fs1/s3user8-dir
[root@storage-rkomandu-x-worker2 fs1]# lsattr /ibm/fs1
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/fset-rkomandu-08Oct
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/fset-rkomandu-noobaa-with-ccs
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/new-noobaa-endpoint-down-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/rkomandu-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3resource-dir-13Jul-cli-created-new-again
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user3-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/fset-rkomandu-noobaa-cs
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/noobaa-down-now-1
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/noobaa-down-now
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/jul13rest-1
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/make-noobaa-endpoint-down-now
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/fset-s3service
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/13jul-newlycreated
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/pvc-764eabbc-ba1d-42b0-a194-fac244a1ffc6
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/newbucket-for-507
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/spectrum-scale-csi-volume-store
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/jul13rest-morn-2
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user11-dir-change
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/pvc-a9efed85-09bb-4110-9578-abe7403b8b59
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/fset-rkomandu
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/pvc-73c58724-1d19-4c75-9486-15b1751029c4
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user11-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user9-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user8-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/absderweewdffsaasddffdsaafffdssaaaasssssdddddddsaaaaaaawweerrttttyyyyyyyy
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3resource-dir-12Jul-cli-created
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3resource-dir-12Jul
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user2-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user-temp-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/jul13rest-morn-1
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/jul13rest-2
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/s3user1-dir
lsattr: Inappropriate ioctl for device While reading flags on /ibm/fs1/jul13rest

[root@storage-rkomandu-x-worker2 ~]# lsattr /ibm/fs1/s3user3-dir
[root@storage-rkomandu-x-worker2 ~]# lsattr /ibm/fs1/s3user1-dir

Cleaned up ODF to get on to a newer version. Ran into issues now with that, will work with Vijay from RH team to get this sorted out. upon successful installation and will create new set of user id's as Noobaa db is no longer there and then will update. 

In the meantime you could look through this

**Comment by igorpick** [comment]
Before creating the new set of user id's, just create namespacefs. it will create /nsfs folder with 755 permissions. Then, from endpoint, try to access your backing files.
Additionally, according to the error "lsattr: Inappropriate ioctl for device While reading flags", the backing cluster doesn't support the extended attributes. Could you check please why?

**Comment by rkomandu** [comment]
@igorpick 

Noobaa is deployed through ODF 4.9 method (latest-stable.4.9.0) and then the namespacestore is created last night. When we check on the Noobaa endpoint it is set to 755 the /nsfs 

sh-4.4# ls -ld /nsfs
drwxr-xr-x. 3 root root 37 Oct 18 18:29 /nsfs
sh-4.4# umask
0000
sh-4.4# ls -la /nsfs
total 256
drwxr-xr-x.  3 root root     37 Oct 18 18:29 .
dr-xr-xr-x.  1 root root     29 Oct 18 18:29 ..
drwxrwxrwx. 43 root root 262144 Oct 18 18:12 noobaa-s3res-4080029599


 ls -ld /nsfs/noobaa-s3res-4080029599/
drwxrwxrwx. 43 root root 262144 Oct 18 18:12 /nsfs/noobaa-s3res-4080029599/

Can we have a webex and then you could pickup the inputs that you need for debugging this. The basic IO to work this is very important step and has to be done automatically than asking a user to change permissions logging through the Noobaa pod

**Comment by nimrod-becker** [comment]
PR #6769

**Comment by rkomandu** [comment]
@igorpick 

As per last discussion, the steps were tried on a freshly deployed OCP 4.9 + CNSA 5121 + CSI 2.4.0 + ODF d/s install environment. The behavior seems to be same that s3 user can't create a bucket inside a directory using s3mb 

Please find below the recreate steps and we need to get this sorted out ASAP. 
[nobaa-6761-permission-denied-5121-csi240.txt](https://github.com/noobaa/noobaa-core/files/7472630/nobaa-6761-permission-denied-5121-csi240.txt)

**Comment by rkomandu** [comment]
@igorpick 
on the same setup i.e 5121 (CSI 2.4.0) tried the busy-box that you have provided above 
```

[root@api.hpo.cp.fyre.ibm.com ~]# oc rsh -n openshift-storage spectrum-nfs-busybox-68f65
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 249.5G     15.7G    233.8G   6% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.3G         0     15.3G   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    15.3G     54.8M     15.3G   0% /etc/resolv.conf
tmpfs                    15.3G     54.8M     15.3G   0% /etc/hostname
remote-sample           200.0G      2.6G    197.4G   1% /mnt/rkomandu
/dev/vda4               249.5G     15.7G    233.8G   6% /etc/hosts
/dev/vda4               249.5G     15.7G    233.8G   6% /dev/termination-log
tmpfs                    15.3G     54.8M     15.3G   0% /run/secrets
tmpfs                    29.6G     20.0K     29.6G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.3G         0     15.3G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    15.3G         0     15.3G   0% /proc/scsi
tmpfs                    15.3G         0     15.3G   0% /sys/firmware
/ # ls -lrt /mnt/rkomandu/
total 4
drwxrwx--x    3 root     root          4096 Oct 29 19:32 primary-fileset-remote-sample-4950932666296584575
drwxrwx--x    3 root     root          4096 Nov  2 21:59 primary-fileset-remote-sample-17836319176931783325
drwxrwx--x    3 root     root          4096 Nov  3 20:13 pvc-57253e00-3417-4154-8022-b747962e19b2
drwxrwx--x    3 root     root          4096 Nov  3 20:16 pvc-49bbbee5-fbb6-470c-91c5-5959d91336bc
drwxr-x---    3 5001     5000          4096 Nov  4 05:13 first-created-bucket
drwxrwxr-x    2 5002     5000          4096 Nov  4 05:16 user2-created-dir-on-sc
drwxrwxr-x    2 5003     5000          4096 Nov  4 05:31 user3-created-dir-on-sc
/ # ls -lrt /mnt/rkomandu/user3-created-dir-on-sc/
ls: can't open '/mnt/rkomandu/user3-created-dir-on-sc/': Permission denied
total 0
/ # ls -lrt /mnt/rkomandu/first-created-bucket/
total 112
-rw-r-----    1 5001     5000        108624 Nov  4 05:13 date
/ # ls -lrt /mnt/rkomandu/user3-created-dir-on-sc/
ls: can't open '/mnt/rkomandu/user3-created-dir-on-sc/': Permission denied
total 0

```

Busybox also the same problem, the permission denied 

```
While the CNSA doesn't show anything problematic 
sh-4.4# pwd
/mnt/remote-sample

sh-4.4# ls -lrt user3-created-dir-on-sc/
total 0
sh-4.4# uname -a
Linux worker0.hpo.cp.fyre.ibm.com 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by rkomandu** [comment]
This is what are the recreate steps. Discussed with CSI team internally as well  

On the Storage cluster have the SELINUX set to Permissive mode 

```
ls -lZ is issued as shown below 

drwxrwxr-x. 2 10001 10000 unconfined_u:object_r:container_file_t:s0:c4,c27 4096 Nov 10 22:41 user10001-created-dir-on-sc
drwxrwxr-x. 2 10002 10000 unconfined_u:object_r:container_file_t:s0:c4,c27 4096 Nov 10 22:41 user10002-created-dir-on-sc

```

After that Noobaa is freshly deployed via ODF operator (S3 service create) and it gets the following SELINUX credentials 

`oc get pod noobaa-endpoint-6874689bfd-bnpqf -o yaml -n openshift-storage |grep seL -A2 -B2
    runAsGroup: 0
    runAsUser: 0
    seLinuxOptions:
      level: s0:c26,c25
  serviceAccount: noobaa-endpoint
`

So this  on Storage Cluster 
c4,c27

On Noobaa freshly deployed --> 
 seLinuxOptions:
      level: s0:c26,c25

This is what is occurring in the system, which needs to be checked from Noobaa side, whether this is generated every time on Deployment

**Comment by nimrod-becker** [comment]
@rkomandu 
If I'm not mistaken, you reproduced this on the busy-box, with no noobaa code. Meaning its not a noobaa code issue?

**Comment by rkomandu** [comment]
@nimrod-becker 
I would have shown you a working one.. yday we had Noobaa deployed and Storage Cluster was set to permissive mode then the Noobaa buckets are working when creating inside the directory 
```

oc get pod noobaa-endpoint-bcbc84f5-xbzn9 -o yaml | grep seLinux -A 2 -B 2
    runAsGroup: 0
    runAsUser: 0
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: noobaa-endpoint

```

Today deployed newer Noobaa (ODF) version and then when checked the yaml it had a different SELinux values . As you could see the value changed is creating the issue as i understand. 


```

oc get pod noobaa-endpoint-6874689bfd-bnpqf -o yaml -n openshift-storage |grep seL -A2 -B2
    runAsGroup: 0
    runAsUser: 0
    seLinuxOptions:
      level: s0:c26,c25
  serviceAccount: noobaa-endpoint

```

**Comment by nimrod-becker** [comment]
I understand that OCP Defaults have changed which causes us what we currently see.

Talking to Igor, overriding the defaults customer has set on his OCP might be problematic from the cust side, maybe what we want to do during the deployment of HPO is to verify values are as expected and if not alert the cust?

@igorpick @rkomandu

**Comment by igorpick** [comment]
Hi @rkomandu @nehasharma5 @nimrod-becker,
According to the conversation with Neha,  steps to reproduce the issue.
1. Create a namespace. Kubernetes generates selinux categories for it, for example, c10,c20.
2. Install odf and spectrum scale cluster. 
3. Create nsfs pointed to spectrum storage.
4. Create buckets and objects which get selinux context with categories c10,c20. Everything is working.
3. Remove the namespace
4. Create a new namespace. Kubernetes generates new categories for it, for example, c15,c25.
5. Install odf and create nsfs pointed to existing spectrum storage.
6. Try to list existing buckets or create a new bucket and get the 'Permission denied' error.

When an administrator reinstalls odf, he should provide the previous selinux categories to the new namespace, otherwise, there is a mismatch between new namespace selinux categories and assigned categories of the existing files and folders in the spectrum storage.

A few options to resolve the issue:
1. The administrator can run 'ls -Z' on the existing spectrum storage files to determine the correct categories and configure the new namespace with them.
2. The administrator can relabel (modify categories) the existing files and folders, according to the new namespace categories. (May take a while, depending on amount of existing files).  
3. The administrator knows categories range on the system and can configure the new namespace with all the range, for example, c0.c1023. It will provide full selinux access from endpoint pod to spectrum storage mounted folder.

**Comment by igorpick** [comment]
In order to modify the selinux labels/categories of a namespace:
# oc edit ns <new namespace> 
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c0.c1023

**Comment by guymguym** [comment]
Linking to related issue from Spectrum Scale CSI - 
https://github.com/IBM/ibm-spectrum-scale-csi/issues/481

Worth comparing the details of that issue vs this one.

**Comment by guymguym** [comment]
Also referring to the Spectrum Scale docs on selinux volume relabeling -
https://www.ibm.com/docs/en/spectrum-scale-csi?topic=pods-considerations-mounting-read-write-many-rwx-volumes

**Comment by rkomandu** [comment]
@nimrod-becker , 

As per the slack discussion https://ibmandredhatguests.slack.com/archives/G015Z7SDWQ0/p1644928886864419, the Access Denied is hit for the "s3 mb" bucket creation at the mount point of the Namespacestore, i.e /nsfs/<namespace-store> where it had 755 permissions on the FS. Please take a look at the below information. 


```
Noobaa-endpoint 

sh-4.4# ls -ldZ /nsfs/noobaa-s3res-4080029599/
drwxr-xr-x. 6 root root system_u:object_r:container_file_t:s0 262144 Feb 15 11:21 /nsfs/noobaa-s3res-4080029599/

sh-4.4# ls -lrZ /nsfs/noobaa-s3res-4080029599/
total 2
drwxr-xr-x. 3 1002 1002 unconfined_u:object_r:container_file_t:s0    4096 Feb 15 11:49 user2
drwxrwx--x. 3 root root system_u:object_r:unlabeled_t:s0             4096 Feb 15 11:16 pvc-53582ead-32f6-4419-8d68-58826ad14542
drwxrwx--x. 3 root root system_u:object_r:unlabeled_t:s0             4096 Feb 15 11:14 pvc-277a24ec-00df-4aec-a4bc-a987e632cabf
drwxrwx--x. 3 root root system_u:object_r:container_file_t:s0:c2,c28 4096 Feb 15 07:57 primary-fileset-remote-sample-3148973613941210680


From Application node as user3 we are trying to create s3 mb and where we get the Access Denied

[root@autoosculate-x-app1 ~]# alias user3='AWS_ACCESS_KEY_ID=3Za49gmn1VcmoV5zkTpW AWS_SECRET_ACCESS_KEY=WZ6PoIPmNoy0oRLGROwELkB5J0AAeZbyoIQvoBMy aws --endpoint https://s3-openshift-storage.apps.don.cp.fyre.ibm.com/  --no-verify-ssl s3'
[root@autoosculate-x-app1 ~]# user3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.don.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[root@autoosculate-x-app1 ~]# user3 mb s3://bucket3
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.don.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://bucket3 An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied


```



@jackyalbo , could you debug this and let us know what are the recommendations for this to work ?

**Comment by nimrod-becker** [comment]
In the live session with Jacky, the last occurrence was found to be irrelevant for NooBaa.

What else is left her eon this bug? @rkomandu

**Comment by rkomandu** [comment]
@nimrod-becker, Ketan mentioned the discussion he had with @jackyalbo on the /nsfs/<namespacestore> on endpoint is having 755 and how the noobaa user can create the directory on the mount-point, which is valid though 

Ulf is saying will have some setup related changes and hasn't shared yet. For now keep this as low priority

**Comment by nimrod-becker** [comment]
@rkomandu Why?
There is nothing to be done on the NooBaa side + its not a bug => should not be kept open

**Comment by rkomandu** [comment]
closing this issue based on the @nimrod-becker comments and our agreements.
