### ISSUE TITLE
s3user can list buckets of all groups that he is part of as per gid- Is this expected ? 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6763]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.

Moving this from the #6757 comment as per Liran comment.

However there is a question of when the s3 ls s3:// lists for both the user buckets ? Why is that happening

drwxrwxr-x. 6 7008 8000 4096 Oct 13 16:07 s3user8-dir
drwxr-xr-x. 4 7009 8000 4096 Oct 13 16:08 s3user9-dir

current buckets in the respective s3users are as follows from the endpoint.

sh-4.4# ls -lrt s3user9-dir/
total 1
drwxr-x---. 3 7009 8000 4096 Oct 13 09:41 newbucket-user9
drwxr-x---. 2 7009 8000 4096 Oct 13 16:08 newbucket-13oct-user8key

sh-4.4# ls -lrt s3user8-dir/
total 2
drwxr-x---. 3 7008 8000 4096 Oct 12 19:40 newbucket-user8
drwxr-x---. 3 7008 8000 4096 Oct 13 09:26 newbucket-user8-new
drwxr-x---. 2 7008 8000 4096 Oct 13 10:23 newbucket-user8-from-user9
drwxr-x---. 2 7009 8000 4096 Oct 13 10:25 newbucket-user9-from-user8

Now when we issue s3u509 list buckets why does it print for all the buckets of s3-user8-dir as well ? Is it b/c the gid is same and is this Expected to work like this ?

s3u509 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-13 09:08:36 newbucket-13oct-user8key
2021-10-13 09:08:36 newbucket-user8-from-user9
2021-10-13 09:08:36 newbucket-user9
2021-10-13 09:08:36 newbucket-user8-new
2021-10-13 09:08:36 newbucket-user8

Hi @rkomandu
Please promote this to a new issue and attach the logs.
You can close this current issue based on your founding.

Attaching the must-gather logs to this issue 

### Expected behavior
1.

### Steps to reproduce
1.

### More information - Screenshots / Logs / Other outpu
[must-gather-s3ls.tar.gz](https://github.com/noobaa/noobaa-core/files/7345591/must-gather-s3ls.tar.gz)
t

**Comment by liranmauda** [comment]
@rkomandu hot at the moment, please take it to the triage meeting, in the meanwhile I will talk to @nimrod-becker

**Comment by rkomandu** [comment]
@liranmauda , did you discuss with Nimrod on this as per 11 days ago. 

Expectation here is, 
When we have 3 users in which 2 of them have same gid value, They create buckets and when **s3 ls s3://** is issued Is it appropriate to list all the buckets that have the same gid ?

**Comment by rkomandu** [comment]
For ex:  this was tried on the odf 212.ci build 

```

s3user81 and s3user82 are user accounts created with same gid 

noobaa bucket list
I1029 17:21:16.679098  744253 request.go:668] Waited for 1.021501289s due to client-side throttling, not priority and fairness, request: GET:https://api.rkomandu-ocp.cp.fyre.ibm.com:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: <nil>
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33051/rpc/ 0xc0002398b0
INFO[0001] RPC: Connecting websocket (0xc0002398b0) &{RPC:0xc000238b40 Address:wss://localhost:33051/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0002398b0) &{RPC:0xc000238b40 Address:wss://localhost:33051/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 0.4ms

BUCKET-NAME
newbucket-30oct-s82user
newbucket-29oct-s81user
first.bucket

The blelow are buckets created for the users using s3 mb from endpoint ls they can be viewed 

drwxr-x---.  3 6001 6000 4096 Oct 29 13:49 newbucket-29oct-s81user
drwxr-x---.  3 8002 6000 4096 Oct 30 00:21 newbucket-30oct-s82user
sh-4.4# pwd
/nsfs/noobaa-s3res-4080029599

From App node when the s3 ls is issued, it displays both of them for s3user81 and s3user82. Is this acceptable ?  

[root@rkomandu-app-node1 ~]# s3u81 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-29 17:21:57 newbucket-30oct-s82user
2021-10-29 17:21:57 newbucket-29oct-s81user
[root@rkomandu-app-node1 ~]# s3u82 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-10-29 17:22:05 newbucket-30oct-s82user
2021-10-29 17:22:05 newbucket-29oct-s81user
```

As s3 mb is created directly by users with the 750 as we see above on the endpoint, the bucket list from s3 for both users is expected or not of what it is currently being displayed ?

**Comment by jeniawhite** [comment]
@rkomandu 
If I'm not mistaken you were saying that if I will create a directory on the FS with permissions of some UID/GID and then attempt to access the directory with a different UID but the same GID then the FS will allow me to do so because I'm part of the group.
In the above case, you basically export both of the buckets (NooBaa is aware of these directories and maps them as buckets), we offload all of the ACL logic to the FS.
So if both of the S3 users have the same GID, it makes sense that they will be able to see both buckets.
I just need to emphasize that the S3 users should only see buckets that are exported or created by them or their GID.
Seems to me like a valid flow.
What do you recon @nimrod-becker @liranmauda @romayalon?

**Comment by liranmauda** [comment]
Sound reasonable, for me it also looks like a valid flow.

**Comment by rkomandu** [comment]
@jeniawhite @liranmauda  or need a final check from Nimrod ? 

DO you think then we should close this one saying WAD ?

**Comment by liranmauda** [comment]
@rkomandu I think we can close this.
@nimrod-becker @jeniawhite ?

**Comment by jeniawhite** [comment]
@liranmauda In my opinion it works as expected.
@nimrod-becker What do you think?

**Comment by nimrod-becker** [comment]
I agree

**Comment by rkomandu** [comment]
Based on the above inputs from Noobaa team, this is WAD hence closing this
