### ISSUE TITLE
Question: S3 bucket policies don't have any effect

### ISSUE THREAD

**Issue by arunprasadmudaliar** [noobaa/noobaa-core#6805]
Hi,
I am trying to set bucket policy for granting access to a user  who is not the owner of a bucket. While the policy is getting updated successfully, it simply is in-effective. For testing, I have granted "s3:ListBucket" access but still that user is unable to list the bucket and get's an AccessDenied error. I have tried explicitly granting all access: "s3:*" but still the user cannot perform any action over that bucket.

If I add this bucket under 'Permitted buckets' from UI for that user account, then he is able to access it but then has full_control over it such as he can even delete it which I want to restrict.

Policy:
[policy.txt](https://github.com/noobaa/noobaa-core/files/7519560/policy.txt)

DB entry of that bucket:
![bucket-info-from-db](https://user-images.githubusercontent.com/11840156/141282900-6639e7e3-8c33-4310-826d-c79d4bebe816.png)

Error:
![error](https://user-images.githubusercontent.com/11840156/141282610-141a85dd-4aa3-4dba-9e80-1cfe59045186.png)

I have verified that the s3cmd configuration is set for the user who has been added using the policy.json file. Please let me know what am I doing wrong and why the policy is not in effect.

Noobaa version is 5.8.0 and is deployed on a OCP cluster 4.8.14.

**Comment by nimrod-becker** [comment]
I suspect this has to do with the allowed buckets. If you look at the UI at the accounts you would see that each account has allowed buckets, and actual access is calculated by both the policy and allowed buckets. We are in the process of removing the allowed buckets altogether, but for now I would suspect adding the bucket to the allowed of the account would make it work

**Comment by jackyalbo** [comment]
This is a well known GAP we have: #6251 
allowed statement currently doesn't overrule bucket missing from allowed buckets. 
So the only option is to allow the bucket and deny what you want from that user, or allow what you need and then add a deny all (again when the bucket is in the allowed list).

**Comment by arunprasadmudaliar** [comment]
@nimrod-becker  @jackyalbo , Thank you for pointing me in correct direction.

By using the combination of 'permitted buckets (available in UI)' + 's3 deny rules' , I was able to deny bucket deletion requests.
