### ISSUE TITLE
Noobaa endpoint pod Terminated before new one comes in Running state

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6811]
### Environment info
- NooBaa Version: ODF 4.9.0 - 236.ci 
- Platform: OCP 4.9 

### Actual behavior
1. The endpoint pods goes into terminating state

### Expected behavior
1. The old endpoint should come to Terminating after new ones in running state

### Steps to reproduce
1. Changed noobaa log level 

```
[root@ocp-akshat-1-inf akshat]# oc get pod
NAME                                               READY   STATUS    RESTARTS   AGE
noobaa-core-0                                      1/1     Running   0          6m45s
noobaa-db-pg-0                                     1/1     Running   0          6m45s
noobaa-default-backing-store-noobaa-pod-41376b30   1/1     Running   0          4m46s
noobaa-endpoint-6b98668666-wkjvq                   1/1     Running   0          45s
noobaa-operator-67c57b5464-wqcww                   1/1     Running   0          4h30m
ocs-metrics-exporter-6fc4cbfcb6-qc7vx              1/1     Running   0          4h30m
ocs-operator-75fc898954-9cqt5                      1/1     Running   0          4h30m
odf-console-7dc4779787-qv44z                       1/1     Running   0          4h30m
odf-operator-controller-manager-548c77868b-nb87q   2/2     Running   0          4h30m
rook-ceph-operator-c796c8c98-nqd8f                 1/1     Running   0          4h30m
[root@ocp-akshat-1-inf akshat]# kubectl edit configmap/noobaa-config
configmap/noobaa-config edited
[root@ocp-akshat-1-inf akshat]# 
[root@ocp-akshat-1-inf akshat]# 
[root@ocp-akshat-1-inf akshat]# oc get pod
NAME                                               READY   STATUS              RESTARTS   AGE
noobaa-core-0                                      1/1     Terminating         0          7m12s
noobaa-db-pg-0                                     1/1     Running             0          7m12s
noobaa-default-backing-store-noobaa-pod-41376b30   1/1     Running             0          5m13s
noobaa-endpoint-6b98668666-px86w                   0/1     ContainerCreating   0          2s    ----->>> This one       
noobaa-endpoint-6b98668666-wkjvq                   1/1     Terminating         0          72s
noobaa-operator-67c57b5464-wqcww                   1/1     Running             0          4h30m
ocs-metrics-exporter-6fc4cbfcb6-qc7vx              1/1     Running             0          4h30m
ocs-operator-75fc898954-9cqt5                      1/1     Running             0          4h30m
odf-console-7dc4779787-qv44z                       1/1     Running             0          4h31m
odf-operator-controller-manager-548c77868b-nb87q   2/2     Running             0          4h31m
rook-ceph-operator-c796c8c98-nqd8f                 1/1     Running             0          4h30m
[root@ocp-akshat-1-inf akshat]# 
```

**Comment by guymguym** [comment]
@akmithal @dannyzaken Which strategy are we setting on the noobaa-endpoint deployments?
Refer to - https://github.com/ContainerSolutions/k8s-deployment-strategies

**Comment by akmithal** [comment]
Hi @dannyzaken , Are you aware of this part ? I couldn't locate any of the strategy names in the noobaa-endpoint deployment.

**Comment by jeniawhite** [comment]
Hey @guymguym, this is what I know from the spec of our deployment
I've also reviewed this at our meeting @akmithal 
```
strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
```
We are using https://github.com/ContainerSolutions/k8s-deployment-strategies/tree/master/ramped
At least from the configuration point of view, it looks valid.
We intend to keep at least 75% of endpoints working with a maximum surge of 1 when spawning new ones (unless I'm missing something).

**Comment by guymguym** [comment]
Thanks @jeniawhite 
I am puzzled with how this config should work with a single endpoint - any idea? 
Maybe a good idea to lookup issues in kubernetes related to that.

**Comment by akmithal** [comment]
One more observation: This behaviour is observed only with step "kubectl edit configmap/noobaa-config". 

When I edit deployment to change CPU/Mem resources, the new endpoint pod first comes into Running state and then the old one goes into Terminating( this is expected behaviour)

**Comment by dannyzaken** [comment]
@guymguym @akmithal so what I think happens here is that we explicitly delete the endpoint pods when the config map is changed so the pods will use the new envs. kuberentes does not automatically restart the pods on config maps changes, so in this case the strategy is not relevant

**Comment by liranmauda** [comment]
Reopening for validation
@akmithal ^^^

**Comment by akmithal** [comment]
Closing this defect as it is not recreatable with build - [5.9_nsfsfixes-20220215](https://hub.docker.com/layers/noobaa/noobaa-core/5.9_nsfsfixes-20220215/images/sha256-446d1ab5d795d5aed911c5fdc85a720ec67fd7f1939b4cb9e30b51a02d5acb8d?context=explore)
