### ISSUE TITLE
Some Files in oc-adm must gather have 0 size

### ISSUE THREAD

**Issue by ketankhurana64** [noobaa/noobaa-core#6817]
### Environment info
- NooBaa Version: 5.9.0-20210722
- ODF version: 4.9.0-214.ci
- Platform: OpenShift 4.9 

### Actual behavior
1. Files are of 0 size and no content inside

### Expected behavior
1. Files shouldn't be of 0 size

### Steps to reproduce
1. Execute oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.9
2. Go to /root/must-gather.local.458190093719636697/quay-io-rhceph-dev-ocs-must-gather-sha256-2cfd1466b584aba7c3d94a6d2397267443416fe7db8a7fc132e4137ed640ca8f/noobaa/raw_output

### More information - Screenshots / Logs / Other output
[root@api.don.cp.fyre.ibm.com raw_output]# ll
total 23524
-rw-r--r-- 1 root root     2957 Nov 23 21:49 BackingStoreList_crs.yaml
-rw-r--r-- 1 root root     2592 Nov 23 21:49 BucketClassList_crs.yaml
-rw-r--r-- 1 root root        0 Nov 23 21:49 db-noobaa-db-pg-0-pvc-describe.txt
-rw-r--r-- 1 root root     2663 Nov 23 21:49 NamespaceStoreList_crs.yaml
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-core-0-core.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-core-0-core-previous.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-core-0-pod-describe.txt
-rw-r--r-- 1 root root     1543 Nov 23 21:49 noobaa-db-pg-0-db.log
-rw-r--r-- 1 root root     1543 Nov 23 21:49 noobaa-db-pg-0-db-previous.log
-rw-r--r-- 1 root root     8898 Nov 23 21:49 noobaa-db-pg-0-initialize-database.log
-rw-r--r-- 1 root root      221 Nov 23 21:49 noobaa-db-pg-0-init.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-db-pg-0-pod-describe.txt
-rw-r--r-- 1 root root 12576413 Nov 23 21:49 noobaa-default-backing-store-noobaa-pod-76ea4a0d-noobaa-agent.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-default-backing-store-noobaa-pod-76ea4a0d-pod-describe.txt
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-default-backing-store-noobaa-pvc-76ea4a0d-pvc-describe.txt
-rw-r--r-- 1 root root   742051 Nov 23 21:49 noobaa_diagnostics_1637732969.tar.gz
-rw-r--r-- 1 root root    25472 Nov 23 21:49 noobaa-endpoint-5554c7f8cb-6r9lh-endpoint.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-endpoint-5554c7f8cb-6r9lh-pod-describe.txt
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-endpoint-scc-describe.txt
-rw-r--r-- 1 root root     6349 Nov 23 21:49 NooBaaList_crs.yaml
-rw-r--r-- 1 root root 10680815 Nov 23 21:49 noobaa-operator-67c57b5464-68mlz-noobaa-operator.log
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-operator-67c57b5464-68mlz-pod-describe.txt
-rw-r--r-- 1 root root        0 Nov 23 21:49 noobaa-scc-describe.txt
-rw-r--r-- 1 root root       15 Nov 23 21:49 obc_list
-rw-r--r-- 1 root root     1897 Nov 23 21:49 status

**Comment by akmithal** [comment]
@liranmauda FYI. Thanks

**Comment by liranmauda** [comment]
@akmithal If I recall we wanted a BZ on this for must gather

**Comment by liranmauda** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2026342

**Comment by ketankhurana64** [comment]
We've associated bugzilla ticket for the same and is tracked there. Hence closing it
