### ISSUE TITLE
Files are deleted from the bucket regardless of the expiration rule defined on the lifecycle configuration

### ISSUE THREAD

**Issue by eyalma01** [noobaa/noobaa-core#6818]
### Environment info
- NooBaa Version: 5.7.0
- Platform: OpenShift 4

### Actual behavior
1. I'm trying to set a lifecycle configuration on my bucket so objects older than 4 days will be expired (deleted).
Thing is that, for some reason, ~30 minutes after setting that cleanup rule all the files in the bucket are deleted, regardless of their creation date.

### Expected behavior
1. Only files that are older than 4 days should be deleted

### Steps to reproduce
1. Existing S3 bucket with existing files. some of the files were uploaded to the bucket more that 4 days ago, some of the files were uploaded to the bucket less than 4 days ago.
2. Call PutBucketLifecycleConfiguration REST API to set a cleanup rule that expires the files after 4 days.
3. Actual - ~30 minutes after that REST call, ALL the files are deleted from the bucket.

### More information - Screenshots / Logs / Other output
The payload used to setup the lifecycle configuration:

`<LifecycleConfiguration>
    <Rule>
        <ID>ExpirationRule</ID>
        <Prefix></Prefix>
        <Status>Enabled</Status>
        <Expiration>
            <Days>4</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>`

**Comment by liranmauda** [comment]
Not sure why but it looks like it is not setting days, but it sets minutes 
https://github.com/noobaa/noobaa-core/blob/f0850fe66417ac7c113ae7222d8f1f2b820b35bc/src/server/bg_services/lifecycle.js#L55

I guess changing that to days will work properly.
@eyalma01 if you like you can change and test, I will refactor the whole file on Sunday.

**Comment by guymguym** [comment]
FYI @tamireran ^
Funny mistake but a serious bug.

**Comment by guymguym** [comment]
We can think of a test case to cover expiration - maybe a "gray box" approach will be most effective,
such as using the S3 putLifecyclePolicy API and after that check the database applied the expected configuration.

**Comment by liranmauda** [comment]
@eyalma01 
can you please check if this fix works for you as expected?
