### ISSUE TITLE
Feature Request: Add possibility to update s3 credentials via RPC API

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6822]
**Is your feature request related to a problem? Please describe.**
We safe the s3 credentials of noobaa in our vault and when we completely reinstall the noobaa instance (with wipe of DB) we automatically recreate the accounts via the RPC API, but when we do so new credentials get automatically created. We then need to update to the new credentials everywhere we use them

**Describe the solution you'd like**
Either having the possibility to provide your own access and secret key when creating an account via the RPC API (`account_api` => `create_account`) or be able to update the credentials via the RPC API after creating the account (maybe `account_api` => `update_account`)

**Describe alternatives you've considered**
It would be possible to directly change them in the db, but this is definitely not the preferred qay

**Additional context**

**Comment by nimrod-becker** [comment]
@liranmauda 

We are adding this option to the CLI, there is an open PR on the operator repo

**Comment by liranmauda** [comment]
@nimrod-becker 
You are referring to https://github.com/noobaa/noobaa-operator/pull/804
This PR is about telling the core to regenerate the S3 credentials.

@lallinger-arbeit is asking to provide his own S3 credentials and not regenerate.

@lallinger-arbeit please keep me honest

**Comment by lallinger-arbeit** [comment]
> @lallinger-arbeit is asking to provide his own S3 credentials and not regenerate.

 exactly
