### ISSUE TITLE
Create bucket fails however the noobaa-db database lists 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6856]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

OCP 4.9.5
Noobaa d/s 4.9.0 RC4 or RC5 build

noobaa status
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: quay.io/rhceph-dev/mcg-core@sha256:6ce2ddee7aff6a0e768fce523a77c998e1e48e25d227f93843d195d65ebb81b9
INFO[0000] operator-image: quay.io/rhceph-dev/mcg-operator@sha256:cc293c7fe0fdfe3812f9d1af30b6f9c59e97d00c4727c4463a5b9d3429f4278e
INFO[0000] noobaa-db-image: registry.redhat.io/rhel8/postgresql-12@sha256:b3e5b7bc6acd6422f928242d026171bcbed40ab644a2524c84e8ccb4b1ac48ff
INFO[0000] Namespace: openshift-storage

Creation of bucket fails from App node as per s3 mb command, however the noobaa db stores it and visible on multiple other tools like noobaa bucket list etc 

### Actual behavior
Step 1: 
[root@rkomandu-app-node1 ~]# s3u5001 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2022-01-17 21:20:42 new-bucket-06jan
2022-01-17 21:20:42 new-bucket-user2-06jan
2022-01-17 21:20:42 new-bucket-5003-07jan
2022-01-17 21:20:42 newbucket-temp-1
2022-01-17 21:20:42 user-5001-bucket
2022-01-17 21:20:42 user-5002-bucket
2022-01-17 21:20:42 user-5003-bucket

[root@rkomandu-app-node1 ~]# s3u5001 mb s3://newbukcet-18jan   --> **This is failing**
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://newbukcet-18jan Read timeout on endpoint URL: "https://10.17.127.178/newbukcet-18jan"

[root@rkomandu-app-node1 ~]# s3u5001 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2022-01-17 21:24:44 new-bucket-06jan
2022-01-17 21:24:44 new-bucket-user2-06jan
2022-01-17 21:24:44 new-bucket-5003-07jan
2022-01-17 21:24:44 newbucket-temp-1
2022-01-17 21:24:44 user-5001-bucket
2022-01-17 21:24:44 user-5002-bucket
2022-01-17 21:24:44 user-5003-bucket

Step 2: 
NAME                                               READY   STATUS    RESTARTS         AGE     IP              NODE                                  NOMINATED
NODE   READINESS GATES
noobaa-core-0                                      1/1     Running   0                7d16h   10.254.18.31    worker0.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-db-pg-0                                     1/1     Running   1 (5d10h ago)    6d18h   10.254.14.18    worker1.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-default-backing-store-noobaa-pod-a1bf952a   1/1     Running   0                7d17h   10.254.18.18    worker0.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-endpoint-bfffdd599-nq6b2                    1/1     Running   0                7d16h   10.254.13.28    worker1.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-endpoint-bfffdd599-pbjcw                    1/1     Running   0                5d20h   10.254.21.164   worker2.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-endpoint-bfffdd599-wlktz                    1/1     Running   0                7d18h   10.254.18.17    worker0.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>
noobaa-operator-5c46775cdd-fbl45                   1/1     Running   0                6d18h   10.254.14.15    worker1.rkomandu-ta.cp.fyre.ibm.com   <none>
       <none>

Step 3: Doesn't show in the noobaa endpoint 
sh-4.4# uname -a
Linux noobaa-endpoint-bfffdd599-nq6b2 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

sh-4.4# cd /nsfs/noobaa-s3res-4080029599/
sh-4.4# ls -l
total 9
drwxr-x---. 2 5001 9999 4096 Jan  6 06:11 new-bucket-06jan
drwxr-x---. 3 5003 9999 4096 Jan 11 10:55 new-bucket-5003-07jan
drwxr-x---. 3 5002 9999 4096 Jan  6 06:15 new-bucket-user2-06jan
drwxr-x---. 3 8091 9002 4096 Dec 16 13:14 newbucket-doesnot-have-newbucketspath
drwxr-x---. 3 8005 9999 4096 Dec 10 07:08 newbucket-s3user8005
drwxr-xr-x. 4 8092 9002 4096 Dec 17 04:45 pre-created-export-user
drwxrwxrwx. 3 root root 4096 Dec 10 01:44 primary-fileset-remote-sample-2591843568833441802
drwxrwx--x. 3 root root 4096 Dec 21 10:48 pvc-3e03cdb0-a374-4aed-bc3f-6e6f9ba74bca
drwxrwx--x. 3 root root 4096 Dec 21 10:51 pvc-bd59c318-dfd1-46e6-89f4-001bde1a34e5
drwxr-xr-x. 2 8003 9999 4096 Dec 10 06:37 s3user83-dir
drwxr-xr-x. 3 8006 9999 4096 Dec 10 07:16 s3user86-dir
drwxr-xr-x. 4 8007 9999 4096 Dec 16 09:43 s3user87-dir
drwxr-xr-x. 3 8008 9999 4096 Dec 14 13:35 s3user88-dir
drwxr-xr-x. 3 8009 9009 4096 Dec 16 10:31 s3user89-dir
drwxr-xr-x. 3 8090 9001 4096 Dec 16 12:24 s3user90-demo-dir
drwxr-x---. 3 5001 9999 4096 Jan 12 06:09 user-5001-bucket
drwxr-x---. 3 5002 9999 4096 Jan 12 06:08 user-5002-bucket
drwxr-x---. 3 5003 9999 4096 Jan 12 06:06 user-5003-bucket

Step 4: 

[root@api.rkomandu-ta.cp.fyre.ibm.com ~]# noobaa bucket list
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: bucket.list_buckets() Request: <nil>
WARN[0000] RPC: GetConnection creating connection to wss://localhost:34133/rpc/ 0xc0005f6fa0
INFO[0000] RPC: Connecting websocket (0xc0005f6fa0) &{RPC:0xc0005f71d0 Address:wss://localhost:34133/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0000] RPC: Connected websocket (0xc0005f6fa0) &{RPC:0xc0005f71d0 Address:wss://localhost:34133/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0000] ✅ RPC: bucket.list_buckets() Response OK: took 0.3ms

BUCKET-NAME
newbukcet-18jan   --> **this got created**
first.bucket
new-bucket-06jan
new-bucket-user2-06jan
new-bucket-5003-07jan
newbucket-temp-1
user-5001-bucket
user-5002-bucket
user-5003-bucket

Step 5: 

[root@api.rkomandu-ta.cp.fyre.ibm.com ~]# noobaa bucket status newbukcet-18jan
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: bucket.read_bucket() Request: {Name:newbukcet-18jan}
WARN[0000] RPC: GetConnection creating connection to wss://localhost:35765/rpc/ 0xc00009afa0
INFO[0000] RPC: Connecting websocket (0xc00009afa0) &{RPC:0xc0002c4c30 Address:wss://localhost:35765/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0000] RPC: Connected websocket (0xc00009afa0) &{RPC:0xc0002c4c30 Address:wss://localhost:35765/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0000] ✅ RPC: bucket.read_bucket() Response OK: took 1.1ms

Bucket status:
  Bucket                 : newbukcet-18jan
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : N/A
  Data Size              : N/A
  Data Size Reduced      : N/A
  Data Space Avail       : N/A

Step 6: Tried upload it fails

[root@rkomandu-app-node1 ~]# s3u5001 cp /bin/date s3://newbukcet-18jan
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.178'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ../bin/date to s3://newbukcet-18jan/date An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist

### More information - Screenshots / Logs / Other output

Noobaa-endpoint logs shows continuously 
-------------------------------------------------

[32mJan-13 18:56:13.125[35m [Endpoint/15] [31m[ERROR][39m core.server.system_services.system_store:: SystemStore: load failed Error: getaddrinfo ENOTFOUND noobaa-db-pg-0.noobaa-db-pg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[32mJan-13 18:56:13.125[35m [Endpoint/15] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv server_inter_process_api.update_master_change reqid 1@ws://[::ffff:10.254.13.28]:41176/(2s4dm09a6r) connid wss://noobaa-mgmt.openshift-storage.svc:443(2qkkbz7k1f) Error: getaddrinfo ENOTFOUND noobaa-db-pg-0.noobaa-db-pg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[32mJan-13 18:56:13.126[35m [Endpoint/15] [31m[ERROR][39m core.util.postgres_client:: postgres_client: T00000000|Q00415727: failed with error: Error: getaddrinfo ENOTFOUND noobaa-db-pg-0.noobaa-db-pg
[90m    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)[39m {
  errno: [33m-3008[39m,
  code: [32m'ENOTFOUND'[39m,
  syscall: [32m'getaddrinfo'[39m,
  hostname: [32m'noobaa-db-pg-0.noobaa-db-pg'[39m
}
[32mJan-13 18:56:13.126[35m [Endpoint/15] [31m[ERROR][39m core.util.postgres_client:: find failed { last_update: { [32m'$gte'[39m: [33m1642013250504[39m } } { projection: { last_update: [33m0[39m } } SELECT data #- '{last_update}' as data FROM namespace_resources WHERE data->'last_update'>='1642013250504'::jsonb Error: getaddrinfo ENOTFOUND noobaa-db-pg-0.noobaa-db-pg
[90m    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)[39m {
  errno: [33m-3008[39m,
  code: [32m'ENOTFOUND'[39m,
  syscall: [32m'getaddrinfo'[39m,
  hostname: [32m'noobaa-db-pg-0.noobaa-db-pg'[39m
}

Could you take a look at this defect..  Unable to upload as noobaa endpoint log is about 29MB.

**Comment by rkomandu** [comment]
@liranmauda added to this

**Comment by jeniawhite** [comment]
Looks similar https://github.com/noobaa/noobaa-core/issues/6622

**Comment by rkomandu** [comment]
Uploading the oc adm log file, noobaa db dump which Liran shared today 

@jeniawhite , @nimrod-becker FYI.. 

[noobaa-bucket-miss.tar.gz](https://github.com/noobaa/noobaa-core/files/7887853/noobaa-bucket-miss.tar.gz)
[noobaa-db-dump-file.gz](https://github.com/noobaa/noobaa-core/files/7887870/noobaa-db-dump-file.gz)

**Comment by rkomandu** [comment]
Today created new das account as shown below 

 mmdas account create s3user5006@in.ibm.com --uid 5006 --gid 9999 --newBucketsPath "/mnt/remote-sample/user-5006-bucket-19jan"
Something went wrong while processing the request.
Check 'ibm-spectrum-scale-das-endpoint' pod logs in 'ibm-spectrum-scale-das' namespace for more details
[root@api.rkomandu-ta.cp.fyre.ibm.com ~]# mmdas account list s3user5006@in.ibm.com

 Name                   UID     GID     Accesskey               Secretkey                                       New buckets path
 ----                   ---     ---     ---------               ---------                                       ----------------
 s3user5006@in.ibm.com  5006    9999    oWz8S4G53Djrf6xpSo2D    PcUJqa4d/KFIYYzuPkV2kXEVUr7dxSUSDKxt8JlZ        /mnt/remote-sample/user-5006-bucket-19jan/
[root@api.rkomandu-ta.cp.fyre.ibm.com ~]#
[root@api.rkomandu-ta.cp.fyre.ibm.com ~]#
[root@api.rkomandu-ta.cp.fyre.ibm.com ~]# mmdas account list

 Name                   UID     GID     New buckets path
 ----                   ---     ---     ----------------
 s3user5006@in.ibm.com  5006    9999    /mnt/remote-sample/user-5006-bucket-19jan/
 s3user5005@in.ibm.com  5005    9999    /mnt/remote-sample/
 s3user5004@in.ibm.com  5004    9999    /mnt/remote-sample/
 s3user5001@in.ibm.com  5001    9999    /mnt/remote-sample/
 s3user5002@in.ibm.com  5002    9999    /mnt/remote-sample/
 s3user5003@in.ibm.com  5003    9999    /mnt/remote-sample/

when creating bucket from this newly created user 

s3u5006 ls s3://
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.180'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2022-01-19 00:27:16 new-bucket-06jan
2022-01-19 00:27:16 new-bucket-user2-06jan
2022-01-19 00:27:16 new-bucket-5003-07jan
2022-01-19 00:27:16 newbucket-temp-1
2022-01-19 00:27:16 user-5001-bucket
2022-01-19 00:27:16 user-5002-bucket
2022-01-19 00:27:16 user-5003-bucket
[root@rkomandu-app-node1 ~]# s3u5006 mb s3://newbucket-5006user
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.180'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.180'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.127.180'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket failed: s3://newbucket-5006user Read timeout on endpoint URL: "https://10.17.127.180/newbucket-5006user"


IMO, something is wrong here as the buckets are not created and the users created displays an error message instead of the proper user creation message of Access Key and Secret Key

**Comment by rkomandu** [comment]
As noobaa db is un-responsive, unable to clean up the buckets as a result the system can't be cleaned for upgrading to 4.9.2

@jeniawhite @nimrod-becker , would someone interested to look at the Live system and try to get a workaround, so the user accounts and exports can be deleted in a proper manner.

**Comment by romayalon** [comment]
Hi @rkomandu,
The provided endpoint logs doesn't contain the bucket creation, although, I do see the creation of the db entry in the noobaa core pod logs.
Please provide logs of a reproduction with NSFS debug level up, I can not see where was the failure without it, and please check that the relevant logs exist there.

and regarding the DB, I see in logs that there are many issues with it, I think we should try reproduce it on a working system..

**Comment by rkomandu** [comment]
@romayalon , not sure why the noobaa-endpoint logs doesn't have the bucket creation. oc adm must-gather was collected and noobaa db dump is posted as per the command that was shared in Tue call. 

I can't provide now at the nsfs log level,  the system is now deleted in a brute-force method since DB was hung and deployed the 4.9.2. Waited for 2 days with the db-dump till today Noobaa interlock call before moving fwd. Checked with jenia and as per discussion he said there shouldn't be any problem for doing the upgrade to 4.9.2. 
As you know this system was working for the last 39days w/o any problem. 

Not sure what did you mean by working system. Added to that, how many days does it take to recreate also not sure

**Comment by rkomandu** [comment]
have posted today also the problem that it got created during our day time. Now the system is not at that level

**Comment by rkomandu** [comment]
you could try reproducing with the steps posted while defect opening on the ODF 4.9.0 RC 4/5 build.

**Comment by akmithal** [comment]
Hello @romayalon, Whatever I have understood, the steps aren't known for this defect recreate. This corruption happened whilst setup was running since few weeks. Just curious, wouldn't DB logs reflect cause of error. 

Hello @nimrod-becker , Would you recommend usage of default log level as "nsfs" as to avoid recreates in customer environments ? An older defect #6622 was also stuck as we were not able to reproduce this DB corruption.

**Comment by akmithal** [comment]
As @rkomandu pointed out, the namespace, catalogsource had to be deleted manually to come out of this stage, so it is a High Severity (but Medium Priority) bug and we would result in complete reconfiguration of customer environment. 

@nimrod-becker , What would you recommend on how to proceed on such defects ?

**Comment by nimrod-becker** [comment]
I don't see how cataloguesource is related, I understand it was deleted but probably not needed.

In any case, we can certainly run with higher debug levels, that would not emulate the real customer flows, and we must not test anything performance related with these runs. But for functional testing, sure

**Comment by romayalon** [comment]
@rkomandu @akmithal 
I tried to reproduce it on my env but as @akmithal I believe that the steps for the defect are unknown (my system is new and healthy), when did the DB start to not respond? I see that there were issues with the DB from January 13th.

Actually, even without the NSFS debug level, in the endpoint logs, just before the bucket folder creation, we should have a log print (debug log 0) with the following message: 'NamespaceFS: create_uls fs_account_config:' and it's missing.
In the core logs, the bucket creation started at Jan-18 5:20:54.388, and at the same time in the endpoint logs we can see the last log print at 5:20:41.987 and after only after 4 minutes we can see another print at 5:24:44.451. 
@jeniawhite are you familiar with this kind of issue?

**Comment by rkomandu** [comment]
> I don't see how cataloguesource is related, I understand it was deleted but probably not needed.
> 
> In any case, we can certainly run with higher debug levels, that would not emulate the real customer flows, and we must not test anything performance related with these runs. But for functional testing, sure

@nimrod-becker , We need to delete the complete Noobaa pods, DAS service and ODF cleaning.  So catalogsource is for ODF 4.9.0 RC4/5 from 9th Dec or so. I need to delete this as ODF has to be deleted and get to 4.9.2-X (d/s builds). The ODF instructions are followed to cleanup 

Let us know if there is a better process to come out of this state when the DB doesn't respond.

**Comment by akmithal** [comment]
[must-gather-0702_1.tar.gz](https://github.com/noobaa/noobaa-core/files/8015543/must-gather-0702_1.tar.gz)
[test_07feb.db.zip](https://github.com/noobaa/noobaa-core/files/8015556/test_07feb.db.zip)

**Comment by romayalon** [comment]
@rkomandu 
I was able to reproduce it after doing randomly IO operations/Creating a bucket.
On each reproduction, I see different DB operations that are getting stuck when they are being called from the endpoint pod. At the same time -  insert to the DB from the core pod is working fine (that is why we can see that the bucket entry was created in the DB).
when we reload the system store in the endpoint or when we update endpoint stats, after a while, we are not receiving an answer from the DB and the create bucket operation is stuck.

And regarding @akmithal as we discussed privately this is not a reproduction, the s3 tool you are using trying again to create the bucket before it got an answer from NooBaa, the thing we should understand here is if the s3 tool should wait a bit more because eventually, NooBaa will return an answer.

**Comment by romayalon** [comment]
@rkomandu I found an issue in that area of code, working on a fix that will hopefully fix this issue.

**Comment by akmithal** [comment]
Please keep it open for test validation @romayalon . We will close it post all related defects for this are closed. 

Please create a custom build till ODF 4.9.4-X version is created and mention the build version here for everyone's reference. Thanks.
