### ISSUE TITLE
CentOS 8 base image is EOL

### ISSUE THREAD

**Issue by DanielSel** [noobaa/noobaa-core#6865]
### Environment info
- NooBaa Version: **ALL**
- Platform: **NOT APPLICABLE**

### Actual behavior
CI builds fail because their CentOS 8 base image is EOL and package repository mirrors have been moved to archive.

### Expected behavior
CI builds succeed

### Steps to reproduce
Run `make tester`

### More information - Screenshots / Logs / Other output
```
> [ 2/11] RUN dnf update -y -q &&     dnf clean all:
#5 1.801 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

### Proposal
Switch to CentOS Stream 8 as base image: `quay.io/centos/centos:stream8`

**Comment by liranmauda** [comment]
Hi @DanielSel 
Thanks for pointing that out.

Can you please open a quick PR?

**Comment by DanielSel** [comment]
Done, PR: #6866
