### ISSUE TITLE
MD5 etag retrieval for list objects and other lists

### ISSUE THREAD

**Issue by jeniawhite** [noobaa/noobaa-core#6878]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Currently the MD5 etag is not getting queried upon listing of objects (we always return inode etag)
2. We can uncomment the below code and have it (with a performance hit, since it is not optimized)
```                // This is done to get the MD5 for the response, should find a more efficient way
                // r.fs_xattr = config.NSFS_CALCULATE_MD5 ? await this._get_fs_xattr_from_path(fs_account_config, entry_path) : undefined;
```
3. We can maybe use some FS caching for performance
4. Another option is not to use the same method for retrieval of xattrs (list and then get), and instead have a separate method for retrieval of md5 xattr (using single getxattr operation since we know the exact key that we want to query)

### Expected behavior
1. The list should return MD5 etag if it is chosen to be calculated by the system

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
I think gving a dedicated API to retrieve the list with all the needed data for the response would be the way to go

**Comment by guymguym** [comment]
@romayalon you meant this one?

**Comment by romayalon** [comment]
@guymguym yes

**Comment by nimrod-becker** [comment]
@jackyalbo fixed by you?
