### ISSUE TITLE
Noobaa endpoints spontaneously restart - 

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6887]
### Environment info
- NooBaa Version: 
[root@hpo-infra1 ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210923
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

[root@hpo-infra1 ~]# oc get csv
NAME                  DISPLAY                       VERSION   REPLACES              PHASE
mcg-operator.v4.9.3   NooBaa Operator               4.9.3     mcg-operator.v4.9.2   Succeeded
ocs-operator.v4.9.3   OpenShift Container Storage   4.9.3     ocs-operator.v4.9.2   Succeeded
odf-operator.v4.9.3   OpenShift Data Foundation     4.9.3     odf-operator.v4.9.2   Succeeded

### Actual behavior
1.  This is a noobbaa defect from the IBM HPO core github issue : https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/516
2. And it is discussed in Slack thread:  https://ibmandredhatguests.slack.com/archives/G015Z7SDWQ0/p1645034462674239

The must-gather information is documented in the github issue 516
It is in the infra-node for the Real World Tucson Bare Metal system in
Path: /root/GitIssues/516/

We were running workloads via crossbench and would see noobaa endpoints  restart.  We changed 3 things in the configuration of the noobaa endpoint pods.  
1.  We changed the CPU from 4 to 2
2. We changed the Memory from 4 Gig to 3 Gig
3. We are now running on 9 enpoint pods, which is 3 per worker node

We are not seeing any more with that but hope you can still investigate to determine cause.  Our customers are going to be changeing cpu, memory and different scaling of endpoint pods and we hope they do not encounter it.

### Expected behavior
Noobaa endpoint Pods do not restart

### Steps to reproduce
See mention above about configuration

**Comment by akmithal** [comment]
Hi @MonicaLemay , Noobaa team doesn't have access to our systems for log access. Please upload it here.

**Comment by kfir-payne** [comment]
Hi @MonicaLemay, receiving the must-gather would be very helpful to the investigation process.

In the Slack thread I saw you asked for a way to persist the endpoint pods labels, I managed to solve it by editing the endpoint deployment and setting the labels I want to persist there, any labels I added to the deployment were also added to new pods.

Regarding the env vars disappearing after the restarts, I ran the same command as you mentioned in the Slack thread 
`kubectl set env deployment/noobaa-endpoint TEST=false`
and deleted the endpoint pod, the deployment triggered a new pod creation, and the new endpoint pod had the env var `TEST`. we can schedule a meeting so I could better understand the behaviour you see.

**Comment by akmithal** [comment]
Hi @MonicaLemay , @kfir-payne Any update from either of you here please.

**Comment by MonicaLemay** [comment]
We have not hit this again.  I wonder if we should close it.

**Comment by nimrod-becker** [comment]
Have you run the exact same scenarios?

**Comment by CarlosInIBM** [comment]
> We have not hit this again. I wonder if we should close it.

I have.

**Comment by MonicaLemay** [comment]
I am closing issue

**Comment by MonicaLemay** [comment]
I did test w/ exact same workload.  Other testers also resport not seeing it anymore
