### ISSUE TITLE
30 endpoint replicas cause s3 mb command to fail on app nodes

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6888]
### Environment info

[root@hpo-infra1 GitIssues]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210923
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@hpo-infra1 GitIssues]# oc get csv
NAME                  DISPLAY                       VERSION   REPLACES              PHASE
mcg-operator.v4.9.3   NooBaa Operator               4.9.3     mcg-operator.v4.9.2   Succeeded
ocs-operator.v4.9.3   OpenShift Container Storage   4.9.3     ocs-operator.v4.9.2   Succeeded
odf-operator.v4.9.3   OpenShift Data Foundation     4.9.3     odf-operator.v4.9.2   Succeeded

This noobaa defect is being opened from HPO-Core defect:
https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514

I will paste some of the information from that defect into this one.

The s3 mb commands work until I increase replicas. I have not tested with other replica numbers but that should not matter. When I test with 30 replicas, the s3 make bucket on the app nodes fail with:

```
[root@hpo-app3 ~]# s3user3 mb s3://test1
make_bucket failed: s3://test1 An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation (reached max retries: 2): Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
[root@hpo-app3 ~]#
```

I edit the noobaa yaml to increase the number of endpoints:

```
[root@hpo-infra1 511]#  oc edit noobaa -n openshift-storage -o yaml
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  creationTimestamp: "2022-02-14T21:35:12Z"
  finalizers:
  - noobaa.io/graceful_finalizer
  generation: 8
  labels:
    app: noobaa
  name: noobaa
  namespace: openshift-storage
  resourceVersion: "12900245"
  uid: d78407e9-f528-4c40-b5de-4a974270d297
spec:
  cleanupPolicy: {}
  dbStorageClass: ibm-spectrum-scale-sample
  dbType: postgres
  endpoints:
    maxCount: 30
    minCount: 30
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
  image: noobaa/noobaa-core:5.9_nsfsfixes-20220208
  pvPoolDefaultStorageClass: ibm-spectrum-scale-sample
  security:
    kms: {}
status:
  accounts:
    admin:
      secretRef:
        name: noobaa-admin
        namespace: openshift-storage
  actualImage: noobaa/noobaa-core:5.9_nsfsfixes-20220208
  conditions:
  - lastHeartbeatTime: "2022-02-14T21:35:12Z"
    lastTransitionTime: "2022-02-15T17:37:15Z"
    message: noobaa operator completed reconcile - system is ready
    reason: SystemPhaseReady
    status: "True"
    type: Available
  - lastHeartbeatTime: "2022-02-14T21:35:12Z"
    lastTransitionTime: "2022-02-15T17:37:15Z"
    message: noobaa operator completed reconcile - system is ready
    reason: SystemPhaseReady
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2022-02-14T21:35:12Z"
    lastTransitionTime: "2022-02-14T21:35:12Z"
    message: noobaa operator completed reconcile - system is ready
    reason: SystemPhaseReady
    status: "False"
    type: Degraded
  - lastHeartbeatTime: "2022-02-14T21:35:12Z"
    lastTransitionTime: "2022-02-15T17:37:15Z"
    message: noobaa operator completed reconcile - system is ready
    reason: SystemPhaseReady
    status: "True"
    type: Upgradeable
  endpoints:
    readyCount: 3
    virtualHosts:
    - s3.openshift-storage.svc
  observedGeneration: 7
  phase: Ready
  readme: "\n\n\tWelcome to NooBaa!\n\t-----------------\n\tNooBaa Core Version:     5.9.2-eef7dc2\n\tNooBaa
    Operator Version: 5.9.2\n\n\tLets get started:\n\n\t1. Connect to Management console:\n\n\t\tRead
    your mgmt console login information (email & password) from secret: \"noobaa-admin\".\n\n\t\t\tkubectl
    get secret noobaa-admin -n openshift-storage -o json | jq '.data|map_values(@base64d)'\n\n\t\tOpen
    the management console service - take External IP/DNS or Node Port or use port
    forwarding:\n\n\t\t\tkubectl port-forward -n openshift-storage service/noobaa-mgmt
    11443:443 &\n\t\t\topen https://localhost:11443\n\n\t2. Test S3 client:\n\n\t\tkubectl
    port-forward -n openshift-storage service/s3 10443:443 &\n\t\tNOOBAA_ACCESS_KEY=$(kubectl
    get secret noobaa-admin -n openshift-storage -o json | jq -r '.data.AWS_ACCESS_KEY_ID|@base64d')\n\t\tNOOBAA_SECRET_KEY=$(kubectl
    get secret noobaa-admin -n openshift-storage -o json | jq -r '.data.AWS_SECRET_ACCESS_KEY|@base64d')\n\t\talias
    s3='AWS_ACCESS_KEY_ID=$NOOBAA_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$NOOBAA_SECRET_KEY
    aws --endpoint https://localhost:10443 --no-verify-ssl s3'\n\t\ts3 ls\n\n"
  services:
    serviceMgmt:
      externalDNS:
      - https://noobaa-mgmt-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com
      internalDNS:
      - https://noobaa-mgmt.openshift-storage.svc:443
      internalIP:
      - https://172.30.225.251:443
      nodePorts:
      - https://192.168.7.34:32545
      podPorts:
      - https://10.128.1.79:8443
    serviceS3:
      externalDNS:
      - https://s3-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com
      internalDNS:
      - https://s3.openshift-storage.svc:443
      internalIP:
      - https://172.30.20.198:443
      nodePorts:
      - https://192.168.7.34:30741
      - https://192.168.7.33:30741
      - https://192.168.7.32:30741
      podPorts:
      - https://10.128.1.96:6443
      - https://10.128.4.43:6443
      - https://10.128.3.151:6443
  upgradePhase: NoUpgrade
[root@hpo-infra1 511]#

```

After this, I can see that I have 30 endpoints

```
[root@hpo-infra1 511]# oc get pods --show-labels  -o wide | grep Running | grep -c endpoint
30
```

All 30 nodes are labeled correctly. I'm not pasting all 30. This is just a sample:

```
[root@hpo-infra1 511]# oc get pods --show-labels  -o wide | grep endpoint
noobaa-endpoint-7867bf6f5f-6fwgg                   1/1     Running   0               9m51s   10.128.3.171   hpo-dan1.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan1.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7867bf6f5f
noobaa-endpoint-7867bf6f5f-6wtg8                   1/1     Running   0               52m     10.128.4.43    hpo-dan2.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan2.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7867bf6f5f
noobaa-endpoint-7867bf6f5f-7dzg2                   1/1     Running   0               9m51s   10.128.3.177   hpo-dan1.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan1.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7867bf6f5f
noobaa-endpoint-7867bf6f5f-7fw9n                   1/1     Running   0               9m51s   10.128.1.118   hpo-dan3.hpoocp4.tuc.stglabs.ibm.com   <none>    

```

When I issue the make bucket, the bucket does not get created, but the export gets created on the HPO cluster.

```
[root@hpo-app3 ~]# s3user3 mb s3://test1
make_bucket failed: s3://test1 An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation (reached max retries: 2): Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
[root@hpo-app3 ~]#
```

On the HPO cluster:

```
[root@hpo-infra1 511]# mmdas export list | grep test
 test1
```

On the storage cluster there is no bucket:

```
[root@emshpo hpofs1]# ls -ail s5003
total 257
199684 drwxr-xr-x.  2 5003 5003   4096 Feb 15  2022 .
     3 drwxrwxrwx. 10 root root 262144 Feb 14 17:45 ..
[root@emshpo hpofs1]#

```
noobaa status:

[root@hpo-infra1 511]# noobaa status
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.9_nsfsfixes-20220208
INFO[0000] operator-image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:773dbaded46fa0a024c28a92f98f4ad64d370011ed1405f2b16f39b9258eb6b2
INFO[0000] noobaa-db-image: quay.io/rhceph-dev/rhel8-postgresql-12@sha256:da0b8d525b173ef472ff4c71fae60b396f518860d6313c4f3287b844aab6d622
INFO[0000] Namespace: openshift-storage
INFO[0000]
INFO[0000] CRD Status:
INFO[0000] ✅ Exists: CustomResourceDefinition "noobaas.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "backingstores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "namespacestores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "bucketclasses.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbucketclaims.objectbucket.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbuckets.objectbucket.io"
INFO[0000]
INFO[0000] Operator Status:
INFO[0000] ✅ Exists: Namespace "openshift-storage"
INFO[0000] ✅ Exists: ServiceAccount "noobaa"
INFO[0000] ✅ Exists: ServiceAccount "noobaa-endpoint"
INFO[0000] ✅ Exists: Role "mcg-operator.v4.9.3-noobaa-7fdbb75fd7"
INFO[0000] ✅ Exists: Role "mcg-operator.v4.9.3-noobaa-endpoint-65854bfccb"
INFO[0000] ✅ Exists: RoleBinding "mcg-operator.v4.9.3-noobaa-7fdbb75fd7"
INFO[0000] ✅ Exists: RoleBinding "mcg-operator.v4.9.3-noobaa-endpoint-65854bfccb"
INFO[0000] ✅ Exists: ClusterRole "mcg-operator.v4.9.3-644558fccd"
INFO[0000] ✅ Exists: ClusterRoleBinding "mcg-operator.v4.9.3-644558fccd"
INFO[0000] ✅ Exists: Deployment "noobaa-operator"
INFO[0000]
INFO[0000] System Wait Ready:
INFO[0000] ✅ System Phase is "Ready".
INFO[0000]
INFO[0000]
INFO[0000] System Status:
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: StatefulSet "noobaa-core"
INFO[0000] ✅ Exists: ConfigMap "noobaa-config"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Service "s3"
INFO[0000] ✅ Exists: Secret "noobaa-db"
INFO[0000] ✅ Exists: ConfigMap "noobaa-postgres-config"
INFO[0000] ✅ Exists: StatefulSet "noobaa-db-pg"
INFO[0000] ✅ Exists: Service "noobaa-db-pg"
INFO[0000] ✅ Exists: Secret "noobaa-server"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-endpoints"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✅ Exists: Secret "noobaa-root-master-key"
INFO[0000] ✅ Exists: StorageClass "openshift-storage.noobaa.io"
INFO[0000] ✅ Exists: BucketClass "noobaa-default-bucket-class"
INFO[0000] ✅ Exists: Deployment "noobaa-endpoint"
INFO[0000] ✅ Exists: HorizontalPodAutoscaler "noobaa-endpoint"
INFO[0000] ✅ (Optional) Exists: BackingStore "noobaa-default-backing-store"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-aws-cloud-creds"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-azure-cloud-creds"
INFO[0000] ⬛ (Optional) Not Found: Secret "noobaa-azure-container-creds"
INFO[0000] ⬛ (Optional) Not Found: Secret "noobaa-gcp-bucket-creds"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-gcp-cloud-creds"
INFO[0000] ✅ (Optional) Exists: PrometheusRule "noobaa-prometheus-rules"
INFO[0000] ✅ (Optional) Exists: ServiceMonitor "noobaa-mgmt-service-monitor"
INFO[0000] ✅ (Optional) Exists: ServiceMonitor "s3-service-monitor"
INFO[0001] ✅ (Optional) Exists: Route "noobaa-mgmt"
INFO[0001] ✅ (Optional) Exists: Route "s3"
INFO[0001] ✅ Exists: PersistentVolumeClaim "db-noobaa-db-pg-0"
INFO[0001] ✅ System Phase is "Ready"
INFO[0001] ✅ Exists:  "noobaa-admin"

#------------------#
#- Mgmt Addresses -#
#------------------#

ExternalDNS : [https://noobaa-mgmt-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com]
ExternalIP  : []
NodePorts   : [https://192.168.7.34:32545]
InternalDNS : [https://noobaa-mgmt.openshift-storage.svc:443]
InternalIP  : [https://172.30.225.251:443]
PodPorts    : [https://10.128.1.79:8443]

#--------------------#
#- Mgmt Credentials -#
#--------------------#

email    : admin@noobaa.io
password : 1o1MQwL+yRDAsSRF/9Rh0g==

#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [https://s3-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com]
ExternalIP  : []
NodePorts   : [https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.33:30741 https://192.168.7.34:30741 https://192.168.7.33:30741 https://192.168.7.32:30741 https://192.168.7.32:30741 https://192.168.7.34:30741 https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.34:30741 https://192.168.7.32:30741 https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.32:30741 https://192.168.7.33:30741 https://192.168.7.34:30741 https://192.168.7.34:30741 https://192.168.7.33:30741 https://192.168.7.34:30741 https://192.168.7.33:30741 https://192.168.7.34:30741 https://192.168.7.34:30741 https://192.168.7.34:30741 https://192.168.7.32:30741 https://192.168.7.34:30741]
InternalDNS : [https://s3.openshift-storage.svc:443]
InternalIP  : [https://172.30.20.198:443]
PodPorts    : [https://10.128.3.176:6443 https://10.128.4.43:6443 https://10.128.4.59:6443 https://10.128.1.117:6443 https://10.128.4.66:6443 https://10.128.3.171:6443 https://10.128.3.169:6443 https://10.128.1.116:6443 https://10.128.3.175:6443 https://10.128.4.62:6443 https://10.128.3.172:6443 https://10.128.4.64:6443 https://10.128.3.170:6443 https://10.128.4.58:6443 https://10.128.1.114:6443 https://10.128.3.151:6443 https://10.128.3.177:6443 https://10.128.4.65:6443 https://10.128.3.174:6443 https://10.128.4.63:6443 https://10.128.1.115:6443 https://10.128.1.96:6443 https://10.128.4.60:6443 https://10.128.1.121:6443 https://10.128.4.61:6443 https://10.128.1.120:6443 https://10.128.1.118:6443 https://10.128.1.119:6443 https://10.128.3.173:6443 https://10.128.1.122:6443]

#------------------#
#- S3 Credentials -#
#------------------#

AWS_ACCESS_KEY_ID     : pw2m6ClsFzB2aAgDk09D
AWS_SECRET_ACCESS_KEY : sMWD5Dny6bFzOmGVAMcX2wq2FGRXCCqihK1UPeqZ

#------------------#
#- Backing Stores -#
#------------------#

NAME                           TYPE      TARGET-BUCKET   PHASE   AGE
noobaa-default-backing-store   pv-pool                   Ready   20h7m17s

#------------------#
#- Bucket Classes -#
#------------------#

NAME                          PLACEMENT                                                        NAMESPACE-POLICY   PHASE   AGE
noobaa-default-bucket-class   {"tiers":[{"backingStores":["noobaa-default-backing-store"]}]}   null               Ready   20h7m45s

#-----------------#
#- Bucket Claims -#
#-----------------#

No OBCs found.

When I go back to 3 replicas, it takes about 10 minutes and then the make bucket (mb) works again.

must-gather will be in this box note labeled with HPO core issue number 514 AND This noobaa issue number.
Your environment

Real world bare metal Tucson Cluster
[root@hpo-infra1 513]# oc get csv
NAME DISPLAY VERSION REPLACES PHASE
mcg-operator.v4.9.3 NooBaa Operator 4.9.3 mcg-operator.v4.9.2 Succeeded
ocs-operator.v4.9.3 OpenShift Container Storage 4.9.3 ocs-operator.v4.9.2 Succeeded
odf-operator.v4.9.3 OpenShift Data Foundation 4.9.3 odf-operator.v4.9.2 Succeeded
[root@hpo-infra1 513]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210923
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@hpo-infra1 513]#
Steps to reproduce

There is a SLACK thread talking about using the mmdas command rather than ediiting the yaml
As mentioned in the slack thread https://ibm-systems-storage.slack.com/archives/G01E6MCPS9Z/p1644986106353199?thread_ts=1644947852.918549&cid=G01E6MCPS9Z

In the Noobaa defect 6856 (https://github.com/noobaa/noobaa-core/issues/6856) , please see Akshat post (https://github.com/noobaa/noobaa-core/issues/6856#issuecomment-1031455323[](https://github.ibm.com/nilesh-bhosale)) and Reply from Romy

And regarding @akmithal as we discussed privately this is not a reproduction, the s3 tool you are using trying again to create the bucket before it got an answer from NooBaa, the thing we should understand here is if the s3 tool should wait a bit more because eventually, NooBaa will return an answer.
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale)
nilesh-bhosale commented [7 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40642012)

@moki[](https://github.ibm.com/nilesh-bhosale) , we need to always use the DAS interfaces to change the config and not directly edit k8s entities ... like edit deployment / noobaa CR.
There is some work-flow that DAS executes to lay out the changes properly.
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale)
nilesh-bhosale commented [7 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40642080)

After the above disccussion, I was able to reproduce the exact same problem via mmdas command

```
[root@hpo-infra1 522]# date; mmdas service update s3 --scaleFactor 10 ; date
Fri Feb 18 11:49:54 MST 2022
Update request for Spectrum Scale Data Access Service: 's3' is accepted
Fri Feb 18 11:49:59 MST 2022
[root@hpo-infra1 522]#

```

On the application node with only 3 endpoints:

```
[root@hpo-app3 ~]# alias s5001='AWS_ACCESS_KEY_ID=PfFh820PPA1hspt4Srch AWS_SECRET_ACCESS_KEY=qpiI1XrSwFVXApCYe18oRTH35y/MDAnlUWokpHKw aws --endpoint http://10.49.0.100  --no-verify-ssl s3'
[root@hpo-app3 ~]# s5001 ls
[root@hpo-app3 ~]# s5001 mb s3://s5001b1
make_bucket: s5001b1
[root@hpo-app3 ~]# s5001 rb s3://s5001b1
remove_bucket: s5001b1

```
Now after 30 endpoints:

```
[root@hpo-app3 ~]# s5001 mb s3://s5001b1
make_bucket failed: s3://s5001b1 An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
[root@hpo-app3 ~]# s5001 mb s3://s5001b2
make_bucket failed: s3://s5001b2 An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation (reached max retries: 2): Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
[root@hpo-app3 ~]# echo $?
1
```
```
[root@hpo-app3 ~]# s5001 mb s3://s5001newname
make_bucket failed: s3://s5001newname An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation (reached max retries: 2): Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
[root@hpo-app3 ~]# echo $?
1
```
On the openshift cluster, the exports get created.

```
[root@hpo-infra1 tests]# mmdas export list

 Name
 ------
 s5001newname
 s5001b2
 s5001b1
```
However on the storage cluster, there are no new directories for the buckets:
```
[root@emshpo s5001]# ls -ail
total 272
199681 drwxr-xr-x.  2 5001 5001  16384 Feb 18  2022 .
     3 drwxrwxrwx. 10 root root 262144 Feb 14 17:45 ..
[root@emshpo s5001]#
```
@[moki](https://github.ibm.com/moki)
Author
moki commented [5 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40728278)[](https://github.ibm.com/moki)

Things are really strange on cleanup of the exports

```
[root@hpo-infra1 tests]# mmdas export list

 Name
 ------
 s5001newname
 s5001b2
 s5001b1
 ```
 ```
[root@hpo-infra1 tests]# mmdas export delete s5001newname
sorry, too many clients already
[root@hpo-infra1 tests]# mmdas export delete s5001b2
sorry, too many clients already
[root@hpo-infra1 tests]# mmdas export delete s5001b1
sorry, too many clients already
[root@hpo-infra1 tests]# mmdas export list
No Exports Available
[root@hpo-infra1 tests]#
```
@[moki](https://github.ibm.com/moki)
Author
moki commented [5 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40729528)[](https://github.ibm.com/nilesh-bhosale)

I am able to get 9 endpoints to work correctly.
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale) nilesh-bhosale added the [Noobaa defect](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/Noobaa%20defect) label [3 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#event-205305781)[](https://github.ibm.com/nilesh-bhosale)
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale)
nilesh-bhosale commented [3 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40751375)[](https://github.ibm.com/nilesh-bhosale)

This should not be based on the number of endpoints, IMO. Anyway, this is on the IO path, and IO path directly is handled by Noobaa (HPO pieces mmdas CLI/REST API is only on the control path, that too calling in Noobaa RPCs or controlpath APIs in the backend).
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale)
nilesh-bhosale commented [3 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40751393)

@moki , @akmithal[](https://github.ibm.com/TROPPENS) ,please open this defect against noobaa-core. If it's easily reproducible, just by changing the number of replicas / scaleFactor from 9 to 10 and the issue starts showing up, that would be a good input to nail down the root cause, to noobaa dev team.
@[TROPPENS](https://github.ibm.com/TROPPENS)
TROPPENS commented [3 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40758812)

@akmithal - please take the lead on the interaction with Red Hat NooBaa team, e.g., open the bug against noobaa-core, review in in the interlock calls with them, get additional logs from @moki[](https://github.ibm.com/rkomandu) if needed.
@[rkomandu](https://github.ibm.com/rkomandu)
rkomandu commented [2 days ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40772872)

@akmithal[](https://github.ibm.com/TROPPENS)
Did you get a chance to open a new defect for the "BucketsOwnedByYou" defect to be removed from the Noobaa-core GH 6856 ?

Brought this up with Romy on the 17th Feb Noobaa Interlock call, where she says the same thing, that it needs investigation from your side. Reason for this is s3 is trying to create the bucket , Noobaa didn't respond in that stipulated time.

Please discuss with Romy on the next steps. ASAIU, this one needs to investigate further from the timing perspective.
@[TROPPENS](https://github.ibm.com/TROPPENS)
TROPPENS commented [6 hours ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/514#issuecomment-40845978)

@akmithal @cxhong @moki[](https://github.ibm.com/moki) - What is the NooBaa issue number for this HPO issue?
@moki
### Actual behavior
1.  See notes above. Sorry for the mess.  It is difficult to move defects between git repos and maintain all of the info

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by romayalon** [comment]
As an initial screen I see many Postgres issues reporting on:
``` 
1. sorry, too many clients already
2. Error: publish_to_cluster: disconnect on error sorry, too many clients already
3.  disconnect on error remaining connection slots are reserved for non-replication superuser connections
4.  error: duplicate key value violates unique constraint "idx_btree_buckets_system_name" 
     "Key ((data ->> 'system'::text), (data ->> 'name'::text))=(620acb462b5a670029f5d743, test1) already exists." 
```

Also, many of the endpoints report these issues and can't even load any data from the DB.

**Comment by romayalon** [comment]
@MonicaLemay 
Please next time, if you could try to minimize the endpoint pods to the minimal amount that you still see the problem it'll be the best for us, investigating 30 different endpoint logs is taking a lot of time.

**Comment by rkomandu** [comment]
@nimrod-becker or @romayalon , please add the NSFS label. 
I don't see this defect is assigned atm

**Comment by romayalon** [comment]
@MonicaLemay We increased the number of connections allowed in the latest build, can you try to reproduce it, please?

**Comment by MonicaLemay** [comment]
I'm waiting for the patch.  I think Akshat  needs to build the noobaa patch for RW

**Comment by akmithal** [comment]
Hi @MonicaLemay , Please update on the run results here with the latest custom build. Thanks. If it is working, please close.

**Comment by MonicaLemay** [comment]
I have the noobaa patch and am not seeing this.  Willing to close.  Please let me know if you need something else.
