### ISSUE TITLE
mmdas creating multiple accounts fails with sorry, too many clients already and s3 mb fails with max retries

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6889]
### Environment info
root@c83f1-infa mokinew]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20211214
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@c83f1-infa mokinew]#

[root@c83f1-infa mokinew]# oc get csv
NAME                  DISPLAY                       VERSION   REPLACES              PHASE
mcg-operator.v4.9.3   NooBaa Operator               4.9.3     mcg-operator.v4.9.2   Succeeded
ocs-operator.v4.9.3   OpenShift Container Storage   4.9.3     ocs-operator.v4.9.2   Succeeded
odf-operator.v4.9.3   OpenShift Data Foundation     4.9.3     odf-operator.v4.9.2   Succeeded
[root@c83f1-infa mokinew]#
### Actual behavior

This is a defect opened from HPO core defect 
https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/538

This information is copied from HPO 538 defect.

On the storage cluster, 10 directories are created, chown'ed and chmod'ed:s5001 - s50010.

Then, I have a script to make 10 users.

#!/bin/sh
for I in {1..10}
do
mmdas account create s500${I} --gid 500${I} --uid 500${I} --newBucketsPath /mnt/hpofs1/s500${I}
done

It fails

[root@c83f1-infa RW_moki]# ./make_account.sh
sorry, too many clients already
sorry, too many clients already
sorry, too many clients already
sorry, too many clients already
remaining connection slots are reserved for non-replication superuser connections
sorry, too many clients already
sorry, too many clients already
sorry, too many clients already
sorry, too many clients already
sorry, too many clients already
[root@c83f1-infa RW_moki]#

The accounts are created

[root@c83f1-infa RW_moki]# mmdas account list

 Name		UID	GID	New buckets path
 ----		---	---	----------------
 s50010		50010	50010	/mnt/hpofs1/s50010/
 s5009		5009	5009	/mnt/hpofs1/s5009/
 s5008		5008	5008	/mnt/hpofs1/s5008/
 s5007		5007	5007	/mnt/hpofs1/s5007/
 s5006		5006	5006	/mnt/hpofs1/s5006/
 s5005		5005	5005	/mnt/hpofs1/s5005/
 s5004		5004	5004	/mnt/hpofs1/s5004/
 s5003		5003	5003	/mnt/hpofs1/s5003/
 s5002		5002	5002	/mnt/hpofs1/s5002/
 s5001		5001	5001	/mnt/hpofs1/s5001/
 newuser	3000	3000	/mnt/hpofs1/newDir/
[root@c83f1-infa RW_moki]#

 
On the application node, mb fails even though ls can connect:

root@c83f1-dan4 RW_workloads]# s50010 mb s3://s50010b1
make_bucket failed: s3://s50010b1 An error occurred (InternalError) when calling the CreateBucket operation (reached max retries: 2): We encountered an internal error. Please try again.

There are 2 sets of logs: noobaa diagnostics, must-gather for ocs and must-gather for odf.
The first set are before the make bucket (mb) was attempted. The latter set was after the mb was attempted. They will be in the box note
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6to[](https://github.ibm.com/moki)
Labeled with the HPO number and if noobaa openend then with both numbers
Your environment

[root@c83f1-infa RW_[moki](https://github.ibm.com/moki)]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20211214
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@c83f1-infa RW_moki]# oc get csv
NAME DISPLAY VERSION REPLACES PHASE
mcg-operator.v4.9.3 NooBaa Operator 4.9.3 mcg-operator.v4.9.2 Succeeded
ocs-operator.v4.9.3 OpenShift Container Storage 4.9.3 ocs-operator.v4.9.2 Succeeded
odf-operator.v4.9.3 OpenShift Data Foundation 4.9.3 odf-operator.v4.9.2 Succeeded
[root@c83f1-infa RW_moki]#

This is on the POK real fast cluster that was turned over to RW. It has 30 endpoint logs (replication of 10) and CPU 4 and Memory 4
Steps to reproduce

See above
Expected behaviour
@moki moki assigned [cxhong](https://github.ibm.com/cxhong) [20 hours ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/538#event-205797169)[](https://github.ibm.com/moki)
@[moki](https://github.ibm.com/moki) moki added [Customer Impact: Localized high impact](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/Customer%20Impact%3A%20Localized%20high%20impact) [Customer Probability: Medium](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/Customer%20Probability%3A%20Medium) [RealWorld](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/RealWorld) [Severity: 2](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/Severity%3A%202) [Type: Bug](https://github.ibm.com/IBMSpectrumScale/hpo-core/labels/Type%3A%20Bug) labels [20 hours ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/538#event-205797242)[](https://github.ibm.com/nilesh-bhosale)
@[nilesh-bhosale](https://github.ibm.com/nilesh-bhosale)
nilesh-bhosale commented [8 hours ago](https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/538#issuecomment-40887502)[](https://github.ibm.com/nilesh-bhosale)

Looks like we are mixing 2 issues here.
Regarding the first:

[root@c83f1-infa RW_moki]# ./make_account.sh
sorry, too many clients already
sorry, too many clients already

This looks like an error coming from Postgres SQL database.
I see the max db connections allowed at a time = 300

# oc rsh noobaa-db-pg-0
Defaulted container "db" out of: db, init (init), initialize-database (init)
sh-4.4$ psql
psql (12.9)
Type "help" for help.

postgres=# show max_connections;
 max_connections
-----------------
 300
(1 row)

postgres=#

Since this is handled by noobaa-db pod, Noobaa team needs to look further on this.

Also, the second issue:

root@c83f1-dan4 RW_workloads]# s50010 mb s3://s50010b1
make_bucket failed: s3://s50010b1 An error occurred (InternalError) when calling the CreateBucket operation (reached max retries: 2): We encountered an internal error. Please try again.

This is also on IO path, so Noobaa team needs to help.
@nilesh-bhosale

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by romayalon** [comment]
seems the same as https://github.com/noobaa/noobaa-core/issues/6888

**Comment by akmithal** [comment]
@romayalon please mark it as duplicate.  We can close one of these then.
 @MonicaLemay , if you disagree, please highlight.

**Comment by romayalon** [comment]
closing as a dup of #6888
