### ISSUE TITLE
ERROR srv object_api.list_objects_admin reqid TypeError: Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by AlfadilTabar** [noobaa/noobaa-core#6890]
### Environment info
noobaa-image: registry.redhat.io/ocs4/mcg-core-rhel8@sha256:36987f088016043c13f73ba3cb6be07330a8e3819dc88b25d3815ecbcaa0795b 
operator-image: registry.redhat.io/ocs4/mcg-rhel8-operator@sha256:ef4c5e6b1ac33106ae44cd5778ff04ae0bc02f103b426deafeba91083db99acd 
noobaa-db-image: registry.redhat.io/rhscl/mongodb-36-rhel7@sha256:ffc67a5d76944cbb073862a61b9928400bb948ca0cb220d6718116b9f5637c24 

- Platform: **OpenShift 4.7**

### Actual behavior
can't see bucket's objects
### Expected behavior
be able to see bucket's objects

### More information - Screenshots / Logs / Other output

at should_proxy (/root/node_modules/noobaa-core/src/util/http_utils.js:352:52)
    at _get_http_agent (/root/node_modules/noobaa-core/src/util/http_utils.js:394:30)
    at Object.get_unsecured_agent (/root/node_modules/noobaa-core/src/util/http_utils.js:376:12)
    at Object.get_signed_url (/root/node_modules/noobaa-core/src/util/cloud_utils.js:39:31)
    at /root/node_modules/noobaa-core/src/server/object_services/object_server.js:1209:49
    at arrayMap (/root/node_modules/noobaa-core/node_modules/lodash/lodash.js:639:23)
    at Function.map (/root/node_modules/noobaa-core/node_modules/lodash/lodash.js:9580:14)
    at Object.list_objects_admin (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1199:28)

**Comment by nimrod-becker** [comment]
@AlfadilTabar thanks for reporting this, however ee'll need more information,
logs, what exactly are you running (a code sample to the command would be great)

**Comment by AlfadilTabar** [comment]
@

> @AlfadilTabar thanks for reporting this, however ee'll need more information, logs, what exactly are you running (a code sample to the command would be great)

I'm running noobaa on openshift, I added some objects to the bucket.
I can see the objects with s3 cli.
I can not see the objects with noobaa management ui.
it shows me 
 core.rpc.rpc:: RPC._request: response ERROR srv object_api.list_objects_admin params { bucket: '*********************',  key_query: '',  sort: 'key',  order: 1,  skip: 0,  limit: 25,  pagination: true,  upload_mode: undefined,  latest_versions: true,  filter_delete_markers: true,  adminfo: { signed_url_endpoint: 'noobaa-mgmt-openshift-storage.*************'

**Comment by AlfadilTabar** [comment]
@nimrod-becker any help please

**Comment by AlfadilTabar** [comment]
@nimrod-becker thanks for your reply.
