### ISSUE TITLE
4.9.4.5 RC code is unusable for metal-lb. 

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6897]
### Environment info
- NooBaa Version: ODF - 4.9.4.5
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. latest-stable-4.9.4 (4.9.4.-5) RC code is not letting us configure metallb IP's

### Expected behavior
1. metal-lb pods should work well.

### Steps to reproduce
1. Install latest-stable-4.9.4 code 
2. Metal-LB namespace pods don't come up. 

4.9.3-2 code works very well with metal-lb. When I changed config back to 4.9.3-2, the code started working well. 

This is a regression. FYI @nimrod-becker , @romayalon

**Comment by nimrod-becker** [comment]
Not a NooBaa issue, closing and communicating with the necessary team
