### ISSUE TITLE
HPO 577:  Noobaa premature close

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6906]
This is from HPO 577
Doing a cosbench test with gigabyte files, I get write errors:
Because of noobaa issue 6896, I was asked to change log level to “nsfs”. In the process of trying to create 6896, I hit this.

Cosbenchnow does md5.

 I am not sure if md5 and logging level is cause or recipe for this new problem that I am describing here.  

In my Cosbench run, I see many of these: 2022-03-09 09:35:50,423 [WARN] [S3Storage] - below exception encountered when creating object s5009o1_rGB at s5009b1:
2022-03-09 09:35:50,423 [WARN] [S3Storage] - below exception encountered when creating object s5009o1_rGB at s5009b1:
2022-03-09 09:35:50,445 [WARN] [S3Storage] - below exception encountered when creating object s5009o2_rGB at s5009b2:
2022-03-09 09:35:50,445 [WARN] [S3Storage] - below exception encountered when creating object s5009o2_rGB at s5009b2:
2022-03-09 09:35:50,445 [WARN] [S3Storage] - below exception encountered when creating object s5009o2_rGB at s5009b2:

When I look in the endpoint pod logs, I see many of this
Mar-9 14:35:50.642 [Endpoint/15] [L1] core.util.http_utils:: HTTP REPLY EMPTY PUT /s5009b1/s5009o1_rGB {"host":"metallb","authorization":"AWS tzO3778Ut1Y4O9ncWYFu:YToPHPutvWNffIVVsCwEb+36vS0=","user-agent":"aws-sdk-java/1.10.76 Linux/4.18.0-240.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.265-b01/1.8.0_265","amz-sdk-invocation-id":"7f51ed26-2e81-4eda-bc88-8e5e6da8aed1","amz-sdk-retry":"0/0/","date":"Wed, 09 Mar 2022 14:10:45 GMT","content-type":"application/octet-stream","content-length":"5000000000","connection":"Keep-Alive"} 200

Followed by many of these:
oc logs noobaa-endpoint-59f969cd76-2csw5
Mar-9 14:35:52.156 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR InternalErrorWe encountered an internal error. Please try again./s5009b1/s5009o1_rGBl0jnnesx-eeb5id-duz PUT /s5009b1/s5009o1_rGB {"host":"metallb","authorization":"AWS tzO3778Ut1Y4O9ncWYFu:ryZKebfGAUJREWUwiQFU5Uormew=","user-agent":"aws-sdk-java/1.10.76 Linux/4.18.0-240.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.265-b01/1.8.0_265","amz-sdk-invocation-id":"3f2555a6-b588-4d7c-97ee-3c51a7d4f847","amz-sdk-retry":"0/0/","date":"Wed, 09 Mar 2022 14:27:06 GMT","content-type":"application/octet-stream","content-length":"8000000000","connection":"Keep-Alive"} Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
Mar-9 14:35:52.237 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR InternalErrorWe encountered an internal error. Please try again./s5009b1/s5009o1_rGBl0jnk6t6-8zd8sj-ixz PUT /s5009b1/s5009o1_rGB {"host":"metallb","authorization":"AWS tzO3778Ut1Y4O9ncWYFu:4NijTbUw2geXR6YYFEtafR8nS6I=","user-agent":"aws-sdk-java/1.10.76 Linux/4.18.0-240.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.265-b01/1.8.0_265","amz-sdk-invocation-id":"1f1797da-b321-49f4-8855-45e816a50603","amz-sdk-retry":"0/0/","date":"Wed, 09 Mar 2022 14:24:36 GMT","content-type":"application/octet-stream","content-length":"10000000000","connection":"Keep-Alive"} Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close

Also, do make bucket (mb) at the same time. This should not be a factor but wanted to mention it to keep track of my test activities.

Must gathers will be in the box note:
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6tocd  
Your environment

POK Bare Metal Real Fast cluster on loan to Real World Cluster
[root@c83f1-infa mb]# noobaa status
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.9-nsfs-fixes-20220303-nsfs
INFO[0000] operator-image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:ca66f681fb5435837543995440661e1ef67a5dce85ae3bf91cafe2f0b66b6e5b
INFO[0000] noobaa-db-image: quay.io/rhceph-dev/rhel8-postgresql-12@sha256:b006af9af125adce28546d0ed9d77421abe54182741f6b5e1d31c88dd763580b

[root@c83f1-infa mb]# oc get csv
NAME DISPLAY VERSION REPLACES PHASE
mcg-operator.v4.9.4 NooBaa Operator 4.9.4 mcg-operator.v4.9.3 Succeeded
ocs-operator.v4.9.4 OpenShift Container Storage 4.9.4 ocs-operator.v4.9.3 Succeeded
odf-operator.v4.9.4 OpenShift Data Foundation 4.9.4 odf-operator.v4.9.3 Succeeded
[root@c83f1-infa mb]#

Recently applied odf 4.9.4-7
Steps to reproduce

Was running a cosbench run with Gigabyte files doing simultaneous read, write and delete
Expected behaviour

No write errors

**Comment by akmithal** [comment]
Hi @nimrod-becker , @romayalon : I can see the string "ERR_STREAM_PREMATURE_CLOSE" in 6766 and 6756, both of which are closed. So is this a regression or seems like a new finding ?

**Comment by romayalon** [comment]
Hey @MonicaLemay 
can you please elaborate on your specific run? 
I see many gigabytes that NooBaa is requested to write but the capacity of the PV is only 50Gi,
What is the total data size that you are trying to write?
Also, I see many requests of the same object trying to be uploaded with different sizes (the range is between 4GB to 10 GB, which I'm not sure we can handle)
anyway, can you check how much space is left on the PV? I see bad descriptor error when getting the premature closure and I suspect it's due to the fact that there is not enough space (according to past scenarios we got this issue)

**Comment by MonicaLemay** [comment]
Let us close this.  I think there is a chance that I ran out of space.  I will try to recreate after a cleanup.  If i can recreate, I will re-open
