### ISSUE TITLE
PUT of file with md5 set occasionally reports TypeError: callback is not a function

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6950]
### Environment info
[root@c83f1-infa ~]# noobaa status
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:8360f899f026691b9b7f8cea9a92f1589e0a7184c694ab843d61ffaa6262b49c
INFO[0000] operator-image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:eb56f52778b71a04b7df62db4ea241c65f84e2b80ddcc9b588414d173d7e086c
INFO[0000] noobaa-db-image: quay.io/rhceph-dev/rhel8-postgresql-12@sha256:be7212e938d1ef314a75aca070c28b6433cd0346704d0d3523c8ef403ff0c69e

[root@c83f1-infa ~]# oc version
Client Version: 4.9.29
Server Version: 4.9.29
Kubernetes Version: v1.22.5+a36406b
[root@c83f1-infa ~]#

[root@c83f1-infa ~]# oc get csv odf-operator.v4.9.6 -o json | grep full
            "full_version": "4.9.6-1",
### Actual behavior
This just showed up after upgrading to above mentioned SW levels.  In noobaa issue 6934, I was able to run warp tests with the S3 server configured for md5 and the warp set to md5=true.  I cannot now.

In this test that I'll show below, both the s3 server is set to MD5 enabled and the warp is set to md5=true.  The below mentioned problem does NOT occur if warp does not use md5=true.

Here is my warp launcher:
```
 ./warp mixed --host=172.20.100.24,172.20.100.23,172.20.100.22 --host-select=roundrobin --access-key=AMKwXLzOJEXzayywWPnO --secret-key=oUJLgVjRH7D0bvzHtoQ6zv8Bec6PQqLusVDlpz9D --obj.size=1G --duration=48h --bucket=s5001b7 --debug  --insecure  --tls --benchdata=/home/RW_moki/warp --warp-client=10.28.20.26 --obj.randsize --objects=1000 --concurrent=20 --md5=true
 ```

On the warp client that does the reading and writing, I see this frequently but not 100%.
```
warp: Sending benchmark_status
warp: <ERROR> upload error: Put "https://172.20.100.22/s5001b7/ske4FX8y/5.GKjFSzt4AeMg22Xb.rnd": write tcp 172.20.100.106:46026->172.20.100.22:443: write: connection reset by peer
```
The noobaa endpoint logs show these errors:
```
root@c83f1-infa 2ndcrash]# oc logs deployment/noobaa-endpoint --all-containers=true --prefix=true --max-log-requests=40 --since=15m | grep -i error  | grep s5001b7
Found 12 pods, using pod/noobaa-endpoint-6c5db7699-65v6f
[pod/noobaa-endpoint-6c5db7699-65v6f/endpoint] May-3 17:47:23.520 [Endpoint/15] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/s5001b7/KvyvDN7c/1.6cCkLM15wBK5Wk39.rnd</Resource><RequestId>l2qg0t1s-ac7on9-1cax</RequestId></Error> PUT /s5001b7/KvyvDN7c/1.6cCkLM15wBK5Wk39.rnd {"host":"172.20.100.23","user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.5.5","content-length":"52535469","authorization":"AWS4-HMAC-SHA256 Credential=AMKwXLzOJEXzayywWPnO/20220503/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=2453c7cb420b275e76823832ff8e667a48d871dca6b0ad44844326f39f4714f4","content-md5":"rT4Yk6bUA0tqBWoa+KFSHg==","content-type":"application/octet-stream","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20220503T174722Z"} TypeError: callback is not a function
[pod/noobaa-endpoint-6c5db7699-65v6f/endpoint] May-3 17:47:24.006 [Endpoint/15] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/s5001b7/cgmchxcV/1.Nf7mezl4pw%285j0Dg.rnd</Resource><RequestId>l2qg0tgd-2hf48b-8ih</RequestId></Error> PUT /s5001b7/cgmchxcV/1.Nf7mezl4pw%285j0Dg.rnd {"host":"172.20.100.23","user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.5.5","content-length":"13157255","authorization":"AWS4-HMAC-SHA256 Credential=AMKwXLzOJEXzayywWPnO/20220503/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=93913534d71b6e7c2482308a4faa950c53878666d9da6b4cc4f3ba40ef82f893","content-md5":"PRFNJUpjFb8K8528LsOwJA==","content-type":"application/octet-stream","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20220503T174723Z"} TypeError: callback is not a function
```
There are more of these, but I only listed a few.

Some files, actually get written so it looks like some do not.

```
[root@c83f1-ems s5001b7]# find ./ -type f | grep rnd
./C9pw)PEd/2.gL4AwPqzS614gWyP.rnd
./C9pw)PEd/1.HufNhY9OO)rcpX2c.rnd
./vXo)je99/1.vazoFtd6xVr3xjxf.rnd
./BOG07N)E/1.4LQ6g05cChfDNJoB.rnd
./r8)W)DfO/2.jr)gQ2Jo0iG(TMsN.rnd
./r8)W)DfO/1.8QWzmcFLEFFx83bt.rnd
./KievflAq/4.qb)kiZwrkWyNjxAQ.rnd
./KievflAq/3.fgkSYQhZc5)6qJUH.rnd
./KievflAq/1.hFNkNnYshcSjW(Xe.rnd
./KievflAq/2.3MC)TGB4Pp))wseV.rnd
./ske4FX8y/4.)a4HXekn5ZGLk9RT.rnd
./ske4FX8y/2.O8mkYfQ1PwjTwlFt.rnd
./ske4FX8y/1.18VhLjDWKEYhPZNj.rnd
./ske4FX8y/3.fkpF(cvZsAmW6AED.rnd
./9ONSHFiD/1.eXKafArX786bwlyJ.rnd
./HS1B6T1l/1.UqbaCco7Zv1PAWRI.rnd
./DtTBQAIM/2.RC4UeMLuMLaVktmW.rnd
./DtTBQAIM/1.G0J7ieMqz1In09sa.rnd
```

noobaa diagnose and must-gather are in the box note.  It is labeled with this defect number.:
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6tocd

### Expected behavior
1.
I expect that if a workload uses MD5 that it should be able to complete I/O and not generate the error.
### Steps to reproduce
1.

**Comment by MonicaLemay** [comment]
I think that this one is also a blocker for our team.

**Comment by romayalon** [comment]
Hey @MonicaLemay,
In the line above I see again the infamous EINVAL error we saw in https://github.com/noobaa/noobaa-core/issues/6896
```
ChunkFS _flush_buffers failed [Error: Invalid argument] { code:'EINVAL' }
May-3 17:30:14.950 [Endpoint/15] [ERROR] CONSOLE:: ChunkFS _transform failed TypeError: callback is not a function
```
Also I don't see any NSFS native log messages, So I checked in the noobaa-config config map the debug level and it is: 
```
   NOOBAA_LOG_LEVEL: default_level
```
So the next steps are - 
1. Please check that this version contains the fix - https://github.com/noobaa/noobaa-core/pull/6928
    you can do it by running the following: 
```
    oc rsh noobaa-endpoint-{pod-suffix}
    cat /root/node_modules/noobaa-core/src/util/chunk_fs.js
```
2.1. If the version doesn't contain the fix, let us know, I'll check on which version it exists (as we know it's available in noobaa/noobaa-core:nsfs_backport_5.9-20220331)  
2.2. If you do have the fix - Run again with NSFS debug level so we can see what is the invalid argument again.


@guymguym the  ``` TypeError: callback is not a function ``` comes from the call to flush_buffers() in line 51, in which we don't pass ```callback``` parameter, this is an old code, is that on purpose? or it's a bug and we should pass it?

**Comment by guymguym** [comment]
@romayalon I think the error is from line 81 is in chunk_fs since we didnt check if (callback) in the catch block like we do before.

**Comment by rkomandu** [comment]
@romayalon , the chunk_fs fix is it in the ODF d/s 4.9.6-1 build? All of us are using that and planning to have GA based on this version.

**Comment by romayalon** [comment]
@MonicaLemay @rkomandu Ravi checked it on his system in which 4.9.6-1 is installed as well and it doesn't contain the fix.
@nimrod-becker can you please help with the d/s image that does contain this fix?

**Comment by nimrod-becker** [comment]
d/s is based on u/s so I don't expect any diff.

Which specific commit are we missing?

**Comment by nimrod-becker** [comment]
ok I see, its 
https://github.com/noobaa/noobaa-core/pull/6928

Its not a part of 4.9.6

**Comment by guymguym** [comment]
I think this - https://github.com/noobaa/noobaa-core/pull/6928 - right @romayalon ?

**Comment by MonicaLemay** [comment]
I patched my cluster with
```
 kubectl patch noobaa noobaa --patch '{"spec": {"image": "noobaa/noobaa-core:nsfs_backport_5.9-20220331"}}' --type="merge"
 ```
 This defect issue, 6950, is now gone.  Should I close this??

**Comment by rkomandu** [comment]
@MonicaLemay , from the above posts the fix should be in 4.9.6 stream as GA is based on that version. You shouldn't close this defect by patching. 

@nimrod-becker @romayalon 
PFA 4.9.6-1 is connected to last latest-stable-4.9.6 in the Quay.io towards d/s builds a month back. 
Now 4.9.6 seems to be in RC phase. Could you guide what could be the alternative for this 

@troppens FYI

**Comment by nimrod-becker** [comment]
https://github.com/noobaa/noobaa-core/pull/6952

**Comment by MonicaLemay** [comment]
Tested ODF 4.9.7-2 and this defect is fixed.  Closing
