### ISSUE TITLE
During upgrade from ODF 4.9.8 to ODF 4.10.2 see error “ResolutionFailed” for “CatalogSources” 

### ISSUE THREAD

**Issue by madhuthorat** [noobaa/noobaa-core#6977]
### Environment info
- NooBaa Version: ODF 4.9.8 upgraded to ODF 4.10.2
- Platform: **OpenShift 4.10**

### Actual behavior
During upgrade from ODF 4.9.8 to ODF 4.10.2, a new pod and subscription for “odf-csi-addons” get added during upgrade, for this saw “ResolutionFailed” for “CatalogSources” during upgrade, which resolves automatically after sometime, usually in ~6-11 minutes.
Question: Is there a solution to handle this in case this automatic resolution fails ? We found a similar issue at https://github.com/operator-framework/operator-lifecycle-manager/issues/2201

### Expected behavior
Do not expect “ResolutionFailed” for “CatalogSources” during upgrade.

### Steps to reproduce
Upgrade from ODF 4.9.8 to ODF 4.10.2

### More information - Screenshots / Logs / Other output
After upgrade to ODF 4.10 a new pod and subscription for “odf-csi-addons” get added. For the newly added subscription see below error which resolves automatically after ~6-11 minutes:

```
conditions:

    - lastTransitionTime: ‘2022-05-31T07:45:04Z’

     message: all available catalogsources are healthy

      reason: AllCatalogSourcesHealthy

      status: ‘False’

      type: CatalogSourcesUnhealthy

    - message: >-

        a unique replacement chain within a channel is required to determine the

        relative order between channel entries, but 2 replacement chains were

        found in channel “stable-4.10” of package “odf-operator”:

        odf-operator.v4.10.1…odf-operator.v4.10.0, odf-operator.v4.10.2

      reason: ErrorPreventedResolution

      status: ‘True’

      type: ResolutionFailed

 

# oc get subscription | grep csi-addons

odf-csi-addons-operator                                           odf-csi-addons-operator   redhat-operators   stable-4.10

 

# oc get pods | grep csi-addons

csi-addons-controller-manager-5645ffbf-jjm87       2/2     Running   13 (3h18m ago)   21h
```

**Comment by nimrod-becker** [comment]
This is not really a NooBaa issue, the issue you found within the OLM might be the RC or there might be something else in the OLM, I think we should take it to that project

**Comment by madhuthorat** [comment]
Do you recommend to raise issue in Bugzilla ? And for which project ?

**Does it impact noobaa functionality ? because only after resolution happens, some pods get restarted in Openshift-storage namespace.**.

**Comment by nimrod-becker** [comment]
@madhuthorat is this relevant?

**Comment by romayalon** [comment]
Closing, HPO is discontinued.
