### ISSUE TITLE
After upgrade, the subscription for ocs-operator shows old subscription version/name, but channel is set to “stable-4.10”

### ISSUE THREAD

**Issue by madhuthorat** [noobaa/noobaa-core#6978]
### Environment info
- NooBaa Version: ODF 4.9.8 to ODF 4.10.2 upgrade
- Platform: **OpenShift 4.10**

### Actual behavior
After upgrade, the subscription for ocs-operator shows old subscription version/name, but channel is set to “stable-4.10”
After upgrade to ODF 4.10.2:
```
# oc get subscription | grep ocs-operator
ocs-operator-stable-4.9-redhat-operators-openshift-marketplace    ocs-operator              redhat-operators   stable-4.10
```
Question: What is the impact of this on noobaa functionality ? Channel for ocs-operator is “stable-4.10” which is right. Is it ok to have subscription with name “ocs-operator-stable-4.9-redhat-operators-openshift-marketplace” ?

### Expected behavior
Subscription for ocs-operator should show new subscription version/name.

### Steps to reproduce
ODF 4.9.8 to ODF 4.10.2 upgrade on OCP 4.10

### More information - Screenshots / Logs / Other output
After upgrade to ODF 4.10.2:
```
# oc get subscription | grep ocs-operator
ocs-operator-stable-4.9-redhat-operators-openshift-marketplace    ocs-operator              redhat-operators   stable-4.10
```

**Comment by rkomandu** [comment]
@madhuthorat 
Should we wait for the Oct ODF 4.10 -> 4.11 upgrade release fixes from RH team and try this out ?

**Comment by rkomandu** [comment]
@madhuthorat , I think this is talking about ODF 4.10.2, Can this be closed if this is working ?

**Comment by madhuthorat** [comment]
@rkomandu Would like to check if similar issue exists during ODF 4.10 to ODF 4.11 upgrade and then close as needed.

**Comment by nimrod-becker** [comment]
@madhuthorat is this relevant?

**Comment by romayalon** [comment]
Closing, HPO is discontinued.
