### ISSUE TITLE
Allow list_objects for anonymous users

### ISSUE THREAD

**Issue by NotABugItsAFeature** [noobaa/noobaa-core#7036]
**Is your feature request related to a problem? Please describe.**
We want to have an anonymously accessible (read-only) s3 bucket you can navigate through a webbrowser.
We noticed that while all necessary operations were allowed the call still failed with a 403.

`Aug-7 19:54:01.610 [Endpoint/13] [L0] core.endpoint.s3.s3_utils:: bucket_policy: action fit? s3:* s3:listbucket
Aug-7 19:54:01.610 [Endpoint/13] [L0] core.endpoint.s3.s3_utils:: bucket_policy: principal fit? SENSITIVE-7846cdd4c2b90527 undefined
Aug-7 19:54:01.610 [Endpoint/13] [L0] core.endpoint.s3.s3_utils:: bucket_policy: resource fit? /^arn:aws:s3:::website-foo-62044d78-39c5-4b65-9e0b-998350fda26c\/.*$/ arn:aws:s3:::website-foo-62044d78-39c5-4b65-9e0b-998350fda26c
Aug-7 19:54:01.610 [Endpoint/13] [L0] core.endpoint.s3.s3_utils:: bucket_policy: is_statements_fit true true false
Aug-7 19:54:01.610 [Endpoint/13] [ERROR] CONSOLE:: RPC._on_request: ERROR srv object_api.list_objects reqid 230@fcall://fcall(7pacxw7c) connid fcall://fcall(7pacxw7c) Error: not anonymous method list_objects
at RpcRequest.req.check_anonymous (/root/node_modules/noobaa-core/src/server/common_services/auth_server.js:528:44)
at authorize (/root/node_modules/noobaa-core/src/server/common_services/auth_server.js:436:17)
at RPC._on_request (/root/node_modules/noobaa-core/src/rpc/rpc.js:323:27)`

Troubleshooting has been done with @guymguym and he came to the conclusion that this call is not allowed for anonymous users.
[ref](https://github.com/noobaa/noobaa-core/blob/12b8a5beeb518d876f4fec22f12d714f57e47c17/src/api/object_api.js#L749)

**Describe the solution you'd like**
Since the policy allows it the call to list_objects should also be allowed.

**Describe alternatives you've considered**
In other cases we need to share either keys (directly or indirectly) and explain to users how to setup.
There is an existing s3 explorer project however it's not built right now for authentication and with auth we need to share keys with the app, change endpoint to use ODF instead of aws, ...
For each bucket we also need to create this setup again.

**Comment by guymguym** [comment]
Adding to the details that we tested this with https://github.com/awslabs/aws-js-s3-explorer
and were stuck the unauthorized call to listObjects here - 
https://github.com/awslabs/aws-js-s3-explorer/blob/4de1fd016f098eec491605829530c31387870b63/index.html#L449

Allowing the list_objects api for anonymous requests would just require adding `anonymous: true` to its api auth definition, but we want to make sure the bucket policy is still securing this api.

**Comment by NotABugItsAFeature** [comment]
Any update on this? :)

**Comment by guymguym** [comment]
@nimrod-becker Would it be possible to assign this?

**Comment by nimrod-becker** [comment]
Sure,
@utkarsh-pro I think this is very related to the allowed buckets removal you are working on, can you pick this up? (different PR ofc, don't think we need to tie both to the same PR :) )
