### ISSUE TITLE
Warp Io workload errors out with "The specified key does not exist" and also noobaa-endpoint restarts 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#7067]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

ODF 4.11 on OCP 4.11 

```
oc get csv -n openshift-storage
NAME                                   DISPLAY                       VERSION               REPLACES   PHASE
mcg-operator.v4.11.0                   NooBaa Operator               4.11.0                           Succeeded
metallb-operator.4.11.0-202208300306   MetalLB Operator              4.11.0-202208300306              Succeeded
ocs-operator.v4.11.0                   OpenShift Container Storage   4.11.0                           Succeeded
odf-csi-addons-operator.v4.11.0        CSI Addons                    4.11.0                           Succeeded
odf-operator.v4.11.0                   OpenShift Data Foundation     4.11.0                           Succeeded

```

oc version
Client Version: 4.11.0
Kustomize Version: v4.5.4
Server Version: 4.11.0
Kubernetes Version: v1.24.0+9546431

warp --version
warp version 0.6.2 - b3149da

### Actual behavior
1.  IO run shouldn't error out and noobaa-endpoint shouldn't restart.. 

### Expected behavior
1. IO error and noobaa-endpoint shouldn't restart 

### Steps to reproduce
1. Run Warp IO workload as shown below 
warp mixed --host=10.17.54.11 --access-key=<accesskey>--secret-key=<key> --obj.size=1k --duration=60m --bucket=newbucket-u5005-warp --debug --insecure --tls 2>&1 | tee /tmp/user5005.warp.14Sep.log

warp: <ERROR> delete error:  The specified key does not exist.
warp: Benchmark data written to "warp-mixed-2022-09-14[034914]-Ikfg.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 59m59s.
Errors: 1
 * Throughput: 56.74 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 1h0m0s.
 * Throughput: 0.24 MiB/s, 255.34 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 1h0m0s.
 * Throughput: 0.08 MiB/s, 85.11 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 1h0m0s.
 * Throughput: 170.23 obj/s

Cluster Total: 0.32 MiB/s, 567.42 obj/s, 1 errors over 1h0m0s.
Total Errors:1.
warp: Cleanup Done.

### More information - Screenshots / Logs / Other output

IP (10.17.54.11) is the one serviced on the worker1 endpoint as per the "oc get svc -n openshift-storage|grep Load" 

xxx-s3-worker1                                    LoadBalancer   172.30.147.183   10.17.54.11    80:32684/TCP,443:31819/TCP,8444:32556/TCP,7004:30152/TCP   3h11m

Noobaa endpoint you could see, got restarted 4 times while IO running to the same endpoint 

```
NAME                                               READY   STATUS    RESTARTS        AGE     IP              NODE                            NOMINATED NODE
READINESS GATES
csi-addons-controller-manager-78d59467d6-w6mnv     2/2     Running   0               3h38m   10.254.13.170   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-core-0                                      1/1     Running   0               3h35m   10.254.13.175   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-db-pg-0                                     1/1     Running   0               3h33m   10.254.16.125   worker2.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-default-backing-store-noobaa-pod-d8050f04   1/1     Running   0               3h32m   10.254.16.128   worker2.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-endpoint-847c78bfb7-9kwss                   1/1     Running   4 (4m30s ago)   3h32m   10.254.13.179   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-endpoint-847c78bfb7-qps5g                   1/1     Running   0               3h32m   10.254.21.173   worker0.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-endpoint-847c78bfb7-xrgf5                   1/1     Running   0               3h31m   10.254.16.129   worker2.sieve.cp.fyre.ibm.com   <none>
<none>
noobaa-operator-7dc887b794-llhk9                   1/1     Running   1 (3h35m ago)   3h38m   10.254.21.168   worker0.sieve.cp.fyre.ibm.com   <none>
<none>
ocs-metrics-exporter-64f49bcbf5-kd585              1/1     Running   0               3h38m   10.254.13.171   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
ocs-operator-5cc5d545cf-cxfvp                      1/1     Running   0               3h38m   10.254.16.123   worker2.sieve.cp.fyre.ibm.com   <none>
<none>
odf-console-5c886b8669-wv87c                       1/1     Running   0               3h38m   10.254.13.172   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
odf-operator-controller-manager-7b9574f9-gz4fb     2/2     Running   0               3h38m   10.254.21.169   worker0.sieve.cp.fyre.ibm.com   <none>
<none>
rook-ceph-operator-558cf6694-z6zqh                 1/1     Running   0               3h38m   10.254.13.173   worker1.sieve.cp.fyre.ibm.com   <none>
<none>
```

Noobaa-endpoint log snippet shows as follows

```
noobaa-endpoint-847c78bfb7-9kwss.previous.txt (when 3rd time restart occurred, collected oc logs <endpoint> --previous
-----------------------------------------------------------

[32mSep-14 11:32:00.277[35m [Endpoint/13] [36m   [L0][39m core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: [33m5100[39m, uid: [33m5005[39m, nsfs_only: [33mtrue[39m, new_buckets_path: [32m's3user-5005-dir/'[39m, backend: [32m'GPFS'[39m, warn_threshold_ms: [33m100[39m } file_path /nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/l58YpesQ/11005.82HpDlTawnXBUO6U.rnd
[32mSep-14 11:32:00.277[35m [Endpoint/13] [36m   [L0][39m core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: [33m5100[39m, uid: [33m5005[39m, nsfs_only: [33mtrue[39m, new_buckets_path: [32m's3user-5005-dir/'[39m, backend: [32m'GPFS'[39m, warn_threshold_ms: [33m100[39m } file_path /nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/DyNUp9cc/10881.KNuxzqTD1NJDMWeK.rnd
[32mSep-14 11:32:00.278[35m [Endpoint/13] [36m   [L0][39m core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: [33m5100[39m, uid: [33m5005[39m, nsfs_only: [33mtrue[39m, new_buckets_path: [32m's3user-5005-dir/'[39m, backend: [32m'GPFS'[39m, warn_threshold_ms: [33m100[39m } file_path /nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/Z7l9eKXL/6268.vIJFEExeOqbNnBxe.rnd
**/noobaa_init_files/noobaa_init.sh: line 75:    13 Killed                  $***


######################################################################
Wed Sep 14 11:32:00 UTC 2022 NooBaa: Process exited RIP (RC=137)
######################################################################

```

4th restart of noobaa-endpoint also showed the same error as 3rd restart of noobaa 

```
[32mSep-14 11:47:12.820[35m [Endpoint/14] [36m   [L0][39m core.sdk.namespace_fs:: NamespaceFS: read_object_stream completed file /nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/UAl2HBF2/2816.n(fTIoQu0hXtDXxZ.rnd { num_bytes: [33m1000[39m, num_buffers: [33m1[39m, avg_buffer: [33m1000[39m, log2_size_histogram: { [32m'10'[39m: [33m1[39m } }
[32mSep-14 11:47:12.820[35m [Endpoint/14] [36m   [L0][39m core.sdk.namespace_fs:: NamespaceFS: read_object_stream { file_path: [32m'/nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/t)3X6N5h/14284.JLSnaUi3O07zq9Rx.rnd'[39m, start: [33m0[39m, end: [33mInfinity[39m }
[32mSep-14 11:47:12.821[35m [Endpoint/14] [36m   [L0][39m core.endpoint.s3.ops.s3_put_object:: PUT OBJECT newbucket-u5005-warp dEYa6bca/14701.GAE4V22DE2EmO5vu.rnd
[32mSep-14 11:47:12.821[35m [Endpoint/14] [36m   [L0][39m core.sdk.namespace_fs:: NamespaceFS: read_object_stream completed file /nsfs/noobaa-s3res-4080029599/s3user-5005-dir/newbucket-u5005-warp/YFhV0Qg1/3070.hHH9h2jfiJ)T7UfK.rnd { num_bytes: [33m1000[39m, num_buffers: [33m1[39m, avg_buffer: [33m1000[39m, log2_size_histogram: { [32m'10'[39m: [33m1[39m } }
/noobaa_init_files/noobaa_init.sh: line 75:    14 Killed                  $*




######################################################################
Wed Sep 14 11:47:13 UTC 2022 NooBaa: Process exited RIP (RC=137)
######################################################################


```

Will upload the oc adm must-gather for noobaa, oc must-gather of cluster, noobaa-endpoint previous logs for the endpoint 

must-gather of odf4.11
[must-gather-odf-11.tar.gz](https://github.com/noobaa/noobaa-core/files/9566271/must-gather-odf-11.tar.gz)

noobaa-endpoint with --previous logs 
[noobaa-endpoint-847c78bfb7-9kwss.previous.txt](https://github.com/noobaa/noobaa-core/files/9566278/noobaa-endpoint-847c78bfb7-9kwss.previous.txt)

**Comment by rkomandu** [comment]
Further checking on the "describe pod" as per Romy , saw the reason as OOM killer.. As this is Fyre infrastructure it could have happened, even though worker node is 32G it has the CNSA, CSI and Noobaa endpoint running ,could have used the complete memory 

oc describe pod noobaa-endpoint-847c78bfb7-9kwss -n openshift-storage |less 

  Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /noobaa_init_files/noobaa_init.sh
      init_endpoint
    State:          Running
      Started:      Wed, 14 Sep 2022 04:47:13 -0700
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 14 Sep 2022 04:32:01 -0700
      Finished:     Wed, 14 Sep 2022 04:47:13 -0700
    Ready:          True
    Restart Count:  4

**Comment by rkomandu** [comment]
Ran on the ODF 4.11 on Fyre, this time for 30min.. could observe 1 time the noobaa-endpoint restarted and the Warp showed the following errors 

```
 warp mixed --host=10.17.49.13 --access-key=6DHgxYrpRebJ4ikW0FgZ --secret-key=E1jxYy5WtxMbmRpGm8n3MQuT/NjQl8g1CyhUcHe8 --obj.size=1k --duration=30m --bucket=newbucket-u5005-warp-30min --debug --insecure --tls 2>&1 | tee /tmp/user5005.warp.15Sep-30min.log
warp: <ERROR> delete error:  The specified key does not exist.
warp: <ERROR> delete error:  Delete "https://10.17.49.13/newbucket-u5005-warp-30min/SwCXzDyV/6736.Pq8HxD4QGGeIkh3e.rnd": dial tcp 10.17.49.13:443: connect: connection refused
warp: <ERROR> delete error:  The specified key does not exist.
warp: Benchmark data written to "warp-mixed-2022-09-15[061116]-v12P.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 30m0s.
Errors: 3
 * Throughput: 65.03 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 30m0s.
 * Throughput: 0.28 MiB/s, 292.64 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 30m0s.
 * Throughput: 0.09 MiB/s, 97.55 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 30m0s.
 * Throughput: 195.09 obj/s

Cluster Total: 0.37 MiB/s, 650.31 obj/s, 3 errors over 30m0s.
Total Errors:3.
warp: Cleanup Done.


```

Noobaa pod is 

```
NAME                                               READY   STATUS    RESTARTS      AGE   IP              NODE                            NOMINATED NODE   READ
INESS GATES
csi-addons-controller-manager-78d59467d6-w6mnv     2/2     Running   0             29h   10.254.13.170   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-core-0                                      1/1     Running   0             29h   10.254.13.175   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-db-pg-0                                     1/1     Running   0             29h   10.254.16.125   worker2.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-default-backing-store-noobaa-pod-d8050f04   1/1     Running   0             29h   10.254.16.128   worker2.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-endpoint-847c78bfb7-9kwss                   1/1     Running   4 (26h ago)   29h   10.254.13.179   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-endpoint-847c78bfb7-qps5g                   1/1     Running   2 (34m ago)   29h   10.254.21.173   worker0.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-endpoint-847c78bfb7-xrgf5                   1/1     Running   0             29h   10.254.16.129   worker2.sieve.cp.fyre.ibm.com   <none>           <non
e>
noobaa-operator-7dc887b794-llhk9                   1/1     Running   1 (29h ago)   29h   10.254.21.168   worker0.sieve.cp.fyre.ibm.com   <none>           <non
e>
ocs-metrics-exporter-64f49bcbf5-kd585              1/1     Running   0             29h   10.254.13.171   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>
ocs-operator-5cc5d545cf-cxfvp                      1/1     Running   0             29h   10.254.16.123   worker2.sieve.cp.fyre.ibm.com   <none>           <non
e>
odf-console-5c886b8669-wv87c                       1/1     Running   0             29h   10.254.13.172   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>
odf-operator-controller-manager-7b9574f9-gz4fb     2/2     Running   0             29h   10.254.21.169   worker0.sieve.cp.fyre.ibm.com   <none>           <non
e>
rook-ceph-operator-558cf6694-z6zqh                 1/1     Running   0             29h   10.254.13.173   worker1.sieve.cp.fyre.ibm.com   <none>           <non
e>

```
As you could observe it restarted twice (noobaa-endpoint-847c78bfb7-qps5g)

**Comment by rkomandu** [comment]
have got the ODF 4.11.1 and on the same virtual infrastructure the run completed successfully for an hour which wasn't the case.. 

oc get csv
NAME                                   DISPLAY                       VERSION               REPLACES                          PHASE
mcg-operator.v4.11.1                   NooBaa Operator               4.11.1                mcg-operator.v4.11.0              Succeeded
metallb-operator.4.11.0-202208300306   MetalLB Operator              4.11.0-202208300306                                     Succeeded
ocs-operator.v4.11.1                   OpenShift Container Storage   4.11.1                ocs-operator.v4.11.0              Succeeded
odf-csi-addons-operator.v4.11.1        CSI Addons                    4.11.1                odf-csi-addons-operator.v4.11.0   Succeeded
odf-operator.v4.11.1                   OpenShift Data Foundation     4.11.1                odf-operator.v4.11.0              Succeeded


This seems to be fixed in 4.11.1 


I ran from each user in a sequential fashion and it seems to work 

For ex: 
warp mixed --host=10.17.49.13 --access-key=6DHgxYrpRebJ4ikW0FgZ --secret-key=E1jxYy5WtxMbmRpGm8n3MQuT/NjQl8g1CyhUcHe8 --obj.size=1k --duration=60m --bucket=newbucket-u5005-warp-19sep --debug --insecure --tls 2>&1 | tee /tmp/user5005.warp.19Sep.log
warp: Benchmark data written to "warp-mixed-2022-09-18[205650]-BoHE.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 59m59s.
 * Throughput: 102.79 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 59m59s.
 * Throughput: 0.44 MiB/s, 462.55 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 59m59s.
 * Throughput: 0.15 MiB/s, 154.19 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 59m59s.
 * Throughput: 308.37 obj/s

Cluster Total: 0.59 MiB/s, 1027.90 obj/s over 1h0m0s.
warp: Cleanup Done.




We will try for longer duration with a decent object size on Baremetal and then confirm on this.

**Comment by romayalon** [comment]
@rkomandu great news
https://github.com/noobaa/noobaa-core/pull/7048 the backport PR to 4.11.1 of the memory leak fix.

**Comment by rkomandu** [comment]
Well interesting thing is.. could spawn from 2 different users concurrently onto 2 different endpoints and it was successful. Looks like the ODF 4.11.1 has a good fix w/r/t Memory consumption / leak fix.

**Comment by rkomandu** [comment]
closing this as 12hr run had a problem .. it generated panic for the Warp, could be due to infrastructure. 

There are 2 defects that are currently tracked with ODF 4.11.1 as a priority for our upcoming release #7076 and #7078
