### ISSUE TITLE
NSFS | Copy object | xattrs are ignored by link file flow

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7073]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Copy object link file flow ignores xattrs and doesn't put them on the file.
2. A refactor of upload_object function is recommended as well.

### Expected behavior
1.

**Comment by nimrod-becker** [comment]
Refactor was done

**Comment by guymguym** [comment]
working by now.
