### ISSUE TITLE
Warp IO workload errors out with "The specified key does not exist" on Bare Metal

### ISSUE THREAD

**Issue by nigamshaurya14** [noobaa/noobaa-core#7076]
### Environment info
- NooBaa Version: 
```
[root@hpo-app11 ~]# noobaa version
INFO[0000] CLI version: 5.10.1
INFO[0000] noobaa-image: noobaa/noobaa-core:5.10.1
INFO[0000] operator-image: noobaa/noobaa-operator:5.10.1
[root@hpo-app11 ~]#
```

- Platform: 

```
[root@hpo-app11 ~]# oc version
Client Version: 4.11.0
Kustomize Version: v4.5.4
Server Version: 4.11.0
Kubernetes Version: v1.24.0+9546431
[root@hpo-app11 ~]#
```

ODF Version

```
[root@hpo-app11 ~]# oc get csv
NAME                                   DISPLAY                       VERSION               REPLACES                          PHASE
mcg-operator.v4.11.1                   NooBaa Operator               4.11.1                mcg-operator.v4.11.0              Succeeded
metallb-operator.4.11.0-202208300306   MetalLB Operator              4.11.0-202208300306                                     Succeeded
ocs-operator.v4.11.1                   OpenShift Container Storage   4.11.1                ocs-operator.v4.11.0              Succeeded
odf-csi-addons-operator.v4.11.1        CSI Addons                    4.11.1                odf-csi-addons-operator.v4.11.0   Succeeded
odf-operator.v4.11.1                   OpenShift Data Foundation     4.11.1                odf-operator.v4.11.0              Succeeded
[root@hpo-app11 ~]#

```

Warp version:

```
[root@hpo-app11 ~]# warp --version
warp version 0.5.5 - 1baadbc
[root@hpo-app11 ~]#
```

### Actual behavior
warp run on Bare Metal fails on all three metallb Endpoints

### Expected behavior
warp should execute successfully

### Steps to reproduce
1. Setup BM with CNSA/CSI RC4, ODF 4.11.1, latest DAS operator. 
2. Run warp on all three metallb IPs with 3 different users:

warp mixed --host=10.49.0.109 --access-key=uIBpl5fBWanFrXxLY6JW --secret-key=Z658YPATWG491XEbnn9ZwCPUGUS8KS36m91zWhUO --obj.size=1K --duration=120m --bucket=bucket11 --debug --insecure --tls 1> capture1.txt 2> error1.txt

warp mixed --host=10.49.0.110 --access-key=lDW9JSyitHuYa0EGx6vM --secret-key=BAu2KPpbAct28rvYwCdjILkO1vNWphsO57H5htlD --obj.size=1K --duration=120m --bucket=bucket22 --debug --insecure --tls 1> capture2.txt 2> error2.txt

warp mixed --host=10.49.0.111 --access-key=8FnXjkMLesfOOOr4TKw6 --secret-key=OjcPkdOyTE6FDujcmBj3JeUVl11TpZznyj4GyVhe --obj.size=1M --duration=120m --bucket=bucket33 --debug --insecure --tls 1> capture3.txt 2> error3.txt

Attachments:
[capture2.txt](https://github.com/noobaa/noobaa-core/files/9599718/capture2.txt)
[capture3.txt](https://github.com/noobaa/noobaa-core/files/9599725/capture3.txt)
[capture1.txt](https://github.com/noobaa/noobaa-core/files/9599713/capture1.txt)
[error1.txt](https://github.com/noobaa/noobaa-core/files/9599747/error1.txt)
[error2.txt](https://github.com/noobaa/noobaa-core/files/9599748/error2.txt)
[error3.txt](https://github.com/noobaa/noobaa-core/files/9599749/error3.txt)

Logs: https://ibmandredhatguests.slack.com/archives/G015Z7SDWQ0/p1663598668494769?thread_ts=1663597420.548999&cid=G015Z7SDWQ0

**Comment by rkomandu** [comment]
@romayalon 
On the BM cluster 

the warp when spawned showed immediately as follows , which is a concern... 

 warp mixed --host=10.49.0.111 --access-key=lDW9JSyitHuYa0EGx6vM --secret-key=BAu2KPpbAct28rvYwCdjILkO1vNWphsO57H5htlD --obj.size=50M --duration=30m --bucket=bucket3-rkomandu --debug --insecure --tls 2>&1 | tee  /tmp/warp-111ip.50m.rkomandu.20Sep.log
warp: <ERROR> The specified key does not exist.
warp: <ERROR> The specified key does not exist.
warp: <ERROR> EOF
Benchmarking:                15m29s / 30m00s ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  51.65%

user exist --> as shown below 
 s3user2        8093    9003    lDW9JSyitHuYa0EGx6vM    BAu2KPpbAct28rvYwCdjILkO1vNWphsO57H5htlD        /mnt/remote-sample/exports-user2/

**Comment by NeeshaPan** [comment]
@romayalon I had started run on 3IP's  for 1k, 2k and 50m consecutively. For 2k and 50m run had completed without issues, however for 1k run I observed issue "Specified key does not exist during warp run.

Please find the required logs below.
ulimit/lsof result file: This file has the output of below command:
`for i in `oc get pods  |grep noobaa-endpoint | awk ' {print $1}'`; do oc rsh $i ulimit -n; oc rsh $i lsof |wc -l; echo $i is done;`
[lsof.txt](https://github.com/noobaa/noobaa-core/files/9624547/lsof.txt)

Noobaa diagnose logs
[noobaa_diagnostics_1663840484.tar.gz](https://github.com/noobaa/noobaa-core/files/9624576/noobaa_diagnostics_1663840484.tar.gz)

Disk space file while running I/O:
[dfcommand2.txt](https://github.com/noobaa/noobaa-core/files/9624675/dfcommand2.txt)

**Comment by nigamshaurya14** [comment]
@romayalon  I ran warp with new bucket for 2 hrs, and it also failed.

warp mixed --host=10.49.0.111 --access-key=8FnXjkMLesfOOOr4TKw6 --secret-key=OjcPkdOyTE6FDujcmBj3JeUVl11TpZznyj4GyVhe --obj.size=1M --duration=120m --bucket=bucket3 --debug --insecure --tls 2>&1 | tee  /tmp/warp-111ip.1M.shaurya.21Sep.log

DB pods:
[logs.tar.gz](https://github.com/noobaa/noobaa-core/files/9624755/logs.tar.gz)

noobaa diagnose logs:
[noobaa_diagnostics_1663765225.tar.gz](https://github.com/noobaa/noobaa-core/files/9624736/noobaa_diagnostics_1663765225.tar.gz)

**Comment by NeeshaPan** [comment]
@romayalon Observed this issue again on warp run on the latest DAS image.
I had started warp run for 10k, 100k and 30m object size consecutively on 3IP's. I have also changed noobaa-log-level to nsfs.
[warp2round2_2hr_run_23Sep.log](https://github.com/noobaa/noobaa-core/files/9634913/warp2round2_2hr_run_23Sep.log)


Please find attached lsof and noobaa diagnose log captured during run.
[noobaa_diagnostics_1663939231.tar.gz](https://github.com/noobaa/noobaa-core/files/9634845/noobaa_diagnostics_1663939231.tar.gz)
[lsof_file2.txt](https://github.com/noobaa/noobaa-core/files/9634853/lsof_file2.txt)

Also attached console output of warp run.
[warp_2hr_run_23sept2nd-round.log](https://github.com/noobaa/noobaa-core/files/9634904/warp_2hr_run_23sept2nd-round.log)

**Comment by rkomandu** [comment]
@romayalon 
On a freshly deployed DAS cluster (ODF 4.11.1 GA) we again hit the duplicate ids in bucketstats table. 

```
Sep-26 6:32:07.896 [Endpoint/14] [ERROR] CONSOLE:: RPC._on_request: ERROR srv object_api.update_endpoint_stats reqid 19524@fcall://fcall(7om8vqvf) connid fcall://fcall(7om8vqvf) AssertionError [ERR_ASSERTION]: _id must be unique. found 2 rows with _id=undefined in table bucketstats
Sep-26 6:32:07.897 [Endpoint/14] [ERROR] core.rpc.rpc:: RPC._request: response ERROR srv object_api.update_endpoint_stats reqid 19524@fcall://fcall(7om8vqvf) connid fcall://fcall(7om8vqvf) params { namespace_stats: [ { io_stats: { read_count: 2199279, write_count: 929200, read_bytes: 55346668240896, write_bytes: 13374358598656, error_write_bytes: 0, error_write_count: 0, error_read_bytes: 0, error_read_count: 0 }, namespace_resource_id: '632d5b3674e74100298682d4' }, [length]: 1 ], bucket_counters: [ { bucket_name: SENSITIVE-d11ed9bf0f42c55a, content_type: 'application/octet-stream', read_count: 1055154, write_count: 358804 }, { bucket_name: SENSITIVE-40584c364915f5f3, content_type: 'application/octet-stream', read_count: 1144123, write_count: 374277 }, [length]: 2 ] } took [8.8+0.4=9.2] [RpcError: _id must be unique. found 2 rows with _id=undefined in table bucketstats] { rpc_code: 'INTERNAL', rpc_data: { retryable: true } }
Sep-26 6:32:07.897 [Endpoint/14] [ERROR] core.sdk.endpoint_stats_collector:: failed on update_endpoint_stats. trigger_send_stats again [RpcError: _id must be unique. found 2 rows with _id=undefined in table bucketstats] { rpc_code: 'INTERNAL', rpc_data: { retryable: true } }
Sep-26 6:32:37.907 [Endpoint/14] [ERROR] core.util.postgres_client:: updateOneWithClient failed { system: 632d5af574e74100298682c0, bucket: 632f441da43595b2582184de, content_type: 'application/octet-stream' } { '$set': { last_write: 1664173957897, last_read: 1664173957897, system: 632d5af574e74100298682c0, bucket: 632f441da43595b2582184de, content_type: 'application/octet-stream' }, '$inc': { writes: 358804, reads: 1055154 } } UPDATE bucketstats SET data = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(data,'{content_type}','"application/octet-stream"'),'{bucket}','"632f441da43595b2582184de"'),'{system}','"632d5af574e74100298682c0"'),'{last_read}','1664173957897'::jsonb),'{last_write}','1664173957897'::jsonb),'{reads}',to_jsonb(COALESCE(Cast(data->>'reads' as numeric),0)+1055154)),'{writes}',to_jsonb(COALESCE(Cast(data->>'writes' as numeric),0)+358804)) WHERE (data->>'system'='632d5af574e74100298682c0' and data->>'bucket'='632f441da43595b2582184de' and data->>'content_type'='application/octet-stream') RETURNING _id, data AssertionError [ERR_ASSERTION]: _id must be unique. found 2 rows with _id=undefined in table bucketstats


```

This issue re-occurred after our Thus discussion. Unfortunately as two people are working on the system, one was cleaning the DAS and eventually the logs are gone before the "noobaa diagnostics" was hit. Bottom line this is an issue in the latest code level of OCP 4.11 with ODF 4.11.1 

We will keep an eye for future runs and collect the logs. 

Need the workaround steps for documentation

**Comment by romayalon** [comment]
@rkomandu I sent you the steps document on slack

**Comment by rkomandu** [comment]
@romayalon , could you analyze from logs provided by Neesha on Friday. It has occurred after cleaning up and deploying the DAS S3 as well after our Thus call.

**Comment by romayalon** [comment]
@rkomandu @NeeshaPan 
I've looked into the logs and saw the following:
```
[32mSep-23 13:20:35.829[35m [Endpoint/14] [36m   [L1][39m core.endpoint.s3.s3_rest:: S3 REQUEST GET /export1-bucket1/FgBQ22SE/37026.Ia8bH5Yj09ey6Stu.rnd op get_object request_id l8eigjcl-3ck6b-jkz { host: [32m'10.49.0.103'[39m, [32m'user-agent'[39m: [32m'MinIO (linux; amd64) minio-go/v7.0.11 warp/0.5.2'[39m, authorization: [32m'AWS4-HMAC-SHA256 Credential=37isnwvQs1ws7quB1S3m/20220923/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0d04785aad9e6ec820cfa1e2d953b056b976133e3379fddb52c721bdca6d3400'[39m, [32m'x-amz-content-sha256'[39m: [32m'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'[39m, [32m'x-amz-date'[39m: [32m'20220923T132035Z'[39m }
[32mSep-23 13:20:35.829[35m [Endpoint/14] [36m   [L0][39m core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: [33m5002[39m, uid: [33m5001[39m, nsfs_only: [33mtrue[39m, new_buckets_path: [32m'export-user1/'[39m, backend: [32m'GPFS'[39m, warn_threshold_ms: [33m100[39m } file_path /nsfs/noobaa-s3res-4080029599/export-user1/export1-bucket1/FgBQ22SE/37026.Ia8bH5Yj09ey6Stu.rnd
[32mSep-23 13:20:35.830[35m [Endpoint/14] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/export1-bucket1/FgBQ22SE/37026.Ia8bH5Yj09ey6Stu.rnd</Resource><RequestId>l8eigjcl-3ck6b-jkz</RequestId></Error> GET /export1-bucket1/FgBQ22SE/37026.Ia8bH5Yj09ey6Stu.rnd {"host":"10.49.0.103","user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.5.2","authorization":"AWS4-HMAC-SHA256 Credential=37isnwvQs1ws7quB1S3m/20220923/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0d04785aad9e6ec820cfa1e2d953b056b976133e3379fddb52c721bdca6d3400","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"20220923T132035Z"} Error: check_bucket_boundaries error Unknown system error -116 /nsfs/noobaa-s3res-4080029599/export-user1/export1-bucket1/FgBQ22SE/37026.Ia8bH5Yj09ey6Stu.rnd Error: Stale file handle
    at NamespaceFS._is_path_in_bucket_boundaries (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:1434:33)
    at async NamespaceFS._check_path_in_bucket_boundaries (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:1445:15)
    at async NamespaceFS.read_object_md (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:508:13)
    at async Object.get_object [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_get_object.js:38:23)
    at async handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:147:19)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:64:9)
   ```
Notice the **stale file handle** error message we got from the file system, it's a different error than the errors we saw on previous runs.
There are many RPC connection timeouts and `  Warning  Unhealthy       125m  kubelet            Readiness probe failed: dial tcp 10.128.3.210:6001: connect: connection refused` in the endpoint logs/descriptions.
was there any activity in the background? like metallb issues
A must gather can help here if the system still available

**Comment by rkomandu** [comment]
@NeeshaPan , i think we no longer have the MG correct or you have got it done earlier ? 
Always we need MG and it has internally has the "noobaa diagnostics"

**Comment by rkomandu** [comment]
@romayalon , 
@NeeshaPan @nigamshaurya14 have taken up the custom builds that are provided in the slack thread for retrials. They are planning to post their inputs accordingly.

**Comment by NeeshaPan** [comment]
@romayalon I had ran the warp consecutively on 3 IP's for  sizes 50m, 10k and 60k. For size 50m no issues were and run completed without any error. For 60k run we got connection and for 10k we got `specified doesn't exist`  error during run.
I checked end-point logs for 10k size, however did not see "duplicate id" issue and also checked for duplicate entries as mentioned in KC page "https://www.ibm.com/docs/en/scalecontainernative?topic=t-known-issues#concept_zrs_kql_drb__noobaa_warp_issue", however did not find any entries.
Please find the attached must gather logs in below box notes and warp run for reference.
Box link: https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6to
[warp_2hr_run_10Oct_2ndIP.log](https://github.com/noobaa/noobaa-core/files/9748271/warp_2hr_run_10Oct_2ndIP.log)

**Comment by rkomandu** [comment]
@romayalon , does it mean the "no connection/route to host"  is due to the noobaa-endpoint got terminated with OOM killer ?

**Comment by romayalon** [comment]
@rkomandu yes I suspect that it happened when the endpoint pod was down

**Comment by rkomandu** [comment]
> @rkomandu yes I suspect that it happened when the endpoint pod was down

unfortunately @NeeshaPan or @nigamshaurya14 didn't mention that noobaa-endpoint have restarted when the run was Active. May be it got missed or is it evident from the MG about the "oc get pods -n openshift-storage" ?

**Comment by nigamshaurya14** [comment]
@romayalon  ran warp with new images shared above for object size 10k,100k and 30M, issue didn't come this time.

```
[root@hpo-app11 ~]# warp mixed --host=10.49.0.109 --access-key=9oJFECLWAFtFH0UTj5S2 --secret-key=PtuAn4KlSVWxcLC7SjcMpWswlbaWRNCsaATiynNY --obj.size=10K --du
ration=120m --bucket=buckettesting1 --debug --insecure --tls 2>&1 | tee  /tmp/warp-109ip.10K.shaurya.18-Oct.log
warp: Benchmark data written to "warp-mixed-2022-10-18[055632]-C57g.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 415.74 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 17.84 MiB/s, 1870.84 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 5.95 MiB/s, 623.61 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 1247.22 obj/s

Cluster Total: 23.79 MiB/s, 4157.41 obj/s over 2h0m0s.

```



```
[root@hpo-app11 ~]# warp mixed --host=10.49.0.110 --access-key=HiREjIVocxJWazFo7MHN --secret-key=eaDcYF+yuwcQ1VEeQTmmzsRia+hL1jZZaJSjjb34 --obj.size=100K --duration=120m --bucket=buckettesting2 --debug --insecure --tls 2>&1 | tee  /tmp/warp-110ip.100K.shaurya.18-Oct.log
Benchmarking:                1h50m00s / 2h00m00s ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░┃  91.68%
warp: Benchmark data written to "warp-mixed-2022-10-18[055727]-Ekgd.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 449.12 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 192.74 MiB/s, 2021.05 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 64.25 MiB/s, 673.68 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 1h59m59s.
 * Throughput: 1347.36 obj/s

Cluster Total: 256.99 MiB/s, 4491.21 obj/s over 2h0m0s.
warp: Cleanup Done.[root@hpo-app11 ~]#

```




```
[root@hpo-app11 ~]# warp mixed --host=10.49.0.111 --access-key=rUVUFlcpohsO4zWg5sFT --secret-key=lDdeT0xOqeVqghsWRo1x/J1YuC9dtaJ6W7UgHTcY --obj.size=30M --du
ration=120m --bucket=buckettesintg3 --debug --insecure --tls 2>&1 | tee  /tmp/warp-111ip.30M.shaurya.18-Oct.log
warp: Benchmark data written to "warp-mixed-2022-10-18[060033]-6I5k.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 1h59m55s.
 * Throughput: 6.81 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 1h59m56s.
 * Throughput: 876.96 MiB/s, 30.65 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 1h59m55s.
 * Throughput: 292.32 MiB/s, 10.22 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 1h59m56s.
 * Throughput: 20.43 obj/s

Cluster Total: 1169.25 MiB/s, 68.11 obj/s over 1h59m56s.
warp: Cleanup Done.[root@hpo-app11 ~]#

```

**Comment by romayalon** [comment]
@nigamshaurya14 great, did you capture must gather/ noobaa diagnose? would be glad to be sure everything is ok

**Comment by nigamshaurya14** [comment]
@romayalon it is just an update for what was tried yesterday as per discussion in the call. we will run with other object sizes as well to make sure that the bug is fixed. I will definately share  the logs in the final update.

**Comment by rkomandu** [comment]
@romayalon , from your above post does it mean the fix is on the way ? do you still need to have any recreate efforts to be made ? please let people know

**Comment by romayalon** [comment]
@rkomandu I would prefer to see other object sizes runs to be sure, and also to check the logs and the db tables
but yes the PR is up

**Comment by romayalon** [comment]
@nigamshaurya14 I created a new image that contains code review changes

**Comment by NeeshaPan** [comment]
@romayalon @rkomandu  Ran three rounds of warp run with` romyayalon/noobaa-core-nightly:dups_fix_up3` image and did not observe any issue in warp run. 
Warp run completed successfully without any issues.

Below are the runs tried on FVT1 system.
1. Ran warp run for 2hrs  for 10k, 20k and 30k obj sizes consecutively on 3 IP's
2. Ran warp run for 4hrs for 50k, 200k and 70m obj. sizes
3. Ran warp run for 8hrs for 10k, 500k and 70k

**Comment by nigamshaurya14** [comment]
@romayalon I ran warp on fvt3 with the image :  `romyayalon/noobaa-core-nightly:dups_fix_up3`

1. warp run passed for object size 1k,5k and 100k for 2 hours.
2. warp run failed for object size 1M,5M and 100M for 4 hours.

I saw 1 of the endpoint pod "noobaa-operator-5cf8b6d77d-5ks4x" restarted  as shown below:
```

[root@hpo-app11 openshift-storage]# oc get pod -n openshift-storage
NAME                                               READY   STATUS    RESTARTS      AGE
csi-addons-controller-manager-5f8c669c75-4k5ps     2/2     Running   0             7d15h
noobaa-core-0                                      1/1     Running   0             25h
noobaa-db-pg-0                                     1/1     Running   0             25h
noobaa-default-backing-store-noobaa-pod-e8967b26   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-2mttv                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-74cj5                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-8vgwk                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-gfz55                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-j9vg2                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-jnq6n                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-k9q85                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-tmh82                   1/1     Running   0             25h
noobaa-endpoint-6747868fc7-twwnw                   1/1     Running   0             25h
noobaa-operator-5cf8b6d77d-5ks4x                   1/1     Running   1 (18h ago)   7d15h
ocs-metrics-exporter-5f7d44b4bf-fn5d6              1/1     Running   0             8d
ocs-operator-6cc594d856-cc7wx                      1/1     Running   0             7d15h
odf-console-7fd7478775-rvxw5                       1/1     Running   0             8d
odf-operator-controller-manager-5b458d7f54-djk8n   2/2     Running   0             7d15h
rook-ceph-operator-6d7d4b45c7-kzbvj                1/1     Running   0             8d
[root@hpo-app11 openshift-storage]#
```


I found this error in its logs:
```

on verifying  logs of this endpoint "noobaa-operator-5cf8b6d77d-5ks4x", it says :
time="2022-10-21T08:14:04Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340044602e+12]}"
time="2022-10-21T08:14:04Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.6663400446e+12]}"
time="2022-10-21T08:14:04Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340044603e+12]}"
time="2022-10-21T08:14:04Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340044709e+12]}"
time="2022-10-21T08:14:04Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340044901e+12]}"
time="2022-10-21T08:14:05Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340044902e+12]}"
time="2022-10-21T08:14:07Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340047254e+12]}"
time="2022-10-21T08:14:08Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340048308e+12]}"
time="2022-10-21T08:14:10Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: update_master_change, Error: <nil>, Params: map[is_master:true]}"
time="2022-10-21T08:14:13Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.666340053858e+12]}"
```
I couldn't monitor the run during the failure and hence couldn't capture noobaa diagnostic logs at that time. However though I managed to capture Must gather logs during the run when there was no error and also today after the warp run had completed with error.


I didn't find any duplicate entry in bucketstats:

```
postgres=# \c nbcore
You are now connected to database "nbcore" as user "postgres".
nbcore=# SELECT data->>'bucket' as bucket,
nbcore-#             data->>'system' as system,
nbcore-#             jsonb_agg(jsonb_build_object('_id', _id)) as ids
nbcore-#             FROM bucketstats
nbcore-#             GROUP BY 1,2
nbcore-#             HAVING count(*) > 1;
 bucket | system | ids
--------+--------+-----
(0 rows)

```

Attaching must gather logs during and after the run as follows:

must gather logs during run : https://ibm.enterprise.slack.com/files/U02RQGT25GT/F047LRC8S90/must-gather.local.7305449135726363688-during-run.tar.gz

must gather logd after run : https://ibm.enterprise.slack.com/files/U02RQGT25GT/F048AGKFW56/must-gather.local.8744322243371186224-after-run.tar.gz

**Comment by nigamshaurya14** [comment]
I reproduced the issue today with same configuration, I found that it was due to disk-space ran out of space on storage cluster. I was able to capture logs this time during the failure. It was showing ENOSPC error on endpoint logs.
the warp ran well till 3:53 hrs out of 4 hours. seems the issue for which this bug was opened is fixed now.

**Comment by NeeshaPan** [comment]
@romayalon Any update on this issue?
Is the fix merged or are you going to merge the fix?

**Comment by romayalon** [comment]
https://github.com/noobaa/noobaa-core/pull/7101 backport PR to 4.12
I'll update regarding 4.11 when we will have more details

**Comment by rkomandu** [comment]
it is in 4.11.4

**Comment by NeeshaPan** [comment]
We had ran warp run with different obj sizes consecutively on 3 IP's  for different durations on odf 4.11.4 and did not observe this issue. Warp run was run for 2hrs, 4hrs, 6hrs, and 8hrs and it completed without any issues. Below is the odf version that we had installed on BM

ODF version
-------------
```
[root@hpo-app1 GM2_build]# oc get csv -n openshift-storage -o yaml | grep -i full_ve
      full_version: 4.11.4-4
      full_version: 4.11.4-4
      full_version: 4.11.4-4
```
So, We can close this issue.

**Comment by nimrod-becker** [comment]
Based on last comment and verification, closing
