### ISSUE TITLE
From HPO defect 830: changing log levels terminates all endpoint pods at the same time = 100% I/O outage

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#7118]
**Is your feature request related to a problem? Please describe.**
Description of what the problem is.
I/O outage from changing log levells
This is from 
https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/830

**Describe the solution you'd like**
Description of what you want to happen.

HPO Das is  high available solution, yet we can't maintain HA when log levels are changed.  When log levels are changed all noobaa endpoint pods terminate at the same time.  This results in an I/O outage for about 1 - 2 minutes.  This is not a very desirable side affect, especially for an HA solution.    It would be better if the pods did not all terminate at the same time to maintain I/O

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rkomandu** [comment]
@romayalon @nimrod-becker , please do add the NS-FS label and it is important to get it fixed in the next ODF 4.11.x and 4.12 stream, given that we ask Customers to do the log level change while other users are running IO would result in failure of their work as well.

**Comment by liranmauda** [comment]
Hi @MonicaLemay 
Please explain your flow, and add the prints of kubectl showing that the endpoint goes down before a new one came up.
We have this fix https://github.com/noobaa/noobaa-operator/pull/815 and I want to see if it is not enough.

**Comment by MonicaLemay** [comment]
Changed the log level.  The I/O outage stopped at this time: Tue Dec 13 17:19:17 MST 2022.  Uploaded the logs to 
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6to

**Comment by rkomandu** [comment]
Hi @liranmauda , Did you get a chance to look at the logs ?

**Comment by liranmauda** [comment]
@MonicaLemay @rkomandu 
how did you change the log level? 
changing it via `kubectl edit configmap/noobaa-config` is for **Internal/dev** use only.

Just wanted to make sure that you are aware that this future is not intended for customers.
It was initially asked by Akshat to help debug the dev flows.
changing the config map will get you downtime as the core pod is terminating.
also, increasing the debug level often not helping us, and actually make it harder for us to understand the issue, as the logs are too versus.
My suggestion is that you will increase the log level only when Dev asks, as it can lead us to lose the time of the root cause, and then we will need a reproduction.

The flow of the config map is to change an env variable in the core and endpoints pod.
In order to do that the kubernetes itself kills the pods and starts a new one with that env variable.

You can also increase the debug level via a CLI command and via an RPC call.
The RPC call or the CLI will not restart the pod.

I also suggest that you fix https://www.ibm.com/docs/en/scalecontainernative?topic=support-changing-log-level-spectrum-scale-das-components

Please tell me if that helped.

**Comment by rkomandu** [comment]
@liranmauda , thank you for the explanation.  Could you share the commands (CLI or RPC) to help us change the log levels. 

We don't change them often, however required to know how to change the same, so we can convey to Customers when needed. 

DAS documentation will be updated once the process is tried out.

**Comment by rkomandu** [comment]
@liranmauda any update on the RPC or the CLI command

**Comment by liranmauda** [comment]
@rkomandu 
you can use: `noobaa system set-debug-level`
```
$ noobaa system
Manage noobaa systems

Available Commands:
  create          Create a noobaa system
  delete          Delete a noobaa system
  list            List noobaa systems
  set-debug-level Sets core and endpoints debug level. level can be 'warn' or 0-5
  status          Status of a noobaa system
  yaml            Show bundled noobaa yaml

Use "noobaa <command> --help" for more information about a given command.
```

**Comment by rkomandu** [comment]
Quick check on the ODF 4.11.4 didn't show this from the noobaa-operator 
```

oc cp -n openshift-storage noobaa-operator-7f9dc67486-xhkb6:usr/local/bin/noobaa-operator /usr/local/bin/noobaa


/usr/local/bin/noobaa system
Manage noobaa systems

Available Commands:
  create      Create a noobaa system
  delete      Delete a noobaa system
  list        List noobaa systems
  status      Status of a noobaa system
  yaml        Show bundled noobaa yaml

Use "noobaa <command> --help" for more information about a given command.

 oc get csv  -n openshift-storage
NAME                                   DISPLAY                       VERSION               REPLACES                          PHASE
mcg-operator.v4.11.4                   NooBaa Operator               4.11.4                mcg-operator.v4.11.3              Succeeded
ocs-operator.v4.11.4                   OpenShift Container Storage   4.11.4                ocs-operator.v4.11.3              Succeeded
odf-csi-addons-operator.v4.11.4        CSI Addons                    4.11.4                odf-csi-addons-operator.v4.11.3   Succeeded
odf-operator.v4.11.4                   OpenShift Data Foundation     4.11.4                odf-operator.v4.11.3              Succeeded

```

Is there a way to get this noobaa binary or is it included in ODF 4.12?

**Comment by nimrod-becker** [comment]
Binary is included in ODF 4.12

**Comment by rkomandu** [comment]
@nimrod-becker , we are still extracting today noobaa binary form noobaa-operator (as we discussed that it should be shipped from the Major GA release perspective and the future z stream would be using that). 

Could you share the steps or the location where this is now in the ODF 4.12 code, so we no longer will extract.

**Comment by nimrod-becker** [comment]
https://access.redhat.com/downloads/content/rhel---8/x86_64/8740/mcg/5.8.0-42.el8/x86_64/fd431d51/package

**Comment by MonicaLemay** [comment]
@nimrod-becker Please help to clarify your comment above:
```
Binary is included in ODF 4.12, we do not recommend extracting from the operator pod.
The binary is built and published by red hat for all Linux, Win and OSX
```
I installed OCP  and ODF 4.12 on a cluster and did NOT get the new binary.  
```
[root@c83f1-app1 bin]# oc get csv
NAME                                   DISPLAY                       VERSION               REPLACES   PHASE
mcg-operator.v4.12.0                   NooBaa Operator               4.12.0                           Succeeded
metallb-operator.4.12.0-202301301729   MetalLB Operator              4.12.0-202301301729              Succeeded
ocs-operator.v4.12.0                   OpenShift Container Storage   4.12.0                           Succeeded
odf-csi-addons-operator.v4.12.0        CSI Addons                    4.12.0                           Succeeded
odf-operator.v4.12.0                   OpenShift Data Foundation     4.12.0                           Succeeded
[root@c83f1-app1 bin]#

```
I  copied the  /usr/loca/bin/noobaa to another file and then installed the rpm that you mentioned.  The 2 noobaa's were different .
```
[root@c83f1-app1 bin]# md5sum noobaa_after_4.12_install noobaa_from_rpm
992ce2c76861f86063311d12ff434da2  noobaa_after_4.12_install
fe12aac4d7da81cc73c27d0328a9d6e6  noobaa_from_rpm
[root@c83f1-app1 bin]#

```
Please clarify whqt  you meant by the binary is included in ODF 4.12.  As you can see, nothing was included when I installed.
Am I missing something?

**Comment by MonicaLemay** [comment]
I tested this on ODF and OCP 4.12 and CNSA and DAS 5.1.7 .  All endoint pods no longer restart all at once when log level is changed.  I can close this after Nimrod, answers the above question.

**Comment by rkomandu** [comment]
> https://access.redhat.com/downloads/content/rhel---8/x86_64/8740/mcg/5.8.0-42.el8/x86_64/fd431d51/package

@nimrod-becker , unable to access this link due to some Subscription Manager issues. Working with IBM team to get this fixed, but none had a clue. Could you provide me the contact from RH , who can help me with this ?

**Comment by rkomandu** [comment]
@nimrod-becker , could you answer Monica Question, then we can close this defect.

**Comment by nimrod-becker** [comment]
The comment is that the CLI is available on the operator pod, although we do not recommend of using that specific binary but rather take it from the Red Hat portal

**Comment by rkomandu** [comment]
> I tested this on ODF and OCP 4.12 and CNSA and DAS 5.1.7 . All endoint pods no longer restart all at once when log level is changed. I can close this after Nimrod, answers the above question.

@MonicaLemay , did you try with the Noobaa binary on setting the log level then it is good to close. 

@nimrod-becker , how is that we would like to communicate with Customers on this noobaa binary rpm.. Is this bundled in some other form ? As the Instructions in DAS KC needs to be updated for this , so Customers will set it when required for enabling the detailed logging.

**Comment by rkomandu** [comment]
@MonicaLemay , it seems with ODF release, the customer would have access to the Noobaa binary package as well. So there should be some way out there to document about this as we can't simply mention the noobaa CLI command for changing the settings w/o letting them know from where this is can be available.

**Comment by rkomandu** [comment]
@liranmauda or @nimrod-becker or @romayalon 
Earlier we have got these log levels to be set 

-- default_level
-- nsfs
-- all 

Now with this setting via the "noobaa CLI", the values are
"must be 'warn' or 0 to 5" 

So can we know what are the values at each level and what is the default value that it is set to now. Is it "0" ? 

We need to document this in our upcoming DAS KC page, early response is appreciated.

**Comment by rkomandu** [comment]
Also, what if we need to have this persistent for example in recreating a scenario / bug 

noobaa system set-debug-level 3
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: redirector.publish_to_cluster() Request: {Target: MethodAPI:debug_api MethodName:set_debug_level RequestParams:{Module:core Level:3}}
WARN[0000] RPC: GetConnection creating connection to wss://localhost:43503/rpc/ 0xc000522d20
INFO[0000] RPC: Connecting websocket (0xc000522d20) &{RPC:0xc00009d4a0 Address:wss://localhost:43503/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0000] RPC: Connected websocket (0xc000522d20) &{RPC:0xc00009d4a0 Address:wss://localhost:43503/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0000] ✅ RPC: redirector.publish_to_cluster() Response OK: took 6.0ms

Debug level was set to 3 successfully
**Debug level is not persistent and is only effective for the currently running core and endpoints pods**  --> if this is the case, is there any other way to turn it on ?

**Comment by romayalon** [comment]
default_level = 0
all = 5
nsfs = 5 & module is a certain struct of files specified in debug_config.js file in noobaa core, but this can not be used with this function, Module is hardcoded "core".
@nimrod-becker @liranmauda have you considered extending the API to support nsfs?

**Comment by rkomandu** [comment]
hi let us know the update on the "nsfs" ,we will mention it in our documentation. 

For now mentioned the noobaa system set-debug-level <value range from 0 - 5>

if "nsfs" is made available or not in ODF 4.12, if we know then documentation will be updated accordingly.

**Comment by nimrod-becker** [comment]
We can, should be hard, but will take some time to get to

**Comment by MonicaLemay** [comment]
Closing this issue as I have resloved this.
