### ISSUE TITLE
NSFS | Versioning | Implement GET/HEAD object 

### ISSUE THREAD

**Issue by v-harihar** [noobaa/noobaa-core#7128]
**Is your feature request related to a problem? Please describe.**
This feature is part of NSFS versioning. 

**Describe the solution you'd like**
GET object will return the latest or the requested version object.
Basically bucket can be version:

1. Disabled 

- No call flow will/behaviour will be changed

2. Enabled

- return the latest object if specific version is not requested. 
- fetch the stat of all objects and return the object which is requested for

4. Suspended
Same behaviour as in case of Version enabled

steps:
1. Funnel the application to namespaceFS.js based on bucketspace and namespace
2. if version is specified as part of the GET, then stat("version") under `.version`directory, 
 ```
   if present  
         return the file 
   else 
          return err
```
3. If no version specified then return the file under the specified path
4. Follow the same process for HEAD object, instead of data just return the metadata of the request file

@dannyzaken @romayalon Please correct if wrong

**Comment by romayalon** [comment]
Few comments:
1. Section 2 Enabled, last sentence -  No need to stat all objects, the only thing needed here is to create the correct path.
2. notice that the specified version_id can be the latest or past version under .versions.
if it's the latest it will be located in the directory itself and not under .versions/ except if it's a delete marker and latest, then the latest will be under .versions/. 
Also, notice that if version_id points to a delete marker ENOENT error should be thrown.

**Comment by v-harihar** [comment]
> No need to stat all objects
Yes, understood it wrongly. 

just a thought, to maintain versions of the object inside a `.version` directory, can we have one more directory by the name of the file and save all versions inside that directory. This way we can reduce `ls` time over the list of versions. When number of objects grow, this would become a bottel neck.

**Comment by romayalon** [comment]
@v-harihar sounds complicated to maintain, but we can suggest it in the research meeting and hear some opinions of the FS experts

**Comment by v-harihar** [comment]
IMHO, If we can handle it now, later we dont suffer when performance issues get it. In production, we must expect 1000s of objects and versions. All in one directory will lead to contention and looping through all versions of all objects. This is serious issue may be.

**Comment by guymguym** [comment]
@v-harihar the same issue can happen with a single key that has many versions too. 
I think that scanning all the versions is something we should keep for rare cases anyhow.
If we will have to deal with it we could even go another step and make a radix-tree of prefixes of the versions on a single key. But all those are quite complex to serve for the common call of list-versions.
Lets discuss this on our next call and think it through.

**Comment by v-harihar** [comment]
> And regarding list object versions - maybe i'm mistaken but I believe that one readdir operation on .versions/ should take less time than millions of readdir operations (when having millions of objects each has a directory under .versions/)

This is true. But if someone wants to do list the versions of a particular object, then noobaa will just go into the particular dir and return those versions. That is like doing readdir one dir and no need of doing readdir on all dirs of all objects.

Do we have any operation which needs to return versions of all objects ?

ex: $BUCKET_PATH/file1
for above object, the versions will be inside $BUCKET_PATH/.versions/ISDIR(file1)/$VERSION{1,2,3,4}

I understand only for list object versions, we need not to do all this. I am just trying to think what all operations depend on list object versions. 

I am still thinking through. :)

**Comment by romayalon** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html
So actually the default behavior of list-object-versions is to return all the bucket versions, The user can pass parameters to filter the result on the server side.
Always continue thinking, I appreciate it!

**Comment by v-harihar** [comment]
Then it doesn't make any sense going for file based directory. :)
