### ISSUE TITLE
FS Ops metrics data  are not getting from noobaa metrics routes `/metrics/nsfs_stats`

### ISSUE THREAD

**Issue by sanvidhansonone** [noobaa/noobaa-core#7134]
### Environment info
- NooBaa Version: **5.12.0**
- NooBaa Image: **quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:b495b59219d78ab468d1e1faedacfda59cb4b9fe13b253157897ff6899811de5**
- MCG Operator Image: **quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:bba4014365a803fc5dc3dec423c0212c0259dd819538e82b28cb7bbe2a0037b7**
- Platform: **Kubernetes 1.25.4 | OpenShift 4.12.0-rc.4**

#### oc get csv
```
$ oc get csv
NAME                                         DISPLAY                       VERSION             REPLACES   PHASE
mcg-operator.v4.12.0-143.stable              NooBaa Operator               4.12.0-143.stable              Succeeded
ocs-operator.v4.12.0-143.stable              OpenShift Container Storage   4.12.0-143.stable              Succeeded
odf-csi-addons-operator.v4.12.0-143.stable   CSI Addons                    4.12.0-143.stable              Succeeded
odf-operator.v4.12.0-143.stable              OpenShift Data Foundation     4.12.0-143.stable              Succeeded
```

### Actual behavior
1. FS Ops metrics data are not seen on NooBaa route `/metrics/nsfs_stats` after performing any s3 operation. 

### Expected behavior
1. It is expected to get FS Ops metrics from noobaa routes, on S3 Operations.

### Steps to reproduce
1. Set up s3 account to with access key and secret key
2. perform s3 operations like create_bucket, upload_object, list_object, download_object, delete_object. eg: `aws s3 mb s3://new-test-bucket1`,  `aws s3 data-test.txt s3://new-test-bucket1`,  `aws s3 cp s3://new-test-bucket1/data-test.txt` , `aws s3 ls s3://new-test-bucket1`  
3. use noobaa route to check metrics on `/metrics/nsfs_stats`
4. will get response without fs

### More information - Screenshots / Logs / Other output
**aws s3 mb s3://new-bucket-test1:**

<img width="613" alt="create_bucket" src="https://user-images.githubusercontent.com/107463477/208150418-d260666f-bf2b-4916-84e0-37f1ea9f441f.PNG">

**aws s3 rm s3://new-bucket-test1/data-object-test.txt:**

<img width="611" alt="delete_object" src="https://user-images.githubusercontent.com/107463477/208150644-a4bd523c-9132-4a6c-b73a-578def64e679.PNG">

**aws s3 cp s3://new-bucket-test1/data-object-test.txt /root/s3ops/data-object-test-download.txt:**

<img width="602" alt="download_object" src="https://user-images.githubusercontent.com/107463477/208150864-62d3260a-d310-4824-a70a-dfb82a938a22.PNG">

**aws s3 ls s3://new-bucket-test1:**

<img width="597" alt="list_object_after_upload_ops" src="https://user-images.githubusercontent.com/107463477/208151128-52a9f54c-47f0-4712-a749-e2bbd6707826.PNG">

### Please find must-gather logs:
https://ibm.ent.box.com/file/1092845779983?s=g16bxab8ujxixp9yy7q2cogh6apuiszl

**Comment by liranmauda** [comment]
Hi @sanvidhansonone 
It looks like we have missed backporting it from master:
```
$ git cherry -v HEAD master
- 35f37e4e37bf808e17321aa50f18ebf35dbd66d8 Fix https://bugzilla.redhat.com/show_bug.cgi?id=2125451
- 146182f8a5a4b4ce9fe95640f5f57ad292413378 Adding namespace sts
- f58261e372f5bfa3a9f709b93f0923896fce27a9 NSFS | Adding additional ops
...
+ 962f8a8c55e004c0834f48d4d447eb0e5164791b NSFS | add read object op metric
+ 7ba184c1f0873cfcd35ff33418b822aa4ff3f8d7 Collecting fs worker stats and sending it to the to /metrics/nsfs_stats
...
+ 473a986457dd4386137dedd3fd9651abb376d844 Documentation for NSFS metrics flow
```
@nimrod-becker ^^

**Comment by romayalon** [comment]
@liranmauda @nimrod-becker any news about the backport?

**Comment by nimrod-becker** [comment]
We will backport to the first 5.12.x (probably 5.12.1)
