### ISSUE TITLE
metrics data being send in chunk part by part to `metrics/nsfs_stats` 

### ISSUE THREAD

**Issue by sanvidhansonone** [noobaa/noobaa-core#7135]
### Environment info
- NooBaa Version: **5.12.0**
- NooBaa Image: **quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:b495b59219d78ab468d1e1faedacfda59cb4b9fe13b253157897ff6899811de5**
- MCG Operator Image: **quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:bba4014365a803fc5dc3dec423c0212c0259dd819538e82b28cb7bbe2a0037b7**
- Platform: **Kubernetes 1.25.4 | OpenShift 4.12.0-rc.4**

#### oc get csv
```
$ oc get csv
NAME                                         DISPLAY                       VERSION             REPLACES   PHASE
mcg-operator.v4.12.0-143.stable              NooBaa Operator               4.12.0-143.stable              Succeeded
ocs-operator.v4.12.0-143.stable              OpenShift Container Storage   4.12.0-143.stable              Succeeded
odf-csi-addons-operator.v4.12.0-143.stable   CSI Addons                    4.12.0-143.stable              Succeeded
odf-operator.v4.12.0-143.stable              OpenShift Data Foundation     4.12.0-143.stable              Succeeded
```

### Actual behavior
1.  metrics data are being send in chunk parts, if we performed upload_object operation on s3, we can get I/O write count and bytes for that s3 ops at first time and after the second operation done, we can see remaining data is being send to the metrics. 

### Expected behavior
1. Not sure about the logic is based on to handle failure state for sending data, but single operation data should be sent at a time. 
So metrics can be understandable. 

### Steps to reproduce
1. Set up s3 account to with access key and secret key
2. perform s3 operations like upload_object and list_object or any other operation to check this use case
3. use noobaa route to check metrics on `/metrics/nsfs_stats`
4. You can half or partial metrics data, half  data can get on first https call for `/metrics/nsfs_stats` , and remaining metrics can be found in after next operation completion.

### More information - Screenshots / Logs / Other output
*Upload Object:*
**aws s3 cp data-object-test.txt s3://new-bucket-test1**

<img width="606" alt="upload_object_without_metrics" src="https://user-images.githubusercontent.com/107463477/208156878-fc891bb2-b3bf-44f4-993b-48fb8aebb18a.PNG">

*Delete Object*
**aws s3 rm s3://new-bucket-test1/data-object-test.txt**
![image](https://user-images.githubusercontent.com/107463477/208157542-2b00532d-988e-4305-91ea-bcc66480f740.png)

### Please find must-gather logs:

https://ibm.ent.box.com/file/1092845779983?s=g16bxab8ujxixp9yy7q2cogh6apuiszl

**Comment by nimrod-becker** [comment]
will backport to 5.12.1
