### ISSUE TITLE
Automatically comment out mongo-db code in Tests.Dockerfile when using Mac with M1

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7179]
**Is your feature request related to a problem? Please describe.**
Today in every branch that I'm using I need to manually comment out `mongo-db` lines in `Tests.Dockerfile`. 

**Describe the solution you'd like**
That it will automatically run it depending on the OS architecture (M1 or others).

**Describe alternatives you've considered**
Leave it as is (and manually comment out this part of the code).

**Additional context**
https://github.com/noobaa/noobaa-core/blob/6ec43ac7cb3591307fb67d7841b5b3cb28b7b005/src/deploy/NVA_build/Tests.Dockerfile#L22-L26

**Comment by jackyalbo** [comment]
Closed by #7218
