### ISSUE TITLE
Use Singelton design in node (MDStore for example)

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7180]
**Is your feature request related to a problem? Please describe.**
Today we do not utilize the way that node js implements Singelton Pattern (class), for [more information](https://medium.com/swlh/node-js-and-singleton-pattern-7b08d11c726a).

**Describe the solution you'd like**
Utilize the way that node js implements Singelton Pattern (class).

**Describe alternatives you've considered**
Leave it as is.

**Additional context**
For example `MDStore` class:
https://github.com/noobaa/noobaa-core/blob/6ec43ac7cb3591307fb67d7841b5b3cb28b7b005/src/server/object_services/md_store.js#L63-L69

We can change to:
`module.exports = new MDStore()`

Except for the elegancy of code, I wonder if it improves performance (and if it is measurable).

**Comment by guymguym** [comment]
@shirady The main drawback against this pattern is that the constructor is called regardless of using the singleton, just upon requiring the module. This can have side effects. For example the current pattern allows to use cyclic requires, but the new pattern will fail . Another example is when the constructor has side effects such as setting globals or connecting to the database. So I think we cannot use this pattern without distinction. Performance is probably so negligible that cannot even be measured.
