### ISSUE TITLE
Change allowed group in web console

### ISSUE THREAD

**Issue by xacobecm** [noobaa/noobaa-core#7181]
**Is your feature request related to a problem? Please describe.**
We need to give access to users to the web console, and we do not wish to give them all the system:cluster-admins role in OpenShift.

**Describe the solution you'd like**
The possibility to change the allowed group in the web console to any other group(s), through a variable for example.

**Comment by xacobecm** [comment]
bump

**Comment by liranmauda** [comment]
hi @xacobecm 
noobaa FE is no longer supported, I suggest using the CLI instead.
hope that answers the question.
