### ISSUE TITLE
from I/O Ops, `noobaa_nsfs_read_count` and `noobaa_nsfs_read_bytes` are unclear, when to expect these I/O metrics

### ISSUE THREAD

**Issue by sanvidhansonone** [noobaa/noobaa-core#7189]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **OpenShift Data Foundation 4.12.0**
```
ODF Operator: 4.12.0
ODF Operator Image: quay.io/rhceph-dev/odf4-odf-rhel8-operator@sha256:64ad5456e46e04551488c0e0a3c10f02d6d1bef9a4e0273347b82acab9e8c101
Noobaa Core Image: quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:d4c5835811499197cc171ac81b0f2ed3d7d732773c8bdeba49598513d75a93b6
Noobaa Operator Image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:16ef22df996c4f77e63761a96b843a74da35023af2c33ec1e0b72f16d7c81fd8
```

### Actual behavior
1. `noobaa_nsfs_read_count`, `noobaa_nsfs_read_bytes` are not getting changed at any type of operations
it is only updating after multiple operations performed with `s3 mb`, `s3 ls`, `s3 cp`, `s3 rb`, `s3 rm` command. 

### Expected behavior
1. It's unclear understand the value of `noobaa_nsfs_read_count` and `noobaa_nsfs_read_bytes`.
 when to get this metrics updated, at or after which operations?
2. 
### Steps to reproduce
1. First perform all operations and check metrics after each operation you done, 
2. You can find 0 value for noobaa_nsfs_read_countand `noobaa_nsfs_read_bytes` for all single performed operation.
3. Perform all operation one by one, and check metrics after completion of all the s3 operations.
4. At this time you will get `noobaa_nsfs_read_count` and `noobaa_nsfs_read_bytes` with metrics value, but unmatched,
with `noobaa_nsfs_write_count` and `noobaa_nsfs_write_bytes` from I/O Ops

#### I/O Metrics after performing single ops:
`s3 mb`:
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 0
noobaa_nsfs_read_bytes: 0
noobaa_nsfs_write_bytes: 0
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```
`s3 ls`:
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 0
noobaa_nsfs_read_bytes: 0
noobaa_nsfs_write_bytes: 0
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```
`s3 rm`:
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 0
noobaa_nsfs_read_bytes: 0
noobaa_nsfs_write_bytes: 0
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```
`s3 cp`:
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 5
noobaa_nsfs_read_bytes: 0
noobaa_nsfs_write_bytes: 250
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```

#### I/O Metrics after performing all ops:
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 1
noobaa_nsfs_read_bytes: 8388608
noobaa_nsfs_write_bytes: 50
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```

**Comment by liranmauda** [comment]
@sanvidhansonone 
`s3 mb`, `s3 ls`, and `s3 rb` are not IO, in the seance of read bytes/count
read bytes/count are only valid in the read flows. 

regarding `s3 cp`, and `s3 rm`, it depends on what you are cp/rm
If this is what we consider a server-side copy, then the operation is link/unlink respectfully. 
link and unlink are not read IO so we are not expecting any count in this flow.

cp to an object in the bucket into your local machine or a different s3 bucket will lead to IO read count and bytes

**Comment by sanvidhansonone** [comment]
@liranmauda thanks 
We'll try cp objects and check it.

**Comment by sanvidhansonone** [comment]
Now its getting some values, after cp from remote to local
```
noobaa_nsfs_read_count: 333
noobaa_nsfs_write_count: 128
noobaa_nsfs_read_bytes: 2793406464
noobaa_nsfs_write_bytes: 1073741824
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0
```
thanks @liranmauda
