### ISSUE TITLE
Support versioned objects in log based replication

### ISSUE THREAD

**Issue by tangledbytes** [noobaa/noobaa-core#7252]
# Description
As of today (30th March 2023), log based replication implementation does **not** support versioned objects. This lack of support may not effect the correctness of the replication (iff scan based replication exists and is functional).

The following scenario is problematic:
1. Source bucket has versioning enabled.
2. User deletes a versioned object such that the deleted version is  _not_ the latest version.
3. Log based replication considers this a candidate for deletion and deletes the **latest** version from the destination bucket.
4. This gap is identified by the scan based replication and the replicator will replicate the missing object.

This gap has **severe implications** if and whenever we remove scan based replication.

Initial discussion on this are here: #7234

**Comment by liranmauda** [comment]
Fixed By: https://github.com/noobaa/noobaa-core/pull/7508
