### ISSUE TITLE
Run storage agent on local volume

### ISSUE THREAD

**Issue by mehdibad** [noobaa/noobaa-core#7333]
Like read in the wiki earlier, I'd like to learn more about running storage agent on local volume.
Thanks in advance.

**Comment by guymguym** [comment]
Hi @mehdibad !
You mean like this - https://github.com/noobaa/noobaa-core/wiki/NSFS-using-a-Local-PV-on-k8s ?
but for BackingStores (PV-Pool)? Or am I missing your question.

**Comment by mehdibad** [comment]
yes thanks for your help !
