### ISSUE TITLE
NSFS Presto uploads large file as multiparts, calls complete with short timeout, causing retries and race on the mpu dir

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7348]
### Environment info
- NooBaa Version: **5.10**
- Platform: **OpenShift 4.10**

### Actual behavior
1. NSFS complete_multipart_upload copies the parts one by one to a final file, and once it's done it moves the final file to target dir and deletes the parts files.
2. For 8 GB files, the default timeout of presto for the complete call is too short (few seconds), and then it aborts and sends second and third retries.
3. Presto will give up anyway, but we also see the retries print errors in the log of "No such file or directory", because the first complete request will eventually finish copying the data and then goes and deletes the part files, failing the other requests.

### Expected behavior
1. We should prefer to upload parts directly to the final file by offset if possible.
2. If not possible, we somehow need to "lock" the multipart directory to prevent more than one requests modifying it.

### Steps to reproduce
1. Presto write large files to S3 endpoints.

**Comment by guymguym** [comment]
@cxhong I don't know, it requires initial effort to implement the suggestion, but then also the question is if there is a path to backport this code, because this will not be a small fix. FYI @nimrod-becker.

For an immediate workaround, we better explore disabling multiparts in the client configuration (for example see [aws cli  multipart_threshold config option](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) that can be used to increase the size threshold), or alternatively try to keep the multipart but increase the timeout (for example in [aws cli there is the --cli-read-timeout flag](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-options.html)).

**Comment by cxhong** [comment]
Thanks @guymguym , let me update to customer

**Comment by rkomandu** [comment]
@guymguym the current chunks is 8M and it is less if we have 8G file to have too much time and deleting this in the .nsfs directory of the directory? 

I am trying to run 20GB file via cosbench hence asking (Fyre cluster though), what is the definition of large file here is 8GB ?

**Comment by rkomandu** [comment]
Every client is doing this thing of upload and S3 cli did it with 8M, whereas cosbench or any other application will do on its own the chunk size. Is my understanding w/r/t performing a 2GB upload (was done as multi-part)

**Comment by guymguym** [comment]
Hi @rkomandu 
Right, cosbench is using put object, not multi part upload (https://github.com/intel-cloud/cosbench/issues/138).

awscli does use multipart above an object size threshold that can be configured.
The size of each part in a multipart upload is 8M by default but can also be configured - see [multipart_chunksize](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).

I know that some clients will be easily configured to overcome this issue in the meanwhile, such as awscli that exposes many options to the user, but other applications that use s3 as a client could be less accessible to configure these settings and therefore will have to use multipart, which could hit this issue during the final complete-multipart-upload request. In that case, we can try to configure the timeout to allow the server to complete the parts copy on time.

Does this clarifies a bit more?

**Comment by cxhong** [comment]
@guymguym feedback from customer: 

> We have tested uploading without multipart several times and that seems to fix the issue.. but as we rely on applications to handle the data streams towards our S3 API we can not always disable it as it is an inbuilt feature of the products.
> AWS cli we only use for manual labor which is less than 1% of the work...
> if you need me to run these test for internal value i will happily do it but it does not solve anything for us to use these parameters as a workaround seen as we do not use AWS cli.
> let me know if its meant as a workaround or for further information for development.

they are asking if there is any workaround that can be implemented or when will a fix be available?  @nimrod-becker

**Comment by cxhong** [comment]
@guymguym and @nimrod-becker , any timeline? customer is waiting and like to know when this fixes will be available.
