### ISSUE TITLE
NSFS Object tagging support needed

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7454]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. NSFS does not store and retrieve object tagging -
https://github.com/noobaa/noobaa-core/blob/06d01f2e4c1ac1cd14368f82e550946ec2e5c23b/src/sdk/namespace_fs.js#L1647-L1662

### Expected behavior
1. Tagging should be supported by nsfs:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html
2. Tags are mutable, which is more flexible than the immutable object meta headers.
3. Can be stored as simple key-value xattrs with some prefix e.g `user.noobaa.tag.KEY=VALUE`

### Steps to reproduce
1. NA

**Comment by guymguym** [comment]
@nimrod-becker we need this for next release, can it be added to the plan?

**Comment by nimrod-becker** [comment]
ofc

**Comment by guymguym** [comment]
@nimrod-becker next Y

**Comment by romayalon** [comment]
@naveenpaul1 is there anything else or we can close this issue?

**Comment by naveenpaul1** [comment]
no @romayalon, Issue can be closed.
