### ISSUE TITLE
NSFS | NC | endpoint metrics should be exposed on prometheus and aggregated to parent of forks

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7482]
### Environment info
- NooBaa Version: **master**
- Platform: **Linux/mac**

### Actual behavior
1. Currently the endpoint_stats_collector just prints the metrics to log in standalone mode (no rpc_client).
3. In addition, when combined with --forks, the metrics port does not work as expected and will just load balance each request to a different fork.

### Expected behavior
1. We want the metrics to be exposed on prometheus metrics port from the endpoint.
2. We want the forks parent to serve the metrics port and be able to collect from all its children.

### Steps to reproduce
1. node src/cmd/nsfs --metrics_port 7001 .
2. curl http://localhost:7001

**Comment by naveenpaul1** [comment]
code merged to master
