### ISSUE TITLE
Issues observed in Delete Account command

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7547]
### Environment info
NooBaa Version: 5.15
Platform: Linux

### 1. config_root is mandatory for each account deletion 

https://github.com/noobaa/noobaa-core/issues/7583

### Command:

node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### Command:

node src/cmd/manage_nsfs account delete  --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### 2. Account should get deleted with name  

https://github.com/noobaa/noobaa-core/issues/7584

### Command:

node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config 
 --access_key a-abcdefghijklmn123456 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### Command :

node src/cmd/manage_nsfs account delete  --name noobaa 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### 3. Account should get deleted with uid:gid combination instead of accesskey  

https://github.com/noobaa/noobaa-core/issues/7585

### Command :

node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config 
 --access_key a-abcdefghijklmn123456 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### Command :

node src/cmd/manage_nsfs account delete  —uid:gid 1092:1093 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 23:17:21.405 [/2858951]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account delete  --access_key a-abcdefghijklmn123456 --config_root /ibm
Oct-25 23:17:26.805 [/2859008]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
[root@ramya-sc-worker noobaa-core]# 

### Command:

[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 23:17:21.405 [/2858951]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account delete  --access_key a-abcdefghijklmn123456
Oct-25 23:17:26.805 [/2859008]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: '' } ]
[root@ramya-sc-worker noobaa-core]#

**Comment by ramya-c3** [comment]
@guymguym @romayalon . Please take a look of this issue. Thank you.

**Comment by ramya-c3** [comment]
the following are apis exposed for ocp for deleting account which either accepts uid/gid or name So the delete functionality should work similar to the below api

```
Api: "account_api", Method: "delete_account",
			Params: getAccountParamsNoobaaRequest{
				Email: name,
				Uid:   int32(uid),
				Gid:   int32(gid),
			},
```

```
Api: "account_api", Method: "delete_account_by_property",
			Params: deleteAccountNoobaaRequestParams{
				Nsfs_account_config: deleteAccountNsfsAccountConfig{
					Uid: int(uid),
					Gid: int(gid),
				},
			},
```

**Comment by liranmauda** [comment]
@ramya-c3 Please break all those 4 observations into separate Issues, and please give the proper subject to each. 
The fixes are different and we should evaluate/discuss each separately.

**Comment by liranmauda** [comment]
Closing in favor of #7583 #7584 #7585 #7586
