### ISSUE TITLE
Issues identified in the Account update command

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7549]
### Environment info

NooBaa Version: 5.15
Platform: Linux

### Command :
 node src/cmd/manage_nsfs account update --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 23:33:53.707 [/2876543]   [LOG] CONSOLE:: Resource updated :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:34:01.535 [/2876597]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account update --config_root /ibm/fs1/ces/s3-config --name noobaa1 --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
^[[AOct-25 23:34:17.630 [/2876882]   [LOG] CONSOLE:: Resource updated :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:34:19.675 [/2876893]   [LOG] CONSOLE::  [ { name: 'noobaa1' } ]
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account update --config_root /ibm/fs1/ces/s3-config --name noobaa1 --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test

**Comment by ramya-c3** [comment]
@guymguym @romayalon . Please take a look of this issue. Thank you.

**Comment by ramya-c3** [comment]
This is used for updating acccount information

```
Api: "account_api", Method: "update_account_s3_access",
		Params: updateAccountParamsNoobaaRequest{
			Email:            name,
			S3_Access:        true,
			Default_resource: resource,
			NsfsAccountConfig: nsfsAccountConfigNoobaaRequest{
				NewBucketsPath: newBucketsPath,
			},
		},

```
This is for generating the accesskey and secretkey 
```
Api: "account_api", Method: "generate_account_keys",
		Params: getAccountParamsNoobaaRequest{
			Email: name,
		},
```

**Comment by liranmauda** [comment]
@ramya-c3 can you explain what you mean?
if I understand, the ask is to regenerate the s3 credentials for a specific account given the account name. 
Currently, we have a JSON file with the account access key as the name
Doing an update to the access key is creating a new file or renaming the file and updating the field inside.

We should remember that once we have a symlink for a <name>.json to that file, we will need to update the symlink as well.

@romayalon WDYT?
@ramya-c3 Please tell me if this is the ask here.

**Comment by romayalon** [comment]
Hey, 
What Liran wrote is implemented in my PR - https://github.com/noobaa/noobaa-core/pull/7591

**Comment by liranmauda** [comment]
Fixed by https://github.com/noobaa/noobaa-core/pull/7591

Please verify
