### ISSUE TITLE
Issues seen in help commands of noobaa standalone code

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7556]
### Environment info
NooBaa Version: 5.15
Platform: Linux

### Help message issues

It is observed that all the help commands provided for accounts and buckets have the grammatical,spell issues and they are even displaying the debug messages which is not expected. Following are the some examples 

###  Command :

[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs bucket --help
Oct-31 1:46:43.994 [/1449373]  [WARN] CONSOLE:: 

Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.

Oct-31 1:46:43.997 [/1449373]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <action> <type> [options...]

Oct-31 1:46:43.997 [/1449373]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Oct-31 1:46:43.997 [/1449373]  [WARN] CONSOLE:: Bucket Options:

    # Read Bucket details from json file, no need to mention all the propery one by one in CLI
    --from_file <dir>           (default none)          Set buckt/account schema full path.
                                                        Get bucket and account details from json file
    # required for add, replace 
    --email <email>             (default none)          Set the email for account/bucket.
    --path <dir>                (default none)          Set the bucket path.

    # required for add, replace and delete
    --name <name>               (default none)          Set the name for account/bucket.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)          Configuration files path for Noobaa standalon NSFS.

###  Command :

[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs bucket --help

Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.
 # Read Bucket details from json file, no need to mention all the property one by one in CLI
    --from_file <dir>           (default none)          Set bucket/account schema full path.
                                                        Get bucket and account details from json file
    # required for add, replace 
    --email <email>             (default none)          Set the email for account/bucket.
    --path <dir>                (default none)          Set the bucket path.

    # required for add, replace and delete
    --name <name>               (default none)          Set the name for account/bucket.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)          Configuration files path for Noobaa standalone NSFS.

###  Command :

node src/cmd/manage_nsfs account --help
Oct-31 1:49:39.919 [/1452209]  [WARN] CONSOLE:: 
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.

Oct-31 1:49:39.922 [/1452209]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <action> <type> [options...]

Oct-31 1:49:39.923 [/1452209]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Oct-31 1:49:39.923 [/1452209]  [WARN] CONSOLE:: Account Options:

    # Read account details from json file, no need to mention all the propery one by one in CLI
    --from_file <dir>           (default none)          Set buckt/account schema full path.
                                                        Get bucket and account details from json file                

    # required for add, replace 
    --name <name>               (default none)          Set the name for account/bucket.
    --email <email>             (default none)          Set the email for account/bucket.
    --uid <uid>                 (default as process)    Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)    Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)          The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)          Set the root of the filesystem where each subdir is a bucket.
    
    # required for add, replace and delete
    --access_key <key>          (default none)                                     Authenticate incoming requests for this access key only (default is no auth).
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)          Configuration files path for Noobaa standalon NSFS.

###  Command :

    # Read account details from json file, no need to mention all the propery one by one in CLI
    --from_file <dir>           (default none)          Set buckt/account schema full path.
                                                        Get bucket and account details from json file                

    # required for add, replace 
    --name <name>               (default none)          Set the name for account/bucket.
    --email <email>             (default none)          Set the email for account/bucket.
    --uid <uid>                 (default as process)    Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)    Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)          The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)          Set the root of the filesystem where each subdir is a bucket.
    
    # required for add, replace and delete
    --access_key <key>          (default none)                                     Authenticate incoming requests for this access key only (default is no auth).
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)          Configuration files path for Noobaa standalon NSFS.

**Comment by liranmauda** [comment]
@ramya-c3 Please verify

**Comment by ramya-c3** [comment]
still issues exists so reopening the defect

**Comment by liranmauda** [comment]
opening per @ramya-c3 request

@ramya-c3 `still issues exists` does not help us, please write the exact issue.
per each issue in the help, please write in this issue:
1. The line itself
2. What should be instead of it

For example: 
`"nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.` should be replaced with:
`"nsfs" is a noobaa-core command that runs a local S3 endpoint on top of a filesystem.

**Comment by ramya-c3** [comment]
# Read account details from json file, no need to mention all the propery one by one in CLI
--from_file <dir>           (default none)          Set buckt/account schema full path.
                                                    Get bucket and account details from json file                

# required for add, replace 
--name <name>               (default none)          Set the name for account/bucket.
--email <email>             (default none)          Set the email for account/bucket.
--uid <uid>                 (default as process)    Send requests to the Filesystem with uid.
--gid <gid>                 (default as process)    Send requests to the Filesystem with gid.
--secret_key <key>          (default none)          The secret key pair for the access key.
--new_buckets_path <dir>    (default none)          Set the root of the filesystem where each subdir is a bucket.

# required for add, replace and delete
--access_key <key>          (default none)                                     Authenticate incoming requests for this access key only (default is no auth).
--config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)          Configuration files path for Noobaa standalon NSFS.


This complete section need to be re-looked for add , delete ,update and list.This options has changed now so that is the reason i mentioned in one liner the issue still exists. For each option the help differs it becomes huge list if i start adding here

**Comment by liranmauda** [comment]
@ramya-c3 This is an output of an older version and not the latest.

Please write the exact version you are using.
Please use the latest version.

on the latest version please see if there are issues, and if there are, please write that as asked in the previous comment. 

Please use \`\`\` to wrap your text so it will be clear.

this is the latest help as it is in master:
```javascript
Nov-29 10:57:08.898 [/44445]  [WARN] CONSOLE::
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories
    to Noobaa as buckets. For more information refer to the noobaa docs.

Nov-29 10:57:08.899 [/44445]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]

Nov-29 10:57:08.899 [/44445]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Nov-29 10:57:08.899 [/44445]  [WARN] CONSOLE:: Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.

    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

Nov-29 10:57:08.899 [/44445]  [WARN] CONSOLE:: Bucket Options:

    # Read Bucket details from JSON file, no need to mention all the properties one by one in CLI
    --from_file <dir>                       (default none)                  Set bucket schema full path.
                                                                            Get bucket details from the JSON file
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update
    --email <email>             (default none)                              Set the email for the bucket.
    --path <dir>                (default none)                              Set the bucket path.

    # required for add, update, and delete
    --name <name>               (default none)                              Set the name for the bucket.
    --new_name <name>           (default none)                              Set a new name for the bucket.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.
```

**Comment by ramya-c3** [comment]
Version referred is noobaa-core-5.15.0-20231121.el8.x86_64.rpm

**Comment by ramya-c3** [comment]
[root@ramya-23 ~]# node /usr/local/noobaa-core/src/cmd/manage_nsfs --help
Error accrued while getting the data from /etc/noobaa-server/jwt: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/jwt'
Error accrued while getting the data from /etc/noobaa-server/server_secret: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/server_secret'
Error accrued while getting the data from /etc/noobaa-auth-token/auth_token: Error: ENOENT: no such file or directory, open '/etc/noobaa-auth-token/auth_token'
2023-11-29 13:30:06.964937 [PID-2509502/TID-2509502] FS::GPFS GPFS_DL_PATH=NULL, fs_napi will call default posix system calls
init_rand_seed: starting ...
read_rand_seed: opening /dev/random ...
Nov-29 13:30:07.107 [/2509502]  [WARN] CONSOLE:: 
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.

Nov-29 13:30:07.108 [/2509502]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]

Nov-29 13:30:07.108 [/2509502]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Nov-29 13:30:07.108 [/2509502]  [WARN] CONSOLE:: Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

Nov-29 13:30:07.110 [/2509502]  [WARN] CONSOLE:: Bucket Options:

    # Read Bucket details from JSON file, no need to mention all the properties one by one in CLI
    --from_file <dir>                       (default none)                  Set bucket schema full path.
                                                                            Get bucket details from the JSON file
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --email <email>             (default none)                              Set the email for the bucket.
    --path <dir>                (default none)                              Set the bucket path.

    # required for add, update, and delete
    --name <name>               (default none)                              Set the name for the bucket.
    --new_name <name>           (default none)                              Set a new name for the bucket.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

**Comment by ramya-c3** [comment]
if you observe in the account access_key is not mandatory still it shows as required so we need to keep it optional

**Comment by naveenpaul1** [comment]
@ramya-c3 now accesy_key is a mandatory field, It will be optional only when generating access key changes are merged.
If this is the only behavior you find in `--help`, please close this issue.
