### ISSUE TITLE
config_root/buckets/ permissions

### ISSUE THREAD

**Issue by janfrode** [noobaa/noobaa-core#7564]
### Environment info
- NooBaa Version: **master** 04db2688417e4410a0e4efa1095c9fb2c3a0b0b1
- Platform: **other: standalone**

### Actual behavior
```
# aws --profile user1 --endpoint http://localhost:6001 s3 mb s3://user1-bucket
make_bucket: user1-bucket

# aws --profile user2 --endpoint http://localhost:6001 s3 mb s3://user2-bucket
make_bucket failed: s3://user2-bucket An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

```
### Expected behavior
Expected to be able to create buckets for user2.

### Steps to reproduce
Create 2 accounts with different uid and gid. Make the config_root/buckets be an empty sticky world writable (seems like a bad idea, but whatever, chmod a+rwxt) directory. Create bucket as first user, then as second user. 

### More information - Screenshots / Logs / Other output

Reason for failure is that when creating the bucket for the first user, there is a config_root/buckets/.noobaa-config-nsfs directory created with read/write only by this user/group. So the second user is not able to use it.

```
# ls -al buckets/
total 258
drwxrwxrwt. 3 root root 262144 Nov  6 16:43 .
drwxr-xr-x. 4 root root   4096 Oct 26 12:32 ..
drwxrwx---. 3 9999 9999   4096 Nov  6 16:43 .noobaa-config-nsfs
-rw-rw----. 1 9999 9999    244 Nov  6 16:43 user1-bucket.json

```

**Comment by guymguym** [comment]
@janfrode we changed so that config dir files are owned by root. Is this still an issue in this case? Tnx

**Comment by shirady** [comment]
@janfrode we can create two accounts and each account would create its buckets.

I tried to reproduce it by using the following steps:
1. Create an account using manage NSFS CLI: `sudo node src/cmd/manage_nsfs account add --name shira-111 --email shira-111@noobaa.com --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid 1111 --gid 1111`.
2. Use alias: `alias s3-nc-user-1='AWS_ACCESS_KEY=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443'` (using the access key of `shira-111 ` account).
3. Create a bucket using AWS CLI: `s3-nc-user-1 s3 mb s3://user1-bucket`.
4. See output: `make_bucket: user1-bucket`.

Now we will do the same steps for another account.
5. Create an account using manage NSFS CLI: `sudo node src/cmd/manage_nsfs account add --name shira-222 --email shira-222@noobaa.com --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid 2222 --gid 2222`.
2. Use alias: `alias s3-nc-user-2='AWS_ACCESS_KEY=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443'`(using the access key of `shira-222 ` account).
3. Create a bucket using AWS CLI: `s3-nc-user-2 s3 mb s3://user2-bucket`.
4. See output: `make_bucket: user2-bucket`.

Anyway, by checking the permissions on the files you can see that the owner is the root:

> -rw-------  1 root  wheel  244 Jan 17 12:21 user1-bucket.json
> -rw-------  1 root  wheel  246 Jan 17 12:28 user2-bucket.json

**Comment by shirady** [comment]
closing the issue, we don't have it in the current master brach.
