### ISSUE TITLE
security issue with owner-writable bucket.json

### ISSUE THREAD

**Issue by janfrode** [noobaa/noobaa-core#7567]
### Environment info
- NooBaa Version: **master 04db2688417e4410a0e4efa1095c9fb2c3a0b0b1**
- Platform: **other: standalone noobaa**

### Actual behavior
Now that config_root/bucket/*json files are owned by the user account creating them,  any user with write access to the config_root/buckets/ files can steal all keys.

### Expected behavior
Don't let users steal keys.

### Steps to reproduce
As a user with access to create new buckets, create a new bucket. Then edit the buckets.json file (as this user) to point  "path" to config_root/accounts/

```
aws --profile user1 --endpoint http://localhost:6001 s3 mb s3://user1-bucket

sudo -u user1 vi /ibm/cesSharedRoot/noobaa/buckets/user1-bucket.json

aws --profile user1 --endpoint http://localhost:6001 s3 ls s3://user1-bucket
2023-11-06 16:37:02        491 0vtx7hPclLUgqgnFRH1i.json
2023-11-06 16:39:44        491 gDzY4OCKUC0BYeGHQhYH.json

aws --profile user1 --endpoint http://localhost:6001 s3 cp s3://user1-bucket/gDzY4OCKUC0BYeGHQhYH.json /tmp/
download: s3://user1-bucket/gDzY4OCKUC0BYeGHQhYH.json to ../../../../tmp/gDzY4OCKUC0BYeGHQhYH.json

```

**Comment by shirady** [comment]
@janfrode would you please check this again?
As Guy said the config dir files are owned by root.

**Comment by shirady** [comment]
closing the issue, we don't have it in the current master brach.

**Comment by romayalon** [comment]
This issue fixed by the following PRs - 
1. CLI flow - [7624](https://github.com/noobaa/noobaa-core/pull/7624) [7661](https://github.com/noobaa/noobaa-core/pull/7661)
2. S3 flow -  [7662](https://github.com/noobaa/noobaa-core/pull/7662)
