### ISSUE TITLE
Duplicate Account creation is allowed in noobaa standalone 

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7578]
Environment info
NooBaa Version: 5.15
Platform: Linux

Actual Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:34.010 [/2817991] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:51:35.254 [/2831958] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

Expected Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:34.010 [/2817991] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:51:35.254 [/2831958] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456 already exists

**Comment by liranmauda** [comment]
The cli is now chacking if the name or the access key exist and if they do, exits.
