### ISSUE TITLE
If new account name is provided then it should create new account instead of updating existing account

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7579]
Environment info
NooBaa Version: 5.15
Platform: Linux

### If the account name is different then it should create new account it should not replace the existing account.
Actual Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa1 --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:51.048 [/2818358] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:38:56.691 [/2818415] [LOG] CONSOLE:: [ { name: 'noobaa1' } ]
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:51:35.254 [/2831958] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:52:38.342 [/2833201] [LOG] CONSOLE:: [ { name: 'noobaa' } ]

Expected Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa1 --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:51.048 [/2818358] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:38:56.691 [/2818415] [LOG] CONSOLE:: [ { name: 'noobaa1' } ]
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:51:35.254 [/2831958] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:52:38.342 [/2833201] [LOG] CONSOLE:: [ { name: 'noobaa' } ,{name:’noobaa1’}]

**Comment by liranmauda** [comment]
@ramya-c3 In the example above the access key and secret key are the same.
`account add` should fail if there is an account with the same access key, as they should be unique.
 what is the use case for having 2 names for the same account?

**Comment by liranmauda** [comment]
Closing per my comment above.
@ramya-c3  If you think that we should have 2 names for the same account, please reopen this issue, and provide the use case of having 2 names for the same account
