### ISSUE TITLE
Accesskey and secretkey should be generated by accepting uid and gid instead of accesskey and secretkey

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7580]
### Environment info
NooBaa Version: 5.15
Platform: Linux

### Accesskey and secretkey should be generated by accepting uid and gid instead it is expecting accesskey and secretkey
Actual Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456
Oct-25 22:38:34.010 [/2817991] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

Expected Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa1 --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --uid 1023 --gid 1024

Oct-25 22:38:34.010 [/2817991] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

ACCESSKEY: a-abcdefghijklmn123456
SECRETKEY: s-abcdefghijklmn123456

**Comment by liranmauda** [comment]
@ramya-c3 
we will not generate based on the UID and GID.
if the access keys are not provided we will generate the keys as we do in the operator CLI calls.

**Comment by nimrod-becker** [comment]
These secrets are generated by NooBaa following AWS complexity considerations. I don't think we should allow users to input their own. We should allow listing with secrets and then this option should not be neccesary
