### ISSUE TITLE
config_root should not be mandatory for account creation

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7581]
### Environment info

NooBaa Version: 5.15
Platform: Linux

### Command:

[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 
Oct-25 22:38:34.010 [/2817991]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456

### Command:

[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 
Oct-25 22:38:34.010 [/2817991]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456

**Comment by liranmauda** [comment]
This is not mandatory, you can see it in the help. you can set it up if you need to change the default (for any reason, such as permissions)
https://github.com/noobaa/noobaa-core/blob/af27d3d731c38d424ba654984295dc3b373bbb03/src/cmd/manage_nsfs.js#L135C9-L135C9
