### ISSUE TITLE
Add @ symbol for the account name

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7582]
### Environment info
NooBaa Version: 5.15
Platform: Linux

We should also have the "@" symbol for the account name as well, this would help the Storage admin to directly email the credentials via email to respective users

**Comment by liranmauda** [comment]
@ramya-c3 can you explain a bit more? 
and can you give an example?

**Comment by liranmauda** [comment]
Adding the @ symbol to the account name can be done using the --name flag and should not be done automatically in the code.
