### ISSUE TITLE
config_root should not bemandatory for each account deletion

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7583]
### Environment info
NooBaa Version: 5.15
Platform: Linux

###  config_root is mandatory for each account deletion
Actual Behaviour:
Command:
node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:35:57.649 [/2815112] [LOG] CONSOLE:: Resource deleted : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218] [LOG] CONSOLE:: []

Expected Behaviour: config_root should be optional
Command:
node src/cmd/manage_nsfs account delete --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:35:57.649 [/2815112] [LOG] CONSOLE:: Resource deleted : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218] [LOG] CONSOLE:: []

**Comment by liranmauda** [comment]
This is not mandatory, you can see it in the help. you can set it up if you need to change the default (for any reason, such as permissions)
https://github.com/noobaa/noobaa-core/blob/af27d3d731c38d424ba654984295dc3b373bbb03/src/cmd/manage_nsfs.js#L135C9-L135C9
