### ISSUE TITLE
Account should get deleted with name

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7584]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
Command:
node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config
--access_key a-abcdefghijklmn123456
Oct-25 22:35:57.649 [/2815112] [LOG] CONSOLE:: Resource deleted : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218] [LOG] CONSOLE:: []

### Expected behavior
Command :
node src/cmd/manage_nsfs account delete --name noobaa
Oct-25 22:35:57.649 [/2815112] [LOG] CONSOLE:: Resource deleted : a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218] [LOG] CONSOLE:: []

### Steps to reproduce
1.

**Comment by liranmauda** [comment]
Fixed by: https://github.com/noobaa/noobaa-core/pull/7591

Please verify
