### ISSUE TITLE
Account should get deleted with uid:gid combination instead of accesskey  

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7585]
### Environment info
NooBaa Version: 5.15
Platform: Linux

Account should get deleted with uid:gid combination instead of accesskey  

### Command :

node src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config 
 --access_key a-abcdefghijklmn123456 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

### Command :

node src/cmd/manage_nsfs account delete  —uid:gid 1092:1093 
Oct-25 22:35:57.649 [/2815112]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 22:36:00.737 [/2815218]   [LOG] CONSOLE::  []

**Comment by liranmauda** [comment]
@ramya-c3 why do we want to delete an account with a specific UID:GID? 
and if we will actually do that, how will it behave? will it delete all the accounts that have this UID:GID set?

**Comment by romayalon** [comment]
@liranmauda Ramya said in the last HPO meeting that they want all the accounts having this uid and gid pair to get deleted.
They asked it because it was a requirement also on HPO.

**Comment by liranmauda** [comment]
Thanks @romayalon for clearing this out.
I never saw such a requirement, and I am not convinced that we should add it to the CLI. 
I will take it with @nimrod-becker
@ramya-c3 can you describe the use case?

**Comment by ramya-c3** [comment]
In case if user want to delete list of accounts based on uid:gid then this use case helps. instead of deleting each one this will be quicker solution

**Comment by romayalon** [comment]
As we discussed in today's meeting, delete by uid:gid will be replaced by list by uid:gid pair.

**Comment by guymguym** [comment]
#7673 was created to support this by list accounts

**Comment by ramya-c3** [comment]
[root@ramyamc-12 noobaa-core]# node src/cmd/manage_nsfs account delete --uid 23 --gid 23 2>/dev/null
{
  "error": {
    "code": "InvalidArgument",
    "message": "Invalid argument",
    "detail": "uid, gid invalid options for account delete, please use only: name, access_key, config_root"
  }
}

**Comment by romayalon** [comment]
@ramya-c3 see my comment, on the HPO meeting we decided that we will support list by uid:gid instead of delete by uid:gid

> As we discussed in today's meeting, delete by uid:gid will be replaced by list by uid:gid pair.

**Comment by romayalon** [comment]
@ramya-c3 did you see my last comment?

**Comment by madhuthorat** [comment]
There is a workaround that can be used for this handling - list with uid:gid then delete with retrieved accesskey.
