### ISSUE TITLE
Account should get deleted / should throw the error if invalid config root provided. Validation is not happening properly

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7586]
### Environment info
NooBaa Version: 5.15
Platform: Linux

### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 23:17:21.405 [/2858951]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account delete  --access_key a-abcdefghijklmn123456 --config_root /ibm
Oct-25 23:17:26.805 [/2859008]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
[root@ramya-sc-worker noobaa-core]# 

### Command:

[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email noobaa@gmail.com --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 23:17:21.405 [/2858951]   [LOG] CONSOLE:: Resource created :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account delete  --access_key a-abcdefghijklmn123456
Oct-25 23:17:26.805 [/2859008]   [LOG] CONSOLE:: Resource deleted :  a-abcdefghijklmn123456
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: '' } ]
[root@ramya-sc-worker noobaa-core]#

**Comment by liranmauda** [comment]
Any use of invalid config_root will lead to:
```sh
$ node src/cmd/manage_nsfs account delete --config_root /test --name noobaa1 --email noobaa1@gmail.com --new_buckets_path /Users/liranmauda/Documents/nsfs_1 --access_key abc2 --secret_key abc2 --uid 4 --gid 4
Nov-20 13:15:26.960 [/80604] [ERROR] CONSOLE:: NSFS Manage command: exit on error Error: ENOENT: no such file or directory, mkdir '/test'
```
