### ISSUE TITLE
Accounts should be listed with all the details present in the manifest

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7587]
### Environment info

NooBaa Version: 5.15
Platform: Linux

### All Account should be listed with all the details present in the manifest
Actual Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
Expected Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[<noobaa@gmail.com|noobaa@gmail.com](mailto:noobaa@gmail.com)>,new_buckets_path:/ibm/fs2  } ]

**Comment by liranmauda** [comment]
https://github.com/noobaa/noobaa-core/pull/7568 is adding --wide flag to show the full details of all the accounts in the list

**Comment by ramya-c3** [comment]
Still we are not seeing the access key and secret key as part of the list so reopening this defect

**Comment by naveenpaul1** [comment]
reopening the issue as requested by @ramya-c3

**Comment by liranmauda** [comment]
https://github.com/noobaa/noobaa-core/issues/7619#issuecomment-1829393249
@ramya-c3 @PravinRanjan10 Please provide the details:
1. The behavior you see and why it is not what you expect.
2. The exact version and revision that the code is on

**Comment by romayalon** [comment]
@ramya-c3 this should work now with --show_secrets flag, adding request validation label
