### ISSUE TITLE
Account details should be listed with particular accountName

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7588]
### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]

### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config —name noobaa
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[noobaa@gmail.com](mailto:noobaa@gmail.com),new_buckets_path:/ibm/fs2  } ]

**Comment by liranmauda** [comment]
listing a single account is not a list, if we want to get specific account details using the account name, we should use the account status command. 
Keeping this issue open till we have a symlink between account and name, and then status can work with only the name flag and without the access key and secret key.

**Comment by ramya-c3** [comment]
we want to see the accesskey and secret key information as part of the status so reopening the defect. if we want to delete it using access key we need to have this info view so we need this info as well.

**Comment by liranmauda** [comment]
reopened as per @ramya-c3 request.
@ramya-c3 
access key and secret key are secrets and should not be printed.
deleting an account per its access key should not be allowed, Access keys are used for access to account resources and should not grant the option to delete the entire account based on it.
To sum it up:
1. access keys should not be printed unless it is the creation of the account, then you need them to be written
2. access keys can be reached by reading the config file, but the CLI should not expose them
3. delete should be based on the account name only and not on the access keys.

@nimrod-becker @romayalon @guymguym WDYT?

**Comment by liranmauda** [comment]
another thing is that the `--wide` flag is printing the account details:
```sh
$ node src/cmd/manage_nsfs account list --wide --config_root /private/tmp/test_bucketspace_fs/config_root_manage_nsfs1

...
Nov-28 12:16:34.871 [/16530]   [LOG] CONSOLE:: Account list: [ { name: 'account1', email: 'account1@noobaa.io', creation_date: '2023-11-28T10:16:08.829Z', new_buckets_path: '/private/tmp/test_bucketspace_fs/root_path_manage_nsfs1/new_buckets_path_user1/' } ]
```

**Comment by romayalon** [comment]
@liranmauda uid and gid are also not printed for some reason...

**Comment by liranmauda** [comment]
> Issues observed in Account List command #7548

@romayalon it was intended. (see https://github.com/noobaa/noobaa-core/pull/7568) 
as described in https://github.com/noobaa/noobaa-core/issues/7548 under the Expected Behaviour of issue number 1 the list should return:
```
Expected Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127] [LOG] CONSOLE:: [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[<noobaa@gmail.com|noobaa@gmail.com](mailto:noobaa@gmail.com)>,new_buckets_path:/ibm/fs2 } ]
```

**Comment by nimrod-becker** [comment]
For access and secret, we can add a --show-secrets (or something similar) and then show it

**Comment by romayalon** [comment]
@ramya-c3 --wide, --show_secrets are available now, please use the status command for the account's full data.
https://github.com/noobaa/noobaa-core/pull/7655
adding require validation
