### ISSUE TITLE
Duplicate requests for create bucket command with same data is showing as success

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7592]
### Environment info
- NooBaa Version: 5.15
- Platform: Standalone noobaa

### Actual behavior
1.[root@anan2node-x-worker1 noobaa-core]# node src/cmd/manage_nsfs account list

Oct-31 2:37:14.290 [/985804]   [LOG] CONSOLE::  [ { name: 'ibm_accnt4' } ]

[root@anan2node-x-worker1 noobaa-core]# node src/cmd/manage_nsfs account add --name ibm_accnt4 --email noobaa4@gmail.com --new_buckets_path /mnt/fs1/ --access_key abcdefgh --secret_key abcdefgh --uid 10110 --gid 10010

Oct-31 2:37:58.313 [/986214]   [LOG] CONSOLE:: Resource created :  abcdefgh

### Expected behavior
1.
[root@anan2node-x-worker1 noobaa-core]# node src/cmd/manage_nsfs account add --name ibm_accnt4 --email noobaa4@gmail.com --new_buckets_path /mnt/fs1/ --access_key abcdefgh --secret_key abcdefgh --uid 10110 --gid 10010

Oct-31 2:37:58.313 [/986214]   [LOG] CONSOLE:: Resource already exist :  abcdefgh

**Comment by liranmauda** [comment]
@ramya-c3 
The subject is about a bucket and the description is about an account. 

In both cases, https://github.com/noobaa/noobaa-core/pull/7591 fixed it.

Please verify.
