### ISSUE TITLE
The RPM should support both RHEL 8 and RHEL 9

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#7608]
https://github.com/noobaa/noobaa-core/pull/7571 changed the centos base to 9.

The RPM should support both RHEL 8 and RHEL 9

We should patch the single line that changes the `'libraries': ['/lib64/libboost_thread.so.1.75.0']` 
We should do it dynamically, On RHEL9 keep it, and on RHEL 8 change it to 1.66 back.
We should also use the correct base for supporting both RHEL versions.
We should change the RPM name according to the RHEL version it supports.

**Comment by romayalon** [comment]
Fixed by https://github.com/noobaa/noobaa-core/pull/7607
