### ISSUE TITLE
Still we are not seeing the access key and secret key as part of the list so reopening this defect

### ISSUE THREAD

**Issue by PravinRanjan10** [noobaa/noobaa-core#7619]
Still we are not seeing the access key and secret key as part of the list so reopening this defect

_Originally posted by @ramya-c3 in https://github.com/noobaa/noobaa-core/issues/7587#issuecomment-1829306412_

**Comment by liranmauda** [comment]
@PravinRanjan10 When there is an issue, please ask us in that issue to reopen it if it was closed and not resolved.
@naveenpaul1 re-opened it.
the `Still we are not seeing the access key and secret key as part of the list so reopening this defect` statement will not help us understand what is missing.
When you ask for a reopen, please provide the behavior you see and why it is not what you expect.
Please also provide the exact version and revision that the code is on. 
Please use the latest version when you are verifying issues. 
Closing.
