### ISSUE TITLE
Deletion of Account error message is not clear

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7620]
### Environment info
- NooBaa Version: 5.15
- Platform: Standalone

### Actual behavior
1. node /usr/local/noobaa-core/src/cmd/manage_nsfs account delete --name accout1 --uid 0 --gid 0 --accessKey  
ERRO[2023-11-27T07:03:44+01:00] Execute command failed
info:
Error accrued while getting the data from /etc/noobaa-server/jwt: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/jwt'
Error accrued while getting the data from /etc/noobaa-server/server_secret: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/server_secret'
Error accrued while getting the data from /etc/noobaa-auth-token/auth_token: Error: ENOENT: no such file or directory, open '/etc/noobaa-auth-token/auth_token'
2023-11-27 07:03:44.619025 [PID-664252/TID-664252] FS::GPFS GPFS_DL_PATH=NULL, fs_napi will call default posix system calls
init_rand_seed: starting ...
read_rand_seed: opening /dev/random ...
Nov-27 7:03:44.762 [/664252]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Nov-27 7:03:44.763 [/664252]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d
Nov-27 7:03:44.766 [/664252]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Nov-27 7:03:44.766 [/664252]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Nov-27 7:03:44.767 [/664252]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/buckets
Nov-27 7:03:44.776 [/664252]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
rand_seed: OpenSSL 3.0.10+quic 1 Aug 2023 seeding randomness
Nov-27 7:03:44.776 [/664252]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/accounts
Nov-27 7:03:44.777 [/664252]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/access_keys
Nov-27 7:03:44.781 [/664252] [ERROR] CONSOLE:: NSFS Manage command: Could not find account to update { name: 'accout1', creation_date: '2023-11-27T06:03:44.777Z', access_keys: [ { access_key: undefined, secret_key: undefined } ], nsfs_account_config: { distinguished_name: undefined, uid: 0, gid: 0, new_buckets_path: undefined } } [Error: ENOENT: no such file or directory, open '/etc/noobaa.conf.d/accounts/accout1.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/etc/noobaa.conf.d/accounts/accout1.json' }
Nov-27 7:03:44.781 [/664252]  [WARN] CONSOLE:: 
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.

Nov-27 7:03:44.781 [/664252]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]

Nov-27 7:03:44.781 [/664252]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Nov-27 7:03:44.782 [/664252]  [WARN] CONSOLE:: Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

error: exit status 1 
ERRO[2023-11-27T07:03:44+01:00] failed to execute command. stderr:exit status 1 
ERRO[2023-11-27T07:03:44+01:00] Failed to delete account!!                   

### Expected behavior
1. If account doesnot exist it should throw account does not error
2. If access key is invalid then the respective key error should be thrown 

### Steps to reproduce
1.

**Comment by liranmauda** [comment]
@ramya-c3 Please provide the exact version and revision that it was tested on (5.15-<revision>)

**Comment by romayalon** [comment]
@ramya-c3 Adding request validation, should be clearer after the errors/responses refactoring https://github.com/noobaa/noobaa-core/pull/7655
