### ISSUE TITLE
NSFS | NC | CLI | account add - new_buckets_path should be optional and set allow_bucket_creation to false if missing

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7625]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Currently on account add - new_buckets_path is mandatory.

### Expected behavior
1. new_buckets_path should be optional and set allow_bucket_creation to false if missing. 
Details: 
1. allow_bucket_creation should be added to account_nsfs_schema.
2. need to check if allow_bucket_creation === true in bucketspace_fs on create bucket.

### Steps to reproduce
1. run account add without specifying new_buckets_path.

**Comment by romayalon** [comment]
@ramya-c3 adding request validation label, Naveen merged a fix -  [7682](https://github.com/noobaa/noobaa-core/pull/7682) PR, please close it if verified.

**Comment by PravinRanjan10** [comment]
[root@prscale-12 noobaa-core]# node src/cmd/manage_nsfs account add --name demoo-acc-1 --email abc@email.com --uid 1000 --gid 2000 2>/dev/null
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "name": "demoo-acc-1",
      "email": "abc@email.com",
      "creation_date": "2024-01-23T09:05:32.613Z",
      "access_keys": [
        {
          "access_key": "wNftlEWdL61o91F4sLdp",
          "secret_key": "M8iO22z515C4HB1iwVDpd0r7w4dDcaFogwHelxwD"
        }
      ],
      "nsfs_account_config": {
        "uid": 1000,
        "gid": 2000
      },
      "allow_bucket_creation": false,
      "_id": "65af815c42aea515175c7b44"
    }
  }
}

**Comment by PravinRanjan10** [comment]
LGTM
