### ISSUE TITLE
Sometimes account deletion not happening for some accounts

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7631]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
Some accounts are not getting deleted even though they display in the account list

 [root@ramya-23 ~]# node /usr/local/noobaa-core/src/cmd/manage_nsfs account list
Error accrued while getting the data from /etc/noobaa-server/jwt: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/jwt'
Error accrued while getting the data from /etc/noobaa-server/server_secret: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/server_secret'
Error accrued while getting the data from /etc/noobaa-auth-token/auth_token: Error: ENOENT: no such file or directory, open '/etc/noobaa-auth-token/auth_token'
2023-11-27 08:07:31.874218 [PID-788314/TID-788314] FS::GPFS GPFS_DL_PATH=NULL, fs_napi will call default posix system calls
init_rand_seed: starting ...
read_rand_seed: opening /dev/random ...
Nov-27 8:07:32.020 [/788314]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Nov-27 8:07:32.024 [/788314]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d
Nov-27 8:07:32.025 [/788314]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Nov-27 8:07:32.025 [/788314]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Nov-27 8:07:32.034 [/788314]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
rand_seed: OpenSSL 3.0.10+quic 1 Aug 2023 seeding randomness
Nov-27 8:07:32.035 [/788314]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/buckets
Nov-27 8:07:32.037 [/788314]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/accounts
Nov-27 8:07:32.040 [/788314]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/access_keys
Nov-27 8:07:32.045 [/788314]   [LOG] CONSOLE:: Account list: [ 'noobaa1', 'noobaa1', 'account11' ]
Nov-27 8:07:32.878 [/788314]   [LOG] CONSOLE:: generate_entropy: entropy_avail 2687
Nov-27 8:07:32.879 [/788314]   [LOG] CONSOLE:: init_rand_seed: done
[root@ramya-23 ~]# 

node /usr/local/noobaa-core/src/cmd/manage_nsfs account delete --name account11 --uid 0 --gid 0 --accessKey  
ERRO[2023-11-27T08:07:53+01:00] Execute command failed
info:
Error accrued while getting the data from /etc/noobaa-server/jwt: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/jwt'
Error accrued while getting the data from /etc/noobaa-server/server_secret: Error: ENOENT: no such file or directory, open '/etc/noobaa-server/server_secret'
Error accrued while getting the data from /etc/noobaa-auth-token/auth_token: Error: ENOENT: no such file or directory, open '/etc/noobaa-auth-token/auth_token'
2023-11-27 08:07:53.479794 [PID-790369/TID-790369] FS::GPFS GPFS_DL_PATH=NULL, fs_napi will call default posix system calls
init_rand_seed: starting ...
read_rand_seed: opening /dev/random ...
Nov-27 8:07:53.620 [/790369]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Nov-27 8:07:53.621 [/790369]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d
Nov-27 8:07:53.625 [/790369]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Nov-27 8:07:53.625 [/790369]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Nov-27 8:07:53.626 [/790369]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/buckets
Nov-27 8:07:53.634 [/790369]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
rand_seed: OpenSSL 3.0.10+quic 1 Aug 2023 seeding randomness
Nov-27 8:07:53.634 [/790369]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/accounts
Nov-27 8:07:53.634 [/790369]   [LOG] CONSOLE:: NSFS config root dir exists: /etc/noobaa.conf.d/access_keys
Nov-27 8:07:53.641 [/790369] [ERROR] CONSOLE:: NSFS Manage command: Could not find account to update { name: 'account11', creation_date: '2023-11-27T07:07:53.635Z', access_keys: [ { access_key: undefined, secret_key: undefined } ], nsfs_account_config: { distinguished_name: undefined, uid: 0, gid: 0, new_buckets_path: undefined } } [Error: ENOENT: no such file or directory, open '/etc/noobaa.conf.d/accounts/account11.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/etc/noobaa.conf.d/accounts/account11.json' }
Nov-27 8:07:53.641 [/790369]  [WARN] CONSOLE:: 
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.

Nov-27 8:07:53.641 [/790369]  [WARN] CONSOLE:: Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]

Nov-27 8:07:53.641 [/790369]  [WARN] CONSOLE:: Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.

Nov-27 8:07:53.642 [/790369]  [WARN] CONSOLE:: Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

error: exit status 1 
ERRO[2023-11-27T08:07:53+01:00] failed to execute command. stderr:exit status 1 
ERRO[2023-11-27T08:07:53+01:00] Failed to delete account!!                   

### Expected behavior
We are unable to delete accounts even though it shows in the account list

### Steps to reproduce
1.

**Comment by naveenpaul1** [comment]
@ramya-c3 could you please add a specific scenario here? 
history of account creation and update commands for such an account would help us narrow down the issue.
Also please check the status of access_key and account config files.

**Comment by ramya-c3** [comment]
Unable to reproduce this with latest build
