### ISSUE TITLE
Bucket list for a user account with bucket added with ‘node.. bucket add’ doesn’t work 

### ISSUE THREAD

**Issue by madhuthorat** [noobaa/noobaa-core#7634]
### Environment info
- NooBaa Version: **noobaa-core-5.15.0-1.el8.x86_64_20231106.rpm**
- Platform: **RHEL 8.x**

### Actual behavior
1. Bucket listing for a user account fails after a bucket is added with  ‘node.. bucket add’.

### Expected behavior
1. Bucket listing for a user account should succeed after a bucket is added with  ‘node.. bucket add’.

### Steps to reproduce
1. Add account: 
```
# node src/cmd/manage_nsfs account add --name project1 --email project1@gmail.com --access_key pr1 --secret_key pr1 --new_buckets_path /root/project1-data --uid "1602" --gid "1996"
# alias s3p1='AWS_ACCESS_KEY_ID=pr1 AWS_SECRET_ACCESS_KEY=pr1 aws --endpoint https://localhost:6443/ --no-verify-ssl s3'
```

2. Give correct permissions to the user for the project1-data and project1-bucket:
```
# chmod 770 /root/project1-data
# chown 1602:1996 /root/project1-data
# chmod 770 /root/project1-bucket
# chown 1602:1996 /root/project1-bucket
# ls -ld /root/project1*
drwxrwx--- 2 1602 1996 6 Nov 23 01:41 /root/project1-bucket
drwxrwx--- 2 1602 1996 6 Nov 23 01:40 /root/project1-data
```

3. Create bucket:
```
# node src/cmd/manage_nsfs bucket add --name project1-bucket --email project1@gmail.com --path /root/project1-buckets
# node src/cmd/manage_nsfs bucket list
# s3p1 ls <-- comment: doesn’t show anything in the output even though bucket project1-bucket exists for user account bucket path 'project1-data'
urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host ‘localhost’. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

**Comment by nimrod-becker** [comment]
Which user/group is running the CLi itself? Can it be that it falls under the "other" which is set to 0 ?

**Comment by romayalon** [comment]
@anandhu-karattu @madhuthorat Is this bug verified? can be closed?
This is one of the issues I discussed with Anandhu and should be fixed with https://github.com/noobaa/noobaa-core/pull/7662

**Comment by anandhu-karattu** [comment]
@romayalon , we discussed #7633 which was related to mb command. I will will verify both #7633 and #7634 soon (I haven't deployed latest noobaa rpm yet with your fixes)

**Comment by madhuthorat** [comment]
This is fixed and can be closed.

**Comment by anandhu-karattu** [comment]
Noobaa d/s rpm with Build Date  : Mon 29 Jan 2024 06:29:07 AM PST

[root@anrhel92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket add --name bucket-vta --email account-15905@gmail.com --path /mnt/fs1/bucket_15905/bucket-vta 2>/dev/null 
{
  "response": {
    "code": "BucketCreated",
    "reply": {
      "name": "bucket-vta",
      "system_owner": "account-15905@gmail.com",
      "bucket_owner": "account-15905@gmail.com",
      "creation_date": "2024-02-08T03:35:33.429Z",
      "versioning": "DISABLED",
      "path": "/mnt/fs1/bucket_15905/bucket-vta",
      "should_create_underlying_storage": false,
      "fs_backend": "GPFS",
      "_id": "65c44c054d93c4905e2cf7ef"
    }
  }
}
