### ISSUE TITLE
make rpm failed due to lack of npm command in noobaa-builder container image

### ISSUE THREAD

**Issue by xcnix** [noobaa/noobaa-core#7637]
### Environment info
- NooBaa Version: 5.15.0
- Platform: AlmaLinux 8.8 on  **ppc64le** platform

### Actual behavior

docker build   --build-arg BUILD_S3SELECT=1 --build-arg BUILD_S3SELECT_PARQUET=0 -f src/deploy/NVA_build/Base.Dockerfile   -t noobaa-base .
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1/19: FROM noobaa-builder
STEP 2/19: COPY ./package*.json ./
--> Using cache aabfd53fc37e9838d0ff1584668f7a334b7dfd921977e7724f0ad20d9ba14fff
--> aabfd53fc37
STEP 3/19: RUN npm install --production &&     npm cache clean --force
/bin/sh: npm: command not found
Error: building at STEP "RUN npm install --production &&     npm cache clean --force": while running runtime: exit status 127
make: *** [Makefile:137: base] Error 127

### Expected behavior
make rpm successfully

### Steps to reproduce
git clone https://github.com/noobaa/noobaa-core.git
cd noobaa-core
make rpm

**Comment by nimrod-becker** [comment]
@tangledbytes can you please take a look ?

**Comment by tangledbytes** [comment]
Hi @xcnix! I tried running the command on NooBaa master branch and it seems to be running just fine. It could be that `npm` download failed in one of the previous steps and now that cached image is being used. To eliminate this possibility, can you please once try purging the Docker cache (if not purge just make sure that NooBaa related caches are deleted) and then try building again?

**Comment by xcnix** [comment]
Thanks.
