### ISSUE TITLE
account status with name as parameter is not listing all the data (uid and gid is missing)

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7646]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: Standalone

### Actual behavior
1.node src/cmd/manage_nsfs account status --name noobaa1
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:27:33.261637 [PID-333312/TID-333312] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:27:33.261728 [PID-333312/TID-333312] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
{
  "name": "noobaa1",
  "email": "noobaa@gmail.com",
  "creation_date": "2023-12-07T12:24:27.202Z",
  "new_buckets_path": "/ibm/fs1/test"
}

### Expected behavior
1.
node src/cmd/manage_nsfs account status --name noobaa1
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:27:33.261637 [PID-333312/TID-333312] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:27:33.261728 [PID-333312/TID-333312] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
{
  "name": "noobaa1",
  "email": "noobaa@gmail.com",
  "creation_date": "2023-12-07T12:24:27.202Z",
  "new_buckets_path": "/ibm/fs1/test"
   "uid": 234
   "gid": 345
}

### Steps to reproduce
1.

**Comment by romayalon** [comment]
@ramya-c3 Adding request validation, should work with https://github.com/noobaa/noobaa-core/pull/7655

**Comment by ramya-c3** [comment]
Issue is fixed
