### ISSUE TITLE
key names are not validated for the node commands invalid key is also considered as input

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7647]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account delete --namek noobaa1 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:57:53.533771 [PID-380067/TID-380067] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:57:53.533872 [PID-380067/TID-380067] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
ERROR : Account do not exists with access key : undefined

### Expected behavior
1.node src/cmd/manage_nsfs account delete --namek noobaa1 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:27:27.758762 [PID-333128/TID-333128] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:27:27.758841 [PID-333128/TID-333128] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
Error: Access key or account name should not be empty
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.
Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]
Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.
Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

### Steps to reproduce
1.

**Comment by ramya-c3** [comment]
It is getting ignored

**Comment by romayalon** [comment]
I still think we need to throw on unexpected flags - 
```
iterate arguments coming from the user and check the following -
there are no extra arguments that are not expected (like the namek she wrote there)
there is at least 1 identifier (account name/access_key and bucket name)
```
@shirady will take a look

**Comment by ramya-c3** [comment]
It is
