### ISSUE TITLE
Account create command should return the json output

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7648]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account add --name noobaa5 --email noobaa@gmail.com --new_buckets_path /ibm/fs1/test --uid 1 --gid 1 --access_key 22w3 --secret_key 2w34 2>/dev/null 
Account created for the user : noobaa5

### Expected behavior
node src/cmd/manage_nsfs account add --name noobaa5 --email noobaa@gmail.com --new_buckets_path /ibm/fs1/test --uid 1 --gid 1 --access_key 22w3 --secret_key 2w34 2>/dev/null 
Account created for the user : "name":"noobaa5","email":"noobaa1@gmail.com","creation_date":"2023-12-07T12:06:34.455Z","access_keys":[{"access_key":"undefined","secret_key":"undefined"}],"nsfs_account_config":{"uid":22w3,"gid":2w34,"new_buckets_path":"/ibm/fs1/test"}} 

### Steps to reproduce
1.

**Comment by romayalon** [comment]
@ramya-c3 should be fixed with https://github.com/noobaa/noobaa-core/pull/7655, adding request validation label
