### ISSUE TITLE
config.json file with all key value pair endup in noobaa_nsfs restart

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7649]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior

{
    "ENDPOINT_FORKS": 2,
    "NSFS_TRIGGER_FSYNC":true,
    "NSFS_CHECK_BUCKET_BOUNDARIES":true,
    "NSFS_OPEN_READ_MODE":true,
    "NSFS_BUF_SIZE":1234,
    "NSFS_BUF_POOL_MEM_LIMIT":234,
    "GPFS_DL_PATH":"/usr/local/234",
    "UV_THREADPOOL_SIZE":4,
    "NOOBAA_LOG_LEVEL":"warn",
    "NSFS_CALCULATE_MD5":false,
    "ALLOW_HTTP":true,
    "EP_METRICS_SERVER_PORT":90,
    "ENDPOINT_SSL_STS_PORT":7443,
    "ENDPOINT_SSL_PORT":5334,
    "ENDPOINT_PORT":23423
} 

[root@ramyac-12 noobaa-core]# systemctl status noobaa_nsfs

: load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
Dec 07 14:08:11 ramyac-12 node[416839]: /usr/local/noobaa-core/config.js:886
Dec 07 14:08:11 ramyac-12 node[416839]:         if (err.code !== 'MODULE_NOT_FOUND' && err.code !== 'ENOENT') throw err;
Dec 07 14:08:11 ramyac-12 node[416839]:                                                                       ^
Dec 07 14:08:11 ramyac-12 node[416839]: Error: INVALID_SCHEMAmust be string
Dec 07 14:08:11 ramyac-12 node[416839]:     at load_nsfs_nc_config (/usr/local/noobaa-core/config.js:868:27)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Object.<anonymous> (/usr/local/noobaa-core/config.js:920:1)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module._load (node:internal/modules/cjs/loader:960:12)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
Dec 07 14:08:11 ramyac-12 node[416839]:     at require (node:internal/modules/cjs/helpers:119:18)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Object.<anonymous> (/usr/local/noobaa-core/src/util/debug_module.js:24:16)
Dec 07 14:08:11 ramyac-12 node[416839]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
Dec 07 14:08:11 ramyac-12 node[416839]: Node.js v18.18.2

**Comment by romayalon** [comment]
@ramya-c3 adding request validation - should be fixed with https://github.com/noobaa/noobaa-core/pull/7643
