### ISSUE TITLE
Error messages need to be corrected for account creation-GIT must be a number 

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7650]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account add --name noobaa1 --email noobaa@gmail.com --new_buckets_path /ibm/fs1/test --uid 1 --gid d1 --access_key 22w3 --secret_key 2w34 2>/dev/null 
Error: GIT must be a number 

### Expected behavior
Error: Invalid gid. gid must be a number

### Steps to reproduce
1.

**Comment by romayalon** [comment]
@ramya-c3 adding request validation - should be fixed with https://github.com/noobaa/noobaa-core/pull/7568
