### ISSUE TITLE
Missing any parameter is causing the invalid error proper error message should be displayed

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7651]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account add --name noobaa1 --email noobaa@gmail.com --new_buckets_path /ibm/fs1/tes  --gid 1 --access_key 22w3 --secret_key 2w34 2>/dev/null 
Error: Account config should not be empty
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.
Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]
Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.
Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

### Expected behavior
1. if more than one parameter missing just display help

### Steps to reproduce
1.

**Comment by romayalon** [comment]
re opening this bug, we still want to make it better by - 
splitting the error `Account config should not be empty` which is not indicative enough to separate errors per invalid tests case.

**Comment by ramya-c3** [comment]
[root@ramyamc-32 noobaa-core]# node src/cmd/manage_nsfs account add --name test --email pr1 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /mnt/cesSharedRoot/ces/s3-config
nsfs: config_dir_path=/mnt/cesSharedRoot/ces/s3-config config.json= {
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-01-23 11:08:09.008107 [PID-2646646/TID-2646646] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-01-23 11:08:09.008226 [PID-2646646/TID-2646646] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
(node:2646646) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Jan-23 11:08:09.331 [/2646646]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Jan-23 11:08:09.334 [/2646646]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Jan-23 11:08:09.335 [/2646646]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Jan-23 11:08:09.335 [/2646646]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
{
  "error": {
    "code": "InvalidAccountNSFSConfig",
    "message": "Account config should not be empty, should contain UID, GID or user",
    "detail": {}
  }
}
[root@ramyamc-32 noobaa-core]# 


This issue still exists

**Comment by shirady** [comment]
Hi @ramya-c3,
You run: `node src/cmd/manage_nsfs account add --name test --email pr1`, which is a command that does not contain either `--gid` and `--uid` nor   `--user`.
The output now contains the message: `Account config should not be empty, should contain UID, GID or user` instead of `Account config should not be empty`.

**Comment by shirady** [comment]
@ramya-c3 is suggesting to change the message:
```diff
-        "detail": "1gid invalid options for account add, please use only: name, email, uid, gid, new_buckets_path, user, access_key, secret_key, fs_backend, from_file, config_root, config_root_backend"
+       "detail": "1gid is an invalid option for account add, Supported Options : name, email, uid, gid, new_buckets_path, user, access_key, secret_key, fs_backend, from_file, config_root, config_root_backend"
```

**Comment by shirady** [comment]
@ramya-c3, would you please validate the message again?
(I merged it today, so you can validate it tomorrow).
