### ISSUE TITLE
uid and gid are missing in the account list in latest build output

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7652]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
1.[root@ramyac-12 noobaa-core]# node src/cmd/manage_nsfs account list --wide 2>/dev/null
{
  "account_list": [
    {
      "name": "noobaa1",
      "email": "noobaa@gmail.com",
      "creation_date": "2023-12-07T12:24:27.202Z",
      "new_buckets_path": "/ibm/fs1/test"
    },
    {
      "name": "noobaa5",
      "email": "noobaa@gmail.com",
      "creation_date": "2023-12-07T13:00:54.281Z",
      "new_buckets_path": "/ibm/fs1/test"
    },
    {
      "name": "noobaa112",
      "email": "noobaa@gmail.com",
      "creation_date": "2023-12-07T09:51:35.626Z",
      "new_buckets_path": "/ibm/fs1/test"
    },
    {
      "name": "noobaatest",
      "email": "noobaa@gmail.com",
      "creation_date": "2023-12-07T09:52:45.170Z",
      "new_buckets_path": "/ibm/fs1/test"
    },
    {
      "name": "noobaa2",
      "email": "noobaa@gmail.com",
      "creation_date": "2023-12-07T03:34:20.471Z",
      "new_buckets_path": "/ibm/fs1/test"
    }
  ]
}

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by romayalon** [comment]
@ramya-c3 Adding request validation, should be fixed with - https://github.com/noobaa/noobaa-core/pull/7655
