### ISSUE TITLE
health command taking longer time to exit

### ISSUE THREAD

**Issue by Roushan45** [noobaa/noobaa-core#7674]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231218.el8.x86_64.rpm

### Actual behavior
1. health command taking longer time to exit after printing the status
real	0m30.102s
user	0m2.286s
sys	0m1.480s

### Expected behavior
1. it should exit immediately after printing the status

### Steps to reproduce
1. /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health

**Comment by romayalon** [comment]
@naveenpaul1 Can you please take a look?

**Comment by romayalon** [comment]
@Roushan45 Naveen fix it in https://github.com/noobaa/noobaa-core/pull/7675, adding request validation label

**Comment by Roushan45** [comment]
verified
<img width="912" alt="image" src="https://github.com/noobaa/noobaa-core/assets/11044623/70a8417b-ce3d-4aed-969f-5bd85834d3a4">

**Comment by guymguym** [comment]
@romayalon should this be re-opened?

**Comment by romayalon** [comment]
@guymguym No, this one is about the health script not the CLI, and it was verified, [7701](https://github.com/noobaa/noobaa-core/issues/7701) is the issue we discussed yesterday
