### ISSUE TITLE
NSFS | NC | CLI | Account update script change access_key without new_access_key argument in config file.

### ISSUE THREAD

**Issue by naveenpaul1** [noobaa/noobaa-core#7683]
### Environment info
- NooBaa Version: **master**

### Actual behavior
1. Account is updating with the wrong access_key. access_key in the config file got updated with the new access-key but the symlink file name remains the old name and it making the account corrupted.

### Expected behavior
1. access_key in config file change only when the `--new_access_key` added to command.

### Steps to reproduce
1.  ``` sudo node src/cmd/manage_nsfs account add --config_root /standalon/noobaa --name account1 --email z1@noobaa.com --new_buckets_path ../../standalon/nsfs_root/ --access_key Dwertyuiopasdfg12345 --secret_key Qwertyuiopasdfg12345Qwertyuiopasdfg12345 --uid 1000 --gid 1000```
2. ``` sudo node src/cmd/manage_nsfs account update --config_root /standalon/noobaa --name account1 --email z111ddddd@noobaa.com --access_key Hwertyuiopasdfg1234 ```

**Comment by liranmauda** [comment]
@naveenpaul1
In this issue --access_key can be without --secret_key which does not make sense. 
#7681 is activating the validation for it.
The `--new_access_key` is not always needed, as autogenerate will not use it, and cannot use it.

**Comment by liranmauda** [comment]
`--regenerate` flag is updating and `--access_key` is not.
as we remove `--access_key` as Identifier, we can remove the `--new_access_key` completely.

**Comment by naveenpaul1** [comment]
@liranmauda AFIK we need both method right?  add access key using `--access_key` arg and --generate access key arg. ?

**Comment by liranmauda** [comment]
@naveenpaul1 
update `--access_key` is required and indeed it has a bug that is not updating the symlink unless `--new_access_key` is there.
The way it worked before the regenerate addition was that you had to add `--new_access_key` to update that key, as access_key was the identifier for the account.
as access_key is no longer the identifier, using this flag should update the key and the symlink, and it makes the `--new_access_key` redundant or unneeded

**Comment by romayalon** [comment]
@liranmauda As discussed at HPO meetings, --access_key and ---secret_key on add account /new_access_key on update needed for a specific use case of HPO and we should not remove them.

**Comment by liranmauda** [comment]
Re-opening for validation

**Comment by PravinRanjan10** [comment]
LGTM

**Comment by romayalon** [comment]
closing per @PravinRanjan10 last comment
