### ISSUE TITLE
NSFS | NC | CLI | update account/bucket  - creation date is being updated on update

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7693]
### Environment info
- NooBaa Version: master

### Actual behavior
1. Creation date is being updated on update 

### Expected behavior
1. Creation date value is being set only on add account/bucket.

### Steps to reproduce
1.  sudo node src/cmd/manage_nsfs account add --name=proj1 .....
2.  sudo node src/cmd/manage_nsfs account update --name=proj1 --regenerate
3. see that the creation date got updated

**Comment by anandhu-karattu** [comment]
Verified on Nobba upstream rpm "noobaa-core-5.15.0-20240122.el9.x86_64.rpm"

account update with --regenerate option does not update the creation date now.
