### ISSUE TITLE
NSFS | NC | CLI | secret_key is not getting updated when using `--regenerate` flag

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-core#7695]
### Actual behavior
1. secret_key is not getting updated when using `--regenerate` flag

**Comment by liranmauda** [comment]
Re-opening for validation

**Comment by PravinRanjan10** [comment]
LGMT
[root@prscale-12 noobaa-core]# sudo node src/cmd/manage_nsfs account update --name account1 --email z111ddddd@noobaa.com --regenerate 2>/dev/null
{
  "response": {
    "code": "AccountUpdated",
    "reply": {
      "name": "account1",
      "email": "z111ddddd@noobaa.com",
      "creation_date": "2024-01-23T09:09:01.772Z",
      "access_keys": [
        {
          "access_key": "gWAWuGZ043rHmxWciDLC",
          "secret_key": "596AQ5u1rJaOTY4Hzp3YJu1NICJFtXzuRh9AeFmo"
        }
      ],
      "nsfs_account_config": {
        "uid": 1000,
        "gid": 1000,
        "new_buckets_path": "/mnt/gpfs0"
      },
      "allow_bucket_creation": true,
      "_id": "65af822d3ffbe08b39a551ca"
    }
  }
}

**Comment by romayalon** [comment]
closing per Pravin's comment
