### ISSUE TITLE
Error messages are not proper for account status command

### ISSUE THREAD

**Issue by anandhu-karattu** [noobaa/noobaa-core#7699]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240102.el9.x86_64
- Platform: Stand alone RHEL 9.2

### Actual behavior
When I do the account status command, it is giving invalid output. 2 scenarios 
Issue 1:- Do account status without any account name. It is showing "Account already exists - access_key" in output.
Output must clearly say that "No account name provides" or something similar

```
[root@anrhel92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status 2>/dev/null
{
  "error": {
    "code": "AccountAccessKeyAlreadyExists",
    "message": "Account already exists - access_key",
    "detail": "xwoCw6Z7LsOInb2yVBU3"
  }
}

```

Issue 2: If I specify any invalid account name, out put is saying "Account already exists - name".
It should clearly error out saying account does not exist.
In the below example "test4" is a non existent account
```
[root@anrhel92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status --name test4 2>/dev/null
{
  "error": {
    "code": "AccountNameAlreadyExists",
    "message": "Account already exists - name",
    "detail": "test4"
  }
}

```

### Expected behavior
All the error messages should be proper. Details are specified in above section

### Steps to reproduce
Details are provided in issue description

**Comment by romayalon** [comment]
adding request validation due to the PR of @naveenpaul1.
@anandhu-karattu please close it when verified.

**Comment by ramya-c3** [comment]
[root@r-12 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status --name terst 2>/dev/null
{
  "error": {
    "code": "NoSuchAccountName",
    "message": "Account does not exist - name",
    "detail": "terst"
  }
}
[root@r-12 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status --name test 2>/dev/null
{
  "response": {
    "code": "AccountStatus",
    "reply": {
      "name": "test",
      "email": "test",
      "creation_date": "2024-02-12T05:13:52.106Z",
      "nsfs_account_config": {
        "uid": 23,
        "gid": 23,
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": false,
      "_id": "65c9a91000cd72afa17fe719"
    }
  }
}
[root@r-12 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status --name te2st 2>/dev/null
{
  "error": {
    "code": "NoSuchAccountName",
    "message": "Account does not exist - name",
    "detail": "te2st"
  }
}
[root@r-12 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account status 2>/dev/null
{
  "error": {
    "code": "MissingIdentifier",
    "message": "Account identifier is mandatory, please use the --access_key or --name flag"
  }
}

**Comment by ramya-c3** [comment]
This issue is working as expected now in downstream build
 [root@r-12 noobaa-core]# rpm -qa | grep noobaa
noobaa-core-5.15.0-20240129.el9.x86_64

**Comment by romayalon** [comment]
closing the issue per the last comment
