### ISSUE TITLE
--new_buckets_path should be optional for the accounts creation

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7700]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240102.el8.x86_64
- Platform: Standalone

### Actual behavior
1.--new_buckets_path should be optional for the accounts creation

 node /usr/local/noobaa-core/src/cmd/manage_nsfs account create --name test --uid 34 --gid 234  2>/dev/null
{
  "error": {
    "code": "InvalidAction",
    "message": "Invalid action, available actions are add, status, update, delete, list"
  }
}

### Expected behavior
1.
 node /usr/local/noobaa-core/src/cmd/manage_nsfs account create --name test --uid 34 --gid 234  2>/dev/null
account created test successfully

### Steps to reproduce
1.

**Comment by naveenpaul1** [comment]
@ramya-c3 action should be add, status, update, delete or list,   can you please try with `add`

**Comment by naveenpaul1** [comment]
@ramya-c3 duplicate please close 
https://github.com/noobaa/noobaa-core/issues/7625

**Comment by nimrod-becker** [comment]
Closed per last comment
