### ISSUE TITLE
NSFS | NC | CLI | Delete account that owns a bucket should result in an error.

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7707]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently we allow the deletion of an account that owns a bucket, in containerized noobaa we didn't allow it (account_server._verify_can_delete_account() - line 1461)

### Expected behavior
1. Delete an account that owns a bucket should result in an error.

### Steps to reproduce
1. manage_nsfs account add --name account1 --email.....
2. manage_nsfs bucket add --name bucket1 --email=account1....
3. manage_nsfs account delete --name account1

**Comment by anandhu-karattu** [comment]
Verified this in upstream build "noobaa-core-5.15.0-20240122.el9.x86_64.rpm"

[root@an3node-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account delete --name account_2345b1 2>/dev/null
{
  "error": {
    "code": "AccountDeleteForbiddenHasBuckets",
    "message": "Cannot delete account that is owner of buckets. You must delete all buckets before deleting the account",
    "detail": "Account account_2345b1 has bucket bucket-2345b1"
  }
}

**Comment by rkomandu** [comment]
@romayalon , @naveenpaul1 
is this added to the d/s build, as it is failing in the d/s that we had got on Friday (0125).

**Comment by rkomandu** [comment]
@anandhu-karattu , is going to update, as he had verified on the 0125 d/s build

**Comment by anandhu-karattu** [comment]
This defect is present in d/s build 01/25.

**Comment by romayalon** [comment]
@anandhu-karattu can you please share details? the fix is backported to 5.15 so it should be in 01/25

**Comment by anandhu-karattu** [comment]
Hello Romy, there was typo in my last comment. I corrected it now. The fix is present in 01/25 d/s build.
We are good now on this fix.
