### ISSUE TITLE
NSFS | NC | Health script | distinguish between temporary and persistent errors & retries addition

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7714]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently there is no separation between temporary and persistent errors on the health script, retries need to be executed from outside of the health script. 

### Expected behavior
1. Separation between persistent and temporary errors, for example - STORAGE_NOT_EXIST on a bucket_path of new_buckets_path is a persistent error, while connectivity might be temporary. (notice that this requires documentation changes)
2. Addition of retries on temporary errors. 

### Steps to reproduce
1. run the health script

**Comment by ramya-c3** [comment]
I validated this scenario it is working
