### ISSUE TITLE
NSFS | NC | Health script | add account uid gid can access new_buckets_path check 

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7715]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently there is no check if an account can access its new_buckets_path during the run of the health script.

### Expected behavior
1. During the health script run, a check if an account can access its new_buckets_path will be executed.

### Steps to reproduce
1. Create a path that only root can access - for example -  sudo mkdir /tmp/root_dir ; chmod 700 /tmp/root_dir/
2. Add an account having uid=200, gid=200, new_buckets_path = /tmp/root_dir/
4. Run health script - currently you won't see an error, after this bug is resolved - expect to see this issue reported.

**Comment by anandhu-karattu** [comment]
Verified on downstream build 02/12

Below is the output from health script . Error is properly reported for the accounts having no access to fs directories

```
[root@ananrhel92-x-worker1 ~]# jq '.' output_all.json
{
  "service_name": "noobaa_nsfs",
  "status": "OK",
  "memory": "338.2M",
  "checks": {
    "services": [
      {
        "name": "noobaa_nsfs",
        "service_status": "active",
        "pid": "2241747",
        "error_type": "PERSISTENT"
      },
      {
        "name": "rsyslog",
        "service_status": "active",
        "pid": "2240893",
        "error_type": "PERSISTENT"
      }
    ],
    "endpoint": {
      "endpoint_state": {
        "response": {
          "response_code": "RUNNING",
          "response_message": "Endpoint running successfuly."
        },
        "total_fork_count": 2,
        "running_workers": [
          2,
          1
        ]
      },
      "error_type": "TEMPORARY"
    },
    "accounts_status": {
      "invalid_accounts": [
        {
          "name": "ibm2",
          "storage_path": "/mnt/fs1/root_dir/",
          "code": "ACCESS_DENIED"
        }
      ],
      "valid_accounts": [
        {
          "name": "ibm1",
          "storage_path": "/mnt/fs1/ibm1/"
        }
      ],
      "error_type": "PERSISTENT"
    },
    "buckets_status": {
      "invalid_buckets": [],
      "valid_buckets": [
        {
          "name": "bucket1000",
          "storage_path": "/mnt/fs1/ibm1/bucket1000"
        }
      ],
      "error_type": "PERSISTENT"
    }
  }
}
```

@naveenpaul1 , marking this as verified

**Comment by naveenpaul1** [comment]
closing the issue per the last comment
