### ISSUE TITLE
NSFS | NC | Allow one or more buckets to use the same dir path for the storage

### ISSUE THREAD

**Issue by naveenpaul1** [noobaa/noobaa-core#7717]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Temp folder name is wrong for all the buckets created (eg: `.noobaa-nsfs_undefined`) with cli and s3 endpoint
This could create issues when one or more buckets use the same storage and try to do the multipart upload. 

### Expected behavior
1. Temp folder should be separate for each bucket with the unique folder name  (eg: `.noobaa-nsfs_bucket._id`)
multipart upload should not face any issues

### Steps to reproduce
1. Create two or more buckets with same storage path and start a multipart upload
2. verify the temp folder name

**Comment by rkomandu** [comment]
Tried on the s3 user with 2 buckets created 

```
alias s3u5001-ip1='AWS_ACCESS_KEY_ID=JjKmEw1fGoRsqk65wnvz AWS_SECRET_ACCESS_KEY=v0geXQWRoVD/vyKr2iAGDiyO8QxVGhSQsAeDxq5+ aws --endpoint https://10.11.77.133:6443 --no-verify-ssl s3'

alias s3u5001-ip2='AWS_ACCESS_KEY_ID=JjKmEw1fGoRsqk65wnvz AWS_SECRET_ACCESS_KEY=v0geXQWRoVD/vyKr2iAGDiyO8QxVGhSQsAeDxq5+ aws --endpoint https://10.11.77.139:6443 --no-verify-ssl s3'

created 2 buckets by the s3 user 

[root@rkomandu-ip-cls-x-master ~]# s3u5001-ip2 ls
urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.77.139'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
2024-01-23 04:25:58 newbucket-multi1
2024-01-23 04:25:58 newbucket-multi2

Uploading a 5G object to 2 different buckets of the same s3 user 

[root@rkomandu-ip-cls-x-master ~]# s3u5001-ip1 cp /root/file_5G s3://newbucket-multi1

[root@rkomandu-ip-cls-x-master ~]# s3u5001-ip2 cp /root/file_5G s3://newbucket-multi2

[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi2/.noobaa-nsfs_65afadf60946c47422e73a64/multipart-uploads/
total 9
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 3 5001 5000 4096 Jan 23 04:23 .
drwxrwx--- 2 5001 5000 8192 Jan 23 04:24 8d768c0d-2da7-46ae-a81e-f8d678dd6c55
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi1/.noobaa-nsfs_65afadeaa429a7dd3a4be14e/multipart-uploads/
total 9
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 3 5001 5000 4096 Jan 23 04:24 .
drwxrwx--- 2 5001 5000 8192 Jan 23 04:24 852f77f0-0997-4285-b881-9d9362b42b1f
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi1/.noobaa-nsfs_65afadeaa429a7dd3a4be14e/multipart-uploads/
total 1
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 2 5001 5000 4096 Jan 23 04:25 .
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi2/.noobaa-nsfs_65afadf60946c47422e73a64/multipart-uploads/
total 1
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 2 5001 5000 4096 Jan 23 04:25 .


```

[root@rkomandu-ip-cls-x-worker1 ~]# rpm -qa |grep noobaa
noobaa-core-5.15.0-20240122.el9.x86_64

**Comment by rkomandu** [comment]
@naveenpaul1 , generally the .noobaa-nsfs_id is unique to each bucket. In the above example, two different buckets are chosen, hence the directory structure is inside each bucket the .noobaa-nsfs_id. it is not the same as .noobaa-nsfs-bucket_id for 2 different buckets as per description. 

the below scenario is tried for the multi-part upload to the same bucket 
```

2 different objects are uploaded to the same bucket path by same user from different different terminals 

before the upload 

[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi1/.noobaa-nsfs_65afadeaa429a7dd3a4be14e/multipart-uploads/
total 1
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 2 5001 5000 4096 Jan 23 04:25 .

[root@rkomandu-ip-cls-x-master ~]# s3u5001-ip1 cp /root/file_4G s3://newbucket-multi1

[root@rkomandu-ip-cls-x-master ~]# s3u5001-ip1 cp /root/file_6G s3://newbucket-multi1

while the upload in progress

[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi1/.noobaa-nsfs_65afadeaa429a7dd3a4be14e/
total 2
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 .
drwxrwx--- 3 5001 5000 4096 Jan 23 04:25 ..
drwxrwx--- 4 5001 5000 4096 Jan 23 04:33 multipart-uploads
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lrat /mnt/fs1/s3user5001-dir/newbucket-multi1/.noobaa-nsfs_65afadeaa429a7dd3a4be14e/multipart-uploads/
total 17
drwxrwx--- 3 5001 5000 4096 Jan 23 04:22 ..
drwxrwx--- 4 5001 5000 4096 Jan 23 04:33 .
drwxrwx--- 2 5001 5000 8192 Jan 23 04:33 60f1f438-54cf-497a-8b23-af60c2506a32
drwxrwx--- 2 5001 5000 8192 Jan 23 04:33 200eb21c-ae5e-47e7-a649-0c27522980d5

```

Looks like the bucket_id naming convention is not present in the multipart upload directory structure,looks like random id is used. I hope this is what you intended on the .noobaa-nsfs_ 

All these are in 0122 upstream build

**Comment by rkomandu** [comment]
bucket id referred to as the id value in the json 
{"_id":"65afadf60946c47422e73a64","name":"newbucket-multi2"
{"_id":"65afadeaa429a7dd3a4be14e","name":"newbucket-multi1"

**Comment by rkomandu** [comment]
this also has to be backported to 5.15 correct ?

**Comment by naveenpaul1** [comment]
@rkomandu yes, It backported to 5.15

**Comment by nimrod-becker** [comment]
Any news on this validation?

**Comment by rkomandu** [comment]
@nimrod-becker , it was tried on the above upstream.. we will need to validate on the d/s build, however Naveen says PR is backported. Are you awaiting on anything. It is verified https://github.com/noobaa/noobaa-core/issues/7717#issuecomment-1905975307

**Comment by rkomandu** [comment]
created a bucket , here same user with different objects are uploaded as multipart and the same is showcased below. 

[root@rkomandu-cesip21 ~]# s3u5001-ip133 mb s3://shared-bucket
urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.77.133'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
make_bucket: shared-bucket

[root@rkomandu-cesip21 ~]# ls -lrt /root/file_25G
-rw-r--r-- 1 root root 26843545600 Feb  1 22:38 /root/file_25G

[root@rkomandu-cesip21 ~]# ls -lrt /root/file_30G
-rw-r--r-- 1 root root 32212254720 Feb  5 21:47 /root/file_30G

 ls -lart /mnt/fs1/s3user5001-dir/shared-bucket/
total 1
drwxrwx--- 9 5001 5000 4096 Feb  7 08:49 ..
drwxrwx--- 2 5001 5000 4096 Feb  7 08:49 .

Upload via CES IP the 25G and 30G file and show the .noobaa_nsfs directory and the multipart-upload directory under it 

[root@rkomandu-ip-cls-x-worker1 ~]# ls -lart /mnt/fs1/s3user5001-dir/shared-bucket/
total 2
drwxrwx--- 9 5001 5000 4096 Feb  7 08:49 ..
drwxrwx--- 3 5001 5000 4096 Feb  7 08:52 .
drwxrwx--- 3 5001 5000 4096 Feb  7 08:52 .noobaa-nsfs_65c3b48018a357668575149a
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lart /mnt/fs1/s3user5001-dir/shared-bucket/.noobaa-nsfs_65c3b48018a357668575149a/
total 2
drwxrwx--- 3 5001 5000 4096 Feb  7 08:52 ..
drwxrwx--- 3 5001 5000 4096 Feb  7 08:52 .
drwxrwx--- 4 5001 5000 4096 Feb  7 08:52 multipart-uploads
[root@rkomandu-ip-cls-x-worker1 ~]# ls -lart /mnt/fs1/s3user5001-dir/shared-bucket/.noobaa-nsfs_65c3b48018a357668575149a/multipart-uploads/
total 2
drwxrwx--- 3 5001 5000 4096 Feb  7 08:52 ..
drwxrwx--- 4 5001 5000 4096 Feb  7 08:52 .
drwxrwx--- 2 5001 5000 4096 Feb  7 08:52 6db054ca-41a9-43bc-b85a-2387be2a9455
drwxrwx--- 2 5001 5000 4096 Feb  7 08:52 6e389888-30fc-4607-bc34-c2bf8fabc465

cat /mnt/ces-shared-root/ces/s3-config/buckets/shared-bucket.json
{"_id":"65c3b48018a357668575149a","name":"shared-bucket","owner_account":"65afa9ea21f47b98b1926756","system_owner":"s3user5001@fvt.com","bucket_owner":"s3user5001@fvt.com","versioning":"DISABLED","creation_date":"2024-02-07T16:49:04.089Z","path":"/mnt/fs1/s3user5001-dir/shared-bucket","should_create_underlying_storage":true,

id is matching the noobaa.nsfs_<id>

@naveenpaul1 , hope this is sufficient 

rpm -qi noobaa-core-5.15.0-20240125.el9.x86_64
Name        : noobaa-core
Version     : 5.15.0
Release     : 20240125.el9
Architecture: x86_64
Install Date: Sun 28 Jan 2024 11:19:45 PM PST
Group       : Unspecified
Size        : 409313992
License     : Apache-2.0
Signature   : (none)
Source RPM  : noobaa-core-5.15.0-20240125.el9.src.rpm
Build Date  : Thu 25 Jan 2024 09:15:13 AM PST
Build Host  : x86-64-07.build.eng.rdu2.redhat.com
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://www.noobaa.io/
Summary     : NooBaa RPM
Description :
NooBaa is a data service for cloud environments, providing S3 object-store interface with flexible tiering, mirroring, and spread placement policies, over any storage resource that allows GET/PUT including S3, GCS, Azure Blob, Filesystems, etc

@nimrod-becker , FYI

**Comment by naveenpaul1** [comment]
@rkomandu Could you please create multiple buckets pointing to the same dir and try multipart upload to these buckets parallelly and verify the upload is successful.

**Comment by rkomandu** [comment]
@naveenpaul1 
yes.. tried the other scenario, 
created 2 buckets with the same filesystempath via mms3 cli and uploaded the objects 5G and 20G 

root@rkomandu-ip-cls-x-master ~]# ls -lrta /mnt/fs1/s3user5001-dir/newdir-shared/
total 2
drwxrwx--- 10 5001 5000 4096 Feb  7 22:22 ..
drwxrwx---  3 5001 5000 4096 Feb  7 22:31 .noobaa-nsfs_65c4731b42edfb0ef631eb50
drwxrwx---  4 5001 5000 4096 Feb  7 22:31 .
drwxrwx---  3 5001 5000 4096 Feb  7 22:31 .noobaa-nsfs_65c4730ec4de8b4fbaa4728f


[root@rkomandu-ip-cls-x-master ~]# ls -lrta /mnt/fs1/s3user5001-dir/newdir-shared/.noobaa-nsfs_65c4731b42edfb0ef631eb50/multipart-uploads/
total 33
drwxrwx--- 3 5001 5000  4096 Feb  7 22:31 ..
drwxrwx--- 3 5001 5000  4096 Feb  7 22:31 .
drwxrwx--- 2 5001 5000 32768 Feb  7 22:33 e07a7d8b-228f-403d-8464-97acd855c421
[root@rkomandu-ip-cls-x-master ~]# ls -lrta /mnt/fs1/s3user5001-dir/newdir-shared/.noobaa-nsfs_65c4730ec4de8b4fbaa4728f/multipart-uploads/
total 1
drwxrwx--- 3 5001 5000 4096 Feb  7 22:31 ..
drwxrwx--- 2 5001 5000 4096 Feb  7 22:33 .


[root@rkomandu-ip-cls-x-master ~]# cat /mnt/ces-shared-root/ces/s3-config/buckets/bucket-shared-1.json
{"name":"bucket-shared-1","system_owner":"s3user5001@fvt.com","bucket_owner":"s3user5001@fvt.com","creation_date":"2024-02-08T06:22:06.310Z","versioning":"DISABLED","path":"/mnt/fs1/s3user5001-dir/newdir-shared","should_create_underlying_storage":false,"_id":"65c4730ec4de8b4fbaa4728f"}

[root@rkomandu-ip-cls-x-master ~]# cat /mnt/ces-shared-root/ces/s3-config/buckets/bucket-shared-2.json
{"name":"bucket-shared-2","system_owner":"s3user5001@fvt.com","bucket_owner":"s3user5001@fvt.com","creation_date":"2024-02-08T06:22:19.743Z","versioning":"DISABLED","path":"/mnt/fs1/s3user5001-dir/newdir-shared","should_create_underlying_storage":false,"_id":"65c4731b42edfb0ef631eb50"}

[root@rkomandu-ip-cls-x-worker2 ~]# rpm -qa |grep noobaa  (d/s build) 
noobaa-core-5.15.0-20240125.el9.x86_64

uploaded 2 objects to the different buckets which has the same directory path as posted above 

 s3u5001-ip133 cp /root/file_5G s3://bucket-shared-1
 
 s3u5001-ip139 cp /root/file_20G s3://bucket-shared-2
 
[root@rkomandu-cesip21 ~]# s3u5001-ip139 ls s3://bucket-shared-2
urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.77.139'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                           PRE .noobaa-nsfs_65c4730ec4de8b4fbaa4728f/
2024-02-07 22:38:57 21474836480 file_20G
2024-02-07 22:33:49 5368709120 file_5G
[root@rkomandu-cesip21 ~]# s3u5001-ip139 ls s3://bucket-shared-1
urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.77.139'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                           PRE .noobaa-nsfs_65c4731b42edfb0ef631eb50/
2024-02-07 22:38:57 21474836480 file_20G
2024-02-07 22:33:49 5368709120 file_5G
