### ISSUE TITLE
ip address format should be validated

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7729]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240107.el8.x86_64.rpm
- Platform: Standalone

### Actual behavior
1./usr/local/noobaa-core/bin/node  /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '[10.1.11]'
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /mnt/cesSharedRoot/ces/s3-config
nsfs: config_dir_path=/mnt/cesSharedRoot/ces/s3-config config.json= {
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default',
  NSFS_WHITELIST: [ '10.1.11' ]
}

### Expected behavior
1. It should throw error if the ip address is not in the proper format

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
Do we have update?

**Comment by shirady** [comment]
@ramya-c3, would you please validate and comment here?

**Comment by ramya-c3** [comment]
@shirady If we have this fix available in downstream will validate the fix.please let me know if you have ported to downstream

**Comment by shirady** [comment]
@ramya-c3 Yes, you should have this fix in the downstream build (it was backported on January 23, it should be on the downstream builds built after this date).

cc @romayalon

**Comment by ramya-c3** [comment]
@shirady @romayalon This issue still exists it is accepting only ipv4 format now if i give ipv6 it is throwing error

**Comment by ramya-c3** [comment]
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '["12.2.2.2.2.22"]' 2>/dev/null
{
  "error": {
    "code": "InvalidWhiteListIPFormat",
    "message": "Whitelist IP body format is invalid",
    "detail": "IP address list has an invalid IP address 12.2.2.2.2.22"
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '[10.1.11.3]' 2>/dev/nullnode src/cmd/manage_nsfs account delete --config_root /ibm/fs1/ces/s3-config
{
  "error": {
    "code": "InvalidAction",
    "message": "Invalid action, available actions are add, status, update, delete, list"
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '[10.1.11.3]' 2>/dev/null
{
  "error": {
    "code": "InvalidWhiteListIPFormat",
    "message": "Whitelist IP body format is invalid"
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '["10.1.11.3"]' 2>/dev/null
{
  "response": {
    "code": "WhiteListIPUpdated",
    "reply": [
      "10.1.11.3"
    ]
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '["2001:0db8:85a3:0000:0000:8a2e:0370:7334"]' 2>/dev/null
{
  "response": {
    "code": "WhiteListIPUpdated",
    "reply": [
      "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    ]
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '[2001:0db8:85a3:0000:0000:8a2e:0370:7334]' 2>/dev/null
{
  "error": {
    "code": "InvalidWhiteListIPFormat",
    "message": "Whitelist IP body format is invalid"
  }
}
[root@ramyamc-12 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs whitelist --ips '["2001:0db8:85a3:0000:0000:8a2e:0e70:7334"]' 2>/dev/null
{
  "response": {
    "code": "WhiteListIPUpdated",
    "reply": [
      "2001:0db8:85a3:0000:0000:8a2e:0e70:7334"
    ]
  }
}

**Comment by ramya-c3** [comment]
This is working as expected i missed adding double quotes so it was causing issues
