### ISSUE TITLE
health command is returning empty and the return code is 2 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#7730]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

Standalone noobaa, CES S3 with 0115 noobaa upstream rpm 

 rpm -qa |grep noobaa
noobaa-core-5.15.0-20240115.el9.x86_64

### Actual behavior
1. 

mmhealth node show CES

Node name:      rkomandu-ces-rh92-x-worker1.fyre.ibm.com

Component         Status        Status Change     Reasons & Notices
-------------------------------------------------------------------------------
CES               HEALTHY       5 hours ago       -
  AUTH            DISABLED      7 hours ago       -
  AUTH_OBJ        DISABLED      7 hours ago       -
  BLOCK           DISABLED      7 hours ago       -
  CESNETWORK      HEALTHY       6 hours ago       -
  HDFS_NAMENODE   DISABLED      7 hours ago       -
  NFS             HEALTHY       6 hours ago       -
  OBJECT          DISABLED      7 hours ago       -
  S3              DISABLED      5 hours ago       -
  SMB             DISABLED      7 hours ago       -

There are no active error events for the component CES on this node (rkomandu-ces-rh92-x-worker1.fyre.ibm.com).
[root@rkomandu-ces-rh92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health 2>/dev/null
[root@rkomandu-ces-rh92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health  --all_bucket_details 2>/dev/null
[root@rkomandu-ces-rh92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health  --all_account_details 2>/dev/null
[root@rkomandu-ces-rh92-x-worker1 ~]# echo $?
2
[root@rkomandu-ces-rh92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health 2>/dev/null
[root@rkomandu-ces-rh92-x-worker1 ~]# echo $?
2

[root@rkomandu-ces-rh92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /gpfs/fs-ces-shared/ces/s3-config
nsfs: config_dir_path=/gpfs/fs-ces-shared/ces/s3-config config.json= {
  ENDPOINT_PORT: 23423,
  ENDPOINT_SSL_PORT: 6443,
  ENDPOINT_SSL_STS_PORT: 7443,
  EP_METRICS_SERVER_PORT: 90,
  ALLOW_HTTP: true,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-01-17 04:21:46.179479 [PID-3776457/TID-3776457] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-01-17 04:21:46.179768 [PID-3776457/TID-3776457] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
Jan-17 4:21:46.848 [/3776457]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Jan-17 4:21:46.849 [/3776457]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Jan-17 4:21:46.849 [/3776457]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Jan-17 4:21:46.850 [/3776457]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
Jan-17 4:21:47.067 [/3776457] [ERROR] core.cmd.health:: Helath: exit on error Error: No such file or directory

[root@rkomandu-ces-rh92-x-worker1 ~]#  /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health  --all_account_details
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /gpfs/fs-ces-shared/ces/s3-config
nsfs: config_dir_path=/gpfs/fs-ces-shared/ces/s3-config config.json= {
  ENDPOINT_PORT: 23423,
  ENDPOINT_SSL_PORT: 6443,
  ENDPOINT_SSL_STS_PORT: 7443,
  EP_METRICS_SERVER_PORT: 90,
  ALLOW_HTTP: true,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-01-17 04:23:13.683860 [PID-3777617/TID-3777617] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-01-17 04:23:13.684126 [PID-3777617/TID-3777617] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
Jan-17 4:23:14.398 [/3777617]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Jan-17 4:23:14.401 [/3777617]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Jan-17 4:23:14.402 [/3777617]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Jan-17 4:23:14.403 [/3777617]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
Jan-17 4:23:14.621 [/3777617] [ERROR] core.cmd.health:: Helath: exit on error Error: No such file or directory
[root@rkomandu-ces-rh92-x-worker1 ~]# echo $?
2

### Expected behavior
1.
When S3 Service is Enabled, it should display the appropriately as Enabled instead of Disabled in our mmhealth (which internally using the health cmd) 
### Steps to reproduce
1. 
Enable the Service and then check the health cmd. 

### More information - Screenshots / Logs / Other output
We have posted in RTC defect https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=324628&tab=com.ibm.stg.tab.stgDefect.main

**Comment by madhuthorat** [comment]
@naveenpaul1 and @romayalon Can you please prioritise the fix for this issue as it affects Scale installation health check too. Can we get fix in today's nightly build ?

**Comment by romayalon** [comment]
@madhuthorat the PR is approved, @naveenpaul1 can you please rebase and merge?

**Comment by romayalon** [comment]
@rkomandu @naveenpaul1 merged the fix, added request validation label, please validate it was fixed and close.

**Comment by rkomandu** [comment]
The code is not in the d/s build of 0119. Please get us the latest d/s build to verify 

@madhuthorat @romayalon

**Comment by rkomandu** [comment]
Noobaa d/s build 0119 doesn't have the fix for the below one 

```
[root@rkomandu-ip-cls-x-worker1 ~]# mmhealth node show CES

Node name:      rkomandu-ip-cls-x-worker1.fyre.ibm.com

Component         Status        Status Change     Reasons & Notices
------------------------------------------------------------------------------------------
CES               DEGRADED      20 hours ago      ces_network_ips_not_defined
  AUTH            DISABLED      20 hours ago      -
  AUTH_OBJ        DISABLED      20 hours ago      -
  BLOCK           DISABLED      20 hours ago      -
  CESNETWORK      DEGRADED      20 hours ago      ces_network_ips_not_defined
  HDFS_NAMENODE   DISABLED      20 hours ago      -
  NFS             DISABLED      20 hours ago      -
  OBJECT          DISABLED      20 hours ago      -
  S3              DISABLED      20 hours ago      -
  SMB             DISABLED      20 hours ago      -


Event                        Parameter   Severity    Active Since         Event Message
----------------------------------------------------------------------------------------------------------------
ces_network_ips_not_defined  CESNETWORK  WARNING     20 hours ago         No CES IP addresses have been defined.
[root@rkomandu-ip-cls-x-worker1 ~]# rpm -qa |grep noobaa
noobaa-core-5.15.0-20240119.el9.x86_64

```

**Comment by romayalon** [comment]
@rkomandu we backported the relevant changes to 5.15, please sync with Madhu regarding the d/s build.

**Comment by ramya-c3** [comment]
[root@ramyamc-32 noobaa-core]# mmhealth node show CES

Node name:      ramyamc-32.vmlocal

Component         Status        Status Change     Reasons & Notices
-------------------------------------------------------------------------------
CES               HEALTHY       1 day ago         -
  AUTH            DISABLED      1 day ago         -
  AUTH_OBJ        DISABLED      1 day ago         -
  BLOCK           DISABLED      1 day ago         -
  CESNETWORK      HEALTHY       1 day ago         -
  HDFS_NAMENODE   DISABLED      1 day ago         -
  NFS             HEALTHY       1 day ago         -
  OBJECT          DISABLED      1 day ago         -
  S3              HEALTHY       1 day ago         -
  SMB             HEALTHY       1 day ago         -

There are no active error events for the component CES on this node (ramyamc-32.vmlocal).
[root@ramyamc-32 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --all_account_details
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /mnt/cesSharedRoot/ces/s3-config
nsfs: config_dir_path=/mnt/cesSharedRoot/ces/s3-config config.json= {
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-01-23 11:02:24.389819 [PID-2636890/TID-2636890] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-01-23 11:02:24.389916 [PID-2636890/TID-2636890] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
Jan-23 11:02:24.759 [/2636890]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Jan-23 11:02:24.761 [/2636890]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Jan-23 11:02:24.762 [/2636890]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Jan-23 11:02:24.764 [/2636890]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
{"service_name":"noobaa_nsfs","status":"OK","memory":"122.6M","checks":{"services":[{"name":"noobaa_nsfs","service_status":"active","pid":"265110","error_type":"PERSISTENT"},{"name":"rsyslog","service_status":"active","pid":"2577490","error_type":"PERSISTENT"}],"endpoint":{"endpoint_state":{"response":{"response_code":"RUNNING","response_message":"Endpoint running successfuly."},"total_fork_count":0,"running_workers":[]},"error_type":"TEMPORARY"},"accounts_status":{"invalid_accounts":[],"valid_accounts":[{"name":"pr2"},{"name":"pr1","storage_path":"/mnt/gpfs0/pr1"}],"error_type":"PERSISTENT"}}}
[root@ramyamc-32 noobaa-core]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health 2>/dev/null
{"service_name":"noobaa_nsfs","status":"OK","memory":"123.4M","checks":{"services":[{"name":"noobaa_nsfs","service_status":"active","pid":"265110","error_type":"PERSISTENT"},{"name":"rsyslog","service_status":"active","pid":"2577490","error_type":"PERSISTENT"}],"endpoint":{"endpoint_state":{"response":{"response_code":"RUNNING","response_message":"Endpoint running successfuly."},"total_fork_count":0,"running_workers":[]},"error_type":"TEMPORARY"}}}
[root@ramyamc-32 noobaa-core]#

**Comment by ramya-c3** [comment]
[root@ramyamc-32 noobaa-core]# rpm -qa | grep noobaa
noobaa-core-5.15.0-20240122.el9.x86_64

**Comment by rkomandu** [comment]
yes, it works in the 0122 upstream build 

[root@rkomandu-ip-cls-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /mnt/ces-shared-root/ces/s3-config
nsfs: config_dir_path=/mnt/ces-shared-root/ces/s3-config config.json= {
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-01-23 03:54:48.974609 [PID-932721/TID-932721] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-01-23 03:54:48.974755 [PID-932721/TID-932721] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
Jan-23 3:54:49.427 [/932721]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Jan-23 3:54:49.428 [/932721]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Jan-23 3:54:49.429 [/932721]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Jan-23 3:54:49.429 [/932721]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
{"service_name":"noobaa_nsfs","status":"OK","memory":"113.3M","checks":{"services":[{"name":"noobaa_nsfs","service_status":"active","pid":"930171","error_type":"PERSISTENT"},{"name":"rsyslog","service_status":"active","pid":"922720","error_type":"PERSISTENT"}],"endpoint":{"endpoint_state":{"response":{"response_code":"RUNNING","response_message":"Endpoint running successfuly."},"total_fork_count":0,"running_workers":[]},"error_type":"TEMP

[root@rkomandu-ip-cls-x-worker1 ~]# mmhealth node show CES

Node name:      rkomandu-ip-cls-x-worker1.fyre.ibm.com

Component         Status        Status Change     Reasons & Notices
------------------------------------------------------------------------------------------
CES               DEGRADED      1 min. ago        ces_network_ips_not_defined
  AUTH            DISABLED      1 day ago         -
  AUTH_OBJ        DISABLED      1 day ago         -
  BLOCK           DISABLED      1 day ago         -
  CESNETWORK      DEGRADED      3 min. ago        ces_network_ips_not_defined
  HDFS_NAMENODE   DISABLED      1 day ago         -
  NFS             DISABLED      1 day ago         -
  OBJECT          DISABLED      1 day ago         -
  S3              HEALTHY       1 min. ago        -
  SMB             DISABLED      1 day ago         -


Event                        Parameter   Severity    Active Since         Event Message
----------------------------------------------------------------------------------------------------------------
ces_network_ips_not_defined  CESNETWORK  WARNING     3 min. ago           No CES IP addresses have been defined.
[root@rkomandu-ip-cls-x-worker1 ~]# rpm -qa |grep noobaa
noobaa-core-5.15.0-20240122.el9.x86_64

Was verifying in the d/s build 0119, as we got that for testing. Now cleaned the system (it is a quite a process) to clean the ces shared root directory structure and retried.

**Comment by rkomandu** [comment]
@naveenpaul1 , please get this into the d/s build as per our slack discussion

**Comment by naveenpaul1** [comment]
@rkomandu changes are backported to 5.15, will be available in next d/s [PR](https://github.com/noobaa/noobaa-core/pull/7749)

**Comment by rkomandu** [comment]
verified on the 0129 noobaa d/s build noobaa-core-5.15.0-20240129.el9.x86_64 


mmhealth node show CES S3 -v

Node name:      c83f1-app2

Component              Status        Status Change            Reasons & Notices
-------------------------------------------------------------------------------
S3                     HEALTHY       2024-02-07 06:30:09      -
  bucket-5002-1        HEALTHY       2024-02-08 05:48:13      -
  s3user6001@fvt.com   HEALTHY       2024-02-08 05:45:13      -
  s3user6002@fvt.com   HEALTHY       2024-02-08 05:47:13      -


Event               Parameter           Severity    Active Since         Event Message
-------------------------------------------------------------------------------------------------------------
s3_active           S3                  INFO        2024-02-07 06:30:09  The S3 service is now active.
[start_s3_service]  s3                  info        2024-02-07 06:30:09  CES S3 service is started.
s3_account_ok       s3user6001@fvt.com  INFO        2024-02-08 05:45:13  S3 account s3user6001@fvt.com is OK.
s3_account_ok       s3user6002@fvt.com  INFO        2024-02-08 05:47:13  S3 account s3user6002@fvt.com is OK.
s3_bucket_ok        bucket-5002-1       INFO        2024-02-08 05:48:13  S3 bucket bucket-5002-1 is OK.

GPFS version 5.2.0.0 240206.103525
