### ISSUE TITLE
NSFS | NC | Passing Flag `--User` With No Value Would Create an Account with `true` User

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7750]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Passing the flag `--user` with no value would create an account with a `true` user.

### Expected behavior
1. Should not save `distinguished_name` as `true`.
We can: (1) throw an error or (2) ignore the value

### Steps to reproduce
1. Create an account with the flag `--user` with no value, example:
`sudo node src/cmd/manage_nsfs account add --name shira-6666 --email shira-6666@noobaa.com --new_buckets_path /tmp/nsfs_root1 --user`

### More information - Screenshots / Logs / Other output
CLI output (notice  `"distinguished_name": "true"`):
```bash
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "name": "shira-6666",
      "email": "shira-6666@noobaa.com",
      "creation_date": "2024-01-23T07:57:20.252Z",
      "access_keys": [
        {
          "access_key": <access_key>,
          "secret_key": <secret_key>
        }
      ],
      "nsfs_account_config": {
        "distinguished_name": "true",
        "new_buckets_path": "/tmp/nsfs_root1"
      },
      "allow_bucket_creation": true,
      "_id": "65af71606e43fc5d0f15d0f6"
    }
  }
}
```

**Comment by ramya-c3** [comment]
working as expected so we can update the defect. Validated in the downstream build

**Comment by shirady** [comment]
closing per the last comment
