### ISSUE TITLE
NSFS | NC | NSFS account/ bucket/config schema validation error message is not informative enough

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7752]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. currently on NSFS schema validation we throw the following error - 
`if (!valid) throw new RpcError('INVALID_SCHEMA', ajv.errors[0]?.message);`
ajv.errors[0]?.message - does not state what property caused the failure, it contains the reason for failure only.

### Expected behavior
NSFS account/ bucket/config schema validation error message -  contains the property that caused the failure, it contains the reason for failure only.
Note: we might need to add more info in addition to the property

### Steps to reproduce
1. Update config.json with wrong schema property
2. run nsfs.js/manage_nsfs.js/health.js

**Comment by shirady** [comment]
Hi @romayalon,
- The message contains the property name - example bucket without `creation_date` property:
`ajv.errors[0]?.message`: "must have required property 'creation_date'".
- But when someone adds additional property - example `lala`:
`ajv.errors[0]?.message`: "must NOT have additional properties".

I can add the `parama` property to the message error and then it would change to:
- must have required property 'creation_date' | {"missingProperty":"creation_date"}
- must NOT have additional properties | {"additionalProperty":"lala"}
Is that what you meant?

**Comment by romayalon** [comment]
@shirady Yes that's good! if you see more relevant information in the errors add it as well :)

**Comment by anandhu-karattu** [comment]
Build Verified on:  5.15 downstream build 02/12
Env details :
Platform rhel9
rpm name noobaa-core-5.15.0-20240212.el9.x86_64

Verification steps:-
Step1 : Create an account : SUCCESS
```
[root@ananrhel92-x-worker1 ces]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account add --name ibm1 --email ibm1@gmail.com --uid 7000 --gid 7000 --new_buckets_path /mnt/fs1/ibm1/
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "name": "ibm1",
      "email": "ibm1@gmail.com",
      "creation_date": "2024-02-14T05:53:43.664Z",
      "access_keys": [
        {
          "access_key": "ClhpeB2pLHIpeNGspUU6",
          "secret_key": "ppiHx/TJP3dIpUAEums7q+BtR8KaqX7pQ2DI1mxY"
        }
      ],
      "nsfs_account_config": {
        "uid": 7000,
        "gid": 7000,
        "new_buckets_path": "/mnt/fs1/ibm1/",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "_id": "65cc5567345d4a5220f4635a"
    }
  }
}
```

Step2: Bucket create : SUCCESS

```
[root@ananrhel92-x-worker1 ces]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket add --name bucket1000 --email ibm1@gmail.com --path /mnt/fs1/ibm1/bucket1000
{
  "response": {
    "code": "BucketCreated",
    "reply": {
      "name": "bucket1000",
      "system_owner": "ibm1@gmail.com",
      "bucket_owner": "ibm1@gmail.com",
      "creation_date": "2024-02-14T05:55:46.795Z",
      "versioning": "DISABLED",
      "path": "/mnt/fs1/ibm1/bucket1000",
      "should_create_underlying_storage": false,
      "fs_backend": "GPFS",
      "_id": "65cc55e2379cbabed744b8d8"
    }
  }
}
```

Step 3 : Edit the bucket1000.json file and add/remove below items 
a) Add additional property "test":"test"
b) Remove existing property "Creation_date:xxxxx"
c) Change property "should_create_underlying_storage":123 (Boolean expected)

Step4 : Update the bucket name to a new name Which is expected to error our as per this issue. Result below
for a)additional property "test":"test"
```
[root@ananrhel92-x-worker1 ces]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket update --name bucket1000 --new_name bucket2000 2>/dev/null
{
  "error": {
    "code": "InvalidSchema",
    "message": "Schema invalid, please use required properties",
    "detail": "Error: must NOT have additional properties | {\"additionalProperty\":\"test\"}\n    at Object.validate_bucket_schema (/usr/local/noobaa-core/src/manage_nsfs/nsfs_schema_utils.js:55:15)\n    at update_bucket (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:281:23)\n    at async manage_bucket_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:308:9)\n    at async bucket_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:114:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:94:13)"
  }
}
```

b) Missing property creation_date

```
[root@ananrhel92-x-worker1 ces]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket update --name bucket1000 --new_name bucket2000 2>/dev/null
{
  "error": {
    "code": "InvalidSchema",
    "message": "Schema invalid, please use required properties",
    "detail": "Error: must have required property 'creation_date' | {\"missingProperty\":\"creation_date\"}\n    at Object.validate_bucket_schema (/usr/local/noobaa-core/src/manage_nsfs/nsfs_schema_utils.js:55:15)\n    at update_bucket (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:281:23)\n    at async manage_bucket_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:308:9)\n    at async bucket_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:114:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:94:13)"
  }
}
```

c) Property is not boolean
```
[root@ananrhel92-x-worker1 ces]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket update --name bucket1000 --new_name bucket2000 2>/dev/null
{
  "error": {
    "code": "InvalidSchema",
    "message": "Schema invalid, please use required properties",
    "detail": "Error: must be boolean | {\"type\":\"boolean\"} | \"/should_create_underlying_storage\"\n    at Object.validate_bucket_schema (/usr/local/noobaa-core/src/manage_nsfs/nsfs_schema_utils.js:55:15)\n    at update_bucket (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:281:23)\n    at async manage_bucket_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:308:9)\n    at async bucket_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:114:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:94:13)"
  }
}
```

Fix looks good to me. 
However if we have more than one issues in the <bucket_name>.json, validation error comes only for the initial issue.
If that is okay, we can close this

**Comment by shirady** [comment]
@anandhu-karattu, It will throw the error only on one of the issues.
closing per the last comment
cc: @romayalon
