### ISSUE TITLE
NSFS | NC | Health script | Add additional syslog services like syslogng

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7755]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. based on the comment - https://github.com/noobaa/noobaa-core/pull/7733#issuecomment-1899030231 - `health script 'Is it possible to enhance these check also to add additional syslog services like syslogng instead rsyslog only?`

### Expected behavior
1. support additional syslog services check on health script

### Steps to reproduce
1. run health script

**Comment by naveenpaul1** [comment]
@ps20renar could you  please share what you are expecting in this task, 
If you can share syslogng installation guide or something that will also help us.

**Comment by ps20renar** [comment]
Hi @naveenpaul1 ,
my request here are enhancement of noobaa standalone to use for logging not only rsyslog only. We had in our linuxplattform syslogng as syslog server implemented. Here you can find the docs:
[ ](https://support.oneidentity.com/de-de/technical-documents/syslog-ng-premium-edition/7.0.34/administration-guide)

**Comment by naveenpaul1** [comment]
Changes are merged.
