### ISSUE TITLE
NSFS | NC | `get-bucket-website` Returns an Error

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7763]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. When running `get-bucket-website` on a bucket that we added website configuration it returns an error.

### Expected behavior
1. When running `get-bucket-website` on a bucket that we added website configuration it should return the website configuration.

#### Requirements
1. First, create the `FS_ROOT` and give permissions:

```bash
mkdir -p /tmp/nsfs_root1
chmod 777 /tmp/nsfs_root1
```

This will be the argument for:
- `new_buckets_path` flag that we will use in the account commands
- `path` in the buckets commands.

#### Additional Requirements:
2. Using the manage nsfs CLI - create an account:
`sudo node src/cmd/manage_nsfs account add --name <account-name> --email <accountemail> --new_buckets_path /tmp/nsfs_root1 --access-key <access-key> --secret_key <secret-key> --uid <uid number> --gid <gid number>`.
3. Use this alias with AWS CLI (copy the `<access-key>` and `<secret-key>`):
`alias s3-nc-user-1='AWS_ACCESS_KEY_ID=<access-key>  AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443`.
4. Run the server (NC NSFS): `sudo node src/cmd/nsfs --debug 3`. (debug level would help us with finding relevant logs).

#### The steps:
5. Put bucket website: `s3-nc-user-1 s3api put-bucket-website --bucket <bucket-name> --website-configuration file://website.json`
website.json:

```json
{
    "RedirectAllRequestsTo": {
        "HostName": "s3.noobaa.io",
        "Protocol": "HTTPS"
    }
}
```

5. Get bucket website: `s3-nc-user-1 s3api get-bucket-website --bucket <bucket-name> --website-configuration file://website.json`

### More information - Screenshots / Logs / Other output
Output:
`s3-nc-user-1 s3api get-bucket-website --bucket bucket-1` (bucket-1 is the bucket name).

> An error occurred (NoSuchWebsiteConfiguration) when calling the GetBucketWebsite operation: The specified bucket does not have a website configuration

In the logs:

Error: The specified bucket does not have a website configuration
>     at Object.get_bucket_website [as handler] (noobaa-core/src/endpoint/s3/ops/s3_get_bucket_website.js:12:31)
>     at async handle_request (noobaa-core/src/endpoint/s3/s3_rest.js:150:19)
>     at async Object.s3_rest [as handler] (noobaa-core/src/endpoint/s3/s3_rest.js:65:9)

Configuration (after put website configuration):
`sudo cat /etc/noobaa.conf.d/buckets/bucket-1.json` (see the `website_configuration`),

> {"name":"bucket-1","system_owner":"shira-9999@noobaa.com","bucket_owner":"shira-9999@noobaa.com","creation_date":"2024-01-24T13:43:24.910Z","versioning":"DISABLED","path":"/tmp/nsfs_root1/","should_create_underlying_storage":false,"_id":"65b113fc7fa7f8d76a458769","website":{"website_configuration":{"redirect_all_requests_to":{"host_name":"s3.noobaa.io","protocol":"HTTPS"}}}}

**Comment by romayalon** [comment]
@nadavMiz closing per your fix
