### ISSUE TITLE
command is showing internal server error message

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7764]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240122.el9.x86_64
- Platform: Standalone

### Actual behavior
1.[root@ramyamc-32 noobaa-core]# node src/cmd/manage_nsfs account add --name test --email pr1 --uid 1235 --gid 234 --new_buckets_path 4e34 2>/dev/null
{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "detail": "TypeError: A string was expected\n    at Object.is_path_exists (/usr/local/noobaa-core/src/util/native_fs_utils.js:463:30)\n    at validate_account_args (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:757:46)\n    at add_account (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:448:11)\n    at manage_account_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:584:15)\n    at account_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:329:11)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:97:13)"
  }
}

### Expected behavior
1. It should display proper error instead of internal server error

### Steps to reproduce
1.

**Comment by shirady** [comment]
The issue is when someone runs the command to add an account with the flag `--new_buckets_path` with an invalid value, (example 4e34), he sees `InternalError` instead of an error about this specific flag.

**Comment by shirady** [comment]
@ramya-c3 I removed the "help" from the title.

**Comment by romayalon** [comment]
@ramya-c3 that's a cute bug actually
@shirady yes, as I mentioned on slack, this is a type-casting problem.
we need to make sure, in all arguments and not only in this specific case.

**Comment by romayalon** [comment]
@shirady another instance of a similar issue, we need to think about more of these cases
```
sudo node src/cmd/manage_nsfs bucket add  --name bucket2 --email noobaa@gmail.com --path 4e34
Jan-25 16:26:02.777 [/72027]   [LOG] CONSOLE:: config_path 4e+34
Jan-25 16:26:02.779 [/72027]   [LOG] CONSOLE::config_path err 4e+34 TypeError: A string was expected
{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "detail": "TypeError: A string was expected\n    ..."
  }
}
```

**Comment by shirady** [comment]
@ramya-c3, would you please validate this?
