### ISSUE TITLE
NSFS | NC | CLI | Deprecate email from CLI

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7766]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. The following CLI commands require an account email address - 
Account's email address being used on account add/update - 

```
sudo node src/cmd/manage_nsfs account add --name account1 --email account1@noobaa.io --uid 0 --gid 0 --new_buckets_path /tmp/b1
```

```
sudo node src/cmd/manage_nsfs account update --name account1 --email account2@noobaa.io --uid 0 --gid 0 --new_buckets_path /tmp/b1
```

Bucket's owner email address also being used on bucket add/update - 
```
sudo node src/cmd/manage_nsfs bucket add  --name bucket2 --email account1@noobaa.io --path /tmp/b1
````

```
sudo node src/cmd/manage_nsfs bucket update  --name bucket2 --email account2@noobaa.io
```

We would like to remove these references and replace them with account name.
### Expected behavior
1. replace these email references with account's name.
This is the first step towards https://github.com/noobaa/noobaa-core/issues/7734 which is the full solution.

### Steps to reproduce
1. mentioned above.

**Comment by shirady** [comment]
@romayalon, If I understand it right - the fix here is a temporary solution since we wish to use the id.
My plan is:
manage nsfs commands
1. In the account we will remove the flag `--email` (account add, account update)
2. In the bucket we will replace the `--email` with flag `--bucket_owner` which is the account name.

As I see it:
- we would need to remove email property from the account schema.
- It would affect also the bucketspace_fs (system_owner and bucket owner are from the `account.email`).

WDYT? something I need to take into account?

**Comment by romayalon** [comment]
@shirady Yes exactly, it's a temp change and we might need to do more changes when replacing to ids.
we need to make sure that on s3 authentication/bucket policy flows we don't miss anything when we check the requesting account.
Also, we need to check specifically the system_owner cases there.
see for example, I had to replace the email with name for bucket policy -  https://github.com/noobaa/noobaa-core/blob/master/src/endpoint/s3/s3_rest.js#L244

**Comment by shirady** [comment]
Thanks @romayalon,
A couple of open questions I have:
1) As I understand it this is not part of the change:
https://github.com/noobaa/noobaa-core/blob/ed0ba58bdba737a2ba8c47c9b06dfa303e4a0c16/src/cmd/nsfs.js#L287-L291
2) In the core test there is this function - I was not sure in which cases we need it:
https://github.com/noobaa/noobaa-core/blob/ed0ba58bdba737a2ba8c47c9b06dfa303e4a0c16/src/test/unit_tests/nc_coretest.js#L221-L229

**Comment by romayalon** [comment]
@shirady 
1. correct
2. NC Coretest contains a mapping between RPC calls and manage_nsfs calls, to be able to run existing tests like test_bucketspace.js with a limited effort. This function was needed because some RPC calls' identifier is the account's email while the identifier on manage_nsfs is the account's name.

**Comment by romayalon** [comment]
@ramya-c3 you validated it's working on upstream, right?
