### ISSUE TITLE
NSFS | NC | CLI | account add/update should check if account can access its new_buckets_path 

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7783]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently there is no check on account add/update if they can access the account's new_buckets_path.

### Expected behavior
1. During account add/update there is a check if they can access the account's new_buckets_path.

### Steps to reproduce
1. Create a path with 000 permissions or other inaccessible permutations of folder permissions + uid:gid / distinguished name.
1. Run account add/update while specifying new_buckets_path to be the path from step 1 and expect an error.

**Comment by romayalon** [comment]
https://github.com/noobaa/noobaa-core/pull/7777 should provide a fix for this issue

**Comment by romayalon** [comment]
re-opening for validation

**Comment by romayalon** [comment]
@anandhu-karattu why the error need to be corrected? InvalidAccountDistinguishedName is a more accurate error than InaccessibleAccountNewBucketsPath because the user doesn't exist

**Comment by anandhu-karattu** [comment]
@romayalon , I am talking about the details in the error message.
```
"detail": "Error: User with distinguished_name not found\n    at get_user_by_distinguished_name (/usr/local/noobaa-core/src/util/native_fs_utils.js:418:15)\n    at async Object.get_fs_context (/usr/local/noobaa-core/src/util/native_fs_utils.js:455:29)\n    at async validate_account_args (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:799:36)\n    at async add_account (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:455:5)\n    at async manage_account_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:590:9)\n    at async account_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:345:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:103:13)"
  }
```
Since we are displaying the same error message in scale, we better need to refactor the detail.
Expected: "Error: User with distinguished_name not found"

**Comment by rkomandu** [comment]
@nimrod-becker , this is verified by @anandhu-karattu , as per his comment. the discussion went around the "message correction",. 

@anandhu-karattu and @romayalon  , could you agree on this and move fwd. this is part of the ODF 4.15.1 d/s build request
