### ISSUE TITLE
NSFS | NC | CLI | Account add/update is failing when uid = 0 and gid != 0 and vice versa

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7787]
### Environment info
- NooBaa Version: Master
- Platform: NC

### Actual behavior
1. Account add/update is failing when uid = 0 but and gid != 0 and vice versa

### Expected behavior
1. An account can get created/updated  when uid = 0 but and gid != 0 and vice versa

### Steps to reproduce
```
> manage_nsfs.js account add --name foo --email foo@example.com --uid 0 --gid 10 2>/dev/null
{
  "error": {
    "code": "MissingAccountNSFSConfigUID",
    "message": "Account config should include UID",
    "detail": {
      "uid": 0,
      "gid": 10,
      "new_buckets_path": "/gpfs/bucket-root"
    }
  }
}
```

**Comment by romayalon** [comment]
re opening for validation

**Comment by romayalon** [comment]
@ramya-c3 can you please provide more details?
Are you running on upstream master / upstream 5.15 / downstream RPM? 
it was not backported yet to 5.15 upstream/downstream

**Comment by ramya-c3** [comment]
downstream RPM - 29/01

**Comment by romayalon** [comment]
@ramya-c3 ok so it makes sense we you can reproduce it, this is also a candidate IMHO to be backported to 5.15 WDYT?
also, would you verify it using upstream master?

**Comment by ramya-c3** [comment]
@romayalon it is working as expected

**Comment by nimrod-becker** [comment]
Closing per last comment
