### ISSUE TITLE
Invalid argument type error details are not clear

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7790]
### Environment info
- NooBaa Version: standalone noobaa
- Platform: noobaa-core-5.15.0-20240131.el9.x86_64

### Actual behavior
[root@ramyamc-12 noobaa-core]# node /usr/local/noobaa-core/src/cmd/manage_nsfs account add --name 12 --email 2>/dev/null
{
  "error": {
    "code": "InvalidArgumentType",
    "message": "Invalid argument type",
    "detail": "type of option email should be string, received: true (type boolean)"
  }
}
[root@ramyamc-12 noobaa-core]# node /usr/local/noobaa-core/src/cmd/manage_nsfs account add --name 2>/dev/null
{
  "error": {
    "code": "InvalidArgumentType",
    "message": "Invalid argument type",
    "detail": "type of option name should be string, number, received: true (type boolean)"
  }
}
[root@ramyamc-12 noobaa-core]# 

### Expected behavior
1. "type of option name should be string, number, received: true (type boolean)"
This should be rephrased  it confusing to the customer

### Steps to reproduce
1.

**Comment by shirady** [comment]
Hi @ramya-c3,
1. In this case: `node /usr/local/noobaa-core/src/cmd/manage_nsfs account add --name 12 --email 2>/dev/null`
The message is about the email argument, it is `--email` without value (hence it is boolean, like `--show-secrets`).
2. In the case: `node /usr/local/noobaa-core/src/cmd/manage_nsfs account add --name 2>/dev/null`
The message is about the name argument, it is `--name` without value (hence it is boolean, like `--show-secrets`).

How would you like it to be changed? 
Please send what you're suggesting.

**Comment by romayalon** [comment]
@ramya-c3 closed this issue, removing the request validation label
