### ISSUE TITLE
NSFS | NC | CLI | remove SensitiveString() usage except on secret_key

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7792]
### Environment info
- NooBaa Version: Master
- Platform: NC

### Actual behavior
1. Currently the manage_nsfs.js CLI contains the creation and manipulation of SensitiveString() in various places, we should remove these usages except for secret_key since the other strings are not sensitive. 

### Expected behavior
1. On manage_nsfs.js CLI, the only string that will be wrapped as sensitiveString() is secret_key.

**Comment by shirady** [comment]
@romayalon in the issue you're asking to leave only the `secret_key`, but I noticed that in the code there are places where the `access_key` is also with `SensitiveString` so I want to make sure about the requirement, for example:
https://github.com/noobaa/noobaa-core/blob/18ef8bc53f6f31a6dc77c8156d79f49069a3a566/src/util/cloud_utils.js#L189-L194

What about the use of `SensitiveString` in `bucketspace_fs`?
It seems to be out of the scope of this issue, but I don't understand why. For example:
https://github.com/noobaa/noobaa-core/blob/18ef8bc53f6f31a6dc77c8156d79f49069a3a566/src/sdk/bucketspace_fs.js#L103-L112

**Comment by romayalon** [comment]
@shirady 
1. You can keep both the access key and secret key as sensitive strings, on manage_nsfs The sensitive String class is used only to avoid printing sensitive strings. I wanted to get rid of sensitive strings because most of the strings are not sensitive and it caused us lots of pain.
2. The manage_nsfs and bucketspace_fs flows are different. manage_nsfs getting arguments and writing a configuration to a config file. 
However, bucketspace_fs is a part of the whole noobaa endpoint process in which we need to stick to the regular noobaa flow, in which names and some other strings are expected to be sensitive strings.

**Comment by shirady** [comment]
> 1. You can keep both the access key and secret key as sensitive strings, on manage_nsfs The sensitive String class is used only to avoid printing sensitive strings. I wanted to get rid of sensitive strings because most of the strings are not sensitive and it caused us lots of pain.
> 2. The manage_nsfs and bucketspace_fs flows are different. manage_nsfs getting arguments and writing a configuration to a config file.
>    However, bucketspace_fs is a part of the whole noobaa endpoint process in which we need to stick to the regular noobaa flow, in which names and some other strings are expected to be sensitive strings.

@romayalon thanks, I will stick to the original requirement in the issue and leave only the `secret_key` as a sensitive string.
