### ISSUE TITLE
List buckets returns CreationDate as current date instead of actual bucket create time

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7795]
### Environment info
- NooBaa Version: **5.14**
- Platform: **NA**

### Actual behavior
1. We always use now for the list buckets reply -

https://github.com/noobaa/noobaa-core/blob/b04f5ab2f17b72ded93b17e8b9f431c66a8c5308/src/endpoint/s3/ops/s3_get_service.js#L11-L18

### Expected behavior
1. Should return the specific creation date of each bucket.

### Steps to reproduce
1. NA

**Comment by guymguym** [comment]
@nimrod-becker @romayalon can this fix be added to a 5.14 release? At least for nsfs.

**Comment by nimrod-becker** [comment]
We need to fix for master to begin with, then we can see when we can backport

**Comment by romayalon** [comment]
I'm re-opening it, I fixed it only for NC NSFS (BucketspaceFS) we need to fix it on other bucketspaces as well

**Comment by nimrod-becker** [comment]
We'll probably want to backport this one

**Comment by romayalon** [comment]
@nimrod-becker Backport PR to 5.15 - https://github.com/noobaa/noobaa-core/pull/7805

**Comment by guymguym** [comment]
@nimrod-becker is this going to be backported and closed?

**Comment by romayalon** [comment]
@guymguym it was backported on https://github.com/noobaa/noobaa-core/pull/7824
