### ISSUE TITLE
NSFS | NC | Add Limitation to Account Name

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7818]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently, we have no limit to account names (they can be numbers or strings).

### Expected behavior
1. Account names should be limited - for example, length (so we should not handle edge cases of name 0 for example).

### Steps to reproduce
1. Create an account: `sudo node src/cmd/manage_nsfs account add --name 0 --new_buckets_path /tmp/nsfs_root1 --uid 1003 --gid 1003`
parietal output:
```
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "name": "0",
      "email": "0",
....
}
```

### More information - Screenshots / Logs / Other output
- For example, in bucket name, we use this function for limitation:
https://github.com/noobaa/noobaa-core/blob/cada310b4f9d3123febccc4515f2da70669cc5e9/src/util/native_fs_utils.js#L465-L472

**Comment by romayalon** [comment]
@shirady The only limitation I found is in validate_create_account_params() -
```
if (req.rpc_params.name.unwrap() !== req.rpc_params.name.unwrap().trim()) {
   throw new RpcError('BAD_REQUEST', 'system name must not contain leading or trailing spaces');
}
```
I don't mind adding limitations but I can't think of a reason for it to be a must, is there a reason you think it's needed?
You can ofc suggest the limitations you find needed to the team and we can have a discussion, thanks!

**Comment by shirady** [comment]
@romayalon I thought that since we use the argv with minimist we don't need this trim, but I checked this and I think we should have it at constraint as well.
Example: When running `sudo node src/cmd/manage_nsfs account add --name ' shira-2013 ' --new_buckets_path /tmp/nsfs_root1  --uid 2013 --gid 2013`
This check `console.log('SDSD name check', argv.name === argv.name.trim());` returns `false`.
And we write this config file:
![Screenshot 2024-03-11 at 11 04 42](https://github.com/noobaa/noobaa-core/assets/57721533/cc6d2ae9-76e3-4536-a9e2-c1cb60b3409a)

My suggestions for naming constraints:
- Add the trim as a constraint `name !== name.trim()`.
- Add a minimum number of characters `name.length < 3`.

I also suggested to have the same constraint as bucket name, so it will be less confusing to remember the differences between them.

**Comment by shirady** [comment]
Hi,
Adding naming restriction that we should check the behavior and add to the naming limitation:
1. '/' (tested and it created `.json` file under `/etc/noobaa.conf.d/accounts`).
2. '.'
3. ''
4. Also 'anonymous' should be added to this list according to PR #7997
Note: this list should be in a file where we can reuse it for username in IAM.

cc: @romayalon @guymguym

**Comment by romayalon** [comment]
@shirady what are the IAM restrictions for account names?

**Comment by shirady** [comment]
@romayalon attached the restrictions for username in User ([link to documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_User.html)):

> UserName
> The friendly name identifying the user.
> Type: String
> Length Constraints: Minimum length of 1. Maximum length of 64.
> Pattern: [\w+=,.@-]+

Those I attached above 1+2+4 are specific examples which are relevant to our system.
I will note that currently, we didn't add user validation in published PRs (known gap).
