### ISSUE TITLE
NSFS | NC | Allow unset 'new_buckets_path'

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7828]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Currently we don't have the option to unset the property `new_buckets_path` after the account was created.

### Expected behavior
1. To allow users to unset the property `new_buckets_path` after the account was created when using Manage NSFS CLI.

### Steps to reproduce
1. none

### More information - Screenshots / Logs / Other output
Like we have the option to unset `fs_backend` and `s3_policy`.

**Comment by nimrod-becker** [comment]
Update to account, disabling creation of new buckets for an account

**Comment by romayalon** [comment]
@nadavMiz closing per your fix
