### ISSUE TITLE
support setting s3 metadata on already existing objects

### ISSUE THREAD

**Issue by janfrode** [noobaa/noobaa-core#7842]
**Is your feature request related to a problem? Please describe.**

When integrating noobaa nsfs with Scale file system with tiering to tape, it would be great if the end user could control which files are migrated to/from tape by setting object metadata like fileState=recall, fileState=migrateToTape, so that we from file system side can use this for selecting which files to migrate to tape, or recall from tape.

Currently there doesn't seem to be any way of setting object metadata on already uploaded objects, so one suggestion might be to overload the `s3 copy-object` to only set metadata if source and destination is the same file.

**Describe the solution you'd like**

Metadata should be set without rewriting the object if `s3 copy-object` is called on existing object with the `--metadata` option.

**Describe alternatives you've considered**

Don't see any good alternatives. Only other options I see is to upload a file-list with instructions for which files to migrate out/in, but that doesn't work well with Scale policy engine.

**Comment by janfrode** [comment]
Never mind... found  that put-object-tagging can do this...

**Comment by nimrod-becker** [comment]
Just note that object tagging adds additional tags on the obj, its not the "MD" of the object.
