### ISSUE TITLE
NSFS | NC | get_bucket_acl fails on reading bucket.owner_account.id

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7853]
### Environment info
- NooBaa Version: **noobaa-core-5.15.0-20240213.el8.x86_64**
- Platform: **rhel8**

### Actual behavior
1. Invoking get-bucket-acl fails with internal error here -

https://github.com/noobaa/noobaa-core/blob/daba777409ffe5e6803282c24ad2f74f098d6de3/src/endpoint/s3/ops/s3_get_bucket_acl.js#L11-L15

2. Seems like  owner_account field is expected to be an object with id and email subfields in the sdk level, but `bucketspace_fs.read_bucket()` returns owner_account as it is stored in the configuration which is a string representing just the id.

### Expected behavior
1. Should not fail the request.
2. This should affect also 

### Steps to reproduce
1. Invoke get-bucket-acl.

### More information - Screenshots / Logs / Other output

Command:
```
$ aws  --endpoint http://localhost:6001/ s3api get-bucket-acl --bucket test1
An error occurred (InternalError) when calling the GetBucketAcl operation (reached max retries: 4): We encountered an internal error. Please try again.
```

From the log:
```
Feb 22 17:06:02 host-01 node[441680]: [nsfs/441680] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR 
  <?xml version="1.0" encoding="UTF-8"?>
  <Error>
    <Code>InternalError</Code>
    <Message>We encountered an internal error. Please try again.</Message>
    <Resource>/test1?acl</Resource>
    <RequestId>lsxf0p7u-ezp1ef-edt</RequestId>
  </Error>
GET /test1?acl  { ... } 
TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.get_bucket_acl [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_get_bucket_acl.js:13:37)
    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:150:19)
    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:65:9)
```

**Comment by romayalon** [comment]
#7862 contains a fix for this issue, closing
