### ISSUE TITLE
NSFS | NC | Cross-account bucket policy not working

### ISSUE THREAD

**Issue by venkateshl24** [noobaa/noobaa-core#7854]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240219.el9.x86_64
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.  Cross-account bucket policy not working 

### Expected behavior
1. We should be able to create cross-account bucket policy and it should be support for users across group

### Steps to reproduce
1. Created 2 accounts - account-test17 and account-test18 and 1 bucket associated with each account - bucket-account-test17 and bucket-account-test18
2. Setting 775 to bucket path

[root@venkat92-x-master ~]# chmod 0775 /mnt/fs1/test18
[root@venkat92-x-master ~]#
[root@venkat92-x-master ~]# chmod 0775 /mnt/fs1/test18/bucket-18-1
[root@venkat92-x-master ~]#
[root@venkat92-x-master ~]# ls -l /mnt/fs1/test18/
total 1
drwxrwxr-x 2 8318 8318 4096 Feb 21 04:58 bucket-18-1
[root@venkat92-x-master ~]# ls -l /mnt/fs1/
total 2
drwxrwx--- 3    8317    8317 4096 Feb 21 04:53  test17
drwxrwxr-x 3    8318    8318 4096 Feb 21 04:58  test18

3. Bucket policy is set to allow all AWS users to access bucket-18-1 to list, copy, delete objects into it
4.  Now, User for account account-test17 is failed to list objects in bucket-account-test18

Questions 1. whether users/groups associated with account-test17 can access buckets/objects associated with account-test18?
          2. Do we need to verify such cross-account access?

**Comment by naveenpaul1** [comment]
@venkateshl24 could you please share the policy you tried.

**Comment by venkateshl24** [comment]
This is the policy that i'm using:

        POLICY="{\"Version\": \"2024-02-15\",\"Statement\": [{\"Effect\": \"Allow\",\"Principal\": {\"AWS\": \"*\"},\"Action\": [\"s3:PutObject\",\"s3:ListBucket\",\"s3:DeleteBucket\",\"s3:DeleteObject\",\"s3:GetBucketLocation\",\"s3:GetObject\"],\"Resource\": [\"arn:aws:s3:::${BUCKET_NAME}\",\"arn:aws:s3:::${BUCKET_NAME}/*\"]}]}"

**Comment by venkateshl24** [comment]
1. Created 2 accounts and 1 bucket associated with each account

[root@venkat92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs account list 2>/dev/null                                                             {
  "response": {
    "code": "AccountList",
    "reply": [
      {
        "name": "account-test17"
      },
      {
        "name": "account-test18"
      }
    ]
  }
}

[root@venkat92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket list 2>/dev/null
{
  "response": {
    "code": "BucketList",
    "reply": [
      {
        "name": "bucket-account-test17"
      },
      {
        "name": "bucket-account-test18"
      }
    ]
  }
}

2. Setting 775 to bucket path

[root@venkat92-x-master ~]# chmod 0775 /mnt/fs1/test18
[root@venkat92-x-master ~]#
[root@venkat92-x-master ~]# chmod 0775 /mnt/fs1/test18/bucket-18-1
[root@venkat92-x-master ~]#
[root@venkat92-x-master ~]# ls -l /mnt/fs1/test18/
total 1
drwxrwxr-x 2 8318 8318 4096 Feb 21 04:58 bucket-18-1
[root@venkat92-x-master ~]# ls -l /mnt/fs1/
total 2
drwxrwx--- 3    8317    8317 4096 Feb 21 04:53  test17
drwxrwxr-x 3    8318    8318 4096 Feb 21 04:58  test18

3. Bucket policy is set to allow all AWS users to access bucket-18-1 to list, copy, delete objects into it
 
Policy: {
    "Policy": "{\"Version\":\"2024-02-15\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"s3:PutObject\",\"s3:ListBucket\",\"s3:DeleteObject\",\"s3:GetObject\"],\"Resource\":[\"arn:aws:s3:::bucket-account-test18\",\"arn:aws:s3:::bucket-account-test18/*\"]}]}"
}


4. When user for account s3u8317 is failed to list objects in bucket-account-test18

[root@c6003v1 ~]# alias s3u8318='AWS_ACCESS_KEY_ID=NBltSc8zq5mFnkAFVsAC AWS_SECRET_ACCESS_KEY=sHh2qerDCvwHGmQ8yzqX+MmlTpOElDHXuwhIk5+K aws --endpoint https://10.11.4.222:6443 --no-verify-ssl s3'
[root@c6003v1 ~]#
[root@c6003v1 ~]# s3u8318 ls s3://bucket-account-test18/

urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.4.222'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
2024-02-21 05:54:20   57549081 awscliv2.zip
[root@c6003v1 ~]#
[root@c6003v1 ~]#
[root@c6003v1 ~]# alias s3u8317='AWS_ACCESS_KEY_ID=XXLSNEiAvHcmCy2zluRg AWS_SECRET_ACCESS_KEY=Ec4SD3TKt86GJpxrywxiaQSUh+BpFrjeCDb578tM aws --endpoint https://10.11.4.222:6443 --no-verify-ssl s3'
[root@c6003v1 ~]#
[root@c6003v1 ~]# s3u8317 ls s3://bucket-account-test17/

urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.4.222'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
2024-02-21 04:56:55 10737418240 file1
[root@c6003v1 ~]#
[root@c6003v1 ~]#
[root@c6003v1 ~]# s3u8317 ls s3://bucket-account-test18/

urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.11.4.222'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
[root@c6003v1 ~]#


Questions 1. whether users/groups associated with account-test17 can access buckets/objects associated with account-test18?
          2. Do we need to verify such cross-account access?

**Comment by venkateshl24** [comment]
Hi Naveen, As you suggested, i updated the bucket with the policy using noobaa command (Early i was adding bucket policy through aws s3api).  These are the buckets:

`[root@venkat92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket list 2>/dev/null
{
  "response": {
    "code": "BucketList",
    "reply": [
      {
        "name": "bucket-test27"
      },
      {
        "name": "bucket-test28"
      }
    ]
  }
}`

I'm updating bucket policy for bucket-test28, which is failling with "Bucket does not exist"!

`[root@venkat92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket update --config_root /mnt/fs1/fs-ces-shared/ces/s3-config/ --name bucket-test28 --bucket_policy '{"Version": "2012-10-17","Statement": [ { "Effect": "Allow", "Principal": { "AWS": "*" }, "Action": [ "s3:PutObject","s3:ListBucket","s3:DeleteObject","s3:GetObject" ], "Resource": [ "arn:aws:s3:::bucket-test28/*", "arn:aws:s3:::bucket-test28" ] }]}'
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /gpfs/fs-ces-shared/ces/s3-config
nsfs: config_dir_path=/gpfs/fs-ces-shared/ces/s3-config config.json= {
  ENDPOINT_PORT: 23423,
  ENDPOINT_SSL_PORT: 6443,
  ENDPOINT_SSL_STS_PORT: 7443,
  EP_METRICS_SERVER_PORT: 90,
  ALLOW_HTTP: true,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default'
}
2024-03-01 05:11:23.839006 [PID-1320931/TID-1320931] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-03-01 05:11:23.839390 [PID-1320931/TID-1320931] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
(node:1320931) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Mar-1 5:11:24.967 [/1320931]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Mar-1 5:11:24.994 [/1320931]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
Mar-1 5:11:24.995 [/1320931]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Mar-1 5:11:25.009 [/1320931]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
Mar-1 5:11:25.040 [/1320931]   [LOG] CONSOLE:: generate_entropy: entropy_avail 256
{
  "error": {
    "code": "NoSuchBucket",
    "message": "Bucket does not exist",
    "detail": "bucket-test28"
  }
}
[root@venkat92-x-worker1 ~]#
`

**Comment by romayalon** [comment]
@naveenpaul1 @venkateshl24 On the bucket list you don't pass --config_root but on the bucket update you do, can you check the update without the config_root?
I suspect there is an issue with the configuration

**Comment by naveenpaul1** [comment]
@romayalon I already asked @venkateshl24 to try without config_root and it's working, But we need to check why the same bucket policy didn't work when he added using S3 api.

**Comment by venkateshl24** [comment]
@naveenpaul1 @romayalon When i tried the above command with config_root removed, bucket policy setting worked as expected 

`[root@venkat92-x-worker1 ~]# /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs bucket update --name bucket-test28 --bucket_policy '{"Version": "2012-10-17","Statement": [ { "Effect": "Allow", "Principal": { "AWS": "*" }, "Action": [ "s3:PutObject","s3:ListBucket","s3:DeleteObject","s3:GetObject" ], "Resource": [ "arn:aws:s3:::bucket-test28/*", "arn:aws:s3:::bucket-test28" ] }]}' 2>/dev/null
{
  "response": {
    "code": "BucketUpdated",
    "reply": {
      "_id": "65e1ce21f1bea421534ab26f",
      "name": "bucket-test28",
      "owner_account": "65e1ccfc4bc4fe81b142e0e1",
      "system_owner": "account-test28",
      "bucket_owner": "account-test28",
      "versioning": "DISABLED",
      "creation_date": "2024-03-01T12:46:25.628Z",
      "path": "/mnt/fs1/bucket8328",
      "should_create_underlying_storage": false,
      "s3_policy": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "*"
            },
            "Action": [
              "s3:PutObject",
              "s3:ListBucket",
              "s3:DeleteObject",
              "s3:GetObject"
            ],
            "Resource": [
              "arn:aws:s3:::bucket-test28/*",
              "arn:aws:s3:::bucket-test28"
            ]
          }
        ]
      }
    }
  }
}
[root@venkat92-x-worker1 ~]#
`

But earlier i used s3api with the same policy which didn't work.  Question is why bucket policy setting is working with noobaa command and not with s3api

**Comment by naveenpaul1** [comment]
@venkateshl24 Could you please check this policy getting updated to bucket schema

**Comment by venkateshl24** [comment]
I discussed with naveen to verify the issue with bucket created from AWS S3 cli and policy created with s3api.  With linux permissions properly set to directories, we saw that cross-account access is working when we use s3api also.

**Comment by naveenpaul1** [comment]
closing this issue per the last comment

**Comment by naveenpaul1** [comment]
folder structure was like this `{config_root}/{account_name}/{bucket_name}`  and  after adding  proper access to the parent folder(`{config_root}/{account_name}` access : 775) issue got fixed. Previously 775 was added only to `{config_root}/{account_name}/{bucket_name}`
 @venkateshl24 do you have anything to add?
