### ISSUE TITLE
NSFS: Restore action corrupts objects (truncated to 0 bytes)

### ISSUE THREAD

**Issue by piste-jp-ibm** [noobaa/noobaa-core#7855]
### Environment info

- NooBaa Version: noobaa-core-5.16.0-20240218.el8.x86_64
- Platform: NSFS

### Actual behavior

- On the restore action, restoring file goes to `resident` state and file size is truncated

### Expected behavior

- The target file shall be recalled by EE
  - State shall be `premigrated`
  - File size must not be changed

### Steps to reproduce

```
# /opt/ibm/ltfsee/bin/eeadm file state /gpfs/bucket-root/testbucket01/10M3; ls -l /gpfs/bucket-root/testbucket01/10M3
Name: /gpfs/bucket-root/testbucket01/10M3
State: migrated
ID: 11568091588502320787-10770320459909038081-493957867-9751-0
Replicas: 1
Tape 1: FF0006L8@pool1@lib1 (tape state=appendable)

-rw-rw----. 1 root wheel 10485760 Feb 29 10:49 /gpfs/bucket-root/testbucket01/10M3

# aws s3api restore-object --bucket testbucket01 --key 10M3 --restore-request '{"Days":1}'

# sleep 900

# /usr/local/noobaa-core/node/bin/node /usr/local/noobaa-core/src/cmd/manage_nsfs.js glacier restore

# /opt/ibm/ltfsee/bin/eeadm file state /gpfs/bucket-root/testbucket01/10M3; ls -l /gpfs/bucket-root/testbucket01/10M3
Name: /gpfs/bucket-root/testbucket01/10M3
State: resident

-rw-rw----. 1 root wheel 0 Feb 29 11:09 /gpfs/bucket-root/testbucket01/10M3
```

### More information - Screenshots / Logs / Other output

In my bench, the file is truncated at https://github.com/noobaa/noobaa-core/blob/4bf10f476ebc0ed213ad3f12553fac620c071e01/src/sdk/nsfs_glacier_backend/tapecloud.js#L184 and https://github.com/noobaa/noobaa-core/blob/4bf10f476ebc0ed213ad3f12553fac620c071e01/src/sdk/nsfs_glacier_backend/tapecloud.js#L249

From the native fs code (`src/native/fs/fs_napi.cpp`), open mode `"rw"` seems to interpret to `O_RDONLY | O_TRUNC | O_CREAT | O_WRONLY` at `static int parse_open_flags(std::string flags)`. It matches to the actual behavior.

https://github.com/noobaa/noobaa-core/blob/4bf10f476ebc0ed213ad3f12553fac620c071e01/src/native/fs/fs_napi.cpp#L175-L223

**Comment by piste-jp-ibm** [comment]
@tangledbytes , @guymguym 

I believe the line L184@src/sdk/nsfs_glacier_backend/tapecloud.js and L249@src/sdk/nsfs_glacier_backend/tapecloud.js might have to be

```JS
                    fh = await nb_native().fs.open(fs_context, entry, 'rw*');
```

otherwise `rw` is trunsrated to `O_RDONLY | O_TRUNC | O_CREAT | O_WRONLY` and finally original object file is truncated to 0.

`*` seems to invert the `O_TRUNC` flag of the `flags` parameter of `open()` systemcall in `src/native/fs/fs_napi.cpp()`

In my bench, this code looks work fine.

**Comment by tangledbytes** [comment]
Ah shoot, you are right @piste-jp-ibm. Addressing this in the same PR: https://github.com/noobaa/noobaa-core/pull/7848

**Comment by piste-jp-ibm** [comment]
@tangledbytes ,

Sure. Please close this. And could you tell me how do I handle the PR close in this project? I will follow that in the next time.
