### ISSUE TITLE
Noobaa is not starting the service by reading the configuration stored in the mount system post the system reboot. 

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7857]
### Environment info
- NooBaa Version: 5.15.0-20240221
- Platform: standalone

### Actual behavior
1. [root@test ~]#  Service is coming up with default configuration

Feb 28 04:46:44 c83f1-app2 kernel: Linux version 5.14.0-362.8.1.el9_3.x86_64 ([mockbuild@x86-vm-07.build.eng.bos.redhat.com](mailto:mockbuild@x86-vm-07.build.eng.bos.redhat.com)) (gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), GNU ld version 2.35.2-42.el9) #1 SMP PREEMPT_DYNAMIC Tue Oct 3 11:12:36 EDT 2023
Feb 28 04:46:44 c83f1-app2 kernel: The list of certified hardware and cloud instances for Red Hat Enterprise Linux 9 can be viewed at the Red Hat Ecosystem Catalog, https://catalog.redhat.com/.
Feb 28 04:46:44 c83f1-app2 kernel: Command line: BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.14.0-362.8.1.el9_3.x86_64 root=/dev/mapper/rhel_c83f1--app2-root ro crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M resume=/dev/mapper/rhel_c83f1--app2-swap rd.lvm.lv=rhel_c83f1-app2/root rd.lvm.lv=rhel_c83f1-app2/swap
Feb 28 04:46:44 c83f1-app2 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Feb 28 04:46:44 c83f1-app2 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Feb 28 04:46:44 c83f1-app2 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Feb 28 04:46:44 c83f1-app2 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Feb 28 04:46:44 c83f1-app2 kernel: x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'compacted' format.
Feb 28 04:46:44 c83f1-app2 kernel: signal: max sigframe size: 1776
Feb 28 04:46:44 c83f1-app2 kernel: BIOS-provided physical RAM map:
....
Feb 28 04:46:53 c83f1-app2 NetworkManager[2313]: <info>  [1709113613.9775] device (ens1f0np0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Feb 28 04:46:53 c83f1-app2 systemd[1]: Started Network Manager Script Dispatcher Service.
Feb 28 04:46:53 c83f1-app2 systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
Feb 28 04:46:54 c83f1-app2 node[2318]: load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /cesSharedRoot//ces/s3-config
Feb 28 04:46:54 c83f1-app2 node[2318]: config.load_nsfs_nc_config could not find config.json... skipping
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[36m   [L0]#033[39m UPGRADE:: upgrade manager started..
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.245#033[35m [Upgrade/2318] #033[36m   [L0]#033[39m UPGRADE:: upgrade manager started..
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[33m [WARN]#033[39m CONSOLE:: config.load_nsfs_nc_config could not find config.json... skipping
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.250#033[35m [Upgrade/2318] #033[33m [WARN]#033[39m CONSOLE:: config.load_nsfs_nc_config could not find config.json... skipping
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[36m  [LOG]#033[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.250#033[35m [Upgrade/2318] #033[36m  [LOG]#033[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[33m [WARN]#033[39m core.util.json_utils:: could not find json file /cesSharedRoot/ces/s3-config/system.json. returning empty data
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.250#033[35m [Upgrade/2318] #033[33m [WARN]#033[39m core.util.json_utils:: could not find json file /cesSharedRoot/ces/s3-config/system.json. returning empty data
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[36m  [LOG]#033[39m UPGRADE:: system does not exist. no need for an upgrade
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.250#033[35m [Upgrade/2318] #033[36m  [LOG]#033[39m UPGRADE:: system does not exist. no need for an upgrade
Feb 28 04:46:54 c83f1-app2 node[2318]: [Upgrade/2318] #033[36m   [L0]#033[39m UPGRADE:: upgrade completed successfully!
Feb 28 04:46:54 c83f1-app2 node[2318]: #033[32mFeb-28 4:46:54.250#033[35m [Upgrade/2318] #033[36m   [L0]#033[39m UPGRADE:: upgrade completed successfully!
Feb 28 04:46:54 c83f1-app2 systemd[1]: Started The NooBaa nsfs service..
Feb 28 04:46:54 c83f1-app2 kernel: mlx5_core 0000:41:00.0 ens1f0np0: Link up
Feb 28 04:46:54 c83f1-app2 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): ens1f0np0: link becomes ready
Feb 28 04:46:54 c83f1-app2 NetworkManager[2313]: <info>  [1709113614.3342] manager: (ens1f1np1): new Ethernet device (/org/freedesktop/NetworkManager/Devices/4)
...
Feb 28 04:46:54 c83f1-app2 node[2356]: load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /cesSharedRoot//ces/s3-config
Feb 28 04:46:54 c83f1-app2 node[2356]: config.load_nsfs_nc_config could not find config.json... skipping
Feb 28 04:46:54 c83f1-app2 kernel: mlx5_core 0000:41:00.1 ens1f1np1: Link up
Feb 28 04:46:54 c83f1-app2 NetworkManager[2313]: <info>  [1709113614.7042] manager: (ens5f0np0): new Ethernet device (/org/freedesktop/NetworkManager/Devices/5)
Feb 28 04:46:54 c83f1-app2 NetworkManager[2313]: <info>  [1709113614.7044] device (ens5f0np0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Feb 28 04:46:55 c83f1-app2 kernel: mlx5_core 0000:a1:00.0 ens5f0np0: Link down
....
....
....

Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.718#033[35m [nsfs/2356] #033[33m [WARN]#033[39m core.util.json_utils:: could not find json file
/cesSharedRoot/ces/s3-config/system.json. returning empty data
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m  [LOG]#033[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.719#033[35m [nsfs/2356] #033[36m  [LOG]#033[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[31m[ERROR]#033[39m CONSOLE:: failed to create NSFS system data [Error: ENOENT: no such file or directo
ry, unlink '/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'] { errno: #033[33m-2#033[39m, code: #033[32m'ENOENT'#033[39m, syscall: #033[32m'un
link'#033[39m, path: #033[32m'/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'#033[39m }
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.719#033[35m [nsfs/2356] #033[31m[ERROR]#033[39m CONSOLE:: failed to create NSFS system data [Err
or: ENOENT: no such file or directory, unlink '/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'] { errno: #033[33m-2#033[39m, code: #033[32m'EN
OENT'#033[39m, syscall: #033[32m'unlink'#033[39m, path: #033[32m'/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'#033[39m }
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: endpoint: replacing old umask:  22 with new umask:  0
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.767#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: endpoint: replacing old
umask:  22 with new umask:  0
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Configured Virtual Hosts: []
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.768#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Configured Virtual Host
s: []
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Configured Location Info: { region: #033[32m''#033[39m }
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.768#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Configured Location Inf
o: { region: #033[32m''#033[39m }
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m  [LOG]#033[39m CONSOLE:: generate_entropy: entropy_avail 256
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.768#033[35m [nsfs/2356] #033[36m  [LOG]#033[39m CONSOLE:: generate_entropy: entropy_avail 256
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[36m   [L0]#033[39m core.util.ssl_utils:: SSL certificate not found in dir /cesSharedRoot/ces/s3-co
nfig/certificates/
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.773#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.util.ssl_utils:: SSL certificate not found
in dir /cesSharedRoot/ces/s3-config/certificates/
Feb 28 04:46:58 c83f1-app2 node[2356]: [nsfs/2356] #033[33m [WARN]#033[39m core.util.ssl_utils:: Generating self-signed SSL certificate for S3
Feb 28 04:46:58 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:58.773#033[35m [nsfs/2356] #033[33m [WARN]#033[39m core.util.ssl_utils:: Generating self-signed SSL
certificate for S3
Feb 28 04:46:59 c83f1-app2 node[2356]: [nsfs/2356] #033[33m [WARN]#033[39m core.util.ssl_utils:: Certificate folder  /cesSharedRoot/ces/s3-config/certific
ates/  does not exist. New certificate won't be loaded.
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.043#033[35m [nsfs/2356] #033[33m [WARN]#033[39m core.util.ssl_utils:: Certificate folder  /c
esSharedRoot/ces/s3-config/certificates/  does not exist. New certificate won't be loaded.
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.073#033[35m [nsfs/2356] #033[33m [WARN]#033[39m core.endpoint.endpoint:: HTTP is not allowed for NC NSFS.
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.073#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Starting S3 HTTPS #033[33m6443#033[39m
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.074#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Started S3 HTTPS successfully
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.074#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.endpoint.endpoint:: Starting metrics server #033[33m7004#033[39m
Feb 28 04:46:59 c83f1-app2 node[2356]: #033[32mFeb-28 4:46:59.074#033[35m [nsfs/2356] #033[36m   [L0]#033[39m core.server.analytic_services.prometheus_reporting:: Starting prometheus metrics server on HTTP port #033[33m7004#033[39m
...

### Expected behavior
1.Service should come up by reading from the configured configuration file

### Steps to reproduce
1. . [root@test ~]# cat /mnt/ces/s3-config/config.json 
{
 "ENDPOINT_FORKS": 2,
 "ENDPOINT_PORT": 6001,
 "ENDPOINT_SSL_PORT": 6443,
 "ALLOW_HTTP": true,
 "UV_THREADPOOL_SIZE": 16,
 "TEST_DL_PATH": "/usr/lpp/mmfs/lib/libtest.so",
 "NOOBAA_LOG_LEVEL": "default",
 "NSFS_NC_STORAGE_BACKEND": "test",
 "NSFS_NC_CONFIG_DIR_BACKEND": "test",
 "NSFS_DIR_CACHE_MAX_DIR_SIZE": 268435456,
 "NSFS_DIR_CACHE_MAX_TOTAL_SIZE": 805306368
}
3. Reboot the system.
4. Post reboot of the system  when the noobaa comes up it is using default configuration instead of reading of config.json. 
5. This issue happens when the service starts before the mounting is available

**Comment by romayalon** [comment]
@ramya-c3 @tangledbytes 
looks like NooBaa is aware of the missing config dir, but we continue to run the server - 
```
failed to create NSFS system data [Error: ENOENT: no such file or directo
ry, unlink '/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'] { errno: https://github.com/noobaa/noobaa-core/pull/33[33m-2#033[39m, code: https://github.com/noobaa/noobaa-core/pull/33[32m'ENOENT'https://github.com/noobaa/noobaa-core/pull/33[39m, syscall: https://github.com/noobaa/noobaa-core/pull/33[32m'un
link'https://github.com/noobaa/noobaa-core/pull/33[39m, path: https://github.com/noobaa/noobaa-core/pull/33[32m'/cesSharedRoot/ces/s3-config/system.json.lt5m4c9q-34357b75'
```
I suggest failing the nsfs.js script completely on this case @tangledbytes WDYT?

**Comment by naveenpaul1** [comment]
noobaa_nsfs service already checking for gpfs file mount before starting the service in `noobaa_nsfs.service`. Looks like it's not working as expected, 
```After=gpfs-wait-mount.service ```
@janfrode @ramya-c3 Could you please provide more specific preconditions check that validate file mount.

**Comment by janfrode** [comment]
According to the documentation, gpfs-wait-mount.service should be correct I think:

https://www.ibm.com/docs/en/storage-scale/5.1.9?topic=gpfs-planning-systemd

```
gpfs-wait-mount.service
Marker service which switches to active after the GPFS filesystems have been mounted. It uses the filesystem state as shown in the mmhealth node show command output for its status. The status for the mmhealth command only looks at filesystems which have automount value set to yes.
```

But checking c83f1-app2 which I think was the machine @ramya-c3 had issue with, I see that this service has not been enabled. Maybe that's the problem, that we must make sure to enable the gpfs-wait-mount.service for the After= to have an effect?

```
[root@c83f1-app2 ~]# systemctl status gpfs-wait-mount.service
○ gpfs-wait-mount.service
     Loaded: loaded (/usr/lib/systemd/system/gpfs-wait-mount.service; disabled; preset: disabled)
     Active: inactive (dead)
```

**Comment by janfrode** [comment]
https://serverfault.com/questions/812584/in-systemd-whats-the-difference-between-after-and-requires

`Also, the way I understand it (although I can't test that now and don't find a reference), After= is "loose coupling", which effectively means that a service with an After statement would still run even if the one named in the After= line isn't started at all, while Requires= would prevent its start if the requirement isn't met.
`

So maybe it should be Requires= instead of After=.  If we do Requires=, that would automatically trigger the gpfs-wait-mount.service to be enabled when noobaa_nsfs service is enabled. But that would break this service on non-GPFS systems..

**Comment by romayalon** [comment]
@janfrode looks like the After= won't start the gpfs service, but if we will add Wants= the gpfs wait mount service will be started when noobaa_nsfs is started...
 WDYT? (Requires= won't be working for non GPFS deployments as you mentioned in the github issue)

**Comment by romayalon** [comment]
re-opening for validation, @ramya-c3 this fix can currently be validated using upstream RPMs
