### ISSUE TITLE
Bucket create should not be able to use account's newbucketspath

### ISSUE THREAD

**Issue by PravinRanjan10** [noobaa/noobaa-core#7861]
### Actual behavior
Issue: User is able to create bucket with account's newbucketspath as FS path. We should not allow this

Step1: Create an account
--name account-123 --uid 1002 --gid 1002 --new_buckets_path **/mnt/fs1/test-123**
Account is created successfully. The secret and access keys are as follows.
Access Key         Secret Key
--------        ---------
xxxxxxxxx    xxxxxxxxx

Step2: Create a bucket with same fs path
--name bucket-123 --owner anandhu-123 --path **/mnt/fs1/test-123**

Bucket bucket-123 created successfully!!

### Expected behavior
This should be blocked due to below use case
Use case: All the new buckets created with aws s3 mb command will be created under --path **/mnt/fs1/test-123.**
That means bucket-123 will have all other buckets listed under it.

### Steps to reproduce
1. Create account with --new_buckets_path **/mnt/fs1/test-123** and bucket with --path  **/mnt/fs1/test-123** same.

**Comment by romayalon** [comment]
@PravinRanjan10 @naveenpaul1 as discussed on Slack -
We wouldn't like to create this kind of limitation because we don't want to limit the user to only be able to export existing directories that are under his new_buckets_path.
We agreed that when running manage_nsfs bucket we will check that the bucket owner has read and write access to the underlying directory and if he doesn't we will throw an error.

**Comment by madhuthorat** [comment]
>> Not sure why we want to limit this, sounds like there are use cases where its valid.
@nimrod-becker Thank you for the input. If this is the case then would like to learn about certain use case in which this is valid ?

**Comment by nimrod-becker** [comment]
@madhuthorat nothing at this point, but it doesn't make sense to block this. If there is a sense to block it from the scale side, then scale should block it and can easily do so via he wrapper calling the CLI

**Comment by guymguym** [comment]
@madhuthorat I would not prevent such cases, just like we would not prevent such exports from nfs for example.

**Comment by guymguym** [comment]
Closing for now. Please reopen if needed.
