### ISSUE TITLE
remove the client_noobaa.log logrotate in NC env ?

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#7869]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

ODF 4.15.0 d/s build 0228 

### Actual behavior
1. 
Do we need to have the following in the /etc/logrotate.d/noobaa/logrotate_noobaa.conf file, we are not creating this file at all or what/when does this create 

/var/log/client_noobaa.log
{
    daily
    size 100M
    start 1
    missingok
    rotate 10
    compress
    create 644 root root
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        /bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}

### Expected behavior
1.

Checking if we need to remove these in the logroate.conf file , if the file is not required for the NC NSFS 
### Steps to reproduce
1.
NA

**Comment by naveenpaul1** [comment]
@rkomandu We are not creating a `client_noobaa.log` for now and log rotate configured in such a way that even if `client_noobaa.log` is missing it wont create any issue(`missingok`). I am not sure are there any standalone noobaa products generating `client_noobaa.log` or not. I dont have any issue with that.
@guymguym @romayalon @tangledbytes WDYT?

**Comment by romayalon** [comment]
tagging @dannyzaken who worked on this area?

**Comment by guymguym** [comment]
As @naveenpaul1 wrote - we do not create this log file for nsfs non-containerizes, so the logrotate config with missingok is expected to skip. This way we don't need to split our logrotate conf to 3 files and can deploy just one. Closing as not planned. Thanks
