### ISSUE TITLE
NSFS | NC | `wide` Property Should Be Removed from `fetch_bucket_data` And `fetch_account_data`

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7871]
### Environment info
- NooBaa Version: master
- Platform: NSFS NC

### Actual behavior
1. Currently, the `wide` property is fetched inside `fetch_bucket_data` and `fetch_account_data` while it is not a property of an account or bucket.

### Expected behavior
1. The `wide` property should be removed from `fetch_bucket_data` and `fetch_account_data` and fetch separately when needed (which is when using account/bucket list).

### Steps to reproduce
1. none, it is internal change.

### More information - Screenshots / Logs / Other output
Relevant parts in the code:
https://github.com/noobaa/noobaa-core/blob/8363cf721afdc2968a324b85751bf9f4717c11ce/src/cmd/manage_nsfs.js#L149

https://github.com/noobaa/noobaa-core/blob/8363cf721afdc2968a324b85751bf9f4717c11ce/src/cmd/manage_nsfs.js#L395

**Comment by naveenpaul1** [comment]
@shirady do we really wanted to make this change? `data` simply hold the data entered by customer related to account/bucket and if the `wide` value is undefined we are removing it in `_.omitBy()`,

**Comment by shirady** [comment]
@naveenpaul1 It is a simple internal change but when reading the code the `wide` is not a property of a bucket or account, but of the we manipulate the reply (with additional properties or without). It is a minor change for readability.
I will assign myself for this (you'll review the code).
