### ISSUE TITLE
NC | NSFS | Creating an Account with an Existing Access Key Doesn’t Return `Accountaccesskeyalreadyexists` Error

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7873]
### Environment info
- NooBaa Version: master
- Platform: NSFS NC

### Actual behavior
1. Creating an account with an existing access key returns `InternalError`:
```json
{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "detail": "Error: Too many levels of symbolic links"
  }
}
```

### Expected behavior
1. Creating an account with an existing access key should return `Accountaccesskeyalreadyexists`.

### Steps to reproduce
1. Create an account using `access_key` and `secret_key` flags: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path <path> --access_key <access_key> --secret_key <secret_key> --uid <uid> --gid <gid>`.
2. Create another account and use the same values for `access_key` and `secret_key` flags: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path <path> --access_key <same_access_key> --secret_key <same_secret_key> --uid <uid> --gid <gid>`.

### More information - Screenshots / Logs / Other output
According to the code we would expect this:
https://github.com/noobaa/noobaa-core/blob/8363cf721afdc2968a324b85751bf9f4717c11ce/src/cmd/manage_nsfs.js#L465-L471

I think the root cause is here:
https://github.com/noobaa/noobaa-core/blob/8363cf721afdc2968a324b85751bf9f4717c11ce/src/util/native_fs_utils.js#L477-L491
We can add `if (err.code === 'ELOOP') return true;` in the catch clause.

**Comment by romayalon** [comment]
@shirady Have you tried it on linux? 
As far as I know it happens only on mac

**Comment by shirady** [comment]
@romayalon I tested it on my Mac, but I haven't tried it on Linux yet.
Would we solve it for Mac? (it seems link a minor change) so we can enjoy all passing tests in `sudo node ./node_modules/.bin/_mocha src/test/unit_tests/test_nc_nsfs_cli.js` in local run.

**Comment by romayalon** [comment]
@shirady Yes, just wanted to mention the Mac vs Linux because if it happens on Linux it's a blocker, else it's a lower priority bug.
I saw it also when running it,  and I thought that we will handle it on the id/email replacement, but if it's a small fix, so it'll be great to fix it before that!
