### ISSUE TITLE
NSFS | NC |  Schema Validation in Upgrade

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7876]
### Environment info
- NooBaa Version: master
- Platform: NSFS | NC

### Actual behavior
1. Currently when we read the config file we validate it against the schema.

### Expected behavior
1. In an upgrade scenario, we might change the schemas so the saved config file will not be valid without changing the config files one by one to the needed change.

### Steps to reproduce
1. none, a scenario that didn't happen yet.

### More information - Screenshots / Logs / Other output
https://github.com/noobaa/noobaa-core/blob/8363cf721afdc2968a324b85751bf9f4717c11ce/src/sdk/bucketspace_fs.js#L123-L133

**Comment by romayalon** [comment]
@shirady It's a part of the knowledge base that all people who work on NC NSFS should be aware of when upgrading schemas, but not an issue.
Same as when we upgrade the schema on Containerized NooBaa, we should update the DB entries as well.
Closing.
