### ISSUE TITLE
NSFS | NC | CLI | Create Bucket - add check if owner of bucket has rw_access to underlying path 

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7883]
### Environment info
- NooBaa Version: Master
- Platform: Non Containerized

### Actual behavior
1. Currently, one can create a bucket that his owner can not access the underlying path of the bucket.

### Expected behavior
1. Currently, one can not create a bucket that his owner can not access the underlying path of the bucket.

### Steps to reproduce
```
1. mkdir /tmp/p1
2. chown 7171:7171  /tmp/p1
3. chmod 770 /tmp/p1
4. create account --name=account1 --uid=7272 --gid=7272 --new_buckets_path=/tmp/p2
5. create bucket, owner=account1 --path=/tmp/p1

```

**Comment by shirady** [comment]
The change is based on the code here:
https://github.com/noobaa/noobaa-core/blob/d1bf8c465af745dedbff9d3803ec13da344884ba/src/cmd/manage_nsfs.js#L822-L825

Also pay attention to the `fs_context` as mention in PR #7885

**Comment by anandhu-karattu** [comment]
Verified on build noobaa-core-5.15.3-20240502.el9.x86_64
RHEL 9.2

Verification steps followed:
**1. Create directories and set ownership/permission**
[root@charlie-x-worker1 ~]# mkdir /mnt/fs1/bucket. --> Dirrectory for bucket
[root@charlie-x-worker1 ~]# mkdir /mnt/fs1/account --> Dirrectory for account
[root@charlie-x-worker1 ~]# sudo chown 7171:7171 /mnt/fs1/bucket  --> Set bucket directory ownership
[root@charlie-x-worker1 ~]# chmod 770 /mnt/fs1/bucket. --> Set permission for directory
[root@charlie-x-worker1 ~]# chmod 770 /mnt/fs1/account --> Set permission for directory

**2. Now try to create an account with a different uid and GID 7272:7272 --> New error is displayed**
```
[root@charlie-x-worker1 ~]# noobaa-cli account add --name=account1 --uid=7272 --gid=7272 --new_buckets_path=/mnt/fs1/account 2>/dev/null
{
  "error": {
    "code": "InaccessibleAccountNewBucketsPath",
    "message": "Account should have read & write access to the specified new_buckets_path",
    "detail": "/mnt/fs1/account"
  }
}
```
**3. Create account with proper ownership** 
```
[root@charlie-x-worker1 ~]# sudo chown 7171:7171 /mnt/fs1/account

[root@charlie-x-worker1 ~]# noobaa-cli account add --name=account1 --uid=7171 --gid=7171 --new_buckets_path=/mnt/fs1/account 2>/dev/null
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "_id": "663a46101d0deb45c28d12dc",
      "name": "account1",
      "email": "account1",
      "creation_date": "2024-05-07T15:17:36.031Z",
      "access_keys": [
        {
          "access_key": "Lb6330YJ2rph37c7v655",
          "secret_key": "ZcvwGjNH1iZpKKeNgG+cB2Z0pjljpbLYCFmkkobe"
        }
      ],
      "nsfs_account_config": {
        "uid": 7171,
        "gid": 7171,
        "new_buckets_path": "/mnt/fs1/account",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "6638c1dcf1d7d446b29e0500"
    }
  }
}
```

**4. Repeat the same test for a bucket --> This should show an error**
```
[root@charlie-x-worker1 ~]# mkdir /mnt/fs1/bucket_new
[root@charlie-x-worker1 ~]# chmod 770 /mnt/fs1/bucket_new
[root@charlie-x-worker1 ~]# noobaa-cli bucket add --name bucket1 --owner account1 --path /mnt/fs1/bucket_new 2>/dev/null
{
  "error": {
    "code": "InaccessibleStoragePath",
    "message": "Bucket owner should have read & write access to the specified bucket storage path",
    "detail": "/mnt/fs1/bucket_new"
  }
}
```

5. Change ownership to match with account --> Bucket should get created

```
[root@charlie-x-worker1 ~]# chown 7171:7171 /mnt/fs1/bucket_new
[root@charlie-x-worker1 ~]# noobaa-cli bucket add --name bucket1 --owner account1 --path /mnt/fs1/bucket_new 2>/dev/null
{
  "response": {
    "code": "BucketCreated",
    "reply": {
      "_id": "663a4723938e11439c569f54",
      "name": "bucket1",
      "owner_account": "663a46101d0deb45c28d12dc",
      "system_owner": "account1",
      "bucket_owner": "account1",
      "versioning": "DISABLED",
      "creation_date": "2024-05-07T15:22:11.795Z",
      "path": "/mnt/fs1/bucket_new",
      "should_create_underlying_storage": false,
      "fs_backend": "GPFS"
    }
  }
}
```

Marking this ticket as verified. @romayalon

**Comment by romayalon** [comment]
thanks @anandhu-karattu I removed the request validation lable
