### ISSUE TITLE
NSFS | NC | `nc_coretest` | Node `DeprecationWarning` Related to `fs.rmdir`

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7890]
### Environment info
- NooBaa Version: master
- Platform: CI

### Actual behavior
1. I noticed that we have `DeprecationWarning` related to `fs.rmdir`.

### Expected behavior
1. Avoid having this warning.

### Steps to reproduce
1. When submitting a pull request/push in the `run-nc-unit-tests` logs you can see this warning.

### More information - Screenshots / Logs / Other output
I saw this in the CI of `run-nc-unit-tests` (see [here](https://github.com/noobaa/noobaa-core/actions/runs/8249432700/job/22561806207?pr=7889)):
> (node:8) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead

**Comment by naveenpaul1** [comment]
@shirady I couldn't find the usage of `fs.rmdir()` in our code. We are using `rmdir()` that implemented in napi layer not node functionality.
I could see `fs.rmdir()` in nc_coretest.js we might need to update that.
cc : @romayalon
