### ISSUE TITLE
Noobaa health command giving trimmed output in pipe

### ISSUE THREAD

**Issue by Roushan45** [noobaa/noobaa-core#7894]
### Environment info
- NooBaa Version: **noobaa-core-5.15.0-20240306.el9.x86_64**
- Platform: RHEL9**

### Actual behavior
1. bucket/account details output getting trimmed when using with pipe
usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --all_bucket_details |  cat

### Expected behavior
1. it should give full output in pipe

### Steps to reproduce
1. usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --all_bucket_details |  cat

**Comment by shirady** [comment]
@Roushan45 would you please share the outputs?
cc: @naveenpaul1

**Comment by naveenpaul1** [comment]
@shirady json output is no complete, JSON is getting trimmed middle of the complete output and json is in invalid state

**Comment by rkomandu** [comment]
Upgraded on one of the CES S3 node and could see the account is displayed in jq when piped 


upgraded noobaa rpm node showed as follows 
/usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --all_account_details | jq |grep 10002
          "name": "s3user-10002",
          "storage_path": "/mnt/fs1/s3user-10002-dir"


on non-upgraded node, it continued to show the output as follows

/usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --all_account_details | jq
**parse error: Unfinished string at EOF at line 1, column 65536**

[root@rkomandu-ip-cls-x-worker2 ras]# rpm -qa |grep noobaa
noobaa-core-5.15.0-20240313.el9.x86_64


looks good for now, please merge into the ODF 4.15.z stream @naveenpaul1 @nimrod-becker

**Comment by rkomandu** [comment]
Looks like @nimrod-becker , will be trying this into the 4.15.1 as per email communication dated 18th Mar

**Comment by nimrod-becker** [comment]
Closing per verification [comment](https://github.com/noobaa/noobaa-core/issues/7894#issuecomment-2003359200)
