### ISSUE TITLE
Question: does noobaa support folder-scoped access control?

### ISSUE THREAD

**Issue by gregsheremeta** [noobaa/noobaa-core#7909]
I'm evaluating noobaa as a drop-in replacement for minio for a specific use case. One of the requirements is to support a single globally shared bucket, and within that bucket, have subfolders that are scoped to specific users.

For example:

```
Single Global Bucket
|
| --- Bob's folder
|    |
|     --- Bob's object 1
|     --- Bob's object 2
 --- Alice's folder
     |
      --- Alice's object 1
      --- Alice's object 2
```

My requirement is that both Bob and Alice can access only their own respective folders and objects within those folders. They wouldn't be able to do a directory listing of `Single Global Bucket` and see anything except their own personal folder.

Additionally, this authz paradigm must work whether the bucket is backed by local storage (PVs), AWS S3, or GCS.

Is this supported by noobaa?

**Comment by guymguym** [comment]
@gregsheremeta Sorry for the delayed response. I believe it is possible with S3 bucket policy rules, just like on aws. One nuance I am not sure about is if it can be used to restrict list-object based on bucket prefixes. But if you manage to create such bucket policy that works on aws buckets, then we would make sure we implement it to be compatible.

Noobaa's bucket policy is supported the same regardless of the backend storage, as you asked for.

When working on top of FS we also have the option to used posix FS permissions (owner and mode) in addition to bucket policies, in case this might be useful.

Let me know if this helps, thanks
