### ISSUE TITLE
Question: can noobaa-core be installed without noobaa-operator?

### ISSUE THREAD

**Issue by gregsheremeta** [noobaa/noobaa-core#7910]
I'm evaluating noobaa as a drop-in replacement for minio for a specific use case. One of the requirements is to support an installation method via only manifests -- no operators should be used to install or maintain the storage component. Preferably a simple `kubectl apply -f install-noobaa.yaml` is all that is required to install it.

Is this supported? If so, can you point me to some documentation?

**Comment by romayalon** [comment]
Hey @gregsheremeta !
We do have some new standalone deployment types of NooBaa - 
1. https://github.com/noobaa/noobaa-core/blob/master/docs/dev_guide/standalone_with_db.md
2. NooBaa NSFS Non containerized - https://github.com/noobaa/noobaa-core/blob/master/docs/non_containerized_NSFS.md (NSFS means buckets are reading and writing plain objects to FS)

These deployments can be installed simply inside a container or directly on a node. Might this help?
Regarding the 1st option, I'm not sure also non FS buckets were tested before.

I'm not familiar with a different way to install containerized NooBaa without also installing NooBaa operator, @guymguym @dannyzaken @nimrod-becker might have other ideas
