### ISSUE TITLE
BackingStore Pod throws test_store_perf error (Operation not supported)

### ISSUE THREAD

**Issue by Philbow** [noobaa/noobaa-core#7932]
### Environment info
- NooBaa Version: **5.15.0-9b709d9**
- Platform: **Kubernetes v1.28.7+6e2789b | OpenShift 4.15.3**

### Actual behavior
1. Create PV Pool BackingStore with StorageClass of an external CSI provider
2. BackingStore Pod successfully mounts PV and is up and running
3. BackingStore Pod successfully writes directory structure to mounted PVC (/noobaa_storage)
4. BackingStore is in BackingStorePhaseRejected state due to reason: 'Backing store mode: NO_CAPACITY'

### Expected behavior
1. Create PV Pool BackingStore with StorageClass of an external CSI provider
2. BackingStore Pod successfully mounts PV and is up and running
3. BackingStore Pod successfully writes directory structure to mounted PVC (/noobaa_storage)
4. BackingStore is in BackingStorePhaseReady state

### Steps to reproduce
1. Install external CSI provider (Netapp Trident / Dell CSI Powerscale) that utilize NFS for mounting of external volumes
2. Create PV Pool BackingStore with StorageClass of above mentioned CSI provider
3. BackingStore is in BackingStorePhaseRejected state due to reason: 'Backing store mode: NO_CAPACITY'
   1. The BackingStore is freshly initilized with 50GB and has enough space.
    ```
    > df -h
    Filesystem                                                     Size  Used Avail Use% Mounted on
    ...
    10.3.3.104:/phch_ocp_pvc_594fdfdb_0ab3_4292_9df6_813c9a4d3fe7   50G   23M   50G   1% /noobaa_storage
    ...
    ```

#### What is working
1. I tried to use the Local Storage Operator with it's StorageClass for provisioning the backing store, which works out.
2. This Operator utilizes local disks instead of NFS shares mounted on the corresponding node where the backing store runs.  

#### Log Analysis

Storage is correctly recognized with enough space and is also communicated upwards
```
Mar-29 9:11:02.156 [Agent/20]    [L0] core.agent.agent_cli:: Loading agents [ { mount: '/noobaa_storage', drive_id: '10.3.3.104:/phch_ocp_pvc_594fdfdb_0ab3_4292_9df6_813c9a4d3fe7', storage: { total: 53687091200, free: 53666185216 } } ]
``` 

The following problematic behaviour repeats constantly, compared to the working BackingStore that utilizes the local storage operator. 
``` 
Mar-29 9:12:10.564 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: get_node_ip: using fallback node ip 10.128.2.53
Mar-29 9:12:10.564 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: Recieved potential servers list [ { address: 'wss://localhost:8443' } ]
Mar-29 9:12:11.457 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: storage_info: { total: 53687091200, free: 53666119680, used: 0 }
Mar-29 9:12:11.461 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: used storage is under 200 KB (0), treat as 0
Mar-29 9:12:11.857 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: DRIVES: [ { mount:  '/' , drive_id:  'overlay' , storage: { total:  128243970048 , free:  96740057088  } }, { mount:  '' , drive_id:  'proc' , storage: { total:  0 , free:  0  } }, ... { mount:  '/noobaa_storage' , drive_id:  '10.3.3.104:/phch_ocp_pvc_594fdfdb_0ab3_4292_9df6_813c9a4d3fe7' , storage: { total:  53687091200 , free:  53666185216 , used:  0  } }, ... ]
Mar-29 9:12:11.863 [Agent/20]    [L0] Agent.netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb:: got _enable_service on storage agent
Mar-29 9:12:11.957 [Agent/20]  [WARN] core.agent.block_store_services.block_store_base:: encountered unknown error in test_store_perf [Error: Operation not supported] { code: 'ENOTSUP' }
Mar-29 9:12:11.958 [Agent/20] [ERROR] CONSOLE:: RPC._on_request: ERROR srv agent_api.test_store_perf reqid 8@ws://[::ffff:10.128.2.53]:45650/(4exhokcbf.zv) connid wss://noobaa-mgmt.openshift-storage.svc.cluster.local/(1g3katq4.01rd) Error: Operation not supported
Mar-29 9:12:12.145 [Agent/20]    [L0] core.rpc.rpc_base_conn:: RPC CONNECTION CLOSED. got event from connection: n2n://nodes_monitor(1y28j8wd.063) N2N ICE CLOSED
Mar-29 9:12:12.149 [Agent/20]    [L0] core.rpc.rpc_n2n:: _close undefined
Mar-29 9:12:12.149 [Agent/20]    [L0] core.rpc.ice:: TLS CLOSED: tcp://[10.128.2.53]:60383=>tcp://[::ffff:10.129.2.118]:47510
```

Unfortunately I could not find any details or bugs on test_store_perf errors. Would be great if someone could help me out here.

#### BackingStore PV data

BackingStore Pod seems to have already written it's correct directory structure to the PV:
```
ls -l /noobaa_storage/
total 12
-rw-r--r--. 1 noob 99  677 Mar 29 09:11 agent_conf.json
drwx------. 3 noob 99 4096 Mar 29 08:48 netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb
```

``` 
ls -l /noobaa_storage/netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb/
total 320
drwxr-xr-x. 4099 noob 99 319488 Mar 29 08:47 blocks_tree
-rw-r--r--.    1 noob 99    273 Mar 29 08:48 token
-rw-r--r--.    1 noob 99     20 Mar 29 08:47 usage
``` 

``` 
ls -l /noobaa_storage/netapp-wait-noobaa-pod-c2d90df8-noobaa_storage-907cadfb/blocks_tree/
total 16388
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 000.blocks
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 001.blocks
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 002.blocks
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 003.blocks
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 004.blocks
...
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:47 fff.blocks
drwxr-xr-x. 2 noob 99 4096 Mar 29 08:49 other.blocks
``` 

The only difference I can see is the lost+found directory is missing on the not working BackingStore pod.

#### Logs

As mentioned the same issue occours on 2 different environments with 2 different CSI provisioners that utilize NFS for mounting PVs. 

Attached you can find the [exported logs](https://github.com/noobaa/noobaa-core/files/14804267/noobaa_logs.zip) from Openshift
- netapp-wait-noobaa-pod        - not working BackingStore pod utilizing PVs from Dell / Netapp CSI Operator
- local-volume-test-noobaa-pod  - working BackingStore pod utilizing PVs from Local Storage Operator 
- noobaa-core-0
- noobaa-endpoint
- noobaa-operator

**Comment by romayalon** [comment]
Hey @Philbow !
Can you please increase the logs debug level to 1 and capture the logs again?
I suspect your FS doesn't support xattr, we used to see this error before on some other flows where xattr was not supported.
By increasing the debug level we can see syscall errors per FS operation.
cc: @guymguym

**Comment by Philbow** [comment]
@romayalon 

Indeed it looks like the netapp storage in the currenty installed version does not support setting extended attributes. Would need to update: https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels

Will check with the customer on his Dell storage on whether this can be or is enabled.

2 questions:
* I assume that Noobaa does not work without extended attributes support?
* I managed to set NOOBAA_LOG_LEVEL to all in the Operator ConfigMap, which enables verbose logging for the core and endpoint pods.
** Unfortunately this does not seem to change the log level of the BackingStore pod. How can I define the log level there to see the FS operations?

**Comment by nimrod-becker** [comment]
@Philbow by saying "customer" do you mean a D/S customer? or an U/S user?

**Comment by romayalon** [comment]
@Philbow 
1. We used to support it without xattr, recently we updated this flow to use xattr, @nimrod-becker we should consider adding back the old code for FS that does not support xattr.
2. you are right, if you have NooBaa CLI, can you try -
```
noobaa api cluster_server_api set_debug_level '{
"level": 1
}'
``` 
if not, that's fine, if you confirmed that the FS doesn't support xattr, this is the issue.

**Comment by Philbow** [comment]
@nimrod-becker Customer is using Openshift and it's Multi Cloud Gateway (based on noobaa), so a D/S customer.

There is no need to follow up, as we have identified the issue and worked around it by using a static S3 native bucket for a single component (no need to dynamic bucket provisioning).

However from my perspective, it would be great if we could improve the log error output without increasing the log level and add the documentation that noobaa (with PVC backend) relies on xattr support.

**Comment by romayalon** [comment]
@Philbow please notice @tangledbytes merged a fix to our master branch.
