### ISSUE TITLE
ListV2 with delimiter option is not working as expected 

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7940]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240306.el8.x86_64
- Platform: standalone
### Actual behavior
1. ListV2                      : Internal Server Error                                             : option '-delimeter afm' is not working with listv2 on noobaa
When delimeter option is used it is throwing the internal server error

### Expected behavior
1. It should filter out with delimeter and provide the output

### Steps to reproduce
1.listObjectsInput := &s3.ListObjectsV2Input{
                  MaxKeys: aws.Int64(10),
                  Bucket:  &bucket,
                  Delimiter: aws.String("afm"),
          }

**Comment by ramya-c3** [comment]
Since this is working with prefix we are closing this defect after the discussion with guy and venkat

**Comment by guymguym** [comment]
To explain - for NSFS listing behaves like [S3 Directory Buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/directory-buckets-overview.html) and supports only `/` as a delimiter.
