### ISSUE TITLE
NSFS needs to handle ENOTDIR

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7974]
### Environment info
- NooBaa Version: **5.15.2**
- Platform: **NA**

### Actual behavior
1. Upload an object to a bucket - `s3 cp file s3://bucket/file`
2. Using the key `file/` - note the ending slash...
3. S3 requests in namespace_fs fails with InternalError because ENOTDIR is not handled (by all ops besides delete-object).
4. This was observed when running `spark.read.parquet('s3a://bucket/file')` (in pyspark.sql) which uses list-objects to check if the path refers to single object or a list of objects (dir) but does not expect to get back an internal error in any case.

### Expected behavior
1. Should not fail with InternalError
2. Instead this should be generally treated as ENOENT is treated by the different ops (list would just return empty, head/get should return 404, put should allow to put).
3. There are multiple code flows that throw and needs fixing, just to name a few common ones - check_bucket_boundaries, check_access, process_dir calling dir_cache calling stat, etc...

### Steps to reproduce
```
s3 cp file s3://bucket/file
s3api list-objects --bucket bucket --prefix file/ --delimiter /
s3api head-object --bucket bucket --key file/
s3api get-object --bucket bucket --key file/ outfile
s3api put-object --bucket bucket --key file/
...
```

### More information - Screenshots / Logs / Other output

This is the error from head-object and put-object after handling check_bucket_boundaries and check_access with a local fix -

`Apr 15 19:37:20 nsfs node[249503]: Apr-15 19:37:20.373 [nsfs/249503] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/guy/policy.json/</Resource><RequestId>lv1lh88j-bog5lr-15de</RequestId></Error> HEAD /guy/policy.json/ {"host":"localhost","accept-encoding":"identity","user-agent":"aws-cli/2.13.32 Python/3.11.6 Linux/4.18.0-372.57.1.el8_6.x86_64 exe/x86_64.rhel.8 prompt/off command/s3api.head-object","x-amz-date":"20240415T233720Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 ..."} Error: Not a directory`

`Apr 15 19:44:32 nsfs node[249503]: Apr-15 19:44:32.973 [nsfs/249503] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/guy/policy.json/</Resource><RequestId>lv1lqi11-4ynxkx-10b2</RequestId></Error> PUT /guy/policy.json/ {"host":"localhost","accept-encoding":"identity","user-agent":"aws-cli/2.13.32 Python/3.11.6 Linux/4.18.0-372.57.1.el8_6.x86_64 exe/x86_64.rhel.8 prompt/off command/s3api.put-object","content-md5":"Tle6aiCWLjF/nSAursS3cw==","expect":"100-continue","x-amz-date":"20240415T234432Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 ...","content-length":"5389"} Error: Not a directory`

**Comment by romayalon** [comment]
@guymguym I don't see an issue with put-object.. what do I miss?
I thought fixing it by adding another case in the translate - 
```
    _translate_object_error_codes(err) {
        if (err.rpc_code) return err;
        if (err.code === 'ENOENT' || err.code === 'ENOTDIR') err.rpc_code = 'NO_SUCH_OBJECT';
        if (err.code === 'EEXIST') err.rpc_code = 'BUCKET_ALREADY_EXISTS';
        if (err.code === 'EPERM' || err.code === 'EACCES') err.rpc_code = 'UNAUTHORIZED';
        if (err.code === 'IO_STREAM_ITEM_TIMEOUT') err.rpc_code = 'IO_STREAM_ITEM_TIMEOUT';
        if (err.code === 'INTERNAL_ERROR') err.rpc_code = 'INTERNAL_ERROR';
        return err;
    }
```
WDYT?
