### ISSUE TITLE
[5.17.0] : noobaa-core rpm installation does not create service file "/etc/systemd/system/noobaa_nsfs.service"

### ISSUE THREAD

**Issue by anandhu-karattu** [noobaa/noobaa-core#7975]
### Environment info
- NooBaa Version: **noobaa-core-5.17.0-20240415.el9.x86_64**
- Platform: **Standalone noobaa on RHEL 9.2**

### Actual behavior
1. After rpm installation it is not creating a service file "/etc/systemd/system/noobaa_nsfs.service".
2.  For that reason we are not able enable S3 service

```
[root@earth-x-worker1 ~]# mmces service enable S3
earth-x-worker1.fyre.ibm.com:  Warning: Permanently added 'earth-x-worker1.fyre.ibm.com' (ED25519) to the list of known hosts.
earth-x-worker1.fyre.ibm.com:  The S3 service can not be enabled because it is not installed.
earth-x-worker1.fyre.ibm.com:  The file /etc/systemd/system/noobaa_nsfs.service was not found.
earth-x-worker1.fyre.ibm.com:  mmcesop: Command failed. Examine previous error messages to determine cause.
mmdsh: earth-x-worker1.fyre.ibm.com remote shell process had return code 1.
mmces service: Command failed. Examine previous error messages to determine cause.
earth-x-worker1.fyre.ibm.com:  S3: service already stopped.
earth-x-worker2.fyre.ibm.com:  S3: service already stopped.
mmces service enable: Command failed. Examine previous error messages to determine cause.
```

### Expected behavior
1. Service file should be present after rpm installation. 

### Steps to reproduce
1. Install scale 5.2.1.0
2. Install noobaa rpm "noobaa-core-5.17.0-20240415.el9.x86_64"
4. Try to enable S3 service

### More information - Screenshots / Logs / Other output
This issue is specific to 5.17.0
We tried an rpm with date 3-26, found the same issue there as well

**Comment by romayalon** [comment]
@anandhu-karattu Please replace the location of the noobaa_service, we changed it lately to -
```/usr/lib/systemd/system/noobaa_nsfs.service``` see the updated docs - https://github.com/noobaa/noobaa-core/pull/7789

**Comment by romayalon** [comment]
@anandhu-karattu can we close this issue?

**Comment by anandhu-karattu** [comment]
Closing this issue. thanks @romayalon
