### ISSUE TITLE
NooBaa nsfs service showing Error No disk candidates found at generate entropy due to unsupported DASD devices

### ISSUE THREAD

**Issue by muenchp1** [noobaa/noobaa-core#7982]
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20240320.el9.s390x
- Platform: Standalone

### Actual behavior
1.
Start NooBaa nsfs service on a RHEL9.3 (s390x) the following error can be found on systems with dasd disks (ECKD) only

[gshtc]# lsblk
NAME               MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
dasda               94:0    0 13.8G  0 disk 
├─dasda1            94:1    0    1G  0 part /boot
└─dasda2            94:2    0 11.4G  0 part 
  └─system_vg-root 253:0    0 11.4G  0 lvm  /

[gshtc]# systemctl status noobaa_nsfs.service
...
[nsfs/1304026]   [LOG] CONSOLE:: generate_entropy: error Error: No disk candidates found
at generate_entropy (/usr/local/noobaa-core/src/util/nb_native.js:137:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    
at async init_rand_seed (/usr/local/noobaa-core/src/util/nb_native.js:62:5) 
...

### Expected behavior
1. generate_entropy should be able to handle dasd devices, so that NooBaa nsfs service starts without error.

### Mitigation
1.
The problem can be mitigated by adding /dev/dasda to 
line 122 in /usr/local/noobaa-core/src/util/nb_native.js

"                for (disk of ['/dev/sda', '/dev/vda', '/dev/xvda', '/dev/dasda']) {"

and restart NooBaa nsfs service

### More information - Screenshots / Logs / Other output

[gshtc]# systemctl status noobaa_nsfs.service
● noobaa_nsfs.service - The NooBaa nsfs service.
     Loaded: loaded (/etc/systemd/system/noobaa_nsfs.service; enabled; preset: disabled)
     Active: active (running) since Wed 2024-04-17 11:13:44 CEST; 24s ago
    Process: 1317566 ExecStartPre=/usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/upgrade/upgrade_manager.js --nsfs true --upgrade_scripts_dir /usr/local/noobaa-core/src/upgrade/nsfs_upgrade_scripts (code=exited, status=0/SUCCESS)
   Main PID: 1317591 (node)
      Tasks: 69 (limit: 204032)
     Memory: 508.8M
        CPU: 11.914s
     CGroup: /system.slice/noobaa_nsfs.service
             ├─1317591 /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js
             ├─1317614 /usr/local/noobaa-core/node/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js
             └─1317615 /usr/local/noobaa-core/node/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js

Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: [nsfs/1317615]    [L0] core.endpoint.endpoint:: Endpoint monitor started
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: Apr-17 11:13:52.025 [nsfs/1317615]    [L0] core.endpoint.endpoint:: Endpoint monitor started
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: [nsfs/1317615]   [LOG] CONSOLE:: nsfs: listening on 'https://localhost:6443/'
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: Apr-17 11:13:52.025 [nsfs/1317615]   [LOG] CONSOLE:: nsfs: listening on 'https://localhost:6443/'
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: [nsfs/1317615]   [LOG] CONSOLE:: generate_entropy: adding entropy: dd if=/dev/dasda bs=1048576 count=32 skip=1056 | md5sum
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: Apr-17 11:13:52.040 [nsfs/1317615]   [LOG] CONSOLE:: generate_entropy: adding entropy: dd if=/dev/dasda bs=1048576 count=32 skip=1056 | md5sum
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317614]: [nsfs/1317614]   [LOG] CONSOLE:: init_rand_seed: done
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317614]: Apr-17 11:13:52.200 [nsfs/1317614]   [LOG] CONSOLE:: init_rand_seed: done
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: [nsfs/1317615]   [LOG] CONSOLE:: init_rand_seed: done
Apr 17 11:13:52 gshtc1d.fpet.pokprv.stglabs.ibm.com node[1317615]: Apr-17 11:13:52.228 [nsfs/1317615]   [LOG] CONSOLE:: init_rand_seed: done

**Comment by guymguym** [comment]
Thanks @muenchp1 !

**Comment by romayalon** [comment]
@muenchp1 thanks!
I created a PR based on your suggestion - https://github.com/noobaa/noobaa-core/pull/7994

**Comment by romayalon** [comment]
@muenchp1 PR is merged to master, can you please validate it?
