### ISSUE TITLE
logrotate is not performing for noobaa logs if it is inside the noobaa dir under logrotate.d directory

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#7993]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa-4.15.0 
Standalone. 

### Actual behavior
1.

logrotate should perform the compression once the size is reached

```
[root@rkomandu-ip-cls-x-worker2 ~]# ls -lrh /var/log/noobaa*
-rw-r--r-- 1 root root 1.4G Apr 23 00:40 /var/log/noobaa.log
-rw-r--r-- 1 root root  19M Apr 22 16:30 /var/log/noobaa_events.log
[root@rkomandu-ip-cls-x-worker2 ~]# logrotate /etc/logrotate.d/noobaa/logrotate_noobaa.conf
[root@rkomandu-ip-cls-x-worker2 ~]# ls -lrh /var/log/noobaa*
-rw-r--r-- 1 root root  74M Apr 23 00:40 /var/log/noobaa.log.1.gz
-rw-r--r-- 1 root root 1.3K Apr 23 00:41 /var/log/noobaa.log
-rw-r--r-- 1 root root  19M Apr 22 16:30 /var/log/noobaa_events.log.1
-rw-r--r-- 1 root root    0 Apr 23 00:41 /var/log/noobaa_events.log
[root@rkomandu-ip-cls-x-worker2 ~]# cd /var/log/noobaa.log.1.gz /tmp
-bash: cd: too many arguments
[root@rkomandu-ip-cls-x-worker2 ~]# cp /var/log/noobaa.log.1.gz /tmp
[root@rkomandu-ip-cls-x-worker2 ~]# cd /tmp

[root@rkomandu-ip-cls-x-worker2 tmp]# file noobaa.log.1.gz
noobaa.log.1.gz: gzip compressed data, last modified: Tue Apr 23 07:40:50 2024, from Unix, original size modulo 2^32 1428749230

[root@rkomandu-ip-cls-x-worker2 tmp]# gunzip noobaa.log.1.gz

[root@rkomandu-ip-cls-x-worker2 tmp]# ls -lh noobaa.log.1
-rw-r--r-- 1 root root 1.4G Apr 23 00:41 noobaa.log.1


```
@naveenpaul1 and I did this over the webex 

Note: We had an issue opened in RTC 38551, 

### Expected behavior
1.
Logrotate should be invoked automatically for the noobaa.log and noobaa_events.log, Please also check on the size front. Is 100M sufficient to do the logrotate, when we enable the other log levels for any tracing purposes. 

### Steps to reproduce
1.

Posted above, that logrotate is not functioning as expected 

### More information - Screenshots / Logs / Other output

Please check and fix this for the 4.15.z stream so we can consume for GA

**Comment by naveenpaul1** [comment]
@nimrod-becker this is for container application, we need to add fix for non-containerised application.

**Comment by aspandey** [comment]
By mistake I clicked on close

**Comment by romayalon** [comment]
closing per @naveenpaul1 [fix](https://github.com/noobaa/noobaa-core/pull/7998), adding request validation label
