### ISSUE TITLE
account update for --user option is throwing some invalid error

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#8023]
### Environment info
- NooBaa Version: 5.15.3
- Platform: standalone

### Actual behavior
1.# noobaa-cli account update --name 2* --user root 2>/dev/null
{
  "error": {
    "code": "InvalidSchema",
    "message": "Schema invalid, please use required properties",
    "detail": "Error: must NOT have additional properties | {\"additionalProperty\":\"distinguished_name\"} | \"/nsfs_account_config\"\n    at Object.validate_account_schema (/usr/local/noobaa-core/src/manage_nsfs/nsfs_schema_utils.js:50:15)\n    at update_account (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:482:27)\n    at async manage_account_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:585:9)\n    at async account_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:337:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:112:13)"
  }
}

### Expected behavior
1. valid error message should be thrown

### Steps to reproduce
1.

**Comment by shirady** [comment]
Closing this issue as duplicate with issue #8072
