### ISSUE TITLE
No error code for inactive syslog-ng service

### ISSUE THREAD

**Issue by Roushan45** [noobaa/noobaa-core#8024]
### Environment info
- NooBaa Version: **noobaa-core-5.15.3-20240502.el9.x86_64**
- Platform: **RHEL9**

### Actual behavior
1. [root@s3test-11 bin]# systemctl show -p ActiveState --value syslog-ng
inactive
[root@s3test-11 bin]# systemctl show -p ActiveState --value rsyslog
inactive

both are inactive but in health command` /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --check_syslog_ng` output error code of showing only for rsyslog, what if customer using syslog-ng then it should report syslog-ng as error. How does noobaa knows which logger service being used for noobaa services?

`{"service_name":"noobaa","status":"NOTOK","memory":"340.1M","error":{"error_code":"RSYSLOG_SERVICE_FAILED","error_message":"RSYSLOG service is not started properly, Please verify the service with status command."},"checks":{"services":[{"name":"noobaa","service_status":"active","pid":"1172983","error_type":"PERSISTENT"},{"name":"rsyslog","service_status":"inactive","pid":"0","error_type":"PERSISTENT"},{"name":"syslog-ng","service_status":"inactive","pid":"0","error_type":"PERSISTENT"}],"endpoint":{"endpoint_state":{"response":{"response_code":"RUNNING","response_message":"Endpoint running successfuly."},"total_fork_count":2,"running_workers":[2,1]},"error_type":"TEMPORARY"}}}`

### Expected behavior
1. error code should be as per logger service which is being used as default for noobaa

### Steps to reproduce
1. ` /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --check_syslog_ng`

**Comment by romayalon** [comment]
@Roushan45 Thank you for bringing this to our attention. We will add it to our task list and address it based on our priorities.

**Comment by romayalon** [comment]
Hey @Roushan45 
I created a PR in which the status of rsyslog/syslog_ng won't affect the overall status. WDYT?
syslog_ng status is still available on the checks.services - `{"name":"syslog-ng","service_status":"inactive","pid":"0","error_type":"PERSISTENT"}`

**Comment by romayalon** [comment]
@Roushan45 adding request validation label, please let us know when the fix for this issue was validated. thanks!
