### ISSUE TITLE
master_keys.json file does not display the timestamp properly

### ISSUE THREAD

**Issue by anandhu-karattu** [noobaa/noobaa-core#8025]
### Environment info
- NooBaa Version: **noobaa-core-5.15.3-20240502.el9.x86_64**
- Platform: **Standalone noobaa RHEL 9.2**

Issue:
Two issues:
1. master_keys.json does not display timestamp properly. Currently it shows in the below format

[root@charlie-x-master accounts]# jq '.' /gpfs/fs-ces-shared/ces/s3-config/master_keys.json
{
  "timestemp": 1714995676859,
  "active_master_key": "6638c1dcf1d7d446b29e0500",
  "master_keys_by_id": {
    "6638c1dcf1d7d446b29e0500": {
      "id": "6638c1dcf1d7d446b29e0500",
      "cipher_key": "tOuCXGaO30PQf4FZ2rqH/4MxlMLym8yiFJMwNYVXlXs=",
      "cipher_iv": "3B3eRNncg9f4yHVoVH9ApA==",
      "encryption_type": "aes-256-gcm"
    }
  }
}

2. There is a typo in the filed  "timestemp": 1714995676859 . This must be changed to timestamp

**Comment by romayalon** [comment]
thanks @anandhu-karattu 
added a quick fix
https://github.com/noobaa/noobaa-core/pull/8034
