### ISSUE TITLE
Incorrect service status for rsyslog if syslog-ng enables

### ISSUE THREAD

**Issue by Roushan45** [noobaa/noobaa-core#8027]
### Environment info
- NooBaa Version: **noobaa-core-5.15.3-20240502.el9.x86_64**
- Platform: **RHEL9**

### Actual behavior
[root@s3test-11 ~]# systemctl show -p ActiveState --value syslog-ng
active
[root@s3test-11 ~]# systemctl show -p ActiveState --value rsyslog
inactive

from above syslog-ng is active but rsyslog is inactive but in health command `/usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --check_syslog_ng` it showing RSYSLOG_SERVICE_FAILED even syslog-ng is active (up & running)

{"service_name":"noobaa","status":"NOTOK","memory":"313.7M","error":{"error_code":"RSYSLOG_SERVICE_FAILED","error_message":"RSYSLOG service is not started properly, Please verify the service with status command."},"checks":{"services":[{"name":"noobaa","service_status":"active","pid":"1172983","error_type":"PERSISTENT"},{"name":"rsyslog","service_status":"inactive","pid":"0","error_type":"PERSISTENT"},{"name":"syslog-ng","service_status":"active","pid":"1006808","error_type":"PERSISTENT"}],"endpoint":{"endpoint_state":{"response":{"response_code":"RUNNING","response_message":"Endpoint running successfuly."},"total_fork_count":2,"running_workers":[2,1]},"error_type":"TEMPORARY"}}}

### Expected behavior
it should not report rsyslog as error

### Steps to reproduce
1. deactivate rsyslog
2. install syslog-ng and enable it
3. run the health command `/usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/health --check_syslog_ng`

### More information - Screenshots / Logs / Other output
<img width="1727" alt="image" src="https://github.com/noobaa/noobaa-core/assets/11044623/0f3f0adf-54b1-4805-bf8d-bcc068dfc64c">

**Comment by romayalon** [comment]
@Roushan45 Thank you for bringing this to our attention. We will add it to our task list and address it based on our priorities.

**Comment by romayalon** [comment]
Hey @Roushan45 
I created a PR in which I add --check_rsyslog flag, without passing this flag we won't check rsyslog status.
Guy and I discussed last week if checking rsyslog/syslog_ng service status during this health check is appropriate, So for now I decided to put all the rsyslog/syslog_ng checks as optional, and the status of these won't affect the overall status. WDYT?

**Comment by romayalon** [comment]
@Roushan45 adding request validation label, please let us know when the fix for this issue was validated. thanks!
