### ISSUE TITLE
NSFS | Create event json from debug module

### ISSUE THREAD

**Issue by naveenpaul1** [noobaa/noobaa-core#8033]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Event message is formatted using rsyslog template
`{"timestamp":"2024-05-09T03:43:35.566472+00:00","message":"{\"code\":\"noobaa_started\",\"message\":\"Noobaa started\",\"description\":\"Noobaa started running\",\"entity_type\":\"NODE\",\"event_type\":\"STATE_CHANGE\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"pid\":101}","host":"4c8c451cfb17","severity":"notice","facility":"local2","syslog-tag":"node[101]:","source":"node"}`

### Expected behavior
1. Create formatted event from debug_module and avoid formatting event message from rsyslog template
2. message JSON format should not be changes. 

### Steps to reproduce
1. Create a event from noobaa(Account create/delete)
2. verify var/log/noobaa_events.log

**Comment by romayalon** [comment]
@naveenpaul1 this was fixed by https://github.com/noobaa/noobaa-core/pull/8207, right? can we close it?

**Comment by naveenpaul1** [comment]
yes @romayalon , will close it
