### ISSUE TITLE
Config-Option to deactivate rsyslog if syslogng are used 

### ISSUE THREAD

**Issue by ps20renar** [noobaa/noobaa-core#8046]
**Is your feature request related to a problem? Please describe.**
Currently the health check script monitor rsyslog and syslobng if we use the sub option --check_syslog_ng. In our linux platform  we had rsyslog masked and use only syslogng for this logging request
(checked Version are 5.15.3)

**Describe the solution you'd like**
generate a config.json option to use syslogng as the only one logging framework. Like ENABLE_SYSLOG_NG: "True"
this should the effect that rsyslog should no more checked. In the health.js script. It will be also great if this issue generate an example (opt/syslog-ng/etc/conf.d/nsfs.conf that defined the filter what should filtered in a separat  log-file. (/var/log/nsfs.log)

**Describe alternatives you've considered**
Description of alternative solutions or features you've considered.

**Additional context**
An example of these logconf-file can be:
# NSFS syslog-ng settings
template nsfs_t {
    template("$R_ISODATE $HOST $MSGHDR $MSG\n");
};
 
filter f_nsfs { match('node[ID0-9][0-9]*[EWID]') and level(info..emerg); };
destination d_nsfs { file("/var/log/nsfs.log" template(nsfs_t) frac-digits(6) ts_format(iso)); };
log { source(s_sys); filter(f_nsfs); destination(d_nsfs); };

As an example it should be verified.

**Comment by naveenpaul1** [comment]
Duplicated issue : https://github.com/noobaa/noobaa-core/issues/8027

**Comment by romayalon** [comment]
Hey @ps20renar @guymguym 
I created a PR in which I add --check_rsyslog flag, without passing this flag we won't check rsyslog status.
Guy and I discussed last week if checking rsyslog/syslog_ng service status during this health check is appropriate, So for now I decided to put all the rsyslog/syslog_ng checks as optional, and the status of these won't affect the overall status. WDYT?

**Comment by ps20renar** [comment]
Hallo @romayalon,
i think this is ok for me.
If someone want to check rsyslog or syslogng, there ist an option to decide wich one.
Thanks

**Comment by romayalon** [comment]
Adding here as well - Renar confirmed on slack that the solution of removing syslog service monitoring from health script works.
