### ISSUE TITLE
NSFS Bucket Tagging

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#8047]
**Is your feature request related to a problem? Please describe.**
No support for S3 bucket tagging operations in BucketSpaceFS:
https://github.com/noobaa/noobaa-core/blob/8c9d47886d8d9d1950e03988466e9b5c0002c51b/src/sdk/bucketspace_fs.js#L413-L427

**Describe the solution you'd like**
Support S3 bucket tagging operations for BucketSpaceFS.

**Describe alternatives you've considered**
NA

**Comment by romayalon** [comment]
Closing, fixed by https://github.com/noobaa/noobaa-core/pull/8234.
