### ISSUE TITLE
NSFS endpoint should set its process/threads name in the OS to be identified accurately

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#8049]
**Is your feature request related to a problem? Please describe.**
We want GPFS to identify the noobaa endpoint processes so that it can assist with #8039.

**Describe the solution you'd like**
Use one of https://linux.die.net/man/2/prctl or pthread_setname_np or setprocname or setproctitle (need to figure out which one) in order to set the process name to "noobaa".

**Describe alternatives you've considered**
We considered adding a special libgpfs library call that will set the calling process attributes, but setting the name is less coupled.

**Comment by romayalon** [comment]
@eshelmarc Should I set the process title (setproctitle) ? this is the property you will get?

**Comment by romayalon** [comment]
re-opening based on @eshelmarc check, setting the process/thread title seems to be not enough, calling gpfs_ganesha() might do the trick.

**Comment by rkomandu** [comment]
if we don't enable gpfs_ganesha in the CES env, does the code path can be reached ?

**Comment by eshelmarc** [comment]
we don't to enable Ganesha t use this interface
