### ISSUE TITLE
NSFS on syscall error should log the operation info and not just the error code (even if debug level is low)

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#8065]
### Environment info
- NooBaa Version: **5.15.3**
- Platform: **rhel**

### Actual behavior
1. on syscall error we only see the err code unless we turn on higher debug log -
```
May 21 16:19:48 host node[2941584]: May-21 16:19:48.654 [nsfs/2941584] [ERROR] core.sdk.namespace_fs::  [Error: Operation not permitted] { code: 'EPERM' }
```

### Expected behavior
1. Should log the operation info with the error code.

### Steps to reproduce
1. Change fs permissions to cause EPERM.

**Comment by guymguym** [comment]
CC @romayalon @eshelmarc

**Comment by tangledbytes** [comment]
@guymguym trying to understand this issue. What is the desired behaviour?
1. fs_napi should log the context of the error but the error that is bubbled up is still what we get out of `errno` conversion?
2. fs_napi should modify the reported error, i.e it should append or prepend the context info with the translated error and then report that to JS layer? This will then appear whenever JS layer `throws` the error?

**Comment by guymguym** [comment]
@tangledbytes I think that option 2 is best if possible, but in any case I would anway do option 1 and log the error context in fs_napi to make sure we have it in the logs.
