### ISSUE TITLE
Account status with show_secrets is not working when master_keys gets updated/changed

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#8084]
### Environment info
- NooBaa Version: 5.15.3
- Platform: standalone

### Actual behavior

noobaa-cli account status --name test 2>/dev/null
{
  "response": {
    "code": "AccountStatus",
    "reply": {
      "_id": "665035e800ed1d249be19986",
      "name": "test",
      "email": "test",
      "creation_date": "2024-05-24T06:38:32.179Z",
      "nsfs_account_config": {
        "uid": 10,
        "gid": 10,
        "new_buckets_path": "/mnt/gpfs0/test",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "6650357884f47e736e1db1ee"
    }
  }
}
noobaa-cli account status --name test --show_secrets 2>/dev/null
{
  "error": {
    "code": "NoSuchAccountName",
    "message": "Account does not exist - name",
    "detail": "test"
  }
}

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by romayalon** [comment]
Thanks @ramya-c3 for opening this issue - A fix PR https://github.com/noobaa/noobaa-core/pull/8090 is under code review.
