### ISSUE TITLE
Enhance logrotate function to support syslog-ng if it used 

### ISSUE THREAD

**Issue by ps20renar** [noobaa/noobaa-core#8098]
**Is your feature request related to a problem? Please describe.**
Currently the logrote config and script support only rsyslog. This should be enhanced to add also syslog-ng if it used

**Describe the solution you'd like**
If the config-option used SYSLOG_SERVICE: "syslog-ng" the log rotate config should point to a logrotate_noobaa.conf that pointed to syslog-ng. 

**Describe alternatives you've considered**
Description of alternative solutions or features you've considered.

**Additional context**
As an example:
/var/log/noobaa.log
{
    daily
    maxsize 100M
    minsize 50M
    start 1
    missingok
    rotate 100
    compress
    create 644 root root
    sharedscripts
    postrotate
           systemctl reload syslog-ng > /dev/null 2>&1
           sleep 5
   endscript
 }
 
/var/log/noobaa_events.log
{
    daily
    maxsize 100M
    minsize 10M
    start 1
    missingok
    rotate 100
    compress
    create 644 root root
    sharedscripts
    postrotate
           systemctl reload syslog-ng > /dev/null 2>&1
           sleep 5
     endscript
 }
 
/var/log/client_noobaa.log
{
    size 100M
    start 1
    missingok
    rotate 10
    compress
    create 644 root root
    sharedscripts
    postrotate
           systemctl reload syslog-ng > /dev/null 2>&1
           sleep 5
    endscript
 }

**Comment by ps20renar** [comment]
As addition there should also a change in the current provided files. 
the logrotate function don't support directories under /etc/logrotate.de/<dir>/logrotate_noobaa.conf. Also the install rpm of noobaa should change the current link of logrotate_noobaa.conf -> /usr/local/noobaa-core/src/deploy/standalone/logrotate_noobaa.conf to a real file in the rpm-script like /etc/logrotate.d/logrotate_noobaa.conf to put it in working status.

**Comment by romayalon** [comment]
@rkomandu @naveenpaul1 Fixed by Naveen on #8182, closing and adding request validation label
Ravi please verify so we can backport it to 5.15.5

**Comment by rkomandu** [comment]
Rakesh would be able to validate about this syslog-ng functionality

**Comment by romayalon** [comment]
@Roushan45 waiting for your validation.

**Comment by rkomandu** [comment]
@romayalon 

As per 8153 (logrotate function has been tested), updated the comments in that defect https://github.com/noobaa/noobaa-core/issues/8153#issuecomment-2211793735) -- this is important and seems to be fixed for the normal noobaa.log file, which had issue in loosing the data once the > 105M size is reached.  



Regarding syslog-ng is Rakesh or MAPS team have to perform it.

**Comment by romayalon** [comment]
Hi @rkomandu, any news regarding the validation of this bug?

**Comment by rkomandu** [comment]
@romayalon, haven't verified yet as I need to check where/how to setup the syslog-ng in the system. We thought Rakesh would verify it, but that doesn't seem to be the case. 

Are there steps to enable syslog-ng in the env today from Noobaa perspective ? Once that is clear then we can see whether this defect can be validated or not.

**Comment by naveenpaul1** [comment]
@rkomandu I can support you on the testing. I am also not sure how to do the texting maybe we can create test plan and do it in a meeting.

**Comment by romayalon** [comment]
@rkomandu @naveenpaul1 any news? we would like to have it verified before backporting

**Comment by naveenpaul1** [comment]
@ps20renar we added fix for syslog-ng logrotation, could you please check logrotation working as expected for syslog-ng
