### ISSUE TITLE
Noobaa is creating the empty _ces_master_key_file file for power PC system 

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#8160]
### Environment info
- NooBaa Version: 5.15.4
- Platform: standalone

### Actual behavior
1. Noobaa is creating the empty master file for power PC system 
 ls -lrt /ibm/fvt_ces_root/ces/s3-config/
total 3
-rwx------. 1 root root  553 Jun 17 06:22 config.json
-rw-r--r--. 1 root root  181 Jun 17 06:22 system.json
-rw-r--r--. 1 root root    0 Jun 17 06:42 _ces_master_key_file
drwx------. 2 root root 4096 Jun 17 10:27 accounts
drwx------. 2 root root 4096 Jun 17 10:27 access_keys
drwx------. 3 root root 4096 Jun 18 08:21 buckets

### Expected behavior
1.-rw-r--r--. 1 root root    0 Jun 17 06:42 _ces_master_key_file should not be created

### Steps to reproduce
1.

**Comment by romayalon** [comment]
@ramya-c3 Please provide the following info - 
1. Full NooBaa service logs, debug level is nsfs if possible. (In this specific case we will need logs around 06:42 when the creation happened. 
2. config.json content 
3. Reproduction steps
4. NooBaa CLI command & response (Did you use account commands at 06:42?).

**Comment by romayalon** [comment]
This issue is being closed because it was labeled "missing info" for more than a week. Please provide the requested information and reopen the issue if necessary.
