### ISSUE TITLE
NSFS | RPM build is not generating NSFS RPM on Mac

### ISSUE THREAD

**Issue by naveenpaul1** [noobaa/noobaa-core#8227]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. RPM command is not generating RPM in `build/rpm` folder, even if the command completed without any issues
    This issues is not happening to all the linux machines, need to understand why its happening for some machines.

### Expected behavior
1. `make rpm` should generate valid RPM for all linux and mac machines.

### Steps to reproduce
1. run `make rpm`
2. check `build/rpm` folder for the latest RPM.

**Comment by romayalon** [comment]
Hey @tangledbytes looks like we have an issue with building RPM locally, it almost never worked for me on mac, any idea what happened?

**Comment by naveenpaul1** [comment]
@tangledbytes I am able to create RPM in build/rpm folder if I run the make rpm from as root suder

> sudo -i
> make rpm

**Comment by romayalon** [comment]
@naveenpaul1 it's not working for me on mac, also @tangledbytes has a PR opened for fixing it https://github.com/noobaa/noobaa-core/pull/8270

**Comment by nimrod-becker** [comment]
@tangledbytes ping :)
