### ISSUE TITLE
NSFS | S3 | Versioning: Internal error returned by DeleteObject with versionId.

### ISSUE THREAD

**Issue by hseipp** [noobaa/noobaa-core#8333]
### Environment info
- NooBaa Version: **5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior

When executing Ceph s3-test `test_versioning_obj_create_read_remove_head()`  a DeleteObject operation returns

```
E           botocore.exceptions.ClientError: An error occurred (InternalError) when calling the DeleteObject operation (reached max retries: 4): We encountered an internal error. Please try again.

.tox/py/lib/python3.8/site-packages/botocore/client.py:1023: ClientError
```

### Expected behavior

DeleteObject works, test passes.

### Steps to reproduce

Execute Ceph s3-tests with the following function:

```
S3TEST_CONF=s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_versioning_obj_create_read_remove_head
```

### More information - Screenshots / Logs / Other output

Noobaa log with loglevel set to "all":
[noobaa_20240906_2.log.gz](https://github.com/user-attachments/files/16910535/noobaa_20240906_2.log.gz)

**Comment by shirady** [comment]
@hseipp I created a suggested fix on master brach.
Here is a command that would let you see it easily using AWS CLI:
```
➜  ~ aws s3 ls s3://noobaa-core-rpms | sort | grep 20240911
2024-09-11 16:45:03   87748396 noobaa-core-5.18.0-20240911-nsfs-nc-versioning-delete-object-with-object-id.el8.x86_64.rpm
```
