### ISSUE TITLE
Bucket lifecycle rules should allow top level Prefix and NoncurrentVersionExpiration and AbortIncompleteMultipartUpload elements

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#8341]
### Environment info
- NooBaa Version: **5.16**
- Platform: **NC**

### Actual behavior
1. We currently reject rules with top level Prefix (outside the Filter), which is allowed on AWS.
2. We currently reject rules with actions NoncurrentVersionExpiration and AbortIncompleteMultipartUpload.

### Expected behavior
1. We need to allow these.
2. This is a followup to #8300

### Steps to reproduce
1. Try to put the following lifecycle policy file which is valid for AWS:

```json
{
    "Rules": [
        {
            "ID": "Expiration",
            "Status": "Enabled",
            "Prefix": "p1",
            "Expiration": { "Days": 1 },
            "NoncurrentVersionExpiration": { "NoncurrentDays": 2 },
            "AbortIncompleteMultipartUpload": { "DaysAfterInitiation": 10 }
        },
        {
            "ID": "NoncurrentVersionExpiration",
            "Status": "Enabled",
            "Filter": {
                "Prefix": "p2"
            },
            "NoncurrentVersionExpiration": { "NoncurrentDays": 2 }
        },
        {
            "ID": "AbortIncompleteMultipartUpload",
            "Status": "Enabled",
            "Filter": {
                "And": {
                    "Prefix": "p3",
                    "ObjectSizeGreaterThan": 11
                }
            },
            "AbortIncompleteMultipartUpload": { "DaysAfterInitiation": 10 }
        }
    ]
}
```

**Comment by guymguym** [comment]
In addition I think we have restricted no-filter rules which are valid:
```
Sep-16 11:46:09.899 [nsfs/43792] [ERROR] core.endpoint.s3.ops.s3_put_bucket_lifecycle:: Rule should not have prefix, it should be filter.prefix {
  ID: [ 'nofilter-expire-days-365' ],
  Status: [ 'Enabled' ],
  Prefix: [ '' ],
  Expiration: [ { Days: [ '365' ] } ]
}
```

although when submitting two rules on the same bucket they cannot overlap in prefix for the same action (expiration) -

```
An error occurred (InvalidRequest) when calling the PutBucketLifecycleConfiguration operation: Found overlapping prefixes '' and 'a' for same action type 'Expiration'
```

**Comment by romayalon** [comment]
Based on @shirady's comment - the following ceph tests might work after adding top level Prefix - 
https://github.com/noobaa/noobaa-core/pull/8373#discussion_r1762775647
test_lifecycle_get_no_id
test_lifecycle_set
Maybe there are more, please remove them from the pending list after solving this issue and check if them or others should work.
