### ISSUE TITLE
NSFS | S3 | Versioning: Access to ListObjectVersions on version-enabled bucket denied despite bucket policy allowance

### ISSUE THREAD

**Issue by hseipp** [noobaa/noobaa-core#8352]
### Environment info
- NooBaa Version: **5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior

A secondary user gets

```
E           botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectVersions operation: Access Denied
```
although a Bucket policy is in place that gives all users ListBucket permissions.

### Expected behavior

The operation should succeed. The secondary user should be able to execute ListObjectVersions.

### Steps to reproduce

Execute the additional test code extending Ceph s3-tests:

```
    @pytest.mark.versioning
    def test_s3cever11():
        client = get_client()
        bucket_name = get_new_bucket(client=client)
    
        # The following operation uses another client instance -> following operations will fail
    #    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        _ces_safe_check_configure_versioning_retry(client, bucket_name, "Enabled", "Enabled")
    
        key = "test"
        version_ids = []
        contents = []
        num_versions = 3
        (version_ids, contents) = create_multiple_versions(client, bucket_name, key, num_versions)
    
        response = client.list_object_versions(Bucket=bucket_name)
        assert len(response['Versions']) == 3
    
        resource1 = "arn:aws:s3:::" + bucket_name
        resource2 = "arn:aws:s3:::" + bucket_name + "/*"
        policy_document = json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [{
            "Effect": "Allow",
            "Principal": {"AWS": "*"},
            "Action": "s3:ListBucket",
            "Resource": [
                "{}".format(resource1),
                "{}".format(resource2)
              ]
            }]
         })
    
        client.put_bucket_policy(Bucket=bucket_name, Policy=policy_document)
    
        alt_client = get_alt_client()
       response = alt_client.list_object_versions(Bucket=bucket_name)
```

### More information - Screenshots / Logs / Other output

Log with "all" level:
[noobaa_20240911_2.log.gz](https://github.com/user-attachments/files/16965201/noobaa_20240911_2.log.gz)

**Comment by shirady** [comment]
@hseipp maybe I'm missing something - but from what I see the policy action is `"Action": "s3:ListBucket"` the bucket policy is added by `client` and then you try to `list_object_versions` with `alt_client`.
Could you change the policy action to `s3:ListBucketVersions`?

I looked at this printing in the logs:

> Sep 11 14:34:38 m1.example.com [19651]: [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Action  fit? s3:ListBucket s3:ListBucketVersions
> Sep 11 14:34:38 m1.example.com node[19572]: Sep-11 14:34:38.240 [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Action  fit? s3:ListBucket s3:ListBucketVersions
> Sep 11 14:34:38 m1.example.com node[19572]: Sep-11 14:34:38.240 [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Principal  fit? SENSITIVE-7846cdd4c2b90527 s3user2
> Sep 11 14:34:38 m1.example.com [19651]: [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Principal  fit? SENSITIVE-7846cdd4c2b90527 s3user2
> Sep 11 14:34:38 m1.example.com [19651]: [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1$/ arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1
> Sep 11 14:34:38 m1.example.com node[19572]: Sep-11 14:34:38.240 [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1$/ arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1
> Sep 11 14:34:38 m1.example.com [19651]: [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1\/.*$/ arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1
> Sep 11 14:34:38 m1.example.com node[19572]: Sep-11 14:34:38.240 [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1\/.*$/ arn:aws:s3:::s3tests-r3z0uamiwnfylei6w17ra-1
> Sep 11 14:34:38 m1.example.com [19651]: [nsfs/19651]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy: is_statements_fit false true true true

What I can understand that you couldn't list the version because the action was not fit (last line in the logs):
https://github.com/noobaa/noobaa-core/blob/4edc2a413b5573b3093ea7aa62826896ea23930f/src/endpoint/s3/s3_bucket_policy_utils.js#L199

I would also mentioned that I tried to run this script in NC POSIX environment and it passed:
```python
@pytest.mark.versioning
def test_s3cever11():
    bucket_name = get_new_bucket()
    client = get_client()
    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")

    key = "test"
    version_ids = []
    contents = []
    num_versions = 3
    (version_ids, contents) = create_multiple_versions(client, bucket_name, key, num_versions)

    response = client.list_object_versions(Bucket=bucket_name)
    assert len(response['Versions']) == 3

    resource1 = "arn:aws:s3:::" + bucket_name
    resource2 = "arn:aws:s3:::" + bucket_name + "/*"
    policy_document = json.dumps(
    {
        "Version": "2012-10-17",
        "Statement": [{
        "Effect": "Allow",
        "Principal": {"AWS": "*"},
        # "Action": "s3:ListBucket",
        "Action": "s3:ListBucketVersions",
        "Resource": [
            "{}".format(resource1),
            "{}".format(resource2)
            ]
        }]
        })

    client.put_bucket_policy(Bucket=bucket_name, Policy=policy_document)

    alt_client = get_alt_client()
    response = alt_client.list_object_versions(Bucket=bucket_name)
```
By running this: `S3TEST_CONF=test_nsfs_ceph_s3_config_2.conf tox -- s3tests_boto3/functional/test_s3.py::test_s3cever11`
Note: I created 2 accounts and added the first one credentials in the config main and the second's credentials in the alt in Ceph config file.

I could see it passed and the logs are:

> Sep-15 16:01:33.070 [nsfs/82377]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Action  fit? s3:ListBucketVersions s3:ListBucketVersions
> Sep-15 16:01:33.070 [nsfs/82377]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Principal  fit? SENSITIVE-7846cdd4c2b90527 66e6d9ca6960bed2e15c3a8f
> Sep-15 16:01:33.070 [nsfs/82377]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::shira-xdf3altxdcskuecjc5k3kqq-1$/ arn:aws:s3:::shira-xdf3altxdcskuecjc5k3kqq-1
> Sep-15 16:01:33.070 [nsfs/82377]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy:  Resource  fit? /^arn:aws:s3:::shira-xdf3altxdcskuecjc5k3kqq-1\/.*$/ arn:aws:s3:::shira-xdf3altxdcskuecjc5k3kqq-1
> Sep-15 16:01:33.070 [nsfs/82377]    [L1] core.endpoint.s3.s3_bucket_policy_utils:: bucket_policy: is_statements_fit true true true true

**Comment by hseipp** [comment]
I agree that `s3:ListBucket` is not the appropriate action keyword, it should be `s3:ListBucketVersions`. If I correct the test code accordingly, the above cited test code passes.
