### ISSUE TITLE
NOOBAA_LOG_LEVEL is not working as expected

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#8380]
### Environment info
- NooBaa Version: noobaa-core-5.17.0-20240904.el9.x86_64
- Platform: Standalone

### Actual behavior
config.LOG_TO_STDERR_ENABLED = true;
config.LOG_TO_SYSLOG_ENABLED = true; 
In this case it is logging all the unwanted messages in the console,noobaa.log and messages.

### Expected behavior
1. we should not see messages in the console. 

### Steps to reproduce
1.config.LOG_TO_STDERR_ENABLED = true;
config.LOG_TO_SYSLOG_ENABLED = true; 

Broadcast message from systemd-journald@ramyamc-42 (Wed 2024-09-18 10:20:09 CEST):

[3267897]: 2024-09-18 10:20:09.491233 [PID-3267897/TID-3267897] FS::set_log_config: LOG_TO_STDERR_ENABLED=1 LOG_TO_SYSLOG_ENABLED=1

**Comment by romayalon** [comment]
@naveenpaul1 can you please take a look?

**Comment by ramya-c3** [comment]
@naveenpaul1 So you mean to say we should not use these 2 config parameters?

**Comment by naveenpaul1** [comment]
issue tested and working as expected
cc : @ramya-c3
