### ISSUE TITLE
NSFS | Tagging bugs

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#8400]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Tagging is not supported on Upload Object/Copy object (non server side copy/taggingDirective Replace) - it's being ignored.
2. Get Object tagging leaves the file opened without closing it - 
```
2024-09-24 11:21:08.704203 [PID-16479/TID-259] FS::FileWrap::dtor: file not closed _path=/private/tmp/dir2/obj-with-tagging _fd=25
2024-09-24 11:21:08.704508 [PID-16479/TID-259] FS::FileWrap::dtor: file not closed _path=/private/tmp/dir2/obj-with-tagging-copy _fd=24
```

### Expected behavior
1. Tagging should be supported on Upload/Copy Object.
2. Get Object Tagging should close all files opened by the operation.

### Steps to reproduce
**Tagging is not supported on Upload Object/Copy object - it's being ignored.**
Upload object -
1. Start NooBaa NC - `sudo node src/cmd/nsfs  --debug=5`
2. Upload an object - 
```bash 
s3api put-object --bucket bucket1 --key obj-with-tagging2 --body obj1 --tagging=`tag1=val1`
```
4. Get object Tagging of the object - 
```bash 
s3api get-object-tagging --bucket bucket1 --key obj-with-tagging77
{
    "TagSet": []
}
```

**Get Object tagging leaves the file opened without closing it**
1. Start NooBaa NC - `sudo node src/cmd/nsfs  --debug=5`
2. Upload an object - `s3api put-object --bucket bucket1 --key obj1 --body obj1`
5. Get Tagging of the object - `s3api get-object-tagging --bucket bucket1 --key obj1`
6. Wait a minute and check the logs of nsfs.js - and search for the following message - 
`2024-09-24 11:33:13.711420 [PID-29422/TID-259] FS::FileWrap::dtor: file not closed _path=/private/tmp/dir2/obj77 _fd=24`

**Comment by naveenpaul1** [comment]
code merged
