### ISSUE TITLE
NSFS | S3 | Versioning: Deleting an object in version-suspended mode does not create a delete marker

### ISSUE THREAD

**Issue by hseipp** [noobaa/noobaa-core#8440]
### Environment info
- NooBaa Version: **5.17.0 20241007**
- Platform: **CentOS 8 deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant), Scale 5.2.2 20241004**

### Actual behavior

When checking for presence of a delete marker after deleting an object in version-supended mode, I get an `KeyError: DeleteMarkers` which means no delete markers are present.

### Expected behavior

A DeleteMarker with `VersionID: "null"` should be present for the deleted object.

### Steps to reproduce

Execute the following test case as extension to Ceph s3-tests:

```
def test_s3cever105():
    client = get_client()
    bucket_name = get_new_bucket(client=client)

    # The following operation uses another client instance -> following operations will fail
#    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
    _ces_safe_check_configure_versioning_retry(client, bucket_name, "Enabled", "Enabled")

    _ces_safe_check_configure_versioning_retry(client, bucket_name, "Suspended", "Suspended")

    key_name = 'obj'
    data = 'object'
    response = client.put_object(Bucket=bucket_name, Key=key_name, Body=data)
    version_id = None
    try:
        version_id = response['VersionId']
    except KeyError:
        version_id = None
    assert version_id == None

    client.delete_object(Bucket=bucket_name, Key=key_name)

    data = 'object-2'
    response = client.put_object(Bucket=bucket_name, Key=key_name, Body=data)
    version_id = None
    try:
        version_id = response['VersionId']
    except KeyError:
        version_id = None
    assert version_id == None

    response = client.list_object_versions(Bucket=bucket_name)
    versions = response['Versions']
    assert len(versions) == 1
    delete_markers = response['DeleteMarkers']
    assert len(delete_markers) == 1
```

### More information - Screenshots / Logs / Other output

Noobaa logs with "all" debug level attached
[noobaa-20241008_1.log.gz](https://github.com/user-attachments/files/17291527/noobaa-20241008_1.log.gz)

**Comment by hseipp** [comment]
Hi @shirady I agree with your conclusions.

I changed the test code the following way:
```
diff --git a/s3tests_boto3/functional/test_s3.py b/s3tests_boto3/functional/test_s3.py
index 48e5b1a..985de2a 100644
--- a/s3tests_boto3/functional/test_s3.py
+++ b/s3tests_boto3/functional/test_s3.py
@@ -2218,8 +2218,7 @@ def test_s3cever105():
     response = client.list_object_versions(Bucket=bucket_name)
     versions = response['Versions']
     assert len(versions) == 1
-    delete_markers = response['DeleteMarkers']
-    assert len(delete_markers) == 1
+    assert 'DeleteMarkers' not in response
 
 @pytest.mark.versioning_suspend
 def test_s3cever106():
```

and it passes.

BTW: I do have Debuglevel set to all as noted above:
```
$ sudo mms3 config list | grep DEBUGLEVEL
 DEBUGLEVEL : all
```
Do we have a (new) issue with logging?

**Comment by shirady** [comment]
Hi @hseipp,
As we understand that test is passing, I suggest to close this issue.

Regarding the logs - I'm not aware of an issue, but I'll mention team members here so we can check it
@romayalon @naveenpaul1

**Comment by naveenpaul1** [comment]
@hseipp could you please check these two configuration in your systed
default :
```
config.LOG_TO_STDERR_ENABLED = true;
config.LOG_TO_SYSLOG_ENABLED = false; 
```

**Comment by hseipp** [comment]
These are exactly like set as default:
```
$ sudo cat /ibm/cesShared/ces/s3-config/config.json | jq ".LOG_TO_SYSLOG_ENABLED,.LOG_TO_STDERR_ENABLED"
true
false
```

**Comment by naveenpaul1** [comment]
@hseipp do you see any error in journal or /var/log/message file?

**Comment by hseipp** [comment]
@naveenpaul1 The journal log I attached above does not seem to contain the necessary "all"-level Noobaa endpoint log information as it did with previous noobaa-core releases.
I looked at the complete syslog (/var/log/messages), bur that is too chatty.
I assume you are asking me to look for Noobaa-specifics by grepping like in
```
sudo cat /var/log/messages | grep "node\[" | grep -i error
```
?
There I don't see any other errors rather than the race condition that happens on my machine not being able to access the Scale file system at bootup where the Noobaa config is stored:
```
Oct  8 08:50:59 m1 node[1194]: Oct-8 8:50:59.833 [nsfs/1194] [EVENT]{"timestamp":"2024-10-08T08:50:59.829Z","host":"m1.example.com","event":{"code":"noobaa_gpfslib_missing","message":"Noobaa GPFS library file is missing","description":"Noobaa GPFS library file is missing","entity_type":"NODE","event_type":"STATE_CHANGE","scope":"NODE","severity":"ERROR","state":"DEGRADED","arguments":{},"pid":1194}}
Oct  8 08:50:59 m1 node[1194]: Oct-8 8:50:59.843 [nsfs/1194] [ERROR] CONSOLE:: failed to create NSFS system data due to - ENOENT: no such file or directory, unlink '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac' [Error: ENOENT: no such file or directory, unlink '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac'] { errno: -2, code: 'ENOENT', syscall: 'unlink', path: '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac' }
Oct  8 08:50:59 m1 node[1194]: Oct-8 8:50:59.843 [nsfs/1194] [ERROR] CONSOLE:: nsfs: exit on error Error: failed to create NSFS system data due to - ENOENT: no such file or directory, unlink '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac'
Oct  8 08:50:59 m1 node[1194]: Oct-8 8:50:59.843 [nsfs/1194] [EVENT]{"timestamp":"2024-10-08T08:50:59.843Z","host":"m1.example.com","event":{"code":"noobaa_s3_crashed","message":"Noobaa S3 crashed","description":"Noobaa S3 crashed, error: Error: failed to create NSFS system data due to - ENOENT: no such file or directory, unlink '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac'","entity_type":"NODE","event_type":"STATE_CHANGE","scope":"NODE","severity":"ERROR","state":"STOPPED","pid":1194}}
```

**Comment by naveenpaul1** [comment]
@hseipp I could see log last printed on yesterday and noobaa crashed in noobaa event log.
```
Oct  8 08:50:59 m1 node[1194]: Oct-8 8:50:59.843 [nsfs/1194] [EVENT]{"timestamp":"2024-10-08T08:50:59.843Z","host":"m1.example.com","event":{"code":"noobaa_s3_crashed","message":"Noobaa S3 crashed","description":"Noobaa S3 crashed, error: Error: failed to create NSFS system data due to - ENOENT: no such file or directory, unlink '/ibm/cesShared/ces/s3-config/system.json.m207bb7m-ba86f1ac'","entity_type":"NODE","event_type":"STATE_CHANGE","scope":"NODE","severity":"ERROR","state":"STOPPED","pid":1194}}
```
Could you please check the noobaa service status.

**Comment by hseipp** [comment]
> Could you please check the noobaa service status and if not started please start.
This is what I do each time I start up the VM. Like I mentioned above, there obviously is a race condition that prevents proper Noobaa startup on this VM, so I always perform
```
sudo mmces service stop s3 && sudo mmces service start s3
```
and watch the status with `sudo mmces state show` after VM bootup events like the one you pointed to.

But this is not the issue we are dealing with here. The question is: what prevents the Noobaa endpoint logs to be added to the `sudo journalctl --no-pager -u noobaa` log in the current Scale and noobaa builds while the Noobaa FS logs are there?

**Comment by hseipp** [comment]
Regarding the missing endpoint log message, it looks like the default systemd settings caused to endpoint logs to get suppressed - for details see [https://my.f5.com/manage/s/article/K70501143](this article). Thanks to @naveenpaul1 for the pointer and troubleshooting help. In the future, my adapted systemd configuration will prevent log messages to get suppressed.

**Comment by shirady** [comment]
@hseipp @naveenpaul1 Thank you
