### ISSUE TITLE
Bucket creation is not checking the mod bits on directory (r) if nfs4acls are present

### ISSUE THREAD

**Issue by anandhu-karattu** [noobaa/noobaa-core#8457]
### Environment info
- NooBaa Version: **noobaa-core-5.17.0-20241005.el9.x86_64**
- Platform: **Standalone noobaa**

### Actual behavior
1. Set NC_DISABLE_ACCESS_CHECK : false
2. Create an account account7000 with --newbucketspath /mnt/gpfs0/account7000/
3. Create a new directory /mnt/gpfs0/account7000/bucket7000-03 with root:root and 770 permission set.
4. If I don't set the nfs4acl on the path “/mnt/gpfs0/account7000/bucket7000-03” , bucket creation is failing as expected.
5. However if I set nfs4acl using “nfs4_setfacl -a A::user7000@:rwaDxtTnNcCoy /mnt/gpfs0/account7000/bucket7000-03", bucket creation is succeeding.

### Expected behavior
My understanding is we still need to check for account7000(uid 7000, gid 7000) must have READ (r) access set via mod bits on the bucket directory. Currently no mod bit check (r) is performed if nfs4acls are present in the directory

### Steps to reproduce
Mentioned in actual behaviour.

**Comment by naveenpaul1** [comment]
@anandhu-karattu with latest code changes [PR](https://github.com/noobaa/noobaa-core/pull/8359) , modbit based access restriction is disable for noobaa by defaultand its controlled using flag `config.NC_DISABLE_POSIX_MODE_ACCESS_CHECK`. If not overriden with config.json change `NC_DISABLE_POSIX_MODE_ACCESS_CHECK` always will have [value](https://github.com/noobaa/noobaa-core/blob/5.17/config.js#L895) `true`. 
cc : @romayalon

**Comment by anandhu-karattu** [comment]
@naveenpaul1 , I am using build "noobaa-core-5.17.0-20241016.el9.x86_64". 
In this build I don't see the parameter "NC_DISABLE_POSIX_MODE_ACCESS_CHECK" in config.json.

@romayalon , do we need to back port this flag in to 5.17 ? As suggested by Naveen, I added the parameter manually in the config.json "NC_DISABLE_POSIX_MODE_ACCESS_CHECK=false" and looks like nfs4acls are not getting considered after that.

**Comment by naveenpaul1** [comment]
@anandhu-karattu I could already see the new configuration in 5.17 branch, Its already backported to 5.17 
new config `NC_DISABLE_POSIX_MODE_ACCESS_CHECK` in 5.17 branch : https://github.com/noobaa/noobaa-core/blob/5.17/config.js#L895

**Comment by anandhu-karattu** [comment]
@naveenpaul1 , I have 16/Oct build . But I can not see this parameter in config.json

```
[root@522oct21-21 ~]# rpm -qa | grep noobaa
noobaa-core-5.17.0-20241016.el9.x86_64
[root@522oct21-21 ~]#
[root@522oct21-21 ~]#
[root@522oct21-21 ~]# jq . /mnt/cesSharedRoot/ces/s3-config/config.json
{
  "CONFIG_ROOT": "",
  "ENDPOINT_FORKS": 2,
  "NSFS_BUF_POOL_MEM_LIMIT": 0,
  "NSFS_BUF_SIZE": 0,
  "ENDPOINT_PORT": 6001,
  "ENDPOINT_SSL_PORT": 6443,
  "ENDPOINT_SSL_STS_PORT": 0,
  "EP_METRICS_SERVER_PORT": 0,
  "ALLOW_HTTP": false,
  "NSFS_CALCULATE_MD5": true,
  "UV_THREADPOOL_SIZE": 16,
  "GPFS_DL_PATH": "/usr/lpp/mmfs/lib/libgpfs.so",
  "NSFS_OPEN_READ_MODE": "",
  "NSFS_CHECK_BUCKET_BOUNDARIES": false,
  "NSFS_TRIGGER_FSYNC": false,
  "NSFS_WHITELIST": [],
  "TIME_TO_SYNC_BUCKET": 0,
  "TIME_TO_SYNC_ACCOUNT": 0,
  "BACKUP_PATH": "",
  "RESTORE_PATH": "",
  "NOOBAA_LOG_LEVEL": "default",
  "NSFS_NC_STORAGE_BACKEND": "GPFS",
  "NSFS_NC_CONFIG_DIR_BACKEND": "GPFS",
  "NSFS_DIR_CACHE_MAX_DIR_SIZE": 536870912,
  "NSFS_DIR_CACHE_MAX_TOTAL_SIZE": 1073741824,
  "NSFS_GLACIER_ENABLED": false,
  "NSFS_GLACIER_LOGS_ENABLED": false,
  "NC_MASTER_KEYS_GET_EXECUTABLE": "/usr/lpp/mmfs/bin/cess3_key_get",
  "NC_MASTER_KEYS_PUT_EXECUTABLE": "/usr/lpp/mmfs/bin/cess3_key_put",
  "NC_MASTER_KEYS_STORE_TYPE": "executable",
  "LOG_TO_SYSLOG_ENABLED": true,
  "LOG_TO_STDERR_ENABLED": false,
  "NC_DISABLE_ACCESS_CHECK": false
}
```

**Comment by naveenpaul1** [comment]
@anandhu-karattu It's not listing here because `NC_DISABLE_POSIX_MODE_ACCESS_CHECK` is not added in config.json. I am not sure who is responsible for updating the config.json, most probably the Scale team
@rkomandu

**Comment by romayalon** [comment]
@anandhu-karattu @naveenpaul1 @guymguym we shouldn't expose it to the user, we kept this flag as an option to use it in the future.
Today our read check is via opening the file/directory and not via mode bits.
@anandhu-karattu If you still want to test it although we should not expose it to the user (currently) you can edit the config.json file directly.

**Comment by anandhu-karattu** [comment]
@romayalon I agree. This is not a bug. Summarising my understanding after the tests
1.  if an ACL (I tested nfs4acl) on the directory, it will be considered for bucket/account creation always.
2. If the user does not want to honour the ACL, currently we have no option. However adding the flag "NC_DISABLE_POSIX_MODE_ACCESS_CHECK=false" will stop considering the ACLs. We are not disclosing this to the users as of now. I discussed this with @madhuthorat and we are good with that approach.
3. If no ACLs present and "NC_DISABLE_ACCESS_CHECK": false , noobaa will look for the READ (r) access in the directory for the account owner.

**Comment by romayalon** [comment]
@anandhu-karattu almost,
3 -> We always check read permissions of the directory by opening it (not bia mod bits), regardless of the existence of an ACL.
So are we good to close it?

**Comment by anandhu-karattu** [comment]
Yes please close it @romayalon

**Comment by naveenpaul1** [comment]
closing issue
