### ISSUE TITLE
s3 cli request for http port on s390x arch hangs in 5.17 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#8479]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa-core-5.17.0-20241016.el9.s390x (S3 standalone) 

ALLOW_HTTP : false
 DEBUGLEVEL : all
 ENABLEMD5 : false
 ENDPOINT_FORKS : 2
 ENDPOINT_PORT : 6001
 ENDPOINT_SSL_PORT : 6443
 
AWS_ACCESS_KEY_ID=aPjdJH9I6YEeEqwsvwx4 AWS_SECRET_ACCESS_KEY=m8yZh3o7dgh1ZlHClTElU+PWhHet3YXsJUwyD15j aws --endpoint http://10.20.83.106:6001/ s3 ls
^C    <<<<<<<<<<<<<<<<--- HANGS HERE

### Actual behavior
1.

It should display as "connection refused" if ALLOW_HTTP is false 

### Expected behavior
1.

Could not connect to the endpoint URL: "http://<IP>:6001/"

on x86_64 

2024-10-24 06:19:27,552 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): <IP>:6001
2024-10-24 06:19:27,554 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

### Steps to reproduce
1.

### More information - Screenshots / Logs / Other output
Attaching the s3 ls --debug option
[s3.log.txt](https://github.com/user-attachments/files/17505674/s3.log.txt)

**Comment by rkomandu** [comment]
@naveenpaul1 could you check this one. Working on x86_64 and pwr arch

**Comment by naveenpaul1** [comment]
issues was happening when connect to http service with noobaa configuration `ALLOW_HTTP = false`, noobaa skip http server creation when ALLOW_HTTP is false. So there is no chance http request will get executed.
And Peter could get the error response(without lag) for http request after updating AWS CLI to latest version
`aws-cli/2.17.20 Python/3.11.9 Linux/5.14.0-427.40.1.el9_4.x86_64 exe/x86_64.rhel.9`

**Comment by muenchp1** [comment]
with latest GPFS build 5.2.2.0 241030.130342 
noobaa-core-5.17.0-20241030.el9.s390x gpfs.mms3-5.2.2-0.241030.130342.el9.s390x 

I'm getting the expected error message from all nodes (protocol and non-protocol nodes)
while ALLOW_HTTP : false 
running 
AWS_ACCESS_KEY_ID=<> AWS_SECRET_ACCESS_KEY=<> aws --endpoint http://192.168.17.149:6001 s3api list-buckets

Could not connect to the endpoint URL: "http://192.168.17.149:6001/"

Tested with different python / aws-cli combination.
aws --version
aws-cli/1.24.10 Python/3.6.8 Linux/4.18.0-553.22.1.el8_10.s390x botocore/1.26.10
aws-cli/1.32.86 Python/3.9.18 Linux/5.14.0-427.42.1.el9_4.s390x botocore/1.34.86
aws-cli/2.18.17 Python/3.11.7 Linux/5.14.0-427.42.1.el9_4.s390x source-sandbox/s390x.rhel.9

**Comment by rkomandu** [comment]
closing this based on above comments from Peter and @naveenpaul1
