### ISSUE TITLE
NC | NSFS | Bucket Logging After Delete Bucket

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#8540]
### Environment info
- NooBaa Version: 5.18, current master - After merging PR #8527
- Platform: NC

### Actual behavior
1.  When trying to `send_bucket_op_logs` on delete bucket operation, we would not have the `bucket_info` anymore in the cache; therefore we would see the printing of "Could not log bucket operation".

### Expected behavior
1. Needs to be discussed what is the optimal solution - but the basic expected is not to see those logs.

### Steps to reproduce
1. Deployment in NC NSFS
2. Create an account and a bucket.
3. Delete the bucket, and look for the printing of "Could not log bucket operation".

We can see it in the Ceph tests
See [this comment](https://github.com/noobaa/noobaa-core/pull/8527#issuecomment-2485524460) in the PR

### More information - Screenshots / Logs / Other output
-

**Comment by shirady** [comment]
Hi,
The main question is to understand what should happen when a bucket is deleted -
Should we create the bucket logging? should we have the bucket notifications?

we cannot access the `bucket_info` anymore (it is `undefined`):
https://github.com/noobaa/noobaa-core/blob/f924d96bc87993ca2d1615bfd69da460bb186093/src/endpoint/s3/s3_bucket_logging.js#L22


@aspandey @alphaprinz
cc: @romayalon @jackyalbo

**Comment by alphaprinz** [comment]
Regarding notifications, deleting a bucket is not an event that triggers a notification.
(You can see the list of events [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-event-types)).
So your suggested fix is ok for notifications.

**Comment by aspandey** [comment]
@shirady We can not do bucket logging if bucket does not exist..so in that case we should not  even log this message if we do not want such logs. 
However, I would not have any issue seeing such logs (may be added info) which could always help to debug.
May be log2 and not error..

**Comment by shirady** [comment]
@aspandey the bucket exists and then the client send a request to delete it (operation is delete bucket).
Do we need to log this information?

**Comment by aspandey** [comment]
@shirady If I remember correctly, bucket logging was introduced to log bucket operation only, means, get/put/delete objects on a bucket if it is configured to log.
Operation "Delete Bucket", where we want to remove a bucket completely, does not fall in that category and should not be logged.
This is what I remember from my patch. However, @jackyalbo had also sent a detailed PR for persistent bucket logging and should also give his thoughts in case things changed.

**Comment by nimrod-becker** [comment]
BucketLogging is set on a specific bucket, if the bucket is gone, then the logging config and the need to log.... no?

**Comment by shirady** [comment]
@nimrod-becker, this is what I'm trying to understand - if we need the last log of the operation of `delete-bucket` (until the cache changes we could have it).
@aspandey do you know why we didn't exclude it like `put-bucket`? (see [comment](https://github.com/noobaa/noobaa-core/issues/8540#issuecomment-2486120197))

**Comment by romayalon** [comment]
@shirady @aspandey 
I think that in general we don't skip bucket operations here except put_bucket, is there a different place where we avoid logging on bucket operations?

**Comment by shirady** [comment]
I discussed with @aspandey and suggested the following minor changes:
1. Exclude the `delete_bucket` from the operations as I suggested here.
2. Wrap with try_catch when trying to read the bucket info - on a non existing bucket (before the change) we also throw an error there.
3. Add a check notification part (`&& bucket_info`) as it might be undefined - @alphaprinz .

If you have any comments regarding the code changes please write them in the PR #8527.

regarding @romayalon's question above - as I understand there many changes, and it is something that needs to be checked. we can open an issue about this gap - related to bucket logging (not related to the Add stat to bucket_namespace_cache).

**Comment by shirady** [comment]
I'm closing the issue since we added the changes in file `s3_bucket_logging.js` to avoid the issue of deleting an existing bucket (and also we had before the PR an error thrown on deleting a non-existing bucket).
