### ISSUE TITLE
Anonymous account - newBucketsPath should be mandatory for non anonymous account

### ISSUE THREAD

**Issue by snehalghadage1** [noobaa/noobaa-core#8624]
### Environment info
- NooBaa Version: **5.18.0-20241214**
- Platform: **Standalone**

### Actual behavior
1.
**noobaa-cli account add --name clustuser --uid 10005 --gid 40000** 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /mnt/cesSharedRoot/ces/s3-config
nsfs: config_dir_path=/mnt/cesSharedRoot/ces/s3-config
nsfs: config.json= {
  ENDPOINT_FORKS: 2,
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  LOG_TO_SYSLOG_ENABLED: true,
  ALLOW_HTTP: true,
  NSFS_CALCULATE_MD5: false,
  UV_THREADPOOL_SIZE: 16,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  LOG_TO_STDERR_ENABLED: false,
  NC_DISABLE_ACCESS_CHECK: false,
  NOOBAA_LOG_LEVEL: 'default',
  NSFS_NC_STORAGE_BACKEND: 'GPFS',
  NSFS_NC_CONFIG_DIR_BACKEND: 'GPFS',
  NSFS_DIR_CACHE_MAX_DIR_SIZE: 536870912,
  NSFS_DIR_CACHE_MAX_TOTAL_SIZE: 1073741824,
  NSFS_GLACIER_ENABLED: false,
  NSFS_GLACIER_LOGS_ENABLED: false,
  NC_MASTER_KEYS_GET_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_get',
  NC_MASTER_KEYS_PUT_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_put',
  NC_MASTER_KEYS_STORE_TYPE: 'executable',
  NC_DISABLE_POSIX_MODE_ACCESS_CHECK: false
}
nsfs: merged config.json= {
  ENDPOINT_FORKS: 2,
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  LOG_TO_SYSLOG_ENABLED: true,
  ALLOW_HTTP: true,
  NSFS_CALCULATE_MD5: false,
  UV_THREADPOOL_SIZE: 16,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  LOG_TO_STDERR_ENABLED: false,
  NC_DISABLE_ACCESS_CHECK: false,
  NOOBAA_LOG_LEVEL: 'default',
  NSFS_NC_STORAGE_BACKEND: 'GPFS',
  NSFS_NC_CONFIG_DIR_BACKEND: 'GPFS',
  NSFS_DIR_CACHE_MAX_DIR_SIZE: 536870912,
  NSFS_DIR_CACHE_MAX_TOTAL_SIZE: 1073741824,
  NSFS_GLACIER_ENABLED: false,
  NSFS_GLACIER_LOGS_ENABLED: false,
  NC_MASTER_KEYS_GET_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_get',
  NC_MASTER_KEYS_PUT_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_put',
  NC_MASTER_KEYS_STORE_TYPE: 'executable',
  NC_DISABLE_POSIX_MODE_ACCESS_CHECK: false
}
2024-12-23 06:26:10.185188 [PID-1887004/TID-1887004] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-12-23 06:26:10.185296 [PID-1887004/TID-1887004] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
(node:1887004) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "_id": "6768f472c87f2ab3c4900c9d",
      "name": "clustuser",
      "email": "clustuser",
      "creation_date": "2024-12-23T05:26:10.929Z",
      "access_keys": [
        {
          "access_key": "ZdefazABlzuYpTwF0B8w",
          "secret_key": "BsDVubpTey84Oglxicdl0hsEpfHgheoph0sforUD"
        }
      ],
      "nsfs_account_config": {
        "uid": 10005,
        "gid": 40000,
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": false
    }
  }
}

### Expected behavior
1.
newBucketsPath should be mandatory for non anonymous account

### Steps to reproduce
1. Create account without newBucketsPath option

**Comment by romayalon** [comment]
@snehalghadage1 The original request from CES team was to have --new_buckets_path optional for having accounts that wouldn't be able to create buckets, you can read more about it here 
https://github.com/noobaa/noobaa-core/issues/7625
https://github.com/noobaa/noobaa-core/issues/7700 
https://github.com/noobaa/noobaa-core/issues/7786
therefore, closing this issue, if you have more questions you are welcomed to ask.
